### ISSUE TITLE
Console.log of Mapcontrols in useThree is null

### ISSUE THREAD

**Issue by Propetro360** [pmndrs/drei#1003]
### What is your question:

I am trying to use savestate and reset callbacks of the controls.

But for some reason, the controls are a null object when I use MapControls but 
for Orbit controls, I get a proper object.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/61523868/183211535-13464ad6-8049-4683-b573-01621884b378.png">

I tried to reproduce this on sandbox here 
where none of the Controls set the control state of useThree.

https://codesandbox.io/s/orbit-controls-frameloop-forked-j3k1p1?file=/src/App.tsx

**Comment by acmoles** [comment]
I'm having this issue too
