### ISSUE TITLE
Can't load FBX with textures in React Native

### ISSUE THREAD

**Issue by TiagoCavalcante** [pmndrs/drei#1010]
- `three` version: 0.141.0
- `@react-three/fiber` version: 8.0.19
- `@react-three/drei` version: 9.11.3
- `node` version: 16.16.0
- `npm` (or `yarn`) version: 8.11.0

### Problem description:

FBX with textures (embedded or not) can't be loaded with the `useFBX` hook.

The following warning is appearing:
```
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: Resource ID #0x0
```

And no model is being shown. I have tested it with multiple FBX files (and I checked all of them in AutoDesk to ensure they are working).

### Relevant code:

```js
import { useFBX } from '@react-three/drei/native'

export const Model = () => {
  const model = useFBX('./model.fbx')

  return <primitive object={model} />
}
```

**Comment by sandersdevelopments** [comment]
same here for the newest versions :(

**Comment by TiagoCavalcante** [comment]
Any news on this?

**Comment by amashianov** [comment]
This helped me https://docs.pmnd.rs/react-three-fiber/getting-started/installation#react-native:
```
import modelPath from './BoxTexture.fbx';
...

  const fbx = useFBX(modelPath);
  return <primitive object={fbx} />
```
