### ISSUE TITLE
Whenever i try to import anything its gives import error given in description

### ISSUE THREAD

**Issue by tahirwaleed399** [pmndrs/drei#1028]
- `three` version:^0.144.0
- `@react-three/fiber` version:^8.6.0
- `@react-three/drei` version:^9.25.3
- `node` version:v16.14.0
- `npm` (or `yarn`) version:8.6.0

### Problem description: Whenever I try to import anything let say perspective camera from drei it gives the the issue : 
export 'ParametricGeometry' (imported as 'ParametricGeometry') was not found in 'three' 
I only import it and it gives issue I use it in my code or not ig gives error continuously 

### Relevant code:

```js
// import { AdaptiveDpr } from '@react-three/drei';
import { PerspectiveCamera } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import {angleToRadians} from '../Utils/angle';

export default function Three(){
    useThree(({camera}) => {
        camera.position.set(0,1,4)
        // camera.rotation.set(angleToRadians(-20), angleToRadians(10), angleToRadians(20));
      });
    return (<>
   
    <mesh position={[0,0.7,0]}>

            <meshStandardMaterial color={'#ffffff'}/>
        <sphereGeometry args={[0.5,32,32]}/>

    </mesh>

    <OrbitControls></OrbitControls>
<mesh rotation={[-(angleToRadians(90)),-(angleToRadians(15)),0]}>

        <planeGeometry args={[29,9]} >

        </planeGeometry>
            <meshStandardMaterial color={'#333333'}/>
    </mesh>
   
    <ambientLight args={['#ffffff',1]}></ambientLight>

    
    </>)
}

```

**Comment by joshuaellis** [comment]
Can you please provide a codesandbox repo?

**Comment by tahirwaleed399** [comment]
It is Working on Codesandbox Repo But not on Local host can you please try on your Computer Please I am Stuck I wanna learn three js

**Comment by joshuaellis** [comment]
If it works on codesandbox then it's probably to do with your set up. You should instead provide your repo so someone can investigate.

**Comment by FackJox** [comment]
I fixed this same issue by rolling three back to  "three": "^0.141.0",

**Comment by Roderickx** [comment]
> Solucioné este mismo problema haciendo retroceder tres a "tres": "^0.141.0",

Muchas gracias me ha funcionado para mi llevé 1 día entero con este problema

**Comment by rezaalp** [comment]
got the issues too when i try to run it on localhost,  has anyone find the solution yet?

**Comment by joshuaellis** [comment]
> got the issues too when i try to run it on localhost, has anyone find the solution yet?

If you can supply a reproduction we can look at the issue.

**Comment by rezaalp** [comment]
> > got the issues too when i try to run it on localhost, has anyone find the solution yet?
> 
> If you can supply a reproduction we can look at the issue.

got u here
https://github.com/rezaalp/boilerplates/tree/dev

**Comment by joshuaellis** [comment]
> > > got the issues too when i try to run it on localhost, has anyone find the solution yet?
> > 
> > 
> > If you can supply a reproduction we can look at the issue.
> 
> got u here [https://github.com/rezaalp/boilerplates/tree/dev](https://github.com/rezaalp/boilerplates/tree/dev?rgh-link-date=2022-09-02T09%3A48%3A31Z)

Wheres your error? I've downloaded the repo I don't see any issues. Please be more specific with what you're struggling with to avoid wasting people's time.

**Comment by tahirwaleed399** [comment]
Ok I have solved it by downgrading the three Package to three@0.143.0  It solves the issue there's a bug in the latest version of three library

**Comment by rezaalp** [comment]
> > > > got the issues too when i try to run it on localhost, has anyone find the solution yet?
> > > 
> > > 
> > > If you can supply a reproduction we can look at the issue.
> > 
> > 
> > got u here [https://github.com/rezaalp/boilerplates/tree/dev](https://github.com/rezaalp/boilerplates/tree/dev?rgh-link-date=2022-09-02T09%3A48%3A31Z)
> 
> Wheres your error? I've downloaded the repo I don't see any issues. Please be more specific with what you're struggling with to avoid wasting people's time.

sry i didn't push it before, but seems like i got the answer above my comment, sorry for the inconvenience :)

**Comment by CodyJasonBennett** [comment]
This comes from https://github.com/pmndrs/three-stdlib/pull/180, fixing shortly.
