### ISSUE TITLE
ParametricGeometry not exported from three -> build error

### ISSUE THREAD

**Issue by DaanKorver** [pmndrs/drei#1029]
- `three` version: 0.144.0
- `@react-three/fiber` version: 8.6.2
- `@react-three/drei` version: 9.25.3
- `node` version: v16.15.1
- `npm` (or `yarn`) version: 1.22.19

### Problem description:

When importing ```<OrbitControls />``` from ```@react-three/drei``` and build the project (with ```yarn build```), the following error will occur:
```js
./node_modules/three-stdlib/geometries/ParametricGeometries.js
Attempted import error: 'ParametricGeometry' is not exported from 'three' (imported as 'ParametricGeometry').
```

### Relevant code:

```js
import { OrbitControls } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export function BoxContainer() {
  return (
    <Canvas>
      <OrbitControls />
      <ambientLight intensity={0.6} />
      <Box />
    </Canvas>
  )
}

function Box() {
  return (
    <mesh>
      <boxGeometry />
      <meshBasicMaterial />
    </mesh>
  )
}
```

**Comment by joshuaellis** [comment]
Sounds like three-stdlib needs an update. Have you opened an issue there?

**Comment by DaanKorver** [comment]
Will do that now.

**Comment by DaanKorver** [comment]
Related issue from three-stdlib: [#178](https://github.com/pmndrs/three-stdlib/issues/178)

**Comment by ridhof** [comment]
it's already solved through new merged PR in three-stdlib, 
I tested in both latest version and the version my friend mentioned, 9.22.9, both works fine.

I think we can close the issue now
