### ISSUE TITLE
PivotControls can not use an object ref, like TransformControls

### ISSUE THREAD

**Issue by Seanmclem** [pmndrs/drei#1060]
### Describe the feature you'd like:

It seems like `PivotControls` must wrap the mesh that it's controlling. The component cannot be a sibling to the mesh.

However, `TransformControls` can do this. 
```
<TransformControls object={mesh} mode="translate">
<mesh ref={mesh} />
```

### Suggested implementation:

My suggestion is that `PivotControls` have this feature added -as it can be very beneficial in the kind of dynamic environments in which a Gizmo like this is actually useful. It may be, that this is not technically possible, and maybe that's why it was omitted. In that case, it might be worth mentioning in the Readme

**Comment by sb55555** [comment]
It seems like there is a version of the PivotControls that accepts an objects props like TransformControls the implementation is here https://codesandbox.io/s/object-gizmo-controls-forked-tedx8t?file=/src/pivotControls/index.tsx:0-10721

**Comment by Seanmclem** [comment]
> It seems like there is a version of the PivotControls that accepts an objects prop like TransformControls. The implementation is here https://codesandbox.io/s/object-gizmo-controls-forked-tedx8t?file=/src/pivotControls/index.tsx:0-10721.

Yeah, I guess maybe you can. Never mind then.

```

      <PivotControls
        object={attach ? ref : undefined}
        visible={attach}
        rotation={[0, -Math.PI / 2, 0]}
        depthTest={false}
        lineWidth={2}
        anchor={[0, 1, 0]}
      />
      <mesh ref={ref} position={[0.75, 0.5, 1]} castShadow receiveShadow>
        <boxGeometry args={[0.5, 1, 0.5]} />
        <meshStandardMaterial />
      </mesh>

```
