### ISSUE TITLE
Not working in React Native Expo SDK 46

### ISSUE THREAD

**Issue by miamiappmachine** [pmndrs/drei#1066]
- `three` version: ^0.145.0
- `@react-three/fiber` version: ^8.8.7
- `@react-three/drei` version: ^9.32.4
- `node` version: v16.17.0
- `yarn` version: 1.22.5

### Problem description:

After following install instructions for React Native for React Three Fiber here: https://docs.pmnd.rs/react-three-fiber/getting-started/installation#install-npm-dependencies

Installed Drei.

When trying to use Drei, the following error is thrown:

<code>
Unable to resolve module react-dom/client from /Users/admin/React Native/expo-3d/node_modules/@react-three/drei/web/Html.js: react-dom/client could not be found within the project or in these directories:
  node_modules
  ../../node_modules
</code>

Installation of react-dom results in the error:

<code>
ReferenceError: Can't find variable: document
</code>

### Relevant code:

Follow installation instructions for a new react native project and try to add OrbitControls to the Hello World type example:

<code>
import React, { useRef, useState } from 'react'
import { Canvas, useFrame } from '@react-three/fiber/native'
import { OrbitControls } from '@react-three/drei/native'

function Box(props) {
  const mesh = useRef(null)
  const [hovered, setHover] = useState(false)
  const [active, setActive] = useState(false)
  useFrame((state, delta) => (mesh.current.rotation.x += 0.01))
  return (
    <mesh
      {...props}
      ref={mesh}
      scale={active ? 1.5 : 1}
      onClick={(event) => setActive(!active)}
      onPointerOver={(event) => setHover(true)}
      onPointerOut={(event) => setHover(false)}>
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'} />
    </mesh>
  )
}

export default function App() {
  return (
    <Canvas>
      <ambientLight />
      <pointLight position={[10, 10, 10]} />
      <Box position={[-1.2, 0, 0]} />
      <Box position={[1.2, 0, 0]} />
      <OrbitControls enableZoom={false} enablePan={false} minPolarAngle={0} maxPolarAngle={Math.PI / 2.25} makeDefault />
    </Canvas>
  )
}
</code>

### Suggested solution:

Should anything in @react-three/drei/native refer to the DOM?

**Comment by AndreLoca** [comment]
Same problem with `OrbitControls`

**Comment by CodyJasonBennett** [comment]
This is a regression since `9.26.0`. Published a fix via #1073 in `9.32.10`.

**Comment by miamiappmachine** [comment]
Hi Cody,

Thanks for looking into this. The error is indeed gone in the latest package version, but it's replaced by the following error:

<code>
TypeError: undefined is not an object (evaluating 'i.domElement.style.touchAction = "none"')
</code>
