### ISSUE TITLE
<Text/> fails to load font when Next.js app is deployed to vercel

### ISSUE THREAD

**Issue by evrazi** [pmndrs/drei#1102]
- `three` version: "^0.145.0"
- `@react-three/fiber` version: "^8.8.10"
- `@react-three/drei` version: "^9.34.4"
- `node` version: 16.4.0
- `npm` (or `yarn`) version: 7.18.1

### Problem description:

Nothing is shown

This is the error:
`Failure loading font https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxM.woff RangeError: Offset is outside the bounds of the DataView`

Can React Three Fiber be used with Next.js in this way?

### Relevant code:
```
export default function R3F() {
  return (
     <Canvas camera={{ position: [0, 0, 2.5] }}>
      <Text position={[0,1,0}>
    exampleText
       </Text>
     </Canvas>
  );
}
```

Same thing would have happened if you would try to deploy this React Three Fiber _Spherical word-cloud_ example.
https://codesandbox.io/s/spherical-word-cloud-yup2o

### Suggested solution:

Is there a different way of loading fonts?
Docs show that this can be added `font={"https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxM.woff"}` but the error remains the same.

**Comment by mspae** [comment]
I have the same issue. I believe the issue hast to do with the SWC minifier of next.js. I found an issue report a few days ago with that exact same issue and someone commented that it is fixed in the current canary. Now I can't find the issue :roll_eyes: but I'll continue looking.

Possible mitigations for now:
- Try the current next.js canary release and see if the issue persists?
- Turn off `swcMinify` in the next js config and see if the issue persists?

**Comment by evrazi** [comment]
Second option fixes it for me. Didn't try first, but will when an official release comes. Until then I'd keep this issue open if you are okey with it @mspae ?
If the official version fixes it I'll close it.

**Comment by evrazi** [comment]
Official version of next 13 fixes this issue, so I am closing it.

**Comment by sf185127** [comment]
I was still running into this on next 13 FWIW. worked fine locally. showed up as either boxes or jumbed characters on vercel in production.

disabling swcMinify worked for me, thanks @mspae

```
"next": "^13.0.3",
"@react-three/drei": "^9.40.0",
"@react-three/fiber": "^8.9.1",
"three": "^0.146.0",
```

**Comment by evrazi** [comment]
@sf185127  I can reopen this issue if you want? This should work without the need to set swcMinify to false anyway.

**Comment by sf185127** [comment]
@evrazi I'm ok with disabling swcMinify, it's not a big issue for me. Not sure why Nextjs 13 didn't fix it for me, just wanted to mention it incase someone else runs into it

**Comment by zhaitao** [comment]
Just to let you guys know that I'm experiencing the same issue on next 13.0.4. Have to disable swcMinify as mentioned above to fix the issue.
