### ISSUE TITLE
Lag just before the 3d model gets loaded

### ISSUE THREAD

**Issue by kul-sudo** [pmndrs/drei#1106]
Hello!

I use this method of loading a 3d model:

![image](https://user-images.githubusercontent.com/95244851/197333431-2f00d1a6-e941-48c2-a397-dfab96f701e0.png)

The issue is that a split second before the 3d model finally gets loaded, the entire website lags briefly. How can I elude it?

**Comment by FarazzShaikh** [comment]
Have you tried useLoader.preload to preload the model? 

Also you’re better off using useGLTF instead for loading GLB files

**Comment by kul-sudo** [comment]
> 

How can I apply `.preload` to `useGLTF('/computer_mouse.glb').scene`?

![image](https://user-images.githubusercontent.com/95244851/198826890-0ceea6b8-a495-4a7f-99f5-469c51f11023.png)

**Comment by kul-sudo** [comment]
> Have you tried useLoader.preload to preload the model?
> 
> Also you’re better off using useGLTF instead for loading GLB files

How can I apply `.preload` to `useGLTF('/computer_mouse.glb').scene`?

![image](https://user-images.githubusercontent.com/95244851/198828279-b04967fe-5c15-43ad-bfb8-330462475d75.png)

**Comment by FarazzShaikh** [comment]
Just call `useGLTF.preload('/computer_mouse.glb')` outside the component

**Comment by kul-sudo** [comment]
> Just call `useGLTF.preload('/computer_mouse.glb')` outside the component

What do you mean by "outside"?

**Comment by kul-sudo** [comment]
> Just call `useGLTF.preload('/computer_mouse.glb')` outside the component

Just like that? 
![image](https://user-images.githubusercontent.com/95244851/198998236-8a075b9c-ba04-4ad0-a2f5-d2aa19ff4ee7.png)

**Comment by kul-sudo** [comment]
> > Just call `useGLTF.preload('/computer_mouse.glb')` outside the component
> 
> Just like that?
> 
> ![image](https://user-images.githubusercontent.com/95244851/198998236-8a075b9c-ba04-4ad0-a2f5-d2aa19ff4ee7.png)

Right?
