### ISSUE TITLE
Pivot controls adding shadow

### ISSUE THREAD

**Issue by devhims** [pmndrs/drei#1119]
I just noticed when loading the GLTF model inside the `Stage` component with pivot controls, a shadow is added which fades in intensity when the model is raised up. Here's a screenshot of the same: 

<img width="643" alt="Screenshot 2022-10-30 at 12 59 52 AM" src="https://user-images.githubusercontent.com/17825870/198849729-adbe219a-ed12-40a6-8df1-af616d5de748.png">

- `three` version:  0.145.0
- `@react-three/fiber` version: 8.8.7
- `@react-three/drei` version: 9.32.5

**Comment by AlexanderMoroz** [comment]
In my case using `<PivotControls />` component with `<Stage />`  also adds unnecessary shadows.
