### ISSUE TITLE
Real occlusion with HTML elements

### ISSUE THREAD

**Issue by Zaniyar** [pmndrs/drei#1129]
I noticed when using the HTML component the occlude option is 0 or 1, means if any object is in front of the element it disappears fully, rather than getting masked. 

https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-nngn7o

I know it is possible to have masked occlusion with two simultaneous renderers, CSSRenderer with alpha for the HTML and the WebGLRenderer for 3D meshes; like this example: 
https://codepen.io/trusktr/pen/RjzKJx (not fiber)

**Comment by FarazzShaikh** [comment]
Clever example, I will be porting this to R3F

But wonder why it dosnt work when ported to CSB https://codesandbox.io/s/magical-pike-btkxuv?file=/src/index.js

**Comment by FarazzShaikh** [comment]
Never mind lol, i wasnt importing the stylesheet. Great Looks like this one will be fun!

**Comment by FarazzShaikh** [comment]
Progress! Although with bugs and limitations, it works at 60 fps on mobile which is more than i coould say for the previous attempt

https://codesandbox.io/s/three-occluded-html-6gq47u

https://user-images.githubusercontent.com/55190601/205454387-bd12c19a-a79c-42a6-b4cf-0de244034636.mp4

**Comment by bennofatius** [comment]
Hi! Just for the sake of using a simpler example, see attached video. Is this expected occlusion behavior? Would there be an easy way to achieve realistic masking with R3F? 

https://user-images.githubusercontent.com/64141736/209188904-ec988ca6-00c8-4e1c-8000-cbd91816a9cf.mov

**Comment by Zaniyar** [comment]
@FarazzShaikh  Really nice what you've achieved! Will it be merged into the main branch? Can't wait to use it!

@bennofatius Exactly this is what I've noticed and Farazz is trying to solve.

**Comment by FarazzShaikh** [comment]
@bennofatius is your video using the HTML component form this PR? 

@Zaniyar yes! I have noticed a few bugs, I will fix those  and merge into main in the next couple days

**Comment by Zaniyar** [comment]
> 

Yes Benno is using the same HTML component I mentioned in the first post (https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-nngn7o) 

I really love it. So but there is one drawback on your solution: Since it is using CSSRenderer it won't work on VR - but on Desktop/Mobile its perfect. Maybe there should be a fallback when the scene is running in VR it should use the old <HTML/> component and otherwise the one you built with CSSRenderer. Thank you anyways for your effort, great work!

**Comment by FarazzShaikh** [comment]
In the PR I have linked here, CSS3DRenderer isn’t used, instead we use the math that already exists within HTML

also the original behavior is still present and can be used by setting the occlude prop to the value of “raycast”

thanks for the kindness!

**Comment by Zaniyar** [comment]
ok impressive!

**Comment by bennofatius** [comment]
Yup, used an iFrame within a drei <Html> component – looking forward to using an improved version of this!!

**Comment by bennofatius** [comment]
Works like a charm now, however, if I may add, only if I explicitly say `occlude = "blending"`, not if I only say `occlude` (as suggested in documentation)

**Comment by FarazzShaikh** [comment]
Oops docs need to be corrected in a couple places. 

This is because we wanted this to remain a non breaking change for now as many projects rely on old occlusion behavior. We may make blending occlusion default in the next Major release

**Comment by sclea** [comment]
@FarazzShaikh great job!

In case of several <Html />'s their are not always occluding correctly.
https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-3rgmwj?file=/src/App.js

How can we fix it?

![image](https://user-images.githubusercontent.com/15073709/213913132-64142186-74ff-4168-b143-49402a7e476e.png)

**Comment by FarazzShaikh** [comment]
It’s a known issue tracked in #1228 im working on a fix, just need to find some time

**Comment by Zaniyar** [comment]
There is a small issue, when using OrbitControl, while rotating the camera with mousedown and hovering over (or dragging into a HTML element) it interacts with the HTML (selects its content) and the OrbitControl loses the context, so that when you release the mouse OrbitControl still stays in the state of mousedown (it is still rotating the camera). 

How could we lock the mouse interaction or set the pointer-events to none for all HTML elements while dragging the OrbitControls?

**Comment by FarazzShaikh** [comment]
@Zaniyar that sounds like a userland issue to me. The library shouldn’t turn off pointer events on HTML as that could be confusing and would look broken

**Comment by FarazzShaikh** [comment]
@drcmda what do you think ^

**Comment by Zaniyar** [comment]
You could be right, if the library would turn off the pointer event by default - but here it is definitely a "bug", because it somehow breaks the existing app (user experience) when you already have a orbit control. My suggestion would be that the HTML library checks if orbitcontrol is used in the scene and disables the pointer-event only on mousedown (outside of the HTML components) and re-enables it again on mouseup. In this case now one will notice that pointer-events were even disabled; but it fixes the problem of blocking orbitcontrol. 

> Or is there a case where you want to drag something from the scene inside the HTML component? hmm

**Comment by Zaniyar** [comment]
fyi, I solved that problem like this:
```
              <OrbitControls
		        onStart={()=>{state.usingOrbitControls = true}}
		        onEnd={()=>{state.usingOrbitControls = false}}
	        />

		<iframe
			style={{"pointerEvents":state.usingOrbitControls ?"none":"auto"}}
                               />
```

**Comment by dberardo-com** [comment]
i am having problems when using the useDrag/useDrop hooks from react-dnd together with occlude="blending". my aim is to enable user to drag and drop HTML elements on canvas, and i am succesfull in doing so. "occlude=true" also works without issues, but when using "blending" the drag and drop system stops to work, as if there were no events fired anymore ... is this a known issue ?

**Comment by Zaniyar** [comment]
@dberardo-com do the same as I did: 

> fyi, I solved that problem like this:
> 
> ```
>               <OrbitControls
> 		        onStart={()=>{state.usingOrbitControls = true}}
> 		        onEnd={()=>{state.usingOrbitControls = false}}
> 	        />
> 
> 		<iframe
> 			style={{"pointerEvents":state.usingOrbitControls ?"none":"auto"}}
>                                />
> ```
