### ISSUE TITLE
Using React Router Link inside Drei Html

### ISSUE THREAD

**Issue by danielbakas** [pmndrs/drei#1137]
Hi, 👋

We wanted to create a simple `react-router` "Link" for our app. Unexpectedly, we found out that we can't, if React Router is declared within the Canvas element.

```js
const App = () => {
    return (
        <StrictMode>
            <Canvas>
                <BrowserRouter>
                    <Routes>
                        <Route path="/one" element={
                            <Html>
                                <p>One that links to {<Link to="/two">Two</Link>}</p>
                            </Html>
                        }/>
                        <Route path="/two" element={
                            <Html>
                                <p>Two that links to {<Link to="/one">One</Link>}</p>
                            </Html>
                        }/>
                    </Routes>
                </BrowserRouter>
            </Canvas>
        </StrictMode>
    );
};
```

This results in the following error:

```console 
Uncaught Error: useHref() may be used only in the context of a <Router> component.
```

This is all that's missing for us to begin programming our website. Your help will be invaluable. Thank you so much!!

**Comment by timohausmann** [comment]
> How about using the `navigate` method from the `useNavigate` ReactRouter Hook?

This gives the same error just with useNavigation.

@CodyJasonBennett your solution works in dev mode, but the build version throws a cryptic error (using vite). Any ideas?

```
Error
    at invariant (index.430d5f2f.js:8031:11)
    at useHref (index.430d5f2f.js:9637:27)
    at LinkWithRef (index.430d5f2f.js:10151:14)
    at Xh (index.430d5f2f.js:3773:7)
    (more cryptic names ...)
```

**Comment by danielbakas** [comment]
@timohausmann I also got it to work with `navigate` but mine worked in production

**Comment by CodyJasonBennett** [comment]
@timohausmann, let me know if you're still having issues. We can try to unblock you.

**Comment by timohausmann** [comment]
@CodyJasonBennett thanks, I'm fine with the useNavigate prop solution!

**Comment by zhangyahan** [comment]
@timohausmann How do you resolve errors thrown in production? I have the same problem now.
