### ISSUE TITLE
Types: Definition of the new useProgress hook overrides ThreeJS globals

### ISSUE THREAD

**Issue by loklaan** [pmndrs/drei#114]
Hey folks, I noticed that the new [`useProgress`](https://github.com/react-spring/drei/blob/master/src/loaders/useProgress.tsx) assigns handlers onto `THREE.DefaultLoadingManager`, without anyway to defer or configure this behaviour.

**This is a destructive side-effect and can break `THREE.DefaultLoadingManager` in some codebases.**

Anyway, bold text aside, it can cause issues for a user, if they had been assigning their own handlers to `DefaultLoadingManager` (or plan to in the future).
* If they import `drei` after their own code is run, their handlers will be overridden.
* The user doesn't have to import the `useProgress` hook specifically for this behaviour to occur, depending on how their bundler works (having to think about whether your bundler is handling tree-shaking, to avoid destructive overrides, is itself not great)
* The user, if they want to continue using their own handlers on the `DefaultLoadingManager` instance, might need to get hacky with Proxy's to keep their own behaviour intact.

Before moving on to suggestions to solve this, I think it's worth mentioning that a destructive side-effective like this, when changed, would usually constitute a major version bump as it's unintentionally  part of this package's API surface (I user might have had to write their own behaviour to get around this, if they needed to).

**Suggestions**:

* Require the user to provide a LoadingManager that will have it's handlers assigned.
	* So like, `useProgress(manager: LoadingManager, selector: Selector, ...)`
	* May not be as helpful, since R3F `useLoader` doesn't have a defined way of providing a different `LoadingManager` to complement the configuration, making this required argument confusing in context of using it beside R3F. You could do something like `useLoader(GLTFLoader, foo, (loader) => loader.manager = MyLoadingManager)` sure, maybe that could be suggested.
* Wrap the current behaviour with "lazy" assignments, so the destructive changes to `DefaultLoadingManager` only happening when when `useProgress` is called for the first time.
	* Better, but the assignments are still ambiguous / unexplicit
* Lastly, we could use a Proxy to enhance the `DefaultLoadingManager` object, to allow more than one handler to be defined on any of the handlers (`onStart` `onLoad` `onError` `onProgress`).

Aaah sorry for the wall of text

**Comment by gsimone** [comment]
Could you verify if this is still the case now that we have better tree-shaking? Unused modules shouldn't be bundled anymore, meaning effects shouldn't run. Closing the issue, let me know if there's any findings and I'll reopen.
