### ISSUE TITLE
Add ScrollSnap to <ScrollControls />

### ISSUE THREAD

**Issue by AidanNelson** [pmndrs/drei#1146]
### Describe the feature you'd like:
I'd love to see [scroll snapping](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap) added to ScrollControls to enable more control over views.  In this case, you could set the number of pages and have the scrolling snap to X number of different views across those pages (i.e. full height views).  

### Suggested implementation:
I've started implementing this by setting `scroll-snap-type` on the parent element and replacing the `fill` [container](https://github.com/pmndrs/drei/blob/master/src/web/ScrollControls.tsx#L112-L115) with multiple child elements with `scroll-snap-align` set.

That said, the behavior is quite odd at this point, and doesn't really feel 'snappy' as expected.  Perhaps damping is interfering?  Does anyone have a different approach to suggest here?

**Comment by drcmda** [comment]
i tried and i couldn't make it work. even just the plain vanilla snap thing feels weird to me from all the sandboxes i'm trying. but working it into scrollcontrols, i failed completely. i think this needs to be done by someone that knows the spec better than i do.

**Comment by AidanNelson** [comment]
Thanks for trying @drcmda 🙏

I found it easier to program the 'snappiness' into my r3f/threejs camera control code directly, rather than trying to enable scroll-snap.  I did this by creating a number of curves to represent different parts of a camera movement, then sampling along those curves with some [easing](https://easings.net/#easeInOutCubic) added to smooth things out.  This way, I was able to program in a 'detent' at each of the stop-points (where I would have used scroll snap).

I will leave this open in case anyone has a better approach using css scroll snap.  Feel free to close if you like!

**Comment by rogersanick** [comment]
I'm also having this issue! I may have to try your solution with curves / camera movement.

**Comment by rogersanick** [comment]
@AidanNelson - let me know if you are comfortable, but I'd love to see how you've handled this. Scroll snapping is sorrily missed in my implementation!

**Comment by TurbatBay** [comment]
> Thanks for trying @drcmda 🙏
> 
> I found it easier to program the 'snappiness' into my r3f/threejs camera control code directly, rather than trying to enable scroll-snap. I did this by creating a number of curves to represent different parts of a camera movement, then sampling along those curves with some [easing](https://easings.net/#easeInOutCubic) added to smooth things out. This way, I was able to program in a 'detent' at each of the stop-points (where I would have used scroll snap).
> 
> I will leave this open in case anyone has a better approach using css scroll snap. Feel free to close if you like!

Hi can you show us ur code ? i'm trying to accomplish same thing and if possible i want to see it : )

**Comment by shunmian** [comment]
Is it possible to have scroll by page feature like [this](https://vikliegostaiev.github.io/react-page-scroller/#/demos/fullpage)?

**Comment by saori-eth** [comment]
bump

**Comment by nmyatt** [comment]
I came here to see if anyone had solved it. I feel i'm getting close, but it's a PIA. A couple of flies in the ointment are:
- Safari does not support scroll.el.onscrollend
Ideally you'd use the onscrollend event so you weren't fighting with the user's current scrolling action. I'm currently getting around this by using this approach:

```
    useEffect(() => {
        // start the scrollcheck loop
        checkIfScrolling()
    }, [])

    const checkIfScrolling = () => {
        // This is a workaround because some browsers (Safari) don't have a scrollEnd event
        // It may seem expensive to check every frame, but it's not - it's just setting a boolean
        if (scroll.offset !== previousScrollOffset) {            
            isScrolling = true            

        } else {            
            isScrolling = false            
        }        

        requestAnimationFrame(checkIfScrolling)
    }
```

- The second problem is that some devices use inertia scroll, so that scroll.offset is still changing for quite some time after all user input has stops - it updates via an easing function.
I propose to get around this by de-sensitizing the value using Math functions. I can get the current 'page' of the scroll container by re-mapping the pixelheight to a nomralised value between 0 and 1
Finally, i'm using a timeout so the scroll snap event happens a short time after user input has ended. This is a better UX.

```
 const handleScroll = () => {
        // inertia scrolling on e.g. touch devices means that scroll.offset is still changing after the user has stopped scrolling.
        // Using .toFixed() desensitises the scroll handler
        previousScrollOffset = scroll.offset.toFixed(SCROLL_PRECISION)
        currentSectionOffset = mapRange(previousScrollOffset, 0, 1, 1, scroll.pages)
        currentSectionIndex = Math.floor(currentSectionOffset)
        
        const sectionDelta = currentSectionOffset - Math.floor(currentSectionOffset)

        if (isScrolling) {            
            return null
        }
        
        scrollTimeout = setTimeout(() => {
            //setSection(currentSectionIndex)                        

            if (Math.abs(sectionDelta) < SCROLL_SNAP_AMOUNT) {
                // snap to the next section
                snapToNext()
            } else if (Math.abs(sectionDelta) > 1 - SCROLL_SNAP_AMOUNT) {
                // snap to the current section
                snapToPrevious()
            }
            clearTimeout(scrollTimeout)
            // calculate the delta between the current section and the current scroll offset
            
        }, SCROLL_SNAP_DELAY)
        
    }
    
    
```

I still have a bunch of issues to work through, but I need to work on something else so I thought i'd throw this code up here in case it helps anyone. If I get it working perfectly, i'll update here.

**Comment by samf01** [comment]
You can roll your own. I think it is preferable. I tried adding `scroll-snap-type:` to scroll container created by `<ScrollControls>` then, add a bunch of divs to it with `height: 100vh; scroll-snap-align: start;`, but it goes bonkers!

Instead, you can run a scroll-test inside `<useFrame>`, no need for useEffect or any other state. This is [example](https://codesandbox.io/p/sandbox/dh95md?file=%2Fsrc%2FApp.js%3A7%2C18) is driving object transition, but you could do camera.
