### ISSUE TITLE
ScrollControl style prop doesnt change via hooks.

### ISSUE THREAD

**Issue by berkaycirak** [pmndrs/drei#1174]
Thanks for that great library. I have a problem actually. 
I want users are not able to scroll my ScrollControl element while they are watching trailer. In order to do that, I  have declared some hooks which returns finish information when trail is finished. When trailer finished, I setting controlStyle object and passing it into ScrollControl style prop. But it isn't working. Do you have any suggestion? 

```
const [isFinished, setIsFinished] = useState(false);
const [controlStyle, setControlStyle] = useState({
		overflow: 'hidden',
	});
	useEffect(() => {
		if (isFinished) {
			setControlStyle({ overflow: 'auto' });
		}
	}, [isFinished]);

<ScrollControls pages={6} style={controlStyle}>
      <Camera isFinished={isFinished} />
      <Text1 isFinished={isFinished} />
</ScrollControls>
```

**Comment by Choco-milk-for-u** [comment]
same

**Comment by hatsumatsu** [comment]
Having the same issue here. Dynamically setting the width of the scrolling element via the `style` prop is not possible. Looks like the style prop is missing in this dependency array:

https://github.com/pmndrs/drei/blob/5710ce5c1b253f062c18372f6ce0d23c252786f7/src/web/ScrollControls.tsx#L158
