### ISSUE TITLE
Pivot Controls is preventing scene.toJSON() and other scene methods

### ISSUE THREAD

**Issue by Janeshwaran** [pmndrs/drei#1183]
- `three` version: 0.147.0
- `@react-three/fiber` version: 8.9.1
- `@react-three/drei` version: 9.46.5

### Problem description:

Because of pivotcontrols we cant able to do scene.toJSON() or JSON.stringify(scene), but  if we remove it from the scene it works

### Relevant code:

https://codesandbox.io/s/practical-elbakyan-injp4j?file=/src/App.js

### Suggested solution:

As of now only if we remove pivotcontrols from the scene those methods will work.

**Comment by hegoro** [comment]
Hi guys. Is there anything new about this?
