### ISSUE TITLE
Gizmo take the Environment texture

### ISSUE THREAD

**Issue by Its-Just-Nans** [pmndrs/drei#1189]
Hello,
I think the issue #358 (when there is an Environment, the gizmo take the texture of the environment) is not fully fixed.

A pictures of the bug is available in the issue : https://github.com/pmndrs/drei/issues/358#issuecomment-822094736

Here is an example where I have still an issue with the gizmo and Environment Value
https://codesandbox.io/s/eager-brook-kghigv?file=/src/App.tsx

Do you know how can I solve this bug ?

**Comment by drcmda** [comment]
if gizmo is in the same suspense bound as env it works. but no idea why it breaks in the first place.

**Comment by Its-Just-Nans** [comment]
If gizmo is in the same `<Suspense />` it's not working for me, because the `<Environment />` is not loading

Gizmo and Environment NOT IN the same `<Supense />`:
https://codesandbox.io/s/eager-brook-kghigv -> gizmo take the texture

Gizmo and Environment IN the same `<Supense />`:
https://codesandbox.io/s/wonderful-moon-k4kxk9 -> background scene is removed
