### ISSUE TITLE
<Box color="red"/> does not apply color

### ISSUE THREAD

**Issue by caseymilne** [pmndrs/drei#1195]
The color property does not apply. Mesh is rendered as grey. Three Fiber objects are colored normally, so I don't believe it's lighting. All the examples show <Box /> as accepting color that is passed to the mesh, so I was expecting this to work. Default shown is a light grey. I did have the <Box color="red" /> wrapped in a rigid body from Rapier, but after testing it outside this rigid body the color still does not apply.

**Comment by isaac-mason** [comment]
This is expected behaviour, the shape components don't have props for materials. You can provide a material as a child of the `Box` component:

```tsx
<Box>
  <meshBasicMaterial color="hotpink" />
</Box>
```

see the readme: https://github.com/pmndrs/drei#shapes

**Comment by isaac-mason** [comment]
Some other abstractions support a `color` prop, which might be the source of the confusion? If you think the docs can be improved a PR is welcome 🙂 


Otherwise, I don't see anything to action for this issue.

**Comment by drcmda** [comment]
material-color=…

**Comment by isaac-mason** [comment]
Maybe a readme update saying it's an abstraction for mesh is in order. I can do that later if nobody beats me to it

**Comment by isaac-mason** [comment]
A docs improvement related to this has been merged: https://github.com/pmndrs/drei/pull/1204

@caseymilne I'll close this issue now, please feel free to create a PR if you think the docs can be improved more.
