### ISSUE TITLE
Blur doesn't do anything when using the <Environment> component

### ISSUE THREAD

**Issue by dskill** [pmndrs/drei#1226]
- `three` version: 0.145.0
- `@react-three/fiber` version: 8.8.10
- `@react-three/drei` version: 9.34.4
- `node` version: v18.13.0
- `npm` (or `yarn`) version: 1.1.10

### Problem description:

Blur doesn't do anything when using the <Environment> component. It works fine in this example:
https://codesandbox.io/s/pbwi6i
But when I add it to my project I see the texture on the background, however the blur parameter has no effect (it looks completely unblurred)

### Relevant code:
`<Environment background preset="sunset" blur={1} />`

### Suggested solution:
I've spent a whole lot of time removing and simplifying things, but to no avail.  I feel like there is some obvious configuration mismatch between the codebox example and how I'm running things locally on my machine (via npm run start in a basic react app)

**Comment by drcmda** [comment]
you need to update, this is a new feature in both threejs and hence drei

**Comment by dskill** [comment]
doh - that's embarrassing in hindsight but I learned how to properly update my npm packages.  Thank you!  All good now.
