### ISSUE TITLE
`<Html>` 'blending' occlude mode is not working when having multiples `<Html>` component that doesn't have the 'blending' mode

### ISSUE THREAD

**Issue by vincentdchn** [pmndrs/drei#1228]
- `three` version: 0.148.0
- `@react-three/fiber` version: 8.9.1
- `@react-three/drei` version: 9.51.1
- `node` version: 16.18.1
- `npm` (or `yarn`) version: 8.19.2

### Problem description:

When having `<Html>` component with `occlude='blending'` and adding another one that doesn't have an occlude props set, it removes the blending properties from the first component. 

### Suggested solution:

One workaround is to always have `<Html>` component with `occlude='blending'` but it gives a white background. 
But I can't use this solution, I'm only using text from the HTML (and the `<Text>` component from Drei seems to not accept emojis)

Any thoughts about this? 
Thanks!

**Comment by FarazzShaikh** [comment]
Can you please share a CodeSandbox demo of this issue, i cannot seem to reproduce it. Here is it working with the latest verison of Drei - https://codesandbox.io/s/floral-bush-bq2533?file=/src/App.js

Yes "blending" mode can only be used with rectangles by default. 

Drei's `<Text />` does accept emojies, you just gotta find a font that supports emojies. [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji?) from Google fonts does - https://codesandbox.io/s/spherical-word-cloud-forked-v1uuw8?file=/src/App.js.

**Comment by vincentdchn** [comment]
> Can you please share a CodeSandbox demo of this issue

Of course, here it is : https://codesandbox.io/s/festive-colden-jr9ekf


> Yes "blending" mode can only be used with rectangles by default.

Ok good to know, thanks! 


Let me know if you need further informations 👍🏻

**Comment by FarazzShaikh** [comment]
Oh I see, yeah this is because the Canvas zIndex is set based on wether transform is set to true or false, this causes race conditions when multiple Html are present

I’ll look into fixes, thanks for reporting!

**Comment by FarazzShaikh** [comment]
@vincentdchn @sclea can you please pull down and the Html.tsx file in the linked PR and test if the fix works in your use cases?

**Comment by sclea** [comment]
@FarazzShaikh nope, it behaves the same way:
https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-7qbp7l?file=/src/App.js

As far as I could understand occlusion triggers when the nearest vertex of back HTML is closer to us then the nearest vertex of front HTML. Just ain's sure how to imress it in code.

**Comment by vincentdchn** [comment]
@FarazzShaikh I looks like it's working : https://codesandbox.io/s/festive-colden-jr9ekf 👌🏼

**Comment by FarazzShaikh** [comment]
@sclea nope the blending occlusion does not use distance checks at all. It uses a hole cut through inside the canvas by a “backing geometry” with 0 alpha that is the same dimensions as the HTML 

the issue you are facing might just be Z index related or may be a limitation if the technique. I will investigate further

**Comment by FarazzShaikh** [comment]
Scratch what i said about distance checks, you are right, the zIndex of the elements is set based off the distance from the camera, this is fine for the raycast occlusion but is a problem for blending.

Looking into fixes

**Comment by FarazzShaikh** [comment]
I dont think this issue is solvable because we cannot perform z-sorting per-pixel on the HTML elements, thus, there will always need to be a threshold where the "bottom" HTML pops over the "top", bellow this threshold, overlapping HTML will look broken. 

I will make a new issue addressing this incase someone has a solution, but for now we can chalk it up to it being a limitation and merge in the the linked PR.

**Comment by sclea** [comment]
@FarazzShaikh It seems the problem is somewhere else. I has experimented just now and find the interesting thing.
Adding rotation-y={1} to <HTML /> [makes it work](https://codesandbox.io/s/mixing-html-and-webgl-w-occlusion-forked-7qbp7l?file=/src/App.js) like a charm, just like it have to be.
Maybe there's some delta somewhere added to Y axis that leads to wrong z-index calculation?

**Comment by FarazzShaikh** [comment]
@sclea can you please add this info to #1255? We’ll solve this there. Or perhaps you can PR a fix if you find the issue faster than me lol
