### ISSUE TITLE
Bug: "class constructors must be invoked with 'new'" when using <MeshWobbleMaterial/> with <Text/>

### ISSUE THREAD

**Issue by johnmarinelli** [pmndrs/drei#123]
https://codesandbox.io/s/bug-mesh-wobble-material-w-text-wl9u5?file=/src/App.js

**Comment by lojjic** [comment]
@johnmarinelli This looks like the same issue as #89, do you agree?

**Comment by johnmarinelli** [comment]
@lojjic indeed it is, sorry for not checking beforehand. i'll close this ticket
