### ISSUE TITLE
Points renders squares instead of points

### ISSUE THREAD

**Issue by TeoAvignon** [pmndrs/drei#1232]
- `three` version: 0.148
- `@react-three/fiber` version: 8.10.0
- `@react-three/drei` version: 9.53
- `node` version: 17.9.1
- `npm` version: 8.11.0

### Problem description:

When using the `Points` component as depicted in the documentation, it renders squares.
![image](https://user-images.githubusercontent.com/34663049/212914407-9918363e-b8e6-4d85-83f7-402c0a785382.png)
### Relevant code:

```js
import { Environment, OrbitControls, Point, Points } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export default function App() {
  return (
    <Canvas camera={{ position: [0, 0, 20], fov: 50 }} performance={{ min: 0.1 }} frameloop="demand">
      <ambientLight intensity={0.5} />
      <directionalLight intensity={0.3} position={[5, 25, 20]} />
      <Points limit={1000} range={1000}>
        <pointsMaterial vertexColors fog={false} />
        <Point position={[1, 2, 3]} color="red" />
        <Point position={[4, 5, 6]} color="blue" />
      </Points>
      <Environment preset="city" />
      <OrbitControls autoRotate autoRotateSpeed={1} />
    </Canvas>
  )
}
```

[Here is a codesandbox with the minimal reproductive case](https://codesandbox.io/s/instanced-points-19d3gk?file=/src/App.js:0-695)

### Suggested solution:
None

**Comment by drcmda** [comment]
that is how THREE.Points and THREE.PointsMaterial works. it's a square. you are expected to create your own shader, but you're in luck because drei/PointMaterial https://github.com/pmndrs/drei#pointmaterial renders an anti aleased circle.

**Comment by TeoAvignon** [comment]
Thank you very much for your quick and precise answer ! 

It was so obvious for me that a point would be a circle that I did not even think about checking what is was in three.js.

Your PointMaterial works super fine !
