### ISSUE TITLE
CameraControls[onChange] - which CC event?

### ISSUE THREAD

**Issue by abernier** [pmndrs/drei#1254]
Thanks to @FarazzShaikh we now have `onStart`, `onEnd` and `onChange` props.

As [we've discussed it on Discord](https://discord.com/channels/740090768164651008/741751532592038022/1067954045668556881), `<CameraControls>` aims at being a drop-in replacement of `<OrbitControls>` component: then it should have the same API/props and behaviours.

I have tested on OrbitControls: the `"change"` event is triggered when the camera is dragged, but also when damping is applied.

@yomotsu which CC event matches best this OC `"change"` event: `"control"` or `"update"`? Or maybe there is no exact equivalent?

Currently, we have:
https://github.com/pmndrs/drei/blob/c79616977f9e3423110aff37b3955c7c6f70b793/src/core/CameraControls.tsx#L18

**Comment by yomotsu** [comment]
According to the source code of OC, the `"change"` event is fired at every update if states have changed.
🔽
https://github.com/mrdoob/three.js/blob/4503ef10b81a00f5c6c64fe9a856881ee31fe6a3/examples/jsm/controls/OrbitControls.js#L272-L276

I think that is the same as `"update"` in CC.
So...

| in OC | in CC |
| ----- | ----- |
| start | controlstart |
| change | update |
| end | controlend |

CC also has `"control"` event which is for "user interaction update", like when mouse/touch dragging is moved. then 
 eventually, it causes `"update"` event at the next `reqestAnimationFrame`.

Other references I checked:
- https://threejs.org/docs/#examples/en/controls/OrbitControls
- https://github.com/yomotsu/camera-controls#events

**Comment by abernier** [comment]
Ok, I have a test here where we can switch between OC/CC https://codesandbox.io/s/s-orbitcontrols-cameracontrols-events-0gdyx3 and console.log `on*` callbacks calls.

Currently for CC (with `"control"` event) the `onChange` is not called when damping (dragging or wheeling). This is a difference with OC.

> I think that is the same as "update" in CC.

Will make a PR to fix this.

NB: For `onStart`/`onEnd` they both behaves the same.
