### ISSUE TITLE
OrbitControls with enablePan prevents right clicks on objects from working

### ISSUE THREAD

**Issue by gewesp** [pmndrs/drei#1265]
### Versions

- `three` version: 0.149.0
- `@react-three/fiber` version: 8.10.1 (also reproducible with 9.x.x alphas)
- `@react-three/drei` version: 9.56.12
- `node` version: 18.12.1 locally, not sure about codesandbox
- `npm` (or `yarn`) version: 9.2.0 locally, not sure about condesandbox

### Problem description:

When a scene uses OrbitControls with panning enabled, the `onContextMenu` callback for right clicks on objects is not called.  The `onClick` callback for left clicks works fine.

### Relevant code:

https://codesandbox.io/s/focused-glade-1hi75k?file=/src/index.js

### Suggested solution:

Probably worth looking at how left click + drag is used to rotate and use the same approach for right click + pan.

**Comment by drcmda** [comment]
i think drei is the wrong place, this is probably something with orbitcontrols. it would be best if you copy OC into your project directly and see if you can fix it. use the OC from three-stdlib. and unless three/jsm/.. we do accept bug fixes in stdlib so this has a good chance of getting though quickly.

**Comment by gewesp** [comment]
> i think drei is the wrong place, this is probably something with orbitcontrols. it would be best if you copy OC into your project directly and see if you can fix it. use the OC from three-stdlib. we do accept bug fixes in stdlib so this has a good chance of getting though quickly.

You mean that fork here, for avoidance of doubt?  -->. https://github.com/pmndrs/three-stdlib/tree/main/src/controls

**Comment by drcmda** [comment]
yes exactly. drei relies on stdlib for this reason, if something's wrong it can be fixed. three/jsm doesn't often accept bug fixes.

**Comment by gewesp** [comment]
> i think drei is the wrong place, this is probably something with orbitcontrols. it would be best if you copy OC into your project directly and see if you can fix it. use the OC from three-stdlib. we do accept bug fixes in stdlib so this has a good chance of getting though quickly.

Update: Copying the drei `<OrbitControls>` of 9.40.0 into our project fixes the issue, no change in three-stdlib.   I tried rolling back three-stdlib to 2.17.3 as well, but that didn't help.

I hypothesize a regression introduced sometimes after 9.40.0 in `drei`.
