### ISSUE TITLE
Chore: Add a custom material story for Text

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#127]

**Comment by johnmarinelli** [comment]
I've started work on this here https://github.com/johnmarinelli/drei/tree/dev/issue-127

**Comment by gsimone** [comment]
If you open a PR it will deploy the storybook for a preview 👍

**Comment by johnmarinelli** [comment]
@gsimone cool, i've opened a PR here https://github.com/pmndrs/drei/pull/151
