### ISSUE TITLE
ArcballControls focus function

### ISSUE THREAD

**Issue by rcsm17** [pmndrs/drei#1270]
Is the focus function supported ?

**Comment by drcmda** [comment]
are you saying it differs from three? in that case i suggest that you can update it in three-stdlib. just copy over the changes and make quick pr.

generally i thought arcball was too buggy when i tried it. cameracontrols is much safer imo and focus works perfectly.

**Comment by rcsm17** [comment]
I couldn't make it work.. When I double click on an object in the scene (in R3F) it do nothing, While if I set the same scene using the standard threejs and I double click on any object it start the animation and focus to it.

For my purposes I need something like the arcball control that look at the object at 360 degrees and if the user want to see another object he can just double click to change the focused object and so on.

This behavior should be set in the cameracontrols ? And if yes how ?
