### ISSUE TITLE
Codesandbox examples fail to run  

### ISSUE THREAD

**Issue by IbrahimSam96** [pmndrs/drei#1271]
I'm running into compiling errors like this for all examples. Any reason why it's not working anymore? 

<img width="960" alt="Drei error" src="https://user-images.githubusercontent.com/72482204/217321952-d1fdf2aa-1117-4993-bc8d-58494ea852d9.PNG">

**Comment by drcmda** [comment]
csb outage, they have just reverted the pr that broke it.
