### ISSUE TITLE
How can I get rid of the whitish layer on the MeshTransmission material when it is over the shader.

### ISSUE THREAD

**Issue by kevinjn3640** [pmndrs/drei#1273]
![image](https://user-images.githubusercontent.com/82707769/217656339-3cf2b769-68bc-4a7c-8b41-55bf116a664d.png)

### What is your question:

How can I get rid of the whitish layer on the MeshTransmission material when it is over the shader. While the image seems alright through the material.

**Comment by drcmda** [comment]
this could prove quite complex. i am guessing this is because of double tonemapping + encoding. you can try using toneMapped={false} and see if that makes it better, but otherwise best make a tiny codesandbox for repro.

**Comment by kevinjn3640** [comment]
I tried but toneMapped={false} doesn't has any effect.
Here's the sandbox link,
https://codesandbox.io/s/glass-transmission-forked-061y4e?file=/src/App.js

**Comment by drcmda** [comment]
doesnt seem like the same sandbox. could i have the one from the first post?

**Comment by drcmda** [comment]
the fragment's missing these
```glsl
  gl_FragColor = vec4(color,1.0);
  #include <tonemapping_fragment>
  #include <encodings_fragment>
```
can't return a gl_FragColor without tonemapping and encoding or else the shader is gamma incorrect. but imo also the way it defines colors is wrong. these should be uniforms so three has a chance of managing it. but either way, look OK to me.

**Comment by kevinjn3640** [comment]
Thanks
