### ISSUE TITLE
Get mouse coordinates when clicked on the canvas

### ISSUE THREAD

**Issue by julurisaichandu** [pmndrs/drei#1281]
Hi @drcmda ,
How to get mouse coordinates when clicked on the canvas. I am able to get normalized coordinates and also the clientX and clientY coordinates when we click on the canvas. Is there any hook in react-three/drei for getting the canvas coordinates?

**Comment by clementroche** [comment]
You can do it by yourself by binding onClick handler on the `<Canvas>` element
https://codesandbox.io/s/black-thunder-furbjk?file=/src/index.js:811-1011
