### ISSUE TITLE
Reduce varying count in MeshRefractionMaterial

### ISSUE THREAD

**Issue by gydence** [pmndrs/drei#1297]
### Describe the feature you'd like:

MeshRefractionMaterial currently uses 16 varying slots.  My 2019 MacBook Pro only supports 15, so the program fails to link.  At quick glance, several of the varyings are unnecessary and could be removed, which would also increase performance.

### Suggested implementation:

- projectionMatrixInv: pass in as uniform
- viewMatrixInv: pass in as uniform
- vInstanceMatrix: I'm not familiar with the reason that `instanceMatrix` is an attribute, not a uniform, in three, so this is maybe less of a question for this repo.  if it were a uniform instead, this could be removed.  otherwise, this is unnecessary if !USE_INSTANCING, so the logic could be switched around to only define + use it if there's instancing.
- vColor: similarly, this looks like it only has to be varying due to instanceColor.  but if !USE_INSTANCING_COLOR, it is unnecessary.  the varying could be hidden behind `#ifdef USE_INSTANCING_COLOR` and the multiplication by `uniform vec3 color` could be moved to the fragment shader, which would be one fewer varying if !USE_INSTANCING_COLOR

**Comment by drcmda** [comment]
could you implement that?

**Comment by CodyJasonBennett** [comment]
I've implemented a fix in #1303. Instancing uses attributes (`THREE.InstancedBufferAttribute`) for per-instance data since uniforms are proper globals and [`gl.vertexAttribDivisor`](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/vertexAttribDivisor) only operates on attributes. I've hidden this behind the proper defines and inlined expressions accordingly.

**Comment by gydence** [comment]
wow thank you for the quick PR!

for the uniform vs. attribute issue, an alternative could be to have a big uniform array of the matrices/colors and index into it using `gl_InstanceID`?
