### ISSUE TITLE
Grid not exported?

### ISSUE THREAD

**Issue by OldManMeta** [pmndrs/drei#1309]
"dependencies": {
    "@emotion/react": "11.10.4",
    "@emotion/styled": "11.10.4",
    "@mui/icons-material": "5.10.3",
    "@mui/material": "5.10.3",
    "@react-spring/web": "^9.6.1",
    "@react-three/cannon": "^6.4.0",
    "@react-three/drei": "^9.56.26",
    "@react-three/fiber": "^8.9.1",
    "@types/react": "18.0.18",
    "@types/react-dom": "18.0.6",
    "@types/three": "^0.146.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hot-loader": "^4.13.1",
    "rxjs": "7.5.6",
    "leva": "0.9.34",
    "three": "^0.147.0"
  },
  "devDependencies": {
    "css-loader": "^6.7.1",
    "file-loader": "^6.2.0",
    "filemanager-webpack-plugin": "^7.0.0",
    "html-webpack-plugin": "^5.5.0",
    "source-map-loader": "^3.0.1",
    "ts-loader": "^9.2.8",
    "typescript": "^4.6.3",
    "webpack": "^5.71.0",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.11.1"
  }

### Problem description:
The Grid element is not exported by the look of it
### Relevant code:

The exact error showing is:

Module '"@react-three/drei"' has no exported member 'Grid'

### Suggested solution:
I've checked across the versions that I can see, and am unable to determine what changes and when caused this issue.

The instructions on use are a little vague, so this may be a case of me incorrectly understanding the use of it.

**Comment by clementroche** [comment]
https://codesandbox.io/s/black-thunder-furbjk?file=/src/index.js no issues over there

**Comment by OldManMeta** [comment]
Something went weird on several projects, with just random packages like this not showing exports correctly.  Cleaned modules and needed a reboot - but it appears to now be showing correctly. My bad. Cheers
