### ISSUE TITLE
bug in @react-spring

### ISSUE THREAD

**Issue by zob360** [pmndrs/drei#1311]
2 months ago the code was working on the last version, something broke.

Module not found: Error: Can't resolve '@react-spring/types/animated' in '.../node_modules/@react-spring/core/dist'
Did you mean 'animated.js'?
BREAKING CHANGE: The request '@react-spring/types/animated' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@react-spring/core/dist/index.mjs 1597:0-50

Module not found: Error: Can't resolve '@react-spring/types/interpolation' in '.../node_modules/@react-spring/core/dist'
Did you mean 'interpolation.js'?
BREAKING CHANGE: The request '@react-spring/types/interpolation' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by lstribli** [comment]
Same here. Seems both of these files are empty- fixing the extensions does nothing.

**Comment by zob360** [comment]
I think solution could be to downgrade "@react-spring/three": "^9.3.1" in path node_modules/@react-three/drei/package.json

**Comment by lstribli** [comment]
This worked for me. Thanks!

**Comment by twmmason** [comment]
What version are you downgrading to?

**Comment by guix77** [comment]
Which latest version of drei does not have this issue ?

**Comment by twmmason** [comment]
Installing these versions works for me:

"@react-spring/three": "^9.6.1",
"@react-three/drei": "^9.56.26",
"@react-three/fiber": "^8.11.5",

**Comment by zob360** [comment]
I cannot fix :( in every version drei reference the last version with "^xx.xx.x" instead a specific one

**Comment by magdazelena** [comment]
@zob360 I have been also struggling with this for last couple hours. What worked for me was installing following fixed versions in my own repo: 
    "@react-spring/core": "9.3.1",
    "@react-spring/three": "9.3.1",
    "@react-spring/types": "9.3.1",

which is annoying because I do not need them, but I plan on removing them once I stop needing the drei controls :)

**Comment by pearson-reese** [comment]
> Installing these versions works for me:
> 
> "@react-spring/three": "^9.6.1", "@react-three/drei": "^9.56.26", "@react-three/fiber": "^8.11.5",

This worked for us, thank you!

**Comment by dk4tz** [comment]
> Installing these versions works for me:
> 
> "@react-spring/three": "^9.6.1", "@react-three/drei": "^9.56.26", "@react-three/fiber": "^8.11.5",

we were able to get it working locally but ran into the same issue building in an AWS CodeBuild Linux container... we were able to resolve by changing the ^ to ~

**Comment by CodyJasonBennett** [comment]
Looks like [react-spring@9.7.0](https://github.com/pmndrs/react-spring/releases/tag/v9.7.0) breaks TS resolution since ESM expects fully specified paths. You can pin to 9.6.x with `~` as mentioned above until we get this fixed upstream:

```json
{
  "dependencies": {
    "@react-spring/three": "~9.6.1"
  }
}
```

**Comment by joshuaellis** [comment]
This issue should definitely be kept open – pinning the dep isn't ideal for the future :)

**Comment by joshuaellis** [comment]
Hi there, for anyone tracking this issue see – pmndrs/react-spring#2097.

There's an experimental version out (if you're using the three package change `web` to `three`):

```shell
yarn add @react-spring/web@0.0.0-1f54fd5554e133fd353fcf3bd85edeac3562a1a0-20230225150642
```

**Comment by AmreshSinha** [comment]
I am facing this issue with: `@react-spring/web` package (version: `9.7.0`)
Is there any older web package version for a temporary fix?

**Comment by joshuaellis** [comment]
> I am facing this issue with: `@react-spring/web` package (version: `9.7.0`)
> 
> Is there any older web package version for a temporary fix?

Did you see my comment above yours? There's an experimental release which I believe solves the issue. You can use that if you'd prefer.

**Comment by zob360** [comment]
on my side @react-spring/web@0.0.0-aefd1e584376be38b1f6ca1ca74e061c4ce9b9d8-20230225174818 not working. 

@react-spring/web@0.0.0-40ac9039be0c657954e31ea7588bee4abbf1df1f-20230227081728 working same as @react-spring/web": "9.6.1". It works only locally, a message error that can be closed is shown.
But impossible to build.

**Comment by joshuaellis** [comment]
Id track and comment on the issue in react-spring, it's hard for me to keep track of two conversations to this magnitude.
