### ISSUE TITLE
GSAP Not working in ScrollControls Html

### ISSUE THREAD

**Issue by pradeepselva204** [pmndrs/drei#1316]
GSAP Not working in ScrollControls Html.

**Comment by clementroche** [comment]
Can you provide an example using codesandbox ? I think you need to use https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy()

**Comment by IhsenBen** [comment]
I second this, gsap scrollTrigger is unable to read the HTML in the <Scroll html>,  classes, ids or refs.

**Comment by AxiomeCG** [comment]
I found a workaround to bind the Scrolltrigger to the ScrollControls.
You need to pass the `fixed.parentElement` to the Scrolltrigger as a scroller. [GSAP ScrollTrigger.scroller](https://gsap.com/docs/v3/Plugins/ScrollTrigger/scroller/)

`fixed` is the sticky div, and its parent has the overflow auto.

![image](https://github.com/pmndrs/drei/assets/18304870/4abf5cae-14c9-4c13-a015-21c3d786e643)


```jsx
  const {fixed} = useScroll();

  useGSAP(() => {
    const boxes = gsap.utils.toArray('.box') as HTMLElement[];
    boxes.forEach(box => {
      gsap.to(box, {
        x: 300,
        rotation: 360,
        scrollTrigger: {
          trigger: box,
          scrub: true,
          scroller: fixed.parentElement,
        }
      })
    });
  }, );
```

Demo: https://r3f-scrolltrigger-scrollcontrols.vercel.app/
Full Test Repo: https://github.com/AxiomeCG/r3f-scrolltrigger-scrollcontrols
