### ISSUE TITLE
Objects are cutting off when the scene is to big

### ISSUE THREAD

**Issue by Zaniyar** [pmndrs/drei#1332]
"@react-three/drei": "^9.40.0",
    "@react-three/fiber": "^8.9.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.146.0",
    "three-stdlib": "^2.17.3"

### Problem description:
Objects are cut off when zoomed on with `api.refresh(object).fit()` but only when the scene is huge. 
### Relevant code:

```js
//selectToZoom Component: 
//...
		<group
			onClick={(e) => (
				e.stopPropagation(),
				e.delta <= 2 && api.refresh(e.object).fit(),
				setSelectedObject(e.object as Group)
			)}
			onPointerMissed={(e) => e.button === 0 && api.refresh().fit()}
		>
			{children}
		</group>
```
Using Bounds and SelectToZoom component wrapper around the scene:
```
                               <PerspectiveCamera
					near={0.1}
					far={1}
					makeDefault
					position={[10, 3, 10]}
					zoom={1}
				/>
				<Suspense fallback={null}>
					<Bounds /*fit*/ clip observe margin={1.2}>
						<SelectToZoom>
							<group name={"Scene"}>
							        <Box position={[-1.2, 0, 0]} /> 
								<Box position={[1.2, 0, 0]} />
								<Suspense fallback={null}>
									<Box position={[1.2, 3, 0]} />
								</Suspense>
							</group>
						</SelectToZoom>
					</Bounds>
				</Suspense>
```

### Suggested solution:
Maybe it has sometthing todo with the Camera settings, but the thing is when I add more objects (or bigger objects) to the scene and spread them so that the whole scene itself is big I get the cutting off problem, but with a small scene (same objects and same camera settings) I see the whole object fit in the canvas by doing e.delta <= 2 && api.refresh(e.object).fit().

**Comment by bryndsey** [comment]
Could it be an issue with your scene going outside of the camera's clipping planes? It looks like you can call `api.refresh(target).clip().fit()`, which will update the clipping planes to avoid that issue.

**Comment by Zaniyar** [comment]
@bryndsey clip() was it! thanks!
