### ISSUE TITLE
Orthographiccamera lookAt prop not working in type script

### ISSUE THREAD

**Issue by julurisaichandu** [pmndrs/drei#1334]
Orthographiccamera lookAt prop not working in type script. I am getting this if i add lookAt ={[1,1,1]},
Type 'Vector3' is not assignable to type '{ (vector: Vector3): void; (x: number, y: number, z: number): void; }'.
  Type 'Vector3' provides no match for the signature '(vector: Vector3): void'.ts(2322)

**Comment by julurisaichandu** [comment]
@clementroche can you say this

**Comment by munj1** [comment]
Does this resolved?

**Comment by julurisaichandu** [comment]
> Does this resolved?

Not yet. @drcmda could you please say how to fix this

**Comment by drcmda** [comment]
lookAt is a function, not a vector, imo the type is correct. same type as on any other object3d. if you do this in vanilla:

```jsx
const o = new THREE.Object3D()
o.lookAt = [1, 2, 3]
// or
o.lookAt.set(1, 2, 3)
```

TS would complain and it would crash runtime. the correct way is

```jsx
o.lookAt(1, 2, 3)
```

in react overwriting the lookAt function would work `<obj lookAt={() => null}` but that would be pointless. what you want to do is either

```jsx
<orthographicCamera onUpdate={self => self.lookAt(1,2,3)} />
```

or

```jsx
const ref = useRef()
useLayoutEffect(() => {
  ref.current.lookAt(1,2,3)
}, [])
<orthographicCamera ref={ref} />
```

useLayoutEffect imo is the cleanest, lookAt *is* a side effect, not a prop access.
