### ISSUE TITLE
Allow for the sdfGlyphSize option on Text

### ISSUE THREAD

**Issue by atlmtw** [pmndrs/drei#1339]
### Describe the feature you'd like:

troika-three-text allows adjusting glyph size that the text uses as a texture (to calculate distance fields). However the implementation in drei doesn't accept glyph size as a prop. Understandably because this isn't something you would want constantly changed on state change. 

**Why would adding sdfGlyphSize be beneficial?**
In some cases increasing glyph size may increase sharpness and decreasing glyph size would decrease memory usage. It gives the user more control and makes the troika-three-text implementation more 1 : 1. 

### Suggested implementation:

Could we suggest adding it as a prop that is only valid after one time use? It does sound a bit hacky but open to other suggestions as well.

**Comment by drcmda** [comment]
it spreads all rest props over the instance so most likely it does support it even if types don't include it. try it, and please make a pR for that type if it's missing.
