### ISSUE TITLE
Light source in <Sky />

### ISSUE THREAD

**Issue by jbixon13** [pmndrs/drei#136]
I would like to have a light source (directional, point, etc.) associated with a `<Sky />` component. A potential use-case would be to have the sun cast shadows on objects in the scene based on `sunPosition`. A basic API based on @drcmda suggestion would look like: 

```jsx
	<Sky>
		<pointLight />
	</Sky>
```

**Comment by johnmarinelli** [comment]
sorry, i don't understand the question, what exactly is the issue?  if you want a light source to emulate the sun, you could probably use a DirectionalLight - https://threejs.org/docs/#api/en/lights/DirectionalLight

**Comment by joshuaellis** [comment]
I'm going to close this, if you need more assistance, we can reopen. Although, you may be better using the [discord server](https://discord.gg/Vsv23WJt)

**Comment by jbixon13** [comment]
Yeah I think this was a misinformed question as I was new to three at the time. 

The goal was to have a sky component that could cast shadows from where the sun is in the scene, but a directional light is more appropriate and shouldn't necessarily be tied to the sun's position exactly
