### ISSUE TITLE
Add the posibility to have labels to the Grid 

### ISSUE THREAD

**Issue by TeoAvignon** [pmndrs/drei#1367]
### Describe the feature you'd like:

Hello ! 

It would be nice to have the possibility to add labels to the grid.
It could looks like similar to the following:

![image](https://user-images.githubusercontent.com/34663049/228453883-a2b4dfb3-b4c0-455b-9d65-5193269a7cbc.png)

**Comment by julurisaichandu** [comment]
hi you could refer to this discussion #1276 for grid component labels implementation
