### ISSUE TITLE
[Grid] I want to know how this effect is achieved.

### ISSUE THREAD

**Issue by archform-eng-yhzeng** [pmndrs/drei#1369]
### Describe the feature you'd like:

I want to achieve the effect of this video, how do I do it

https://www.youtube.com/watch?v=6jHafwiaFAE

**Comment by wawahuy** [comment]
Are you using a projection perspective or orthographic projection?
You should use perspective and set near, far, and fov by a reasonable value. You may need to adjust fov to make it more realistic.

**Comment by clementroche** [comment]
You may find partial answer here, then you'll have to play with camera position i guess

https://madebyevan.com/shaders/grid/
