### ISSUE TITLE
Webstorm completion not working

### ISSUE THREAD

**Issue by Xample** [pmndrs/drei#1378]
Hi, I'm wondering why the "three-types" completion is not working:

For instance, when I start typing mesh, the typed defined in:

`node_modules/@react-three/fiber/dist/declarations/src/three-types.d.ts``

is not taken into consideration, while other functions starting with "mesh" are
<img width="630" alt="image" src="https://user-images.githubusercontent.com/944605/229284530-0aaf09b5-e242-436c-b62e-af4c650cb29f.png">

This should normally work as they are declared in `node_modules/@react-three/fiber/dist/declarations/src/three-types.d.ts` i.e.:

```typescript
declare global {
    namespace JSX {
        interface IntrinsicElements extends ThreeElements {
        }
    }
}
```

If instead of extending ThreeElements I replace with the content it works, for instance
```typescript
declare global {
    namespace JSX {
        interface IntrinsicElements extends ThreeElements {
...
    positionalAudio: PositionalAudioProps;
    mesh: MeshProps;
    instancedMesh: InstancedMeshProps;
...
        }
    }
}
```
It works as expected
<img width="653" alt="image" src="https://user-images.githubusercontent.com/944605/229289819-8ee46a46-42f9-4a32-b532-d5b62e80e692.png">

My understanding is that either something is broken in extending `ThreeElements` or I'm doing something wrong, but what ?

**Comment by wimersdev** [comment]
Hey, I have the same strange issue. Seems like if I install  @react-three/drei@9.8 - autocompletion works, but if I install it like  @react-three/drei@9.80.0 - completion is disabled.
