### ISSUE TITLE
'AsciiRenderer' cannot be used as a JSX component. Its return type 'void' is not a valid JSX element. (TypeScript i Guess)

### ISSUE THREAD

**Issue by JustKira** [pmndrs/drei#1380]
- `three` version: 0.152.2
- `@react-three/fiber` version: 8.12.0
- `@react-three/drei` version: 9.61.1
- `node` version: 16.17.1
- `npm` version: 9.1.1

### Problem description:

Problem is when i use AsciiRenderer with typescript i get this error 

_'AsciiRenderer' cannot be used as a JSX component.
  Its return type 'void' is not a valid JSX element._

also note Code is from [Example](https://codesandbox.io/s/vq9wsl?file=/src/Canvas.js) that was provided.
### Relevant code:

```ts
"use client";
import { AsciiRenderer } from "@react-three/drei";
import { Canvas, ThreeElements, useFrame, useThree } from "@react-three/fiber";
import React, { useRef } from "react";
import { Mesh } from "three";

export default function HomeMainSectionCanvas() {
  return (
    <div className="absolute h-screen w-screen -left-12">
      <Canvas>
        <color attach="background" args={["black"]} />
        <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
        <pointLight position={[-10, -10, -10]} />
        <Torusknot />
        <AsciiRenderer fgColor="black" bgColor="transparent" />
      </Canvas>
    </div>
  );
}

function Torusknot(props: any) {
  const ref = useRef<Mesh>();
  const viewport = useThree((state) => state.viewport);
  useFrame((state, delta) => {
    if (ref.current) {
      ref.current.rotation.x = ref.current.rotation.y += delta / 2;
    }
  });
  return (
    <mesh
      scale={Math.min(viewport.width, viewport.height) / 5}
      {...props}
      ref={ref}
    >
      <torusKnotGeometry args={[1, 0.2, 128, 32]} />
      <meshStandardMaterial color="red" />
    </mesh>
  );
}
```

what i did and it works ,but problem is when i deploy what i did is i removed void from AsciiRender
```ts
//before
export declare function AsciiRenderer({ renderIndex, bgColor, fgColor, characters, invert, color, resolution, }: AsciiRendererProps) : void;
//after
export declare function AsciiRenderer({ renderIndex, bgColor, fgColor, characters, invert, color, resolution, }: AsciiRendererProps)

```

i have no idea what that will do to project but i cant deploy using because packages arent same so i cant find any other work around

**Comment by Chajac** [comment]
I believe you can fix this issue by returning an empty fragment within the AsciiRenderer.  As it cannot render as a component if it is void which is what the typescript error is alluding to. 

Dive into the AsciiRenderer function and enter this `return <></>;`, this should work in your deployment as it will always return an empty fragment rather than void if there isn't anything to render.
