### ISSUE TITLE
Bounds doesn't work with CameraControls when makeDefault is true

### ISSUE THREAD

**Issue by dih7** [pmndrs/drei#1408]
- `three` version: 0.150.1
- `@react-three/fiber` version: 8.12.0
- `@react-three/drei` version: 9.65.4
- `node` version: 16.12.0
- `npm` (or `yarn`) version: Not sure how to see this in CodeSandbox.

### Problem description:

As the title says - it seems that Bounds does not work when the makeDefault prop on CameraControls is true.

It works fine using OrbitControls with makeDefault.

### Relevant code:

I've created a sandbox based on an existing example: [https://codesandbox.io/s/clones-forked-ysh4e7?file=/src/App.js](https://codesandbox.io/s/clones-forked-ysh4e7?file=/src/App.js)

### Suggested solution:

I've done a little digging, but I wasn't able to find a definitive solution. It could be related to the `controls.target` in Bounds, or a difference between CameraControls and other cameras, such as OrbitControls. 

One example of this is in `src/core/Bounds.tsx`, line 138 ([https://github.com/pmndrs/drei/blob/master/src/core/Bounds.tsx#L138](https://github.com/pmndrs/drei/blob/master/src/core/Bounds.tsx#L138)) - `controls.target` is undefined, however `controls` is not.

**Comment by mishazawa** [comment]
This issue still exists.

**Comment by Kavish20** [comment]
This issue still exists. It says that cannot read properties of undefined when doing controls.target.copy()
