### ISSUE TITLE
Scroll with HTML doesn't match speed with 3D elements

### ISSUE THREAD

**Issue by jpwhitaker** [pmndrs/drei#1414]
- `three` version: 0.151.3
- `@react-three/fiber` version: 8.12.0
- `@react-three/drei` version: 9.26.2 and up
- `node` version: 
- `npm` (or `yarn`) version:

### Problem description:

In **9.26.2** and up, html that should be 'pinned' to a 3D element will scroll past it when in a Scroll component.

### Relevant code:

Working in a codesandbox with an older version of Drei:
[https://codesandbox.io/s/scroll-8-20-2-g4mbg7?file=/src/composition.js](https://codesandbox.io/s/scroll-8-20-2-g4mbg7?file=/src/composition.js)

Not working in codesandbox with newer version:
[https://codesandbox.io/s/scroll-9-58-4-ozopvb?file=/src/composition.js](https://codesandbox.io/s/scroll-9-58-4-ozopvb?file=/src/composition.js)

The last working version was 9.26.1:
[https://github.com/pmndrs/drei/compare/v9.26.1...v9.26.2](https://github.com/pmndrs/drei/compare/v9.26.1...v9.26.2)

### Suggested solution:
It looks related to this change in 9.26.2
```react
// Append to the connected element, which makes HTML work with views
const target = (portal?.current || events.connected || gl.domElement.parentNode) as HTMLElement

```

**Comment by chenyuf2** [comment]
I think my issue is also related to this. The tooltip doesn't follow mesh when using ScrollControls. 
https://codesandbox.io/s/eager-hawking-hvw38i?file=/src/Scene.tsx

**Comment by chenyuf4** [comment]
> I think my issue is also related to this. The tooltip doesn't follow mesh when using ScrollControls. https://codesandbox.io/s/eager-hawking-hvw38i?file=/src/Scene.tsx

For me. Only the version 8.20.2 works for me. After that, all the versions have issues.

**Comment by jpwhitaker** [comment]
> > I think my issue is also related to this. The tooltip doesn't follow mesh when using ScrollControls. https://codesandbox.io/s/eager-hawking-hvw38i?file=/src/Scene.tsx
> 
> For me. Only the version 8.20.2 works for me. After that, all the versions have issues.

Can you make a codesandbox with it working?  I tried yours with 8.20.2 but it broke the sandbox.
Also in the interim I'm using https://www.npmjs.com/package/patch-package to make it work, maybe it can help unblock you!
