### ISSUE TITLE
Can I use a local font file path for fontUrl? Or even system fonts 

### ISSUE THREAD

**Issue by Kelier** [pmndrs/drei#1415]
### What is your question:

```
<Text font={'cursive'} />
or 
<Text font={localPath} />
```

It didn't work for me.What could be the possible reasons for this issue?

**Comment by jpwhitaker** [comment]
Font takes a URL:
https://protectwise.github.io/troika/troika-three-text/#preloading

You could move your font file to your public folder and use reference it like this:
`font={"./Roboto-Regular.ttf"}`

**Comment by Kelier** [comment]
> Font takes a URL: https://protectwise.github.io/troika/troika-three-text/#preloading
> 
> You could move your font file to your public folder and use reference it like this: `font={"./Roboto-Regular.ttf"}`

thanks a lot!
