### ISSUE TITLE
How get depthBuffer work with XR?

### ISSUE THREAD

**Issue by hecodeit** [pmndrs/drei#1427]
### How get depthBuffer work with XR?

As the example of SpotLight which provide a  depth-buffer which converts the spotlight into a soft particle as:
```javascript
function Foo() {
    const depthBuffer = useDepthBuffer()
    return (
        <SpotLight
            position={[0, 1, 0]}
            depthBuffer={depthBuffer}
        />
    )
}
```

It's working with none XR devices. But don't work with Quest 2, only showing black screen.

How can I make soft particle working with XR devices?

**Comment by hecodeit** [comment]
Showing the scene after change the file useDepthBuffer.tsx
``` javascript
const w = width * dpr
const h = height * dpr

......


useFrame((state) => {
    if (frames === Infinity || count < frames) {
        const currentRenderTarget = state.gl.getRenderTarget();
        state.gl.setRenderTarget(depthFBO)
        state.gl.render(state.scene, state.camera)
        state.gl.setRenderTarget(currentRenderTarget)
        count++
    }
})
```

But only work correctly with left eye, right eye has problem. Anybody help?

![Screenshot_com pico browser_2023 05 04-04 24 35 359_831](https://user-images.githubusercontent.com/61313089/236098754-96b65b0e-ea0f-4298-b6cc-72467b342a19.jpeg)

**Comment by CodyJasonBennett** [comment]
Can you create a codesandbox to compare with? To start, I'd try disabling XR projection when rendering the depth buffer, see if that helps with sampling in spotlight.

```js
useFrame((state) => {
  if (frames === Infinity || count < frames) {
    const xrEnabled = gl.xr.enabled
    gl.xr.enabled = false
    state.gl.setRenderTarget(depthFBO)
    state.gl.render(state.scene, state.camera)
    state.gl.setRenderTarget(null)
    gl.xr.enabled = xrEnabled
    count++
  }
})
```

**Comment by hecodeit** [comment]
> Can you create a codesandbox to compare with? To start, I'd try disabling XR projection when rendering the depth buffer, see if that helps with sampling in spotlight.
> 
> ```js
> useFrame((state) => {
>   if (frames === Infinity || count < frames) {
>     const xrEnabled = gl.xr.enabled
>     gl.xr.enabled = false
>     state.gl.setRenderTarget(depthFBO)
>     state.gl.render(state.scene, state.camera)
>     state.gl.setRenderTarget(null)
>     gl.xr.enabled = xrEnabled
>     count++
>   }
> })
> ```

@CodyJasonBennett 
I try the code that you provided, no success.

The Drei version of useDepthBuffer, show black screen:
https://codesandbox.io/s/soft-particles-vr-nqjkz8?file=/src/App.tsx

The version that change useDepthBuffer's width height and replace setRenderTarget to currentRenderTarget. This version left eye look right but no working with right eye.
https://codesandbox.io/s/soft-particles-vr-fixed-mylyeu?file=/src/components/useDepthBuffer.ts

![Screenshot_com pico browser_2023 05 09-00 25 11 445_167](https://user-images.githubusercontent.com/61313089/236952935-68a3df01-97b5-4fce-82ff-4798f208c68a.jpeg)

**Comment by hecodeit** [comment]
Find the problem, how calculate "w" and "h".  Should use device size or viewport size?

## useDepthBuffer.ts use device size
``` javascript
const dpr = useThree((state) => state.viewport.dpr)
const { width, height } = useThree((state) => state.size)
const w = size || width * dpr
const h = size || height * dpr
// quest 2 zise (width: 1000, height:504, dpr: 1)
// PICO 4 zise (width: 1280, height:600, dpr: 1.25)
```

## Correction use viewport size
``` javascript
// Quest 2 viewport (width: 1440, height: 1584)
// PICO 4 viewport (width: 1504, height:1504)
const w = 1440 * 2 // plus two for left and right both
const h = 1584
```

## codesandbox
https://codesandbox.io/s/soft-particles-vr-viewport-brbze1?file=/src/components/useDepthBuffer.ts

Both useDepthBuffer.ts and SpotLight.tsx, where chang the device size to viewport size
