### ISSUE TITLE
detect-gpu & Vercel: "window is not defined" 

### ISSUE THREAD

**Issue by earthbound1912** [pmndrs/drei#143]
Hello! I'm using r3f and drei in my current Next.js-based project which is hosted on Vercel. There is an issue with latest versions of drei. It fails to build with the following error: "ReferenceError: window is not defined". The probem is in "node_modules/detect-gpu" package.

**Comment by gsimone** [comment]
We are looking into it, if you can please use 1.5.6 for now 🙏

**Comment by devpascoe** [comment]
In same situation. Holding back a release version is a fine solution for now <3
