### ISSUE TITLE
<GradientTexture /> renders black with latest dependencies

### ISSUE THREAD

**Issue by hatsumatsu** [pmndrs/drei#1430]
- `three` version: 0.152.2
- `@react-three/fiber` version: 8.13.0
- `@react-three/drei` version: 9.66.1

### Problem description:

Updating all dependencies in the official gradient texture example renders the material black. No error is thrown in the console.

https://codesandbox.io/s/gradient-textures-forked-9s5ug3?file=/src/App.js

**Comment by hatsumatsu** [comment]
Returning `<canvasTexture />` instead of `<texture />` in https://github.com/pmndrs/drei/blob/d4e7f638f42b4a6a6bda175cfcc025c4c9e68c7e/src/core/GradientTexture.tsx#L25 seems to fix the issue.

**Comment by drcmda** [comment]
could you make this a pr?
