### ISSUE TITLE
Stars break when temporarily removing from scene

### ISSUE THREAD

**Issue by LukeWood** [pmndrs/drei#144]
I've used a few components from Drei and really enjoyed them - so thanks for your hard work!

My issue here is that on https://lukewood.dev when you toggle to day mode, reload the page, then switch to night mode the sky stays white for some reason.  Note sure if this is related to the Star shader code or what.

Thanks for any guidance!

**Comment by gsimone** [comment]
I can't seem to reproduce this, I'll close this for now, please try to make a codesandbox with a repro so we can take a look!
