### ISSUE TITLE
Property 'TextDecoder' doesn't exist

### ISSUE THREAD

**Issue by fillybrese** [pmndrs/drei#1449]
```
"@react-three/drei": "9.64.0",
"@react-three/fiber": "8.12.0",
"@types/three": "0.150.1",
"expo-gl": "12.4.0",
"three": "0.151.3",
"react": "18.2.0",
"react-native": "0.71.7",
```

React Native is built with new Fabric Architecture.

### Problem description:

useGLTF was working before (~2wks ago) but now is not with the same threejs dependencies setup.

I'm getting this same error about TextDecoder when attempting to import a .glb or .gltf file with useGLTF: `Property 'TextDecoder' doesn't exist`

### Relevant code:

At top of file:

```
import { useGLTF } from "@react-three/drei/native";
import testGltf from '/test.glb';

```

Inside component:

`const { nodes, materials } = useGLTF(testGltf);`

### Suggested solution:

Post in react-three-fiber with same TextDecoder error: https://github.com/pmndrs/react-three-fiber/issues/2855

Does it have something to do with the Draco Loader CDN? Besides this, which is dynamically loaded from a URL, i don't understand how there could have been anything changed related to TextDecoder compared to when it was working a couple weeks ago with same deps.

There was recently a couple updates with three-stdlib https://github.com/pmndrs/three-stdlib/releases regarding the GLTFLoader - could this be related? In the meantime, as drei maybe hasn't merged these updates yet, I attempted to replace useGLTF with useLoader + GLTFLoader from Three directly as suggested here: https://github.com/pmndrs/react-three-fiber/issues/2848#issuecomment-1519010252 but my issues didn't resolve.

Also tried to polyfill TextDecoder with this method: https://github.com/hapijs/joi/issues/2141#issuecomment-558429490 which gets past the TextDecoder error, but am left with a new strange error: `Cannot read property 'indexOf' of undefined)`

I don't know, pretty stumped at this point! Any assistance would be appreciated, thanks.

**Comment by drcmda** [comment]
i think in react native you need to require urls.

useGLTF(require(url))

**Comment by samipe** [comment]
Having same issue. Tried hosting the file but same issue persists. 

As a workaround I tried using OBJLoader instead which loads the model but for some reason the model only appears on every 3rd reload or so.

**Comment by CodyJasonBennett** [comment]
This would be because of https://github.com/pmndrs/three-stdlib/pull/226. There's no reason to not use `LoaderUtils` which has a fallback. I'll PR a fix there.

**Comment by samipe** [comment]
TextDecoder error disappeared now, thanks! Next error seems to be the `Cannot read property 'indexOf' of undefined` that OP mentioned also. Tried to follow the stack trace but couldn't figure out where it comes from. Maybe somewhere in `loadingFn` of fiber.

**Comment by CodyJasonBennett** [comment]
That would likely come from `LoaderUtils` or from parsing the url/module. If you can figure out that, there are issues with missing low-level APIs in react-native for Blob/ArrayBuffer which is required for all graphics APIs and I have patches/PRs in https://github.com/pmndrs/react-three-fiber/issues/1972. I haven't seen movement from react-native on this in years, but hopefully we can get them across the line and things should eventually work OOTB.

**Comment by samipe** [comment]
Feel free to ping if there are any problems regarding the demo. I’m happy to help!

**Comment by itsmnjn** [comment]
> [pmndrs/three-stdlib#228](https://github.com/pmndrs/three-stdlib/pull/228) resolved it, thank you @CodyJasonBennett

how should we use the `three-stdlib` package within our react-three-fiber react-native projects?

**Comment by CodyJasonBennett** [comment]
You'd `npm i three-stdlib` and `import { GLTFLoader, OrbitControls, ... } from 'three-stdlib'` -- see [pmndrs/three-stdlib](https://github.com/pmndrs/three-stdlib).

**Comment by itsmnjn** [comment]
awesome, thanks for the super fast response. found this comment from you which explains how to use it with `useLoader` from drei

https://github.com/pmndrs/react-three-fiber/issues/2848#issuecomment-1519010252
