### ISSUE TITLE
Server Side Rendering issue with Razzle

### ISSUE THREAD

**Issue by irfanka** [pmndrs/drei#145]
Hi :wave: 

I'm using Jared Palmer's wonderful [Razzle](https://github.com/jaredpalmer/razzle)  to do SSR.
However, if try importing anything from `@react-three/drei`, I get the following error when the app is being rendered on the server side:

```
> razzle start

 WAIT  Compiling...

Using .babelrc defined in your app root
Using .babelrc defined in your app root

✔ Client
  Compiled successfully in 7.99s

✔ Server
  Compiled successfully in 666.58ms

/home/irfan/bss/web/node_modules/three/examples/jsm/lines/LineGeometry.js:2
import { LineSegmentsGeometry } from "../lines/LineSegmentsGeometry.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/irfan/bss/web/node_modules/@react-three/drei/index.cjs.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

Any clues how I can fix this would be greatly appreciated.
So far, I tried setting `"type": "module"` in my "package.json", as well as looking for similar issues in the `razzle` repo - but no luck.

I'm using `node v14.10.0`

Thank you.

**Comment by jakechv** [comment]
Following; I'm having exactly this same issue with Next.js. I get the same stack trace as well (thought the frameworks-specific logging is different, of course). 

I'm using Node.js v13.8.0 and have also tried with Node.js v12.15.0.

**Comment by irfanka** [comment]
@jakechv yup, that's partly why I reported the issue here - it's not really specific to Razzle, but instead has to do with SSR rendering in general (I think).

**Comment by irfanka** [comment]
BTW, my workaround for this issue was to just lazy-load the component which imports stuff from drei, using loadable-components:

```jsx
import loadable from "@loadable/component"
const Viewport = loadable(() => import("./Viewport"));

const ViewportContainer = () => {
  return (
    <div>
      <Viewport />
    </div>
  )
}
```

Not sure if this will work with NEXT's build-time SSG / pre-rendering - but it works with regular SSR (and by extension, with Razzle).

**Comment by jameswesc** [comment]
I ran into the same issue using Next.js . Using their dynamic imports without ssr ([as shown here](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr)) worked for me.

**Comment by coopbri** [comment]
Thanks @jameswesc, that worked for me too.

It's a bit messy in my case, since the way my component hierarchy is laid out, the `drei` imports I'm using are directly in a Next.js page/route. I'm sure this will get cleaner in the future, three.js and its extension libraries are a bit dicey with SSR right now!

**Comment by gsimone** [comment]
This is also the solution we propose in the official next.js example https://github.com/vercel/next.js/blob/canary/examples/with-three-js/next.config.js
