### ISSUE TITLE
Grid component error in react-native

### ISSUE THREAD

**Issue by jmatsushita** [pmndrs/drei#1451]
- `three` version: 0.152.2 
- `@react-three/fiber` version: 8.13.0
- `@react-three/drei` version: 9.66.6
- `node` version: 16.20.0
- `npm` (or `yarn`) version: 3.5.0

### Problem description:

When using the `<Grid/>` component

`gl.uniform1f( this.addr, v );` with `expo-gl` with `Exception in HostFunction: Value is false, expected a number`.

### Relevant code:

If not set, the defaults are set to JS booleans and passed as `uniform1f` to the shader instead of the expected float values..

https://github.com/pmndrs/drei/blob/cfed6df9fb445e8a245742f95cd59fe8f8600e5a/src/core/Grid.tsx#L110-L111

### Suggested solution:

It probably makes sense to parse the JS truthy/falsy values into the uniform float value expected of 0 or 1.

A workaround in the meantime is to bypass the defaults by passing the `followCamera` and `infiniteGrid` values explicitly to the R3F component like so:
```jsx
<Grid infiniteGrid={1} followCamera={0}/>
```

**Comment by CodyJasonBennett** [comment]
The code should otherwise use bool or integer types for the current logic, but this should indeed wrap the values without changing the API. I'll PR a fix momentarily.
