### ISSUE TITLE
meshes.AuxScene

### ISSUE THREAD

**Issue by PaganViking** [pmndrs/drei#1459]
let width = 0   
const { nodes } = useGLTF("./models/elements/"+file)
const meshes = Object.values(nodes).filter((node) => node.type === 'Mesh')

if(meshes.length > 1) {
  const size = new THREE.Box3().setFromObject(meshes.AuxScene).getSize(new THREE.Vector3())
  width = size.x/2
}
![AuxScene](https://github.com/pmndrs/drei/assets/73079279/4cd8fd33-dfb4-4fc2-8ca7-cd6b3c9a4256)

AuxScene error _

**Comment by drcmda** [comment]
this is a bug in your code. Object.values(nodes).filter gives you an array, there's no ".auxScene" in an array.
