### ISSUE TITLE
Tree-shaking not working

### ISSUE THREAD

**Issue by axelboc** [pmndrs/drei#147]
I've been trying to tree-shake ThreeJS in my project, since I have a bundle that weighs 1.7 MB... I've tried using [three-minifier](https://github.com/yushijinhun/three-minifier), as well as creating my own export file as suggested in a [react-three-fiber recipe](https://github.com/pmndrs/react-three-fiber/blob/master/recipes.md#reducing-bundle-size), but neither solution worked.

Then, I tried removing `drei`, which I use for the `Html` component, and **my bundle dropped by 800 kB**!

I see that a previous attempt was made at fixing this in #106, but it did not seem to work (I'm on `drei` v1.5.6). 

I think the issue is caused by the `export *` syntax used in https://github.com/pmndrs/drei/blob/master/src/index.tsx (cf. this [webpack issue](https://github.com/webpack/webpack/issues/2847)). Fortunately, it looks like it's been fixed in webpack v5.

It may be worth replacing `export *` with named exports, since broad adoption of webpack v5 in the ecosystem may take a while.

**Comment by gsimone** [comment]
Would you consider making a PR for this?

**Comment by axelboc** [comment]
Failed attempt in #148.

Note, however, that with `@react-three/drei@1.5.8`, my bundle now weighs 1.43 MB, so the changes made in the last couple of minor revisions are baring fruit!

**Comment by gsimone** [comment]
Consider cherry picking components like this

`import { Text } from '@react-three/drei/abstractions/Text'`

I had started work on a babel plugin to do just that but stuff took precedence :(
