### ISSUE TITLE
MeshTransmissionMaterial doesn't work when setClearColor alpha value is 0

### ISSUE THREAD

**Issue by rishipandey125** [pmndrs/drei#1474]
three@0.148.0
@react-three/fiber@8.13.0
react-three/drei@9.55.0

### Problem description:

I am using MeshTransmissionMaterial to create a glass and frosted glass material. However, I also need to set the alpha value of the renderer to 0 to use passthrough on the Oculus Quest Pro for WebXR. 

When I set the renderer alpha value to 0 the passthrough works, but then the color of the MeshTransmissionMaterial is just black. 

However, when I set the renderer alpha value to 1 the MeshTransmissionMaterial works well, but XR passthrough doesn't work. 

How would I resolve this? 

Example with alpha = 1 materials are working. 

<img width="453" alt="image" src="https://github.com/pmndrs/drei/assets/35504258/996efe9d-63ec-424c-b322-4672aaeec7f9">

Example with alpha = 0 some materials turn black. 
<img width="352" alt="image" src="https://github.com/pmndrs/drei/assets/35504258/c5777617-916c-466b-aa18-986e288a6205">

Thanks for your help <3

**Comment by CodyJasonBennett** [comment]
I'd try with r153 which brings https://github.com/mrdoob/three.js/pull/25819.

**Comment by rishipandey125** [comment]
> I'd try with r153 which brings [mrdoob/three.js#25819](https://github.com/mrdoob/three.js/pull/25819).

what do you mean by "r153"? is that react three fiber 153? I am using version 8.13.0

**Comment by rishipandey125** [comment]
> I'd try with r153 which brings [mrdoob/three.js#25819](https://github.com/mrdoob/three.js/pull/25819).

thank you! looks like r153 isn't ready yet, so can't "npm update" 

but seems like it will be ready this week!
