### ISSUE TITLE
useAnimations is not updating on clip effects

### ISSUE THREAD

**Issue by justinseibert** [pmndrs/drei#1481]
- `three` version: `0.153.0`
- `@react-three/fiber` version: `8.13.0`
- `@react-three/drei` version: `9.70.1`
- `node` version: `18.3.0`
- `yarn` version: `1.22.19`

### Problem description:

I have a use-case where I need to be able to load and play animation clips from different source files (_.glb_). I am loading the source files by updating and passing the `path` parameter to the `useGLTF` hook.

I can confirm that changing the `path` produces a side effect that updates the loaded scene, as expected. However, the updated `animations` clip array does not appear to trigger an update to the object returned by `useAnimations`.

It seems the `useAnimations` hook will only refresh the cache of animations if the component is unmounted ([useAnimations.tsx#L42](https://github.com/pmndrs/drei/blob/c959e0d4232f541130dcd25aced22c6f9fb63138/src/core/useAnimations.tsx#L42)). Is this the intended behavior? If so, are there recommended ways for swapping animations without re-mounting a component?

### Relevant code:

Below is just a test to demonstrate what I am experiencing. Every 3 seconds, the `path` to the animation file changes. I am testing with 2 files that have a different amount of animation clips. I expect the `isEqual` output to _always_ be `true` and the sorted arrays to be the same.

What actually happens is the `animations` array changes with every side effect, but the `names` array _never_ changes after the component is initially mounted.

```tsx
const ANIMATIONS = [`animations_01.glb`, `animations_02.glb`]

const TestPage = () => {
    const [activeIndex, setActiveIndex] = useState(0)
    useEffect(() => {
        const interval = setInterval(() => {
            setActiveIndex(activeIndex => (activeIndex + 1) % ANIMATIONS.length)
        }, 3000)
        return () => clearInterval(interval)
    }, [])

    return (
        <Canvas>
            <Suspense fallback={null}>
                <AnimationChild path={ANIMATIONS[activeIndex]} />
            </Suspense>
        </Canvas>
    )
}

const AnimationChild = ({ path }: { path: string }) => {
    const { scene, animations } = useGLTF(path)
    const { names } = useAnimations(animations, scene)

    useEffect(() => {
        const sortedAnimations = animations.map(animation => animation.name).sort()
        const sortedNames = names.sort()

        console.log({
            sortedAnimations,
            sortedNames,
            isEqual: sortedAnimations.join('') === sortedNames.join(''),
        })
    }, [animations, names])

    return <primitive object={scene} />
}
```

### Suggested solution:

I think effects on the `clips` property should cause an update to the object returned by `useAnimations` during any render, not just in the cleanup function. It should be the responsibility of parent components to decide when the clips cache should be refreshed.

**Comment by Jonathynlee** [comment]
Do you know if anyone has found a solution or legitimate workaround for this? 

My plan as of now is to try unmounting then remounting as a temporary solution. 

Thanks!

**Comment by ninjz** [comment]
I'm still experiencing this issue as of the latest version `9.92.1`.  @justinseibert did the latest changes fix the problem on your end?

Otherwise, what is the recommended way to switch an animation on the same model without remounting?
