### ISSUE TITLE
MeshTransmissionMaterial breaking on three.js r153 when playing with clearcoat or anisotropy

### ISSUE THREAD

**Issue by AxiomeCG** [pmndrs/drei#1482]
- `three` version: "^0.153.0"
- `@react-three/fiber` version: "^8.12.0"
- `@react-three/drei` version: "^9.58.4"
- `node` version: v16.17.0
- `npm` version: 9.1.3

### Problem description:

The MeshTransmissionMaterial is breaking when using the clearcoat or the anisotropy parameter since the release of the r153 for three.js

![Error showing up](https://github.com/pmndrs/drei/assets/18304870/5d6cb049-6e7a-4310-8143-5e0eea55e413)

It works back on three.js `v0.150.1`

### Relevant code:
```jsx
<Sphere>
        <MeshTransmissionMaterial
          distortionScale={0}
          temporalDistortion={0}
          backside={true}
          thickness={0.1}
          distortion={0}
          chromaticAberration={1}
          roughness={0.6}
          flatShading={true}
          anisotropy={0.05}
          clearcoat={1}
          color={"#ffffff"}
          transmission={0.95}
          envMapIntensity={3}
          ior={1.02}
        />
</Sphere>
 ```

Codesandbox: https://codesandbox.io/p/sandbox/fervent-bird-jofpi1

**Comment by CodyJasonBennett** [comment]
This is because of the `anisotropy` prop which was introduced for the base `MeshPhysicalMaterial` and `MeshTransmissionMaterial` does not support.

**Comment by AxiomeCG** [comment]
It existed before, it's been changed freshly in 549493d
We may want to warn people in the doc that they should not try to put the new `anisotropy` in the `MeshTransmissionMaterial`, to the risk of breaking it.

This **demo sandbox** would break if we were to update the packages, and is somewhat misleading on this specific usecase as it does not take care of switching the parameter to `anisotropicBlur` when switching from `MeshPhysicalMaterial` to `MeshTransmissionMaterial`:

https://codesandbox.io/s/hmgdjq?file=/src/App.js
