### ISSUE TITLE
SpriteAnimator wont stop looping

### ISSUE THREAD

**Issue by jakke-korpelainen** [pmndrs/drei#1497]
Hello,

I'm having an issue that the SpriteAnimator wont stop looping the animation. Tried debugging with console and it seems that it isn't rendering again forever either so that shouldn't be an issue. If I disable autoPlay it will stop animating of course.

- `three` version: ^0.152.2
- `@react-three/fiber` version: ^8.13.0
- `@react-three/drei` version: ^9.69.3
- `node` version: 16.16.0
- `npm` (or `yarn`) version: 8.11.0

### Example of sprite data, the death sprite is exactly like this but with a different image and number of frames
```
{
  fps: 4,
  loop: false,
  name: 'Bandit Idle',
  numberOfFrames: 4,
  scale: 1.5,
  src { url: 'https://images.ctfassets.net/70m6o24orx4o/6sZjG5dI…BV7hkDZ/151752d856d1e3ff4235f7a45e3f060d/idle.png' },
  startFrame: 1
}
```

### Components
endFrame prop doesn't seem to work either in this setup, it throws: 
```TypeError: Cannot destructure property 'frame' of 'spriteFrames[currentFrame.current]' as it is undefined.```

```
function Monster(props: { entity: MonsterEntity }) {
  const entity = props.entity;
  const sprite = entity.health > 0 ? entity.sprite : entity.spriteDeath;

  console.log("Monster render");

  const spriteEl = useMemo(
    () => (
      <SpriteAnimator
        fps={sprite.fps}
        scale={[sprite.scale, sprite.scale, sprite.scale]}
        startFrame={sprite.startFrame}
        numberOfFrames={sprite.numberOfFrames}
        textureImageURL={sprite.src.url}
        position={[0, 1, 0]}
        alphaTest={0.01}
        loop={false} // tried also with undefined etc.
        autoPlay={true}
      />
    ),
    [sprite]
  );

  return spriteEl;
}

export default function Monsters({ entities }) {
  const monsters = (entities as MonsterEntity[])
    .filter((e) => e.hostile)
    .map((e) => (
      <Selectable
        key={`monster-${e.id}`}
        entityId={e.id}
      >
        <Monster entity={e} />
      </Selectable>
    ));

  return <>{monsters}</>;
}

Let me know if I you'd require more details.

**Comment by netgfx** [comment]
This is fixed. Perhaps this should be closed now.
