### ISSUE TITLE
TransformControls dont like other components ? 

### ISSUE THREAD

**Issue by erikpa1** [pmndrs/drei#1504]
"@react-three/drei": "^9.74.8",
    "@react-three/fiber": "^8.13.0"

Not sure if it is bug. But I found some noncompatibility in 

`<TransformControls/>
`
and beeing in same canvas with:

```
                <AccumulativeShadows frames={100} color="#9d4b4b" colorBlend={0.5} alphaTest={0.9} scale={20}>
                    <RandomizedLight amount={8} radius={4} position={[5, 5, -10]}/>
                </AccumulativeShadows>
```

causes error:

![image](https://github.com/pmndrs/drei/assets/19526670/6c9ae2e4-438a-427b-ad89-9c1678e9477f)

and 

` <CameraControls/>`

When TransformHelper and camera controls are in same world when you move with gizmo camera moves too.

With orbit controls there is no problem:
```

                <OrbitControls makeDefault target={[0, 0, 0]}
                               enableDamping={false}
                               maxPolarAngle={Math.PI / 2}/>

```
This works nice.

**Comment by jelling** [comment]
I'm seeing the same issue and it happens with `<PivotControls>` as well.
