### ISSUE TITLE
evnetSource type isssue of <View /> component.

### ISSUE THREAD

**Issue by KangUkG** [pmndrs/drei#1539]
Hello? I'm using the <View > component with TypeScript. An error occurs when I put 'divRef' in the 'eventSource' of the View component's props. How do I solve this? The following sentence is an error code.

`property) CanvasProps.eventSource?: HTMLElement | React.MutableRefObject<HTMLElement> | undefined
Type 'RefObject<HTMLDivElement>' is not assignable to type 'HTMLElement | MutableRefObject<HTMLElement> | undefined'.
 Type 'RefObject<HTMLDivElement>' is not assignable to type 'MutableRefObject<HTMLElement>'.
Types of property 'current' are incompatible.
Type 'HTMLDivElement | null' is not assignable to type 'HTMLElement'.
Type 'null' is not assignable to type 'HTMLElement'.ts(2322).
Canvas.d.ts(8, 5): The expected type comes from property 'eventSource' which is declared here on type 'IntrinsicAttributes & Props & RefAttributes<HTMLCanvasElement>'`

![image](https://github.com/pmndrs/drei/assets/97942487/a48042a0-aaba-4d89-9453-fac96c36ca85)

"In my opinion, visualizeWrapRef is a RefObject<HTMLDivElement>, and the ref type desired in eventSource is a RefObject<HTMLDivElement>. However, the ref type that can be obtained from the DOM is a RefObject<HTMLDivElement>.

**My questions Is...the type of eventSource incorrectly declared? Or am I obtaining the ref type incorrectly?**

**Comment by jglee96** [comment]
ref type too narrow ( #867 , #730).
try non-null assertions

```tsx
const visualizeWrapRef = useRef<HTMLDivElement>(null!);
const mainRef= useRef<HTMLDivElement>(null!);
```

It looks weird but works to me. ([codesandbox](https://codesandbox.io/p/github/jglee96/drei-vitest/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljhbcupx000b356omelcu87i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljhbcupx000d356ohoimfqbf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljhbcupx000b356omelcu87i%2522%253A%257B%2522id%2522%253A%2522cljhbcupx000b356omelcu87i%2522%252C%2522activeTabId%2522%253A%2522clji9zvl5005o356p6xsjesi6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljhbcupx000a356oy82n7g8n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clji9zvl5005o356p6xsjesi6%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522cljhbcupx000d356ohoimfqbf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljhbcupx000c356ofayvy7v7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cljhbcupx000d356ohoimfqbf%2522%252C%2522activeTabId%2522%253A%2522cljhbcupx000c356ofayvy7v7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D))

**Comment by KangUkG** [comment]
thanks. It works...to me...I don't understand why I need to put 'null!' as the initial value for useRef.
