### ISSUE TITLE
Select Example is not working 

### ISSUE THREAD

**Issue by vulevukusej** [pmndrs/drei#1541]
- `three` version: "0.148.0"
- `@react-three/fiber` version: "8.10.0"
- `@react-three/drei` version: "9.51.20"

### Problem description:

The "Select" example found here doesn't work:  https://codesandbox.io/s/ny3p4?file=/package.json:257-266

The error show is:

"Could not load potsdamer-platz/potsdamer_platz_1k.hdr: Failed to fetch)"

### Relevant code:

Available in sandbox

**Comment by drcmda** [comment]
fixed it

**Comment by vulevukusej** [comment]
@drcmda could you let me know what the fix is? I've had that same error pop up in my private repos and would love to fix it :)
