### ISSUE TITLE
When building a Next.js 13 project using version 9.77.7, an error occurs

### ISSUE THREAD

**Issue by Ethan-30** [pmndrs/drei#1544]
- `three` version:
- `@react-three/fiber` version:
- `@react-three/drei` version: 9.77.7
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:
When building a Next.js 13 project using version 9.77.7, an error occurs :

![image](https://github.com/pmndrs/drei/assets/49227995/286da7a9-0896-4649-a8d7-bbe35c2bad2b)

### Suggested solution:
I had to downgrade the version to 9.56.25 in order to successfully build. Please fix it in version 9.77.7.

**Comment by felixrnqst** [comment]
I have this issue too in a Next.js project running the latest version of @react-three/drei - however downgrading to 9.65.3 works for me. 
three version: 0.142.0
@react-three/fiber version: 8.2.0
@react-three/drei version: 9.77.7
node version: v18.11.0
npm (or yarn) version: 9.4.0

**Comment by konstantine811** [comment]
I am to, I fix this upgrade drei to 9.77.6

**Comment by gcolombi** [comment]
I also had the same problem, I solved it temporarily by downgrading to version 9.77.6.

**Comment by valentincognito** [comment]
I ran into this problem also so I tried the suggested downgraded versions but none of them work for me. Even worst I rolled back everything to a version I know for sure was working, deleted my entire node modules folder and reinstalled everything but I still get this error for a reason I really cannot understand..

**Comment by jglee96** [comment]
I think rollup changes in [v9.77.7](https://github.com/pmndrs/drei/releases/tag/v9.77.7) are causing the issue.
I tried debug. (#1546 )
install v9.77.6 (`"@react-three/drei": "9.77.6"`) works to me. (Actually, another error occurs but not related with this issue)

**Comment by belgattitude** [comment]
Can confirm as well, set a reproduction in https://github.com/belgattitude/artist/pull/6 if it helps.

**Comment by JHansen2000** [comment]
I'm experiencing this as well. Linked to #1546

**Comment by JHansen2000** [comment]
> I think rollup changes in [v9.77.7](https://github.com/pmndrs/drei/releases/tag/v9.77.7) are causing the issue. I tried debug. (#1546 ) install v9.77.6 (`"@react-three/drei": "9.77.6"`) works to me. (Actually, another error occurs but not related with this issue)

under `v9.77.7` (`v9.77.6` ~)
![image](https://github.com/pmndrs/drei/assets/22130454/68f5fa47-bd3e-487e-bc9b-d88e052b124f)

`v9.77.7`
![image](https://github.com/pmndrs/drei/assets/22130454/cc9e2e0b-194d-4d96-b973-f48ffd86ed09)

The[ v9.77.7](https://github.com/pmndrs/drei/releases/tag/v9.77.7) was released yesterday.
There are rollup changes in the release, and this seems to be causing this issue.

_Originally posted by @jglee96 in https://github.com/pmndrs/drei/discussions/1546#discussioncomment-6322639_

---

Dropping @jglee96's valuable debugging on this issue here
