### ISSUE TITLE
Orbit controls give errors

### ISSUE THREAD

**Issue by EGGamer** [pmndrs/drei#1552]
- `three` version: 0.77.1
- `@react-three/fiber` version: 8.13.4
- `@react-three/drei` version: 9.77.8
- `node` version: 18.14.1
- `npm` (or `yarn`) version: 9.7.2

### Problem description:

When using the OrbitControls it throws an error:
`TypeError: create is not a function`

### Relevant code:

**index.js**
```js
import { Canvas } from "@react-three/fiber"
import { OrbitControls } from '@react-three/drei'

import Box from '@/components/Box'

export default function Home() {
  return (
    <>
      <Canvas className={styles.canvas}>
        <OrbitControls />
        <ambientLight intensity={0.5} />
        <directionalLight position={[-2, 5, 2]}intensity={1}/>
        <Box />
      </Canvas>
    </>
  )
}
```

**Box.js component**
```js
import React from "react";

export default function Box() {
    return (
        <mesh rotation={[90, 0, 20]}>
            <boxGeometry attach={"geometry"} args={[3, 3, 3]}/>
            <meshLambertMaterial attach={"material"} color={"blue"}/>
        </mesh>
    )
}
```

### Suggested solution:

I've seen that the latest versions fix something about zustand, and digging in the code that *could* have created the issue? I have tested the previous version **9.77.7** and it didn't work. Going back all the way to **9.77.0** fixed the issue.

**Comment by CodyJasonBennett** [comment]
This was fixed in 9.77.9.
