### ISSUE TITLE
Center component not working properly

### ISSUE THREAD

**Issue by EGGamer** [pmndrs/drei#1553]
- `three` version: 0.154.0
- `@react-three/fiber` version: 8.13.4
- `@react-three/drei` version: 9.77.10
- `node` version: v18.14.1
- `npm` (or `yarn`) version: 9.7.2

### Problem description:

When using Text3D the Center component is not correctly working. I want the text to be aligned to the center, and I have seen than in previous versions (the latest working version seems to be 9.60.* from a Code sandbox example). 

In the code below you will see that in the latest versions it **initially** centers the element, but if you update the text, it doesn't center it after it has been updated. As I said, it seems that in previous versions it did work even if you updated the text.

### Relevant code:
(Extract of [this example](https://codesandbox.io/s/x6obrb). Removed stuff and left only what's important for the bug report)

```js
import { Canvas, useThree } from '@react-three/fiber'
import { useGLTF, useTexture, Center, Decal, Text3D, OrbitControls } from '@react-three/drei'

export default function App() {
  return (
    <Canvas camera={{ position: [0, 0, 100], zoom: 100 }}>
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 10]} />
      <Scene />
      <axesHelper scale={2} position={[0, 0, 0]} onUpdate={(self) => self.setColors('#ff2080', '#20ff80', '#2080ff')} />
      <OrbitControls enableZoom={true} enablePan={false} minPolarAngle={Math.PI / 2} maxPolarAngle={Math.PI / 2} />
    </Canvas>
  )
}

function Scene({ margin = 0.5 }) {
  return (
    <>
      <Center>
        <Text3D
          curveSegments={32}
          bevelEnabled
          bevelSize={0.04}
          bevelThickness={0.1}
          height={0.5}
          lineHeight={0.5}
          letterSpacing={-0.06}
          size={1.5}
          font="/Inter_Bold.json">
          {`Test 123`}
          <meshNormalMaterial />
        </Text3D>
      </Center>
    </>
  )
}
```

### Suggested solution:

The Center component should always center the element, or, if this is an expected behaviour, add a prop so allow the center element to always center the children.

**Comment by drcmda** [comment]
That is expected, Center is a very expensive operation, if it did that indiscriminately every render it would be bad. Instead there is a prop now that can be used to invalidate, cacheKey, put a value in there that indicates change, like the text contents.
