### ISSUE TITLE
Use Effects with MeshPortalMaterial

### ISSUE THREAD

**Issue by samf01** [pmndrs/drei#1561]
Does anyone know of a way to get Effects to work 'within' meshPortalMaterial scene? The problem seems similar to this [issue](https://github.com/pmndrs/drei/issues/890#issue-1227891818) .

Relevant example [codesandbox](https://codesandbox.io/s/enter-portals-forked-4vnncq?file=/src/App.js). I have simply combined the example for [meshPortalMaterial](https://github.com/pmndrs/drei#meshportalmaterial) and [Effects](https://github.com/pmndrs/drei#effects). As you can see, the effect works at the root level (added AO to all scenes) regardless of which scene you place the <Effects> component in. But when you 'enter' a meshPortalMaterial scene, the effect doesn't work.

- If the effect worked uniformly, you could control it with the blend property of the meshPortal.
- I have tried changing the renderPass properties and adding stencilBuffer = true, but nothing has an effect.
- Changing renderIndex > 1 causes the portal blend to stop working and you can't 'enter' the scene.

If anyone has seen a working example, that might point me in the right direction, would be appreciated?

**Comment by symbiosdotwiki** [comment]
Also curious about this

**Comment by samf01** [comment]
> Also curious about this, except in my case I need the DepthBuffer to reflect the depth of the internal scene to allow Depth of Field to work properly. Currently the depth is taken from the surface of the object the portal material is attached to.

Have found this [post ](https://discourse.threejs.org/t/postprocessing-with-portal-scene/49052/3) that seems relevant. I haven't tried it yet, but it sounds applicable.
