### ISSUE TITLE
Orthographic camera properties getting reset in the views

### ISSUE THREAD

**Issue by julurisaichandu** [pmndrs/drei#1562]
Hi, I have added drei OthorgraphicCamera as child of an object and I am currently rendering the same scene using drei Views component. I am also setting the OrthographicCamera properties like left, right, top, bottom using the reference. But when I reseize the window, the drei orthographic camera properties are getting reset. So does drei othograpic camera get reset when we do window resize? How to handle this camera properties resetting? I would like to stop resetting when we resize window.

**Comment by brandongit2** [comment]
Check out #515, i think that's the same issue.
