### ISSUE TITLE
What are the options for animating a line in r3f using drei?

### ISSUE THREAD

**Issue by adamsmietanka** [pmndrs/drei#1565]
### What is your question:

Hi, I'm currently building a chart visualization tool in react-three-fiber. For the most part, I've struggled with the limitations of the LineGeometry, but I finally went the shader route and wrote something that suites my needs:
```glsl
#include "easings.glsl"

uniform float u_time;
uniform float u_time_start;
uniform float u_position_duration;
uniform float u_position_stagger;
uniform float u_count;
attribute vec3 positionFrom;
attribute float index;
varying float v_index;

void main() {
  v_index = index;

  float point_delay = linear(index / u_count) * u_position_stagger;
  float point_start = u_time_start + point_delay;
  float x = (u_time - point_start) / u_position_duration;
  float inter = cubic_in_out(x);

  vec3 new_position = mix(positionFrom, position, inter);
  vec4 modelPosition = modelMatrix * vec4(new_position, 1.0);
  vec4 viewPosition = viewMatrix * modelPosition;
  vec4 projectedPosition = projectionMatrix * viewPosition;

  gl_Position = projectedPosition;
}
```
My main goal with this code is to have a way of interpolating the chart trace on a change in a form. The main problem I struggled with was the lineWidth would cap out at 1, which is a bummer, but I got around it by creating copies of the mesh and moving it sligthly left or right (which is not ideal):
```react
      <Line trace={trace} />
      <Line trace={trace} position-y={0.03} />
      <Line trace={trace} position-x={0.03} />
      <Line trace={trace} position-y={-0.03} />
      <Line trace={trace} position-x={-0.03} />
```
I've looked into incorporating drei's `<Line />` into my mesh but it has a rather complicated geometry and it was hard to make it work with my vertex shader. So I tried `react-spring` too, but I find the docs surrounding its use with `r3f` or `drei` quite lacking for my needs. I have troubles making a simple animation that is chained (so the axes appear first, than the markers and the trace at last and etc.) and at the same time have everything be reactive to my changes like position animations.

I would like to make a simple API for chart animations and have all the control of opacities and positions I need. What would you suggest to use? 

https://github.com/pmndrs/drei/assets/42046760/c5a72131-5bb9-4204-97cb-89c14fbddb5b

This is the current state of my solution. The vertical axis is completely drei based with `Line` and `Text` and react-spring for animations. The horizontal axis is shader based, so I have no idea how to animate the text position. Any help would be appreciated!

**Comment by adamsmietanka** [comment]
Ok, I have an update. I managed to do the animation staging with react-spring, but I still have a problem with animating a drei's `Line` opacity. It just stays fully transparent except for the places of intersection with another mesh until a React rerender.
![image](https://github.com/pmndrs/drei/assets/42046760/fd88d0e1-941a-4265-b9e9-d5e946c1ef12)

**Comment by leenephi** [comment]
I'm also interested in using `react-spring` with these shapes. Where I'm stuck is how to correctly convert one of the shape's `mesh`es to an `animated.mesh` according to the [docs](https://docs.pmnd.rs/react-three-fiber/tutorials/using-with-react-spring#spring-animations).
