### ISSUE TITLE
[BUG] TS2339: Property 'nodes' does not exist on type 'GLTF'.

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/drei#157]
"three": "^0.121.1",
"@react-three/drei": "^2.1.0",

![image](https://user-images.githubusercontent.com/69426460/95295663-2dabc500-0880-11eb-8d61-12ca7944c441.png)

```ts
export interface GLTF {
	animations: AnimationClip[];
	scene: Group;
	scenes: Group[];
	cameras: Camera[];
	asset: {
		copyright?: string;
		generator?: string;
		version?: string;
		minVersion?: string;
		extensions?: any;
		extras?: any;
	};
	parser: GLTFParser;
	userData: any;
}
```

But `nodes` exists
-

**Comment by helgardferreira** [comment]
Yes, this is extremely frustrating. Additionally, I've seen several examples use the helper as such:
`js
const { nodes, materials } = useGLTF<GLTFResult>("/model.glb")
`
And yet useGLTF's TypeScript declaration file doesn't support generics...

So far the TypeScript support for this lib has been disappointing to say the least.

**Comment by bartlomiej-krakowski** [comment]
Extend the base interface like this:
```
import { GLTF, GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Head: THREE.Mesh /* replece with your nodes names */
  }
  materials: {
    base: THREE.MeshStandardMaterial
    inner: THREE.MeshStandardMaterial
  }
}

const { nodes } = useLoader<GLTFResult>(GLTFLoader, "./david_head.gltf");
```

**Comment by drcmda** [comment]
gltfjsx has a types option, it generates a proper interface for all contents. nodes, materials is not part of threejs, this is r3f. but since useLoader can handle any arbitrary loader it cant give you types, they must be added like in the example above
