### ISSUE TITLE
Enviroment/useEnviroment breaks when queryparameters are present in URL's

### ISSUE THREAD

**Issue by mynameisgump** [pmndrs/drei#1573]
- `three` version: "^0.154.0"
- `@react-three/fiber` version: "^8.13.5"
- `@react-three/drei` version: "^9.78.2"
- `node` version: "v18.16.1"
- `npm` (or `yarn`) version: "9.5.1"

### Problem description:

When using useEnvironment, if the url contains query parameters the file extension is flagged as unrecognized with the error message: "useEnvironment: Unrecognized file extension". This began to occur after updating from the previous versions:

- "@react-three/drei": "^8.20.2"
- "@react-three/fiber": "^7.0.29"
- "three": "^0.141.0"

### Relevant code:
Example of code that does not work:
```js
<Environment files={https://myurl.com/myfile.hdr?myparam=foo} />
```

### Suggested solution:
Potentially change the line of code in useEnvironment to allow URL's for this case:
https://github.com/pmndrs/drei/blob/96902c7db0b5b1bebf64a1ea36c62d895add38e5/src/core/useEnvironment.tsx#L44C1-L44C1

**Comment by drcmda** [comment]
could you make a pr for this?

**Comment by mynameisgump** [comment]
> could you make a pr for this?

PR has been created:
https://github.com/pmndrs/drei/pull/1574

**Comment by mynameisgump** [comment]
@drcmda hey this would actually be my first PR contributing to an open source project so I was just wondering if I needed to do anything else to request a review. Currently says that "the workflow requires approval from a maintainer." since I'm an outside contributor, apologies ahead of time if I've done anything wrong 🙃
