### ISSUE TITLE
ScreenQuad stopped rendering

### ISSUE THREAD

**Issue by projekt86** [pmndrs/drei#1578]
- `three` version: >= 1.151.0
- `@react-three/fiber` version: 8.13.5
- `@react-three/drei` version: 9.78.2
- `node` version: 16

### Problem description:
Since `threejs` version 1.151.0 ScreenQuad stopped rendering and is throwing errors:
- `THREE.BufferGeometry.computeBoundingBox(): Computed min/max have NaN values. The "position" attribute is likely to have NaN values`
- `client.js:1 THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.`

<img width="592" alt="Screenshot 2023-07-16 at 22 50 54" src="https://github.com/pmndrs/drei/assets/27769440/9fb1bf09-27d2-4d9e-bd2e-a069d3073eab">

### Relevant code:

[sample repo](https://github.com/projekt86/three-drei-buffer-geometry-bug-repo/blob/main/src/pages/index.tsx)

**Comment by davcri** [comment]
![image](https://github.com/pmndrs/drei/assets/6860637/0dbc18c7-5381-4fac-bdd1-ec95f3303932)

This happens on the storybook as well (upgrading ThreeJS to r155).
