### ISSUE TITLE
detect-gpu moving forwards (2.0.0)

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [pmndrs/drei#158]
Hi drei maintainers,

I noticed you are using `DetectGPU` (https://github.com/pmndrs/drei#usedetectgpu) and I would like to inform you that I am planning to release a 2.0.0 version in the near future with the following improvements:

- Improved method of determining the GPU tier based on benchmark FPS (screen dimension normalised)
- Deobfuscation of iOS 12.2+ devices and Safari 14+ browsers
- Improved tests
- Reduced library size with 60%! (2.86 KB)
- Dynamic loading of benchmark data based on detected renderer

It is that last point that I am a bit worried about for your library. Because the benchmark data is roughly 40kb gzipped and the user only needs a small chunk of that data (e.g. if you have an Intel GPU it only fetches the Intel benchmark data) we have decided on having users download the benchmark data from the Github repository and serving that on a public endpoint they control. Whilst this makes sense as an end-user it doesn't work for intermediate libraries such as yours.

I would love to keep support for your library but this is clearly something we will have to sort out before publishing.

If you have any feedback, notes or ideas they are welcome in https://github.com/TimvanScherpenzeel/detect-gpu/pull/30.

**Comment by TimvanScherpenzeel** [comment]
Hi, I've come up with a proposal. The syntax for library use would be the following:

```ts
// Application
import { getGPUTier } from 'detect-gpu';

// Data (use a bundler with a JSON file loader)
import benchmarks from 'detect-gpu/benchmarks/all.json';

(async () => {
  const data = await getGPUTier({
    override: {
      // This overrides the default benchmark loader 
      // (loads from within benchmarks structure using filename e.g. `benchmarks['d-amd.json']`)
      loadBenchmarks: async (file: string) => await (benchmarks as any)[file],
    },
  });

  console.log(data);
})();
```

Alternatively you could encourage end-users of the hook to serve the benchmarks on a public URL (this is the preferred method as it prevents the loading of unnecessary kB's). I'll provide a clear download link in the README.md of the library to download the benchmark data.

**Comment by gsimone** [comment]
I like this approach, it's similar to what we do with the draco loader, giving users the ability to load their own but defaulting to CDN. Instead of importing the json we could use unpackage like:

```
import { getGPUTier } from 'detect-gpu';

const benchmarks = 'https://unpkg.com/detect-gpu@latest/benchmarks/all.json';

(async () => {
  const data = await getGPUTier({
    override: {
      // This overrides the default benchmark loader 
      // (loads from within benchmarks structure using filename e.g. `benchmarks['d-amd.json']`)
      loadBenchmarks: async (file: string) => await (benchmarks as any)[file],
    },
  });

  console.log(data);
})();
```

This would better eliminate tree-shaking and bundle size problems, loading the json only when the test is being used. What do you think?

**Comment by TimvanScherpenzeel** [comment]
Sounds great! I'll make sure that is supported.

**Comment by TimvanScherpenzeel** [comment]
@gsimone the final syntax will be as follows, no special handling required!

The library is automatically pointed to `https://unpkg.com/detect-gpu@next/dist/benchmarks` so it can dynamically pick the correct benchmarks (e.g. https://unpkg.com/detect-gpu@next/dist/benchmarks/d-amd.json).

```ts
import { getGPUTier } from 'detect-gpu';

(async () => {
  const gpuTier = await getGPUTier();

  console.log(gpuTier);

  // Example output:
  // {
  //   "tier": 1,
  //   "isMobile": false,
  //   "type": "BENCHMARK",
  //   "fps": 21,
  //   "gpu": "intel iris graphics 6100"
  // }
});
```

I'm planning to release the 2.0.0 version as `@latest` in the next few days.
