### ISSUE TITLE
TrackballControls don't work with frameloop="demand"

### ISSUE THREAD

**Issue by romarybi** [pmndrs/drei#1588]
The title says it all. TrackballControls only work with frameloop set to "always". No such issue found in similar OrbitControls. 
Sandbox: [https://codesandbox.io/s/dreamy-frog-8tvnkn?file=/src/App.js](https://codesandbox.io/s/dreamy-frog-8tvnkn?file=/src/App.js)

**Comment by EliCDavis-Vinci** [comment]
Still a bug...
