### ISSUE TITLE
What is that? I try lots ways to clean this err but failed:]]]

### ISSUE THREAD

**Issue by laoLiDeHao** [pmndrs/drei#1598]
"react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
Failed to parse source map from 'D:\code\devs\ExpThreejs\my-app\node_modules\@mediapipe\tasks-vision\vision_bundle_mjs.js.map' file: Error: ENOENT: no such file or directory, open 'D:\code\devs\ExpThreejs\my-app\node_modules\@mediapipe\tasks-vision\vision_bundle_mjs.js.map'

**Comment by sergioc32** [comment]
I've got the same error and tried clearing node models and everything else I could think of but error hasn't gone away. Also using     "react": "^18.2.0",  "react-dom": "^18.2.0", "react-scripts": "^5.0.1".

**Comment by Mascariddu8** [comment]
Same problem for me, clearing node modules didn't work. Any news?
