### ISSUE TITLE
Unable to resolve "@mediapipe/tasks-vision" from "node_modules\@react-three\drei\native\index.js"

### ISSUE THREAD

**Issue by Guiladg** [pmndrs/drei#1599]
- `three` version: 0.155
- `@react-three/fiber` version: 8.13.6
- `@react-three/drei` version: 9.80.1
- `node` version: v18.15.0
- `npm` version: 9.5.0

### Problem description:

I get the following error when trying to use this library in **React Native**:

`Unable to resolve "@mediapipe/tasks-vision" from "node_modules\@react-three\drei\native\index.js"`

**Comment by qalqi** [comment]
+1 in react native

**Comment by Diego-Fdez** [comment]
+2 in react native
