### ISSUE TITLE
SSAA / TAA postprocessing makes scene darker

### ISSUE THREAD

**Issue by Russo-creation** [pmndrs/drei#1601]
Hi,

I tried to add SSAA and TAA to the project but I noticed that the more **Sample Level** I'm setting the screen is getting darker - this happens with the fresh version of r3f. in three.js examples it works good TAA https://threejs.org/examples/webgl_postprocessing_taa.html and SSAA https://threejs.org/examples/?q=ssaa#webgl_postprocessing_ssaa

Here is the codesanbox fiber 8.13.3: https://codesandbox.io/s/enter-portals-forked-5vpqtn?file=/src/postProccesing.js:456-457
<img width="683" alt="image" src="https://github.com/pmndrs/react-three-fiber/assets/69282925/648f4f97-9263-453e-a0cd-0a91203a5053">

and to compare code sandbox fiber 8.12.0: https://codesandbox.io/s/blazing-fire-mz5fgs?file=/src/postProccesing.js:531-532
<img width="735" alt="image" src="https://github.com/pmndrs/react-three-fiber/assets/69282925/9266f5d7-d10e-4ab5-82e7-48554c4acd1c">

**Comment by Russo-creation** [comment]
Here I prepared repository to reproduce https://github.com/Russo-creation/ssaa-bug with dependency list
* @react-three/drei": "^9.58.4
* @react-three/fiber": "^8.13.6
* three": "^0.155.0"

**Comment by Russo-creation** [comment]
After couple of tests with three-stdlib (local version) it looks like screen is not going darker with "three-stdlib": "^2.22.5" I can't test versions 2.23.X because I'm getting an errors. I don't know if it's working fully because background HDRI is reviling layers - this can be caused by halfTones or something (I don't know how to switch it)

<img width="1656" alt="image" src="https://github.com/pmndrs/drei/assets/69282925/cdb933b2-7ef9-4cf5-90d3-63871dd24ac7">

**Comment by CodyJasonBennett** [comment]
Thanks for the thorough reproduction, I'll take a look.

**Comment by CodyJasonBennett** [comment]
I released three-stdlib@2.24.2 with https://github.com/pmndrs/three-stdlib/pull/277 which should address darkening. Remaining banding I can only attribute to undersampling and/or lack of precision. I don't believe we use fp16 there yet.

**Comment by Russo-creation** [comment]
Thanks for the fix- sampleLevel it's not affecting on scene darkening, but SSAA is still affecting on the colors (is adding more contrast or something as in screenshots above) along with unrealBloom scene is glowing a lot even when threshold is set above 1. 

It would be cool to have it fixed because it makes impossible to smooth Alpha hash (feature from three r 154) https://threejs.org/examples/?q=has#webgl_materials_alphahash for improving quality and react-three/postprocessing (vanruesc) does not support this type of antyaliasing.
