### ISSUE TITLE
GradientTexture doesn't get detached/unmounted?

### ISSUE THREAD

**Issue by lukehorvat** [pmndrs/drei#1605]
- `three` version: 0.155.0
- `@react-three/fiber` version: 8.13.6
- `@react-three/drei` version: 9.80.1
- `node` version: 20.5.0
- `npm` (or `yarn`) version: 9.8.0

### Problem description:

I want to conditionally swap out a material with an attached GradientTexture for another material. However the GradientTexture doesn't seem to get detached/unmounted properly. As a result the color of the new material is affected.

### Relevant code:

Here's a repro: https://codesandbox.io/s/gradienttexture-bug-7dj57j

When the checkbox is unchecked, the sphere _should_ be a flat yellow:

![expected](https://github.com/pmndrs/drei/assets/1034878/0804f34f-6240-4328-b4fc-583fe3974d93)

But instead the GradientTexture still seems to be applied?

![actual](https://github.com/pmndrs/drei/assets/1034878/d4800b45-816c-4553-808f-70f528583472)

I also tried adding a `useLayoutEffect` that sets the material's `map` to null when I want to "clean up" the GradientTexture, but that didn't seem to work either...

Is this a bug or am I missing something?

### Suggested solution:

\-

**Comment by CodyJasonBennett** [comment]
Three.js materials need to be flagged for update when adding/removing textures. In your case, you'd need to set `material.needsUpdate = true`.

**Comment by lukehorvat** [comment]
Oh, so due to the way's React's diffing works, it's the same material instance because `meshBasicMaterial` is used in both the true and false parts of the ternary... 😑

And if I was to change one side of the conditional to be `meshLambertMaterial`, then a new material instance would be created every time and I wouldn't need to do `material.needsUpdate = true`. https://codesandbox.io/s/gradienttexture-bug-forked-qlldyx

That's an annoying little "gotcha", but it makes sense. Thanks, I'll close this.
