### ISSUE TITLE
useDetectGPU props object is required, while not required by detect-gpu package

### ISSUE THREAD

**Issue by aVileBroker** [pmndrs/drei#161]
In all the examples of the hook, it is used without passing anything into the hook params, which in typescript throws an error, as props is required.

The [typing on detect-gpu](https://github.com/TimvanScherpenzeel/detect-gpu#usage) suggests that all of its params are optional, which makes it seem that `useDetectGPU()` should work, but it still expects something, and an empty object causes it to not memoize the value properly, creating a new webgl context every render (because {} !== {}).

I'll try and put up a PR for this to help out if this seems reasonable!

**Comment by aVileBroker** [comment]
https://github.com/pmndrs/drei/pull/162

**Comment by TimvanScherpenzeel** [comment]
`detect-gpu@2.0.0` will have strong default values so props can stay optional.

**Comment by aVileBroker** [comment]
Perfect! As long as the props object itself is set to optional as well we should be good with v1 and v2

**Comment by gsimone** [comment]
Closed by #162, thank you @aVileBroker
