### ISSUE TITLE
Curious why the magic number 16777271 (used in Html)?

### ISSUE THREAD

**Issue by unphased** [pmndrs/drei#163]
0xFFFFFF is 16777215
0x1000000 is 16777216
0x1000001 is 16777217

It seems like the magic number is 0x1000001 with the last 2 decimal digits accidentally transposed? 

If so, what would be the significance of 0x1000001 over either of the other two options above?

**Comment by AndrewPrifer** [comment]
@unphased the max z-index value on Safari 3 was 16777271.

**Comment by joshuaellis** [comment]
This doesn't seem to require any help so I'm going to close it, we can revisit if changes are needed.
