### ISSUE TITLE
CameraControls does not preserve settings when camera is edited

### ISSUE THREAD

**Issue by ghost** [pmndrs/drei#1634]
- `three` version: 0.155.0
- `@react-three/fiber` version: 8.13.7
- `@react-three/drei` version: 9.66.6
- `yarn` version: 1.22.19

### Problem description:

When using the CameraControls, the properties that have been set are not preserved when the camera changes (e.g. when changing from a PerspectiveCamera to an OrthographicCamera).

Since the properties of the CameraControls are directly editable I assume it is intended behavior to be able to change them after initialization. Therefore I would also assume they should be preserved when changing the camera.

### Relevant code:

[The section of  CameraControls causing this issue can be found here](https://github.com/pmndrs/drei/blob/6ddc5ec042f69e52106a66a8ebeeb78de38f60de/src/core/CameraControls.tsx#L82)

```
  const controls = useMemo(() => new CameraControlsImpl(explCamera), [explCamera])
```

Every time the camera is updated, a new CameraControl is created and the previous settings are lost.

### Suggested solution:

Either do not allow the properties to be changed after initializing CameraControls, or preserve the settings within the CameraControls component.

**Comment by dongho-shin** [comment]
I think it's not a bug `const controls = useMemo(() => new CameraControlsImpl(explCamera), [explCamera])` this way is more declarative. so if you want succession, you better use fromJSON, toJSON function in camera-controls ref(https://github.com/yomotsu/camera-controls?tab=readme-ov-file#tojson)
