### ISSUE TITLE
useGLTF loader does not work with any glb other than the default suzanne.glb

### ISSUE THREAD

**Issue by LinuxIsCool** [pmndrs/drei#164]
When I put in a custom glb of any kind that is exported from blender, I see no object, only a grey screen. I checked the network traffic to make sure that the asset is getting a 200. 

It's this story here: https://github.com/pmndrs/drei/blob/master/.storybook/stories/useGLTF.stories.js

Thank you!

**Comment by gsimone** [comment]
Are you using draco compression when exporting? Because the example suzanne glb does and so the example uses  draco loader

**Comment by johnmarinelli** [comment]
@LinuxIsCool could you link a sample asset to use as a test case?

**Comment by gsimone** [comment]
Closed since inactive
