### ISSUE TITLE
worldCamProjPosition error on <Grid/>

### ISSUE THREAD

**Issue by jeffscottward** [pmndrs/drei#1644]
- `three` version: latest served from esm.sh
- `@react-three/fiber` version: latest served from esm.sh
- `@react-three/drei` version: latest served from esm.sh
- `node` version: v20.0.0
- `npm` (or `yarn`) version: ?

### Problem description:

Latest update as of 30 mins ago causes Grid to throw an error.
`Uncaught TypeError: Cannot read properties of undefined (reading 'worldCamProjPosition')      Grid.js: 109`

### Relevant code:

```js
  const App = () => {
        return (
          <Canvas>
            <Grid
              position={[0, -3, 0]}
              args={[20, 20]}
              cellColor='#BFA301'
              sectionColor='#BFA301'
            />
          </Canvas>
        );
      };
      createRoot(document.getElementById("root")).render(<App />);
```

**Comment by jeffscottward** [comment]
Is anyone else seeing this or is it just me?

**Comment by Maxssobolev** [comment]
+1

**Comment by geyang** [comment]
still exists on current version `v9.109.2`

**Comment by Archimagus** [comment]
I am still getting this issue.
