### ISSUE TITLE
View for React-Native

### ISSUE THREAD

**Issue by bchang1217** [pmndrs/drei#1650]
Is there anyway to make this work?

**Comment by ryadhoussam** [comment]
where is the code ?

**Comment by CodyJasonBennett** [comment]
Source is https://github.com/pmndrs/drei/blob/master/src/web/View.tsx. I realize the naming is a bit awkward on react-native, but you can measure layout dimensions with https://reactnative.dev/docs/view#onlayout.

**Comment by bchang1217** [comment]
My

> Source is https://github.com/pmndrs/drei/blob/master/src/web/View.tsx. I realize the naming is a bit awkward on react-native, but you can measure layout dimensions with https://reactnative.dev/docs/view#onlayout.

**Comment by bchang1217** [comment]
My understanding of the issue is that View needs to track a React DOM, but I'm unsure how to track a React-Native View

**Comment by MainzerKaiser** [comment]
So, a usage of several Views in one Canvas does not work in react native?
Something like this:
https://codesandbox.io/p/sandbox/view-skissor-1wmlew?file=%2Fsrc%2FApp.js%3A15%2C32

For now: Module '"@react-three/drei/native"' has no exported member 'View'.ts(2305)
