### ISSUE TITLE
<ScrollControls> from drei library is causing an "issuse" with <Html>

### ISSUE THREAD

**Issue by Padjex** [pmndrs/drei#1654]
When I add <ScrollControls>, even if I'm not controlling the camera, the <Html> tag that should be in a specific position in the 3D scene gets displaced incorrectly when scrolling. It should actually move based on the camera.

This is the code where you can see what the problem is: https://codesandbox.io/s/da-ttgdx7

Shouldn't it be the case that even when scrolling, the <Html> tag remains in the same position in the 3D scene, meaning it moves relative to the camera's movement?

**Comment by enderh3art** [comment]
i think this is being addressed in this PR: https://github.com/pmndrs/drei/pull/1126
