### ISSUE TITLE
Cloud image file TIME_OUT

### ISSUE THREAD

**Issue by godwinpinto** [pmndrs/drei#1666]
- `three` version: 0.146.0
- `@react-three/fiber` version: 8.9.1
- `@react-three/drei` version: 9.86.0
- `node` version: 20.7.0
- `npm` (or `yarn`) version: 10.1.0

### Problem description:
I am getting error while integrating clouds.

### Relevant code:
<Cloud segments={40} bounds={[10, 2, 2]} volume={10} color="orange" />

### Suggested solution:
I looked as the error logs. Looks like https://raw.githubusercontent.com/pmndrs/drei-assets/9225a9f1fbd449d9411125c2f419b843d0308c9f/cloud.png is missing

**Comment by drcmda** [comment]
seems to load for me, but in any case, copy the cloud into your /public dir and use `<Canvas texture={useTexture("cloud.png")}` that's the safest and you wouldn't be beholden to fragile cdns.

**Comment by Sixlty** [comment]
You can use `<Clouds texture={'/cloud.png'}><Cloud segments={40} bounds={[10, 2, 2]} volume={10} color="orange"  /></Clouds>` to resolve it.
