### ISSUE TITLE
Setting `Object3D.DEFAULT_UP` with `GizmoViewcube`

### ISSUE THREAD

**Issue by sylee957** [pmndrs/drei#1668]
- `three` version: 0.151.3
- `@react-three/fiber` version: 8.12.0
- `@react-three/drei` version: 9.58.4
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:

If I configure `Object3D.DEFAULT_UP` to change the coordinate system to Z-up, the texts in viewcube is not facing in correct direction.

![wfqh8n csb app_](https://github.com/pmndrs/drei/assets/34944973/423e5370-4470-4156-b5d1-ea54aee4da30)

### Relevant code:

https://codesandbox.io/s/gizmohelper-z-up-wfqh8n?file=/src/App.tsx:235-353

**Comment by lidaltonlima** [comment]
Conseguiu resolver? Estou com o memo problema.

**Comment by suiramdev** [comment]
Re-open this please!
