### ISSUE TITLE
API suggestion: export component prop types

### ISSUE THREAD

**Issue by AndrewPrifer** [pmndrs/drei#167]
A use case that often comes up is the need to extend existing components, while retaining some or all of their original props. It would be more convenient to do this if the component props were also exported, e.g. for `Sky`, there would also be a `SkyProps` type export.

The workaround is not too hard but requires a bit of TypeScript know-how:

```ts
import { Sky as SkyImpl } from 'drei';

type SkyImplProps = Parameters<typeof SkyImpl>[0];

interface SkyProps extends SkyImplProps {
    // ...
}
```

Compare with:

```ts
import { Sky as SkyImpl, SkyProps as SkyImplProps } from 'drei';

interface SkyProps extends SkyImplProps {
    // ...
}
```

**Comment by giulioz** [comment]
There should be no need:
```typescript
type SkyProps = React.ComponentProps<typeof Sky>;
```

**Comment by giulioz** [comment]
I mean, I would prefer export as least types as possible, especially the ones that can be done with type expressions.

What do you think @stephencorwin ?

**Comment by AndrewPrifer** [comment]
@giulioz cool, I didn't know that existed, looks even better than my workaround because it handles refs. The reason I suggested is that all components already have a `Prop` type neatly defined above them, exporting them wouldn't be a few additional characters per file.
