### ISSUE TITLE
Bundle increase by 200kb

### ISSUE THREAD

**Issue by caticHarun** [pmndrs/drei#1671]
### Before update
@react-three/drei   9.56.24   

### After update
@react-three/drei   9.86.3

### Problem description:

The bundle size increases by 200kb

**Comment by CodyJasonBennett** [comment]
Can you share a project or lockfile? This likely comes from a dependency, so we need to track it down.

**Comment by caticHarun** [comment]
Unfortunately I cannot share anything about the project. 

I checked all imports and I only import from "@react-three/drei"

When I go `npm update @react-three/drei --save` and run `npm run build` (NextJS) my bundle size increases by 200kb

**Comment by drcmda** [comment]
could you please clamp it down to the update that's causing the jump? go down in half steps until you have the release that does it.

**Comment by caticHarun** [comment]
Hello. I have found an update which increases the bundle size by 200kb. It is [v9.68.5](https://github.com/pmndrs/drei/releases/tag/v9.68.5)

**Comment by CodyJasonBennett** [comment]
Seems to correspond with #1457. What does `npm ls three-stdlib` give you? Recent versions of both libraries should tree-shake, perhaps we need to bump it again.

**Comment by caticHarun** [comment]
Before the update: three-stdlib@2.21.8
After the update: three-stdlib@2.26.13

**Comment by CodyJasonBennett** [comment]
Which version of Next is this? Are you doing anything special with `transpileModules` or SWC minification?

I'd see if `npm i three-stdlib@2.26.3` reverts to before the size increase.

**Comment by CodyJasonBennett** [comment]
I put out `2.27.1` of `three-stdlib` with #304 to see if that resolves things. It inlines deps which tree-shake fine elsewhere, but still pop up when I trace through Next.

**Comment by stephent** [comment]
See also https://github.com/pmndrs/drei/discussions/1660
