### ISSUE TITLE
Edge Effect not working currectly

### ISSUE THREAD

**Issue by sharifiniaa** [pmndrs/drei#1674]
**Issue Description:**

When utilizing the Edge Effect to add edges to a shape in my project using React Three Fiber, I encountered an issue where the shape is not displayed correctly in certain sections. Specifically, the edges are somehow positioned at the bottom area of the shape, and the rendering appears messy.

**Steps to Reproduce:**

1. Run the project with the specified versions of Next.js, React Three Fiber, and @react-three/drei.
2. View the 3D shape with the applied Edge Effect.

**Expected Behavior:**

The Edge Effect should accurately outline the shape, without any displacement or misalignment issues, providing a clear and defined edge to the shape.

**Actual Behavior:**

The Edge Effect is not displaying the shape as expected, and it appears misplaced, particularly in the bottom area of the shape.

**Environment:**

- Project: Next.js 13
- React Three Fiber: Latest version
- @react-three/drei: Latest version

**Code Snippets:**

Model Section:
```jsx
import {Edges, useGLTF} from '@react-three/drei';
import {TViewProps} from '../../types';

export function Model({actives, second}: TViewProps & {second?: boolean}) {
  const {nodes} = useGLTF('/3dnew.gltf');
  const selectedColor = '#f24c3d';

  return (
    <group dispose={null}>
      <group rotation={!second ? [0.5, 0.5, 0] : [0.5, -0.7, 0]}>
        <mesh geometry={nodes.mesh_0.geometry}>
          <Edges color='blue' renderOrder={11000}/>
          <meshStandardMaterial color={actives?.top ? selectedColor : '#ddd'} />
        </mesh>
        <mesh geometry={nodes.mesh_1.geometry}>
          <Edges color='blue' renderOrder={11000} />
          <meshStandardMaterial color={actives?.side ? selectedColor : '#ddd'} />
        </mesh>
        <mesh geometry={nodes.mesh_2.geometry}>
          <Edges color='blue' renderOrder={11000} />
        <meshStandardMaterial color={actives?.behind ? selectedColor : '#ddd'} />
        </mesh>
        <mesh geometry={nodes.mesh_3.geometry}>
          <Edges color='blue' renderOrder={11000} />
          <meshStandardMaterial transparent />
        </mesh>
      </group>
    </group>
  );
}
```

Rendering Section:
```jsx
import {Environment, GizmoHelper, GizmoViewport, TrackballControls} from '@react-three/drei';
import {Canvas} from '@react-three/fiber';
import {Suspense} from 'react';
import {Model} from './Model';
import {TViewProps} from '../../types';

const ThreeDView = (props: TViewProps) => {
  return (
    <Suspense fallback={<h1>loading ....</h1>}>
      <Canvas camera={{position: [0, 0, 1],zoom: 500,far: 100}} orthographic={true}>
        <ambientLight intensity={0.5} />
        <spotLight intensity={0.5} angle={0.2} penumbra={1} position={[10, 15, 10]} />
        <Model {...props} />
        <Environment preset="city" />
        <TrackballControls rotateSpeed={5} />
        <GizmoHelper alignment="bottom-right" margin={[50, 50]}>
          <GizmoViewport labelColor="white" axisHeadScale={1} />
        </GizmoHelper>
      </Canvas>
    </Suspense>
  );
};

export default ThreeDView;
```

**Screenshots:**

![Screenshot 1402-07-12 at 5 04 25 in the afternoon](https://github.com/pmndrs/react-three-fiber/assets/45081278/55a3baa2-e1aa-4c24-b62c-34e5586f14a8)
![Screenshot 1402-07-12 at 5 05 47 in the afternoon](https://github.com/pmndrs/react-three-fiber/assets/45081278/62660841-723f-4a7a-a837-6ebfca51eefd)
Please let me know about potential solutions to address this issue and achieve the desired rendering of the shape with the Edge Effect.

---

**Comment by drcmda** [comment]
edges just uses threejs edgesgeometry, if there's something to do it would be upstream i guess. but edgesgeo for sure is pretty poor, it basically guess-stimates which edges to draw with an angle.

**Comment by sharifiniaa** [comment]
> edges just uses threejs edgesgeometry, if there's something to do it would be upstream. but edgesgeo for sure is pretty poor, it basically guess-stimates which edges to draw with an angle.
> 
> the whole component isn't more than this
> 
> ```tsx
> export const Edges: ForwardRefComponent<Props, THREE.LineSegments> = React.forwardRef(
>   (
>     { userData, children, geometry, threshold = 15, color = 'black', ...props }: Props,
>     fref: React.ForwardedRef<THREE.LineSegments>
>   ) => {
>     const ref = React.useRef<THREE.LineSegments>(null!)
>     React.useLayoutEffect(() => {
>       const parent = ref.current.parent as THREE.Mesh
>       if (parent) {
>         const geom = geometry || parent.geometry
>         if (geom !== ref.current.userData.currentGeom || threshold !== ref.current.userData.currentThreshold) {
>           ref.current.userData.currentGeom = geom
>           ref.current.userData.currentThreshold = threshold
>           ref.current.geometry = new THREE.EdgesGeometry(geom, threshold)
>         }
>       }
>     })
>     React.useImperativeHandle(fref, () => ref.current)
>     return (
>       <lineSegments ref={ref} raycast={() => null} {...props}>
>         {children ? children : <lineBasicMaterial color={color} />}
>       </lineSegments>
>     )
>   }
> )
> ```
> 
> if you're missing edges try adjusting the angle/threshold.

Thank you for your suggestion it is so weird for me when changing the scale property to more than 1.2; all the edges are valid, but there is a priority in showing them like z-index in CSS!  Also for the custom Edge component, there is some challenge because I use a "gltf" file and convert that to the jsx!
<img width="529" alt="Screenshot 1402-07-12 at 11 52 11 at night" src="https://github.com/pmndrs/drei/assets/45081278/655411aa-06a2-4054-8ef8-30c19c895a3f">

**Comment by sharifiniaa** [comment]
Finally, I figured out the solution for this problem and that was using polygonOffsetFactor={1} and polygonOffset to make priority.

for example:

```jsx
       <mesh geometry={nodes.mesh_1.geometry}>
          <meshStandardMaterial transparent polygonOffsetFactor={1} polygonOffset />
          <Edges />
        </mesh>
```
