### ISSUE TITLE
<Orbitcontrols /> blocks click events on <Html  /> elements (button or similar)

### ISSUE THREAD

**Issue by saumac** [pmndrs/drei#1675]
- `three` version: 0.157.0
- `@react-three/fiber` version: 8.14.3
- `@react-three/drei` version: 9.81.0
- `node` version: v18.18.0
- `npm` (or `yarn`) version: 1.22.19

### Problem description:

We have been using OrbitControls for some time now but after a recent package upgrade, the click events on Html elements stopped working (no events). Click events works perfectly fine if we remove OrbitControls from our web app and we have not managed to figure out why it blocks those type of event.  

Is anyone else experiencing this?

### Relevant code:

No relevant code atm.

### Suggested solution:

No suggested solution (unfortunantley)

**Comment by saumac** [comment]
After some investigation:
- The issue seems to be related to package: three-stdlib
- Everything works as expected if we manually downgrade three-stdlib to 2.25.0 in our yarn.lock file (for the dependency in package @react-three/drei@9.86.3)

Should this issue be added/moved to three-stdlib or?

**Comment by CodyJasonBennett** [comment]
Perhaps it should. Maybe it's related to https://github.com/pmndrs/three-stdlib/pull/297. Try `npm i three-stdlib@2.26.12`.

**Comment by gsimone** [comment]
Change was rolled back and released in https://github.com/pmndrs/three-stdlib/releases/tag/v2.27.2
Resolving your three-stdlib to this version should fix it - I'm still to verify myself.

@CodyJasonBennett should I make a PR to bump three-stdlib here?

**Comment by CodyJasonBennett** [comment]
Sure. If it wasn't a breaking change, I'd let it resolve transiently.

**Comment by saumac** [comment]
Thanks for the quick fix and reply.
