### ISSUE TITLE
Html jumpy when rotating camera.

### ISSUE THREAD

**Issue by ming-deng** [pmndrs/drei#168]
Hi,

When we rotate the camera, there is always ONE Html that's jumpy. The other Html are solid in their position relative to their Object.  Can be seen here in the storybook https://drei-storybook.netlify.app/?path=/story/abstractions-html--html-st the "First" Html is jumpy as you rotate the camera with click and drag up/down.

**Comment by gsimone** [comment]
This doesn't seem to be an issue anymore, please reopen if needed
