### ISSUE TITLE
Error: Could not load 21: undefined in React Native Expo

### ISSUE THREAD

**Issue by ArjunPatidarRadix** [pmndrs/drei#1680]
I;m trying to load the GLB model in react native but I'm always getting this error I'm using the same code from 
[](https://docs.pmnd.rs/react-three-fiber/tutorials/v8-migration-guide#react-native-support)
![Screenshot_1696850193](https://github.com/pmndrs/drei/assets/108668432/1ee9d856-009b-458d-a246-257cece052f4)

- `three` version:
- `@react-three/fiber` "^8.14.4":
- `@react-three/drei` "^9.86.3":
- `node` v16.15.0:
- `npm`  8.5.5:

### Problem description:

Error: Could not load 21: undefined

This error is located at:
    in Unknown
    in FiberProvider
    in CanvasWrapper (created by AvatarScreen)
    in AvatarScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by RootStackNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by RootStackNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by RootStackNavigator)
    in RootStackNavigator (created by App)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
    

### Relevant code:
`import React, { Suspense } from 'react'
import { useGLTF } from '@react-three/drei/native'
import { Canvas } from '@react-three/fiber/native'
import modelPath from './assets/monkey.glb'

function Model(props) {
  const { scene } = useGLTF(modelPath)
  return <primitive {...props} object={scene} />
}

export default function App() {
  return (
    <Canvas>
      <Suspense fallback={null}>
        <Model />
      </Suspense>
    </Canvas>
  )
}`tsx

### Suggested solution:

It should load the 3d model glb or gltf file in mobile and web

**Comment by CodyJasonBennett** [comment]
This was fixed upstream at https://github.com/pmndrs/react-three-fiber/issues/3036.
