### ISSUE TITLE
TypeError: Object.defineProperty called on non-object ( mediapipe/tasks-vision )

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#1687]
This is on a next.js project with

@react-three/drei 9.88.2
@react-three/fiber 8.14.5
three 0.157.0
next 13.5.2
three-stdlib 2.27.2

This is both a symptom of something wrong with three shaking and a problem with @mediapipe/tasks-vision, also see:
- #1599 
- #1596 

<details>
<summary>Screenshot of the error:</summary>

<img width="992" alt="Screenshot 2023-10-16 at 11 09 28" src="https://github.com/pmndrs/drei/assets/1862172/9669fefc-ceb0-4983-86a2-3bd932e458af">

</details>

**Comment by CodyJasonBennett** [comment]
We're going to have to vendor that library and repackage it so it's safe for NPM.

**Comment by CodyJasonBennett** [comment]
IDK if this helps at all since Next is notoriously bad at dynamic or linked dependencies, but I have #1688 which should filter out the broken module.

**Comment by gsimone** [comment]
You rock, I'll see if this helps and create a minimal repro if I can find some time

**Comment by CodyJasonBennett** [comment]
What's bothering me is that we have E2E tests for CRA and Next from a snapshot tgz and they don't encounter this issue. If you find any preferences which are interactive, I'll be sure to add it to our coverage.
