### ISSUE TITLE
MeshRefractionMaterial: iOS 17 Crashing Issue

### ISSUE THREAD

**Issue by illestrater** [pmndrs/drei#1690]
- `three` version: 0.152.0
- `@react-three/fiber` version: 8.13.5
- `@react-three/drei` version: 9.88.2

### Problem description:

WebGL Context Lost infinite loop on iOS (17.0.3, 15 Pro Max) across all browsers (Android untested)
Sometimes will load fine (rare), but first reload will then throw the error: `null is not an object (evaluating 'gl.getShaderPrecisionFormat( gl.VERTEX_SHADER, gl.HIGH_FLOAT ).precision')`

### Relevant code:

https://codesandbox.io/s/diamond-refraction-forked-zxzj96?file=/src/App.js

**Comment by grischaerbe** [comment]
I can confirm the issue on macOS Sonoma 14.1 on a Nov '23 M3 Max MBP. The example above renders Chrome most of the times completely unresponsive and Safari throws this error (after having a hard time loading anything and producing lots of artifacts on the rendered page):

```
WebGL: context lost.
TypeError: null is not an object (evaluating 'gl.getShaderPrecisionFormat( gl.VERTEX_SHADER, gl.HIGH_FLOAT ).precision')
```

I was once able to make a short screen recording where Chrome threw another error:

```
THREE. WebGLRenderer: A WebGL context could not be created.
Reason: Could not create a WebGL context, VENDOR = 0xffff, DEVICE = Oxffff, GL_VENDOR = Google Inc. (Google), GL_RENDERER = ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (LLVM 10.0.0) (0x0000CODE)), SwiftShader driver-5.0.0), GL_VERSION = 5.0.0, Sandboxed = yes, Optimus = no, AMD switchable = no, Reset notification strategy = 0x8252, ErrorMessage = BindToCurrentSequence failed: .
```

<img width="1470" alt="Bildschirmfoto 2024-02-06 um 22 52 47" src="https://github.com/pmndrs/drei/assets/46897060/c92c6929-6ce1-4a02-83b9-484a959a2bff">

I hope that helps! 👍

**Comment by valado** [comment]
I can confirm the issue is still present using the following lib versions and Web XR Viewer [2.0 (280)] on iOS 17.4.1 (iPad 7)

```
"@react-three/fiber": "8.16.2",
"three": "0.163.0",
"@react-three/drei": "9.105.4",
```

**Comment by james-growmagination** [comment]
has any action been taken to resolve this, I am using MeshPortalMaterial in my code and it is working fine on desktop but crashing on iOS, tested on 17 and 18.

**Comment by julianneatpencil** [comment]
We are having this come up for customers. It is device specific, though not exclusively phones (one customer is on a mac laptop). It happens across different browsers, same device. We created the following example which breaks on one of the problematic devices the same way our app does which has the most up to date versions of drei and react (10 and 19 respectively): https://julianneatpencil.github.io/refractiontest/
Which leads us to believe upgrading our repo won't fix the problem. Has there been any action on this?
