### ISSUE TITLE
Safari : Cloud is not rendered / useProgram: program not valid

### ISSUE THREAD

**Issue by capsule5** [pmndrs/drei#1699]
"@react-spring/three": "9.7.2",
"@react-three/drei": "9.77.3",
"@react-three/fiber": "8.13.0",

### Problem description:

Cloud is not rendered on safari 15.

Error : WebGL: INVALID_OPERATION: useProgram: program not valid
and : THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Check : https://codesandbox.io/s/gwthnh?file=/src/App.js:564-935

**Comment by MY1112** [comment]
hi guys, I have the same question.

    "@react-three/drei": "^9.97.0",
    "@react-three/fiber": "^8.15.15",
    "three": "0.156.1",
   **Browser parameters**  
   Mozilla/5.0 (Linux; Android 13; PHK110 Build/SKQ1.221119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160065 MMWEBSDK/20231201 MMWEBID/4844 MicroMessenger/8.0.45.2521(0x28002D3D) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64
    
    Error: THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false Program Info Log: Name conflicts between an uniform and an attribute: opacity
    
   **Check:**  https://codesandbox.io/s/gwthnh?file=/src/App.js:564-935
   
   Thanks
