### ISSUE TITLE
Animating Text

### ISSUE THREAD

**Issue by Vincentjonssonqi** [pmndrs/drei#170]
First of all i want to give a big thank you for developing this and react-spring and react-three-fiber. Massive creative unlock! I have been working on building my own portfolio with all these libraries and they have been working pretty much for everything I can throw at it, with the exception of animating text. Here is what I have tried:

```import {Text} from 'drei'
import {useSpring,a} from 'react-spring/three'
function SomeComponent({show,text}:any){
var animatedProps = useSpring({
opacity:show?1.0:0.0
})
return <a.Text	
		fontSize={1},
		color="white"
	        font="https://cdn.jsdelivr.net/npm/lato-font@3.0.0/fonts/lato-bold/lato-bold.woff",
		anchorX="center",
		anchorY="middle">
	<a.meshBasicMaterial 
              attach="material" 
              color={"white"}  
              opacity={animatedProps.opacity}  
              depthWrite={false}/>
				{text}	 
				  </a.Text>
}
```
For the code above I get the following typescript error 

Error 1 `Property 'Text' does not exist on type 'WithAnimated'. Did you mean 'text'?  TS2551`

If I force typescript to ignore the error so that the webpage renders I get the following error:

Error 2`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

There is probably some obvious thing I have missed with how react-springs/three can be extended to support custom objects such as this DREI text component. If thats the case any pointers to the documentation would be much appreciated.

Another avenue I have investigated was to just use the underlying troika-three-text lib, extend react-three-fiber and use it with the react-spring  library. again everything works fine (meaning that the text renders and all is well and dandy) until I add that animated prefix (something like this <a.troikaText>). When I do, I receive the same error as before (error 2). 

Something that has worked by feels a bit hackish is just overriding the value in the onFrame method like so:

```import {Text} from 'drei'
import {onFrame,useResource} from 'react-three-fiber'
import {useSpring,a} from 'react-spring/three'
function SomeComponent({show,text}:any){
var [textRef,textMesh]:any = useResource()
var animatedProps = useSpring({
opacity:show?1.0:0.0
})
onFrame(()=>{
        if(!textMesh) return
	textMesh.material.opacity = animatedProps.opacity.get()
	textMesh.sync()
		
})
return <a.Text	
                ref={textRef}
		fontSize={1},
		color="white"
	        font="https://cdn.jsdelivr.net/npm/lato-font@3.0.0/fonts/lato-bold/lato-bold.woff",
		anchorX="center",
		anchorY="middle">
	<a.meshBasicMaterial 
              attach="material" 
              color={"white"}  
              opacity={animatedProps.opacity}  
              depthWrite={false}/>
				{text}	 
				  </a.Text>
}
```

Any ideas or pointers that would let me animate both transform and material changes such as opacity and color for the drei Text or the troika-three-text component without using the onFrame method would be very helpful. If something needs changing in the library for this to work let me know and maybe I can help with this.

**Comment by drcmda** [comment]
const AnimText = a(Text)

this works exactly like react-natives animated. the "a" namespace cannot possibly know about your text component, you can either extend that namespace, there's a method for it, or you create a animatable component like i did above.

**Comment by stephencorwin** [comment]
You can also place the Text in a group and animate the group if you only need to animate things like position, rotation, scale. It's not a perfect solution, but it is covers a lot of the animation use cases for text.

**Comment by Vincentjonssonqi** [comment]
@stephencorwin thank you for the tip. I have used this very solution to do transform animations up to this point. If only I could animate the opacity and color of an entire group of objects as well! that would be amazing.

@drcmda I tried to do as you said and voila no typescript errors. I appreciate you helping me fill that knowledge gap. Animating transforms work beautifully but animating the material properties such as opacity and color on the meshBasicMaterial does not work for me still. I took a look at how troika is implemented and noticed that the material property seems to be copied and patched: _"This material will be automatically replaced with a new material derived from it, that adds shader code to decrease the alpha for each fragment (pixel) outside the text glyphs, with antialiasing."_ [https://www.npmjs.com/package/troika-three-text]. Perhaps react-spring is animating the material but on the material instance that was replaced and not the derived material that has been attached to the text? Regardless of the reason I appreciate the help so far from both of you!
```
import {useSpring,a} from 'react-spring/three'
const AnimatedText = a(Text)

function SomeComponent({show,text}:any){
var animatedProps = useSpring({
opacity:show?1.0:0.0,
position:show?[0,0,0]:[1,2,0],
rotation?[0,0,0]:[Math.PI/4,-Math.PI/4,0]
})

return <AnimatedText	
   position={contentProps.position}
   rotation={contentProps.rotation} 
   ref={textRef}
   fontSize={1},
   color="white"
   font="https://cdn.jsdelivr.net/npm/lato-font@3.0.0/fonts/lato-bold/lato-bold.woff",
   anchorX="center",
   anchorY="middle">

     {text}

      <a.meshBasicMaterial 
      ref={textMaterialRef} 
      attach="material"
      color={"white"} 
      opacity={animatedProps.opacity} 
      depthWrite={false}/>

 </AnimatedText>
}
```

**Comment by joshuaellis** [comment]
@Vincentjonssonqi I'm going to close this, if you need more help we can reopen it 🚀
