### ISSUE TITLE
TrackballControls prevents click events

### ISSUE THREAD

**Issue by Pomevak** [pmndrs/drei#171]
I found that adding `TrackballControls` to the scene prevents click events from happening.

Here is a reproduction: <https://codesandbox.io/s/pedantic-kilby-l4ggk>

**Comment by Pomevak** [comment]
I was able to resolve this problem by importing `Trackball Controls` from `"three/examples/jsm/controls/experimental/CameraControls"` instead of "three/examples/jsm/controls/TrackballControls". Moreover, it is compatible with the `invalidateFrameLoop` flag as it manages updates internally like `OrbitControls`. See this PR  [#18483](https://github.com/mrdoob/three.js/pull/18483) of three.js.
Still don't know why the previous version blocks click events though. 😢

**Comment by Marviel** [comment]
Still having this issue.

**Comment by joshuaellis** [comment]
Hi @Marviel, 

If you can provide a minimal working example of the issue, I'd be happy to open this again and we can look into it.

**Comment by drcmda** [comment]
orbit does that, too. they swallow "onClick" on mobile. the reason for this is probably not related to drei or r3f, it's something three does most likely and in that case we couldn't fix it anyway, but would be nice to know what it is.

the current workaround is to use onPointerUp instead, which has some disadvantages but often works ok.
