### ISSUE TITLE
Fail to fetch ```.hdr``` assets from Environment @react-three/drei

### ISSUE THREAD

**Issue by itz-Amethyst** [pmndrs/drei#1710]
### The problem:
I think the problem is with the preset I've tried to change them but it didn't work on any of them
also tried to use options inside the list but no response...

- `@react-three/drei` version: ```9.54.1```

![Error](https://cdn.discordapp.com/attachments/1113510096622862375/1171851474402291783/image.png?ex=655e2ebb&is=654bb9bb&hm=8db51b0be48e570e53347feaa20819d28535396efdd4c2f4d5dc7cd3234a05d7&)

### Relevant code:

```js
<Environment preset='city'/>
        <color args={['#1d1919']} attach='background'/>
        
        <Suspense fallback={null}>
            <PresentationControls
                global
                rotation={[0.03 , -0.2 , -0.1]}
                polar ={[-0.2 , 0.2]}
                azimuth ={[-1 , 0.75]}
                config={{mass: 2 , tension: 200}}
                snap={{mass: 4 , tension: 400}}
            >
                <Float rotationIntensity={0.3} floatIntensity={1.6}>
                    <rectAreaLight
                        width={1.5}
                        height={2.65}
                        intensity={75}
                        color={'#000fff'}
                        rotation={[0 , Math.PI + 0.55 , 0]}
                        position={[0 ,0 , -1.5]}
                    />
                    <Mac position-y ={-1.2} />
                </Float>
            </PresentationControls>

            <ContactShadows opacity={0.4} scale={6} blur={2.4} position-y={-1.2}/>
        </Suspense>
```
I would appreciate any suggestions

**Comment by drcmda** [comment]
the safest option is to put your own hdrs into /public or use https://github.com/pmndrs/assets so that you are not reliant on fragile cdns.

**Comment by itz-Amethyst** [comment]
## Fixed

I found out that the problem is with the react drei version, which is fixed in the new version
So i tried

```bash
ncu 
ncu -u
```
that fixed my problem
