### ISSUE TITLE
Cloud opacity broken

### ISSUE THREAD

**Issue by pobidowski** [pmndrs/drei#1711]
- `three` version: 0.158.0
- `@react-three/fiber` version: 8.15.10
- `@react-three/drei` version: 9.88.11

### Problem description:

After this fix: https://github.com/pmndrs/drei/commit/1169c02fcfd1151fa08effb4ca7215f91b140f53 cloud opacity stopped working. It worked in version 9.88.10

### Relevant code:

https://codesandbox.io/s/clouds-forked-fmdw9r?file=/src/App.js

### Suggested solution:

Restore previous version.

**Comment by drcmda** [comment]
you most likely need to move threejs up. they renamed the include. :-/

**Comment by pobidowski** [comment]
Look at the sandbox. I'm using 0.158.0 there and its still not working

**Comment by drcmda** [comment]
@CodyJasonBennett do you know since when that problem exists in threejs? i remember now that you mentioned it needs a conditional.

**Comment by CodyJasonBennett** [comment]
r154. I believe you used the old chunk name which is not covered by normal three.js deprecation policy since this relies on string replacement. Need to use version or feature detection like #1592.

**Comment by pobidowski** [comment]
Looks like it's fixed
