### ISSUE TITLE
Html transform is not rendered in Safari

### ISSUE THREAD

**Issue by quanvanbinh** [pmndrs/drei#1719]
- `three` version: ^0.157.0
- `@react-three/fiber` version: ^8.15.9
- `@react-three/drei` version: ^9.88.11
- `node` version: v18.14.2
- `npm` (or `yarn`) version:

### Problem description:

Html with transform property on will not be rendered at the first time on Safari version 16.5 and upper. It will be rendered after I rotate. On Chrome, everything is perfectly. 

It happens with the Sandbox example below, which I get from Drei documentation

### Relevant code:

[[](https://codesandbox.io/s/6oei7)](https://codesandbox.io/s/6oei7)

**Comment by drcmda** [comment]
i think @CodyJasonBennett fixed that. it should be in, could you test?

**Comment by quanvanbinh** [comment]
Yes. I tested. There is no issue with Safari older version. But with latest Safari, it happens. You can refer to the video I recorded. First load, the markers will not be seen. They just show up after I rotate the object

Uploading Screen Recording 2023-11-16 at 2.15.49 PM.mov…

**Comment by mcav** [comment]
Ah, I stumbled on this too, first on an older `drei` with newest Safari, then with `9.88.17` too. In my case, it seems to be something with the transform calculations: the `<Html>` element's transform gets calculated to be offscreen (e.g. `transform: translate3d(-4700.772342px, -6849.707297px, 0px);`). If I hit ⌘- or ⌘+ (to change zoom level), the position recalculates and the elements become visible.

**Comment by mcav** [comment]
Actually, I see that behavior in Chrome too, so perhaps my issue is unrelated. Sorry if that's extra noise!
