### ISSUE TITLE
Add new edgesplit and curve modifiers

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#172]
New modifiers have been added to three in r122 

https://threejs.org/examples/?q=modifie#webgl_modifier_curve

Can be made similar to the other existing hooks such as https://drei.react-spring.io/?path=/story/modifiers-usesimplification--use-simplification-scene-st

https://github.com/pmndrs/drei/blob/master/src/useTessellation.tsx
https://github.com/pmndrs/drei/blob/master/src/useSimplification.tsx
https://github.com/pmndrs/drei/blob/master/src/useSubdivision.tsx

**Comment by joshuaellis** [comment]
Happy to look at this 👍🏼

**Comment by gsimone** [comment]
Awesome, dm me on twitter/discord or email or whatever if you need support

**Comment by joshuaellis** [comment]
So the `CurveModifier` is a class called `Flow` or `InstancedFlow` it doesn't have modify function, it looks like you have to add the class to the scene – [example](https://github.com/mrdoob/three.js/blob/master/examples/webgl_modifier_curve.html). Because of this, I'm wondering if it wants to be a component like `Box` where the child component is the mesh you want to travel. 

But im unfamiliar with how you regularly handle these things in the library so it'd be good to hear your thoughts.

**Comment by gsimone** [comment]
So, a bunch of thoughts:

Our component should accept:
- a mesh that will be curved
- a curve 

Will return:
- the flow instance accessible via ref

The mesh is not added to the scene, instead it's done later via flow.object3D
https://github.com/mrdoob/three.js/blob/master/examples/webgl_modifier_curve.html#L127

Updating the curve should result in an update to the curved object
https://github.com/mrdoob/three.js/blob/master/examples/webgl_modifier_curve.html#L148

So the component approach would make sense, need to think about an API

**Comment by joshuaellis** [comment]
My initial thought was something like this
```tsx
<Flow curve={new THREE.CatmullRomCurve3(...args)}>
  <Octahedron args={[3, 2]}>
    <meshNormalMaterial attach="material" flatShading color="hotpink" />
  </Octahedron>
</Flow>
```

I imagine this would work with `InstancedFlow` too?

Since this component requires 2 "elements" (the curve & mesh) we could however do a similar approach to how mesh works where you can pass two children, and it understands how to handle the geometry and material, but I don't know enough to know if that's feasible.

**Comment by joshuaellis** [comment]
Hi @gsimone any thoughts on the above implimentation suggestion?

**Comment by gsimone** [comment]
I'll be honest, I'm not sure what the best way would be, it might be worth making a prototype on codesandbox and see how we like the API. Generally, you need to make sure you don't do any unnecessary computation on re-renders (which are rare, but it's better if they are free), the rest is up to interpretation and personal preference, imo

**Comment by joshuaellis** [comment]
here's a codesandbox with my proposal, I think there's probably some room for improvement. I imagine the Types could be written better & I think theres a small type error to be amended. Be great to hear your feedback.

https://codesandbox.io/s/react-threedrei-flow-proposal-wxzqx?file=/src/Flow.tsx:366-374

**Comment by AndrewPrifer** [comment]
@joshuaellis I like the API! There are two implementation issues I can see at a glance: whenever you are setting a forwarded ref imperatively, you should be using `useImperativeRef`, and the object should change when I rerender the Flow component with different children.

**Comment by joshuaellis** [comment]
Hi @AndrewPrifer I'll look into `extend` before looking at changing to use `useImperativeHandle`. Cheers for that 👍🏼

**Comment by joshuaellis** [comment]
Hey @AndrewPrifer I've been looking at the `extend` route. `Flow` needs a mesh as part of the constructor, I thought I could do something like this to pass that –
```tsx
    <Flow ref={flowRef} curve={curve}>
      <Octahedron attach="mesh" args={[3, 2]}>
        <meshNormalMaterial attach="material" flatShading color="hotpink" />
      </Octahedron>
    </Flow>
```
But that doesn't seem to work although i'm not experience with r3f `extend`. Do you have a suggestion on how to pass this child as a mesh to the constructor?
I've also updated the above sandbox to include re-setup on child change & to use `useImperativeHandle`.

**Comment by AndrewPrifer** [comment]
@joshuaellis nice work! I don't have much time right now but I quickly looked at Flow's implementation and indeed it seems you need to pass the object in the constructor, there's no other way. Unfortunately it isn't possible to attach React elements to constructor arguments (yet, @gsimone I think this would be awesome), so your initial useEffect solution was 👌.

**Comment by gsimone** [comment]
Attaching elements to constructor arguments would be awesome, not sure if we would ever be able to, since there's a timing issue - the elements are created before their children

We should discuss this in an r3f issue though, could be interesting

**Comment by AndrewPrifer** [comment]
Yeah I imagine especially with concurrent mode this is probably a hard no.

**Comment by joshuaellis** [comment]
Thanks @AndrewPrifer I'll submit a PR with the necessary updates following the useEffect flow 💃🏼

**Comment by joshuaellis** [comment]
@gsimone should this be closed now?

**Comment by gsimone** [comment]
Yes, I forgetti! 
![image](https://user-images.githubusercontent.com/1862172/103520954-47a57580-4e78-11eb-8bdf-5d5083b7f2f7.png)
