### ISSUE TITLE
Unable to view my 3d model in the webpage

### ISSUE THREAD

**Issue by Kishore1150** [pmndrs/drei#1731]
![2023-11-30 10_19_55-Greenshot](https://github.com/pmndrs/drei/assets/110534691/c25e40ae-ffcb-48b2-b4c0-73df5a57ee90)
raw.githubusercontent.com/pmndrs/drei-assets/456060a26bbeb8fdf79326f224b6d99b8bcce736/hdri/venice_sunset_1k.hdr:1 
        
        
  Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
2index-76c68185.esm.js:1642  Uncaught Error: Could not load venice_sunset_1k.hdr: Failed to fetch)
    at Object.onError (index-76c68185.esm.js:1642:36)
    at three.module.js:41956:39
(anonymous) @ index-76c68185.esm.js:1642
(anonymous) @ three.module.js:41956
Show 2 more frames
Show less
react-reconciler.development.js:9747  The above error occurred in the <EnvironmentCube> component:

    at EnvironmentCube (http://localhost:5174/node_modules/.vite/deps/@react-three_drei.js?v=027a7193:97542:3)
    at Environment (http://localhost:5174/node_modules/.vite/deps/@react-three_drei.js?v=027a7193:97626:16)
    at Experience (http://localhost:5174/src/components/Experience.jsx:50:26)
    at Suspense
    at ErrorBoundary (http://localhost:5174/node_modules/.vite/deps/chunk-MRF6HK4J.js?v=1c649e75:16025:5)
    at FiberProvider (http://localhost:5174/node_modules/.vite/deps/chunk-MRF6HK4J.js?v=1c649e75:17754:21)
    at Provider (http://localhost:5174/node_modules/.vite/deps/chunk-MRF6HK4J.js?v=1c649e75:17372:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-reconciler.development.js:9747
callback @ react-reconciler.development.js:9815
callCallback @ react-reconciler.development.js:4279
commitUpdateQueue @ react-reconciler.development.js:4300
commitLayoutEffectOnFiber @ react-reconciler.development.js:14877
commitLayoutMountEffects_complete @ react-reconciler.development.js:16290
commitLayoutEffects_begin @ react-reconciler.development.js:16276
commitLayoutEffects @ react-reconciler.development.js:16214
commitRootImpl @ react-reconciler.development.js:18945
commitRoot @ react-reconciler.development.js:18811
finishConcurrentRender @ react-reconciler.development.js:17990
performConcurrentWorkOnRoot @ react-reconciler.development.js:17907
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less
2index-76c68185.esm.js:1642  Uncaught Error: Could not load venice_sunset_1k.hdr: Failed to fetch)
    at Object.onError (index-76c68185.esm.js:1642:36)
    at three.module.js:41956:39
(anonymous) @ index-76c68185.esm.js:1642
(anonymous) @ three.module.js:41956
Show 2 more frames
Show less
react-dom.development.js:18687  The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (http://localhost:5174/node_modules/.vite/deps/chunk-MRF6HK4J.js?v=1c649e75:17898:3)
    at FiberProvider (http://localhost:5174/node_modules/.vite/deps/chunk-MRF6HK4J.js?v=1c649e75:17754:21)
    at CanvasWrapper
    at App
    at ChatProvider (http://localhost:5174/src/hooks/useChat.jsx:21:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
update.callback @ react-dom.development.js:18720
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23391
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 15 more frames
Show less
react-dom.development.js:26923  Uncaught Error: Could not load venice_sunset_1k.hdr: Failed to fetch)
    at Object.onError (index-76c68185.esm.js:1642:36)
    at three.module.js:41956:39
(anonymous) @ index-76c68185.esm.js:1642
(anonymous) @ three.module.js:41956
Show 2 more frames
Show less
three.module.js:28560 THREE.WebGLRenderer: Context Lost.

**Comment by DrTheteSigma** [comment]
Same issue happening to me here. I can't find a fix
