### ISSUE TITLE
Using <Html> with <instancedMesh>?

### ISSUE THREAD

**Issue by clintharris** [pmndrs/drei#174]
Hi, is it possible to use `<Html>` with `<instancedMesh>`?

I'd like to use `<Html>` to render an overlay/tooltip over one of thousands of objects. Hopefully there is a way to simply change the position of an `<Html>` "singleton" (i.e., bind it to whatever mesh has been clicked).

Any tips or advice would be greatly appreciated. Thanks!

**Comment by drcmda** [comment]
no, that will break because every Html is a render root, literally ReactDOM.render(<div>...</div>, domTarget)

**Comment by clintharris** [comment]
Sorry for the naive question, but how does one re-set the position of a DOM element to an `Object3D` instance?

Any pointers to existing examples would be really appreciated. Thank you!

**Comment by clintharris** [comment]
There's probably a better solution, but in case it's helpful to someone else, here's the gist of what works for me:
```typescript

  const meshRef = useRef<InstancedMesh>();
  const groupRef = useRef<Group>();

  const onInstanceClick = (event: MouseEvent): void => {
    const dummy = new Object3D();
    meshRef.current.getMatrixAt(selectedPoint, dummy.matrix);

    const position = new Vector3();
    position.setFromMatrixPosition(dummy.matrix);
    groupRef.current?.position.set(position.x, position.y, position.z);
  };

  return (
    <>
      <instancedMesh
        args={[null as any, null as any, data.length]}
        count={data.length}
        onClick={onInstanceClick}
        ref={meshRef}
        dispose={null}
      >
        <boxBufferGeometry args={[1, 1, 1]} attach="geometry" />
        <meshStandardMaterial attach="material" />
      </instancedMesh>
      <group ref={groupRef}>
        <Html scaleFactor={50}>
          <div>Tooltip details here...</div>{' '}
        </Html>
      </group>
    </>
  );
```
