### ISSUE TITLE
three 0.159.0 logs deprecation warning for access to updateRange in Instances on every frame

### ISSUE THREAD

**Issue by Methuselah96** [pmndrs/drei#1742]
- `three` version: 0.159.0
- `@react-three/fiber` version: 8.15.12
- `@react-three/drei` version: 9.89.3
- `node` version: 20.9.0
- `npm` (or `yarn`) version: yarn 4.0.2

### Problem description:

three@0.159.0 deprecates `updateRange` and spams the console with warnings:

![image](https://github.com/pmndrs/drei/assets/693755/de360fa1-b191-41ee-a978-c1a838f4b362)

### Relevant code:

Any usage of `Instances`.

### Suggested solution:

Check to see if `addUpdateRange` exists and use that instead and/or submit an issue/PR to three to only log the deprecation warning once.

**Comment by CodyJasonBennett** [comment]
This was fixed in #1744 since [v9.90.1](https://github.com/pmndrs/drei/releases/tag/v9.90.1).
