### ISSUE TITLE
Error: Could not load venice_sunset_1k.hdr: Failed to fetch

### ISSUE THREAD

**Issue by Utkarshkapil** [pmndrs/drei#1769]
version - 9.75.0
code error 
import { Environment } from "@react-three/drei";
<Environment preset="sunset" /> 

explanation - sometimes modal loaded is not visible and it gives this error Error: Could not load venice_sunset_1k.hdr: Failed to fetch 

is there any way to fix it

**Comment by Utkarshkapil** [comment]
if anyone is facing this error just load asset locally  <Environment path="/images/" files={"venice_sunset_1k.hdr"} /> it would solve the problem

**Comment by narasimhajupally** [comment]
from where did you download that file ?

**Comment by Utkarshkapil** [comment]
https://github.com/pmndrs/drei-assets
