### ISSUE TITLE
MeshReflectorMaterial increases the number of geometries and textures dramatically

### ISSUE THREAD

**Issue by XavierYribarren** [pmndrs/drei#1777]
- `three` version: 0.159.0
- `@react-three/fiber` version: 8.15.13
- `@react-three/drei` version: 9.93.0
- `node` version: 18.17.1
- `npm` (or `yarn`) version: 9.6.7 (npm)

### Problem description:

I've added a plane with a MeshReflectorMaterial to my scene, and when I scroll down, the number of textures and geometries increases dramatically. I know the problem comes from the material because it only happened when I added it, and 'solved' it when I removed to reflector mat.

### Relevant code:

```js
 <mesh position={[0,0,15]}>
  <planeGeometry args={[20,20,20,20]}/>
  <MeshReflectorMaterial
            blur={[400, 100]}
            resolution={1024}
            mixBlur={1}
            mixStrength={15}
            depthScale={1}
            minDepthThreshold={0.85}
            color="#151515"
            metalness={0.6}
            roughness={1}
            debug={4}
          />
 </mesh>
```

See the r3f-perf report below :

![Capture d’écran de 2024-01-11 17-41-35](https://github.com/pmndrs/drei/assets/100535633/acf9ae3f-73ff-42af-8673-f51412034788)

**Comment by zhavoronskaya** [comment]
try removing `blur={[400, 100]}`. did the trick for me with geometries, but not with textures..
