### ISSUE TITLE
Alternative PointerLockControls implementation

### ISSUE THREAD

**Issue by snsie** [pmndrs/drei#178]
I modified the PointerLockControls sandbox [**here**](https://codesandbox.io/s/pointerlock-nophysics-reticlefocuswhenlock-x36rl?file=/src/App.js). The code is messy, but some people may find the listed changes useful. 

1. Three's original PointerLockControls' `moveForward` and `moveRight` movement methods are used, which orients movement and binds players to the ground without the need for the cannon physics library.

2. A callback was added to the default raycaster that changes the mouse offsets to match the centered reticle whenever the pointer lock element exists within the `document` object. The callback was added when creating the canvas, but ideally it would be nice if the default raycaster could be directly modified by the PointerLockControls component to keep the logic self-contained.

3. Movement speed is set to be a function of fps so that movement stays consistent among players with varying frame rates. The `useFPS` hook is messy, but it would be a useful tool to incorporate into this library as well. A performant `useFPS` hook would make it easier to tweak apps based on how well they are running on each player's machine. For example, it would be helpful if this library's `Detailed` component could use average fps bound to decide which component to render in addition to distance.

4. The Space key is used to lock/unlock the controls instead of clicking. Some people may like this feature since it enables apps to include click events without initiating pointer lock. [**The Witness**](https://en.wikipedia.org/wiki/The_Witness_(2016_video_game)) is an example a game that makes use of a similar mechanic. The sandbox uses the `react-spring` and `react-use-gesture` libraries to enable dragging the box around without initiating pointer lock. Currently, these gestures are only possible if pointer lock isn't active and I'm working on resolving this issue.

5. Pressing the `Shift` key will increase movement speed by a configurable multiplier.

I don't have much experience with Typescript so I posted this as an issue in case any of the contributors would like to incorporate some of the listed features into the default implementation.

**Comment by snsie** [comment]
I organized the sandbox and added an overlay to inform users of the space bar locking mechanism. Any feedback that could improve performance and/or address potential issues would be much appreciated.

**Comment by stephencorwin** [comment]
@gsimone I think something like this could be pretty cool. From the demo he gave the other day, it looks like it has some interesting use cases. Could you take a look when you get a chance?

**Comment by joshuaellis** [comment]
This is great @snsie, would you be interested in making a PR if you think this feature is in a good enough state? It's easier to critique and refine that way 🙏🏼

**Comment by joshuaellis** [comment]
Think this could **really** complement another feature currently being built #245.

**Comment by snsie** [comment]
Cool, will do. I need to improve the current implementation but will submit a PR next week. I'll close this issue for now.

**Comment by snsie** [comment]
I don't think this as been integrated into Drei but it should work with your app if you copy the code in the sandbox.
