### ISSUE TITLE
<RenderTexture> uses wrong camera in WebXR session

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#1789]
- `three` version: r160
- `@react-three/fiber` version: 8.14.5
- `@react-three/drei` version: 9.88.0
- `node` version: 18.17.1
- `npm` (or `yarn`) version: 9.6.7

### Problem description:

When XR mode is enabled (for example after starting a WebXR session with `@react-three/xr`), the contents of drei's `<RenderTexture>` component appear incorrect. The texture is rendered using the XR camera instead of the camera from the texture's context due to this logic in Three's WebGLRenderer:

https://github.com/mrdoob/three.js/blob/e43ed970eaf1b1bf835878c815d5691d87ab3216/src/renderers/WebGLRenderer.js#L1156-L1162

```js
if ( xr.enabled === true && xr.isPresenting === true ) {

  if ( xr.cameraAutoUpdate === true ) xr.updateCamera( camera );
  
  camera = xr.getCamera(); // use XR camera for rendering

}
```

### Relevant code:

https://codesandbox.io/p/sandbox/winter-fast-dnw38y?file=%2Fsrc%2Findex.jsx%3A13%2C24

|XR disabled|XR enabled|
|------------|-----------|
|<img width="300" alt="CleanShot 2024-01-21 at 14 26 36@2x" src="https://github.com/pmndrs/drei/assets/22670878/878dfc8f-c803-40fa-9065-8790597cd5ff"> | <img width="300" alt="CleanShot 2024-01-21 at 14 26 39@2x" src="https://github.com/pmndrs/drei/assets/22670878/ea562550-1138-40f4-a6e1-5bd9054a4a17">

### Suggested solution:

Currently the implementation saves and restores the render target and autoClear values before/after rendering:

https://github.com/pmndrs/drei/blob/9c5300c243d275d49a39bcf2bf2ea81ac3b84e49/src/core/RenderTexture.tsx#L114-L124

I suggest also saving and restoring the value of `gl.xr.enabled` before/after rendering the texture, and keeping it as `false` during the RT render.

```ts
const oldXrEnabled = gl.xr.enabled
// ...

gl.xr.enabled = false
gl.render(state.scene, state.camera)
// ...

gl.xr.enabled = oldXrEnabled
```

See this forum thread for additional context:

https://discourse.threejs.org/t/webxr-issue-with-uvs-viewport-when-rendering-into-a-webglrendertarget-that-is-not-matching-screen-res/48999/4

**Comment by CodyJasonBennett** [comment]
Your fix looks correct. Note that it also disables viewport transforms for XR in addition to camera hijacking.
