### ISSUE TITLE
Trackball Controls can zoom in but not out.

### ISSUE THREAD

**Issue by LeoReubelt** [pmndrs/drei#1795]
- `three` version: 0.160.1
- `@react-three/fiber` version: 8.15.15
- `@react-three/drei` version: 9.96.3
- `node` version: v16.14.0
- `npm` (or `yarn`) version: 8.3.1

### Problem description:

Using TrackballControls with OrthographicCamera lets me zoom in, but not out.

### Relevant code:

```js
  <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <Canvas>
        <OrthographicCamera makeDefault position={[0, 0, 1000]}>
          <ambientLight intensity={0.1} />
          <directionalLight color="white" position={[0, 0, 1000]} />
        </OrthographicCamera>
        <TrackballControls
          makeDefault={true}
          zoomSpeed={0.1}
          rotateSpeed={7}
        ></TrackballControls>
        <Bounds margin={1.2} fit clip observe maxDuration={0}>
          <mesh>
            <Box>
              <meshStandardMaterial color="red" />
            </Box>
          </mesh>
        </Bounds>
      </Canvas>
    </div>
```

### Suggested solution:

I don't know what is causing it. But if I replace `<OrthographicCamera makeDefault position={[0, 0, 1000]}>` with `<orthographicCamera position={[0, 0, 1000]}>` it works and I can zoom out. Please see sandbox.

[Sandbox](https://codesandbox.io/p/sandbox/threejs-movement-4xcyrk?file=%2Fpackage.json%3A16%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrt63imi00063b6fn168qvf3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrt63imi00023b6f3y29lo2x%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrt63imi00033b6fe23wgfb6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrt63imi00053b6fuwy7nlb3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrt63imi00023b6f3y29lo2x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrt63imi00013b6fa1eou3nt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrta7kxs00023b6fdgexg9i0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrt63imi00023b6f3y29lo2x%2522%252C%2522activeTabId%2522%253A%2522clrta7kxs00023b6fdgexg9i0%2522%257D%252C%2522clrt63imi00053b6fuwy7nlb3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrt63imi00043b6f9kz9pe4d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrt63imi00053b6fuwy7nlb3%2522%252C%2522activeTabId%2522%253A%2522clrt63imi00043b6f9kz9pe4d%2522%257D%252C%2522clrt63imi00033b6fe23wgfb6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrt63imi00033b6fe23wgfb6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by FlafyDev** [comment]
if i remove makeDefault then the camera is not OrthographicCamera  anymore
