### ISSUE TITLE
Splat init problem with cached files

### ISSUE THREAD

**Issue by inear** [pmndrs/drei#1796]
When loading .splat-file everything works as expected if the file loads the first time (or throttle network-speed and disable browser-cache). Then the stream.read() serves smaller data-chunks and he model is fine. But when reloading and the read returns one or two big chunks and directly all data is not processed. I can't figure out what's causing the faulty sort-order of splats.

I can work around this by splitting up the incoming stream into smaller parts to process (not the built in chunkSize). But I'm not sure if it's the size or any the async problem to begin with. 

Would be interesting to hear if anyone else have had this problem. It can be sneaky to detect when just a few splats are wrong, especially when the correct render is also often noisy

**Comment by Mousatat** [comment]
I am facing the same problem, could you please mention the solution if you find it?
Kind regards
