### ISSUE TITLE
Orbit controls cause model to jump when used in conjunction with bounds.

### ISSUE THREAD

**Issue by LeoReubelt** [pmndrs/drei#1801]
- three version: 0.160.1
- @react-three/fiber version: 8.15.15
- @react-three/drei version: 9.96.5
- node version: v16.14.0
- npm (or yarn) version: 8.3.1

### Problem description:

When bounds is used with orbit controls, when the camera is panned or zoomed, the model jumps in the direction of the offset and the center of rotation changes.

### Relevant code:

[sandbox](https://codesandbox.io/p/sandbox/threejs-bounds-breaks-arcball-controls-3shh9s?file=%2Fsrc%2FApp.tsx%3A6%2C32&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrt62s8v00063b6ffahdd8lv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrt62s8v00023b6fdmitks5v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrt62s8v00033b6fju4cqxhn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrt62s8v00053b6fkyxjn53h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrt62s8v00023b6fdmitks5v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrt62s8v00013b6f41093zg1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clruphh4y00023b6f3pxb2vig%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A32%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A32%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrt62s8v00023b6fdmitks5v%2522%252C%2522activeTabId%2522%253A%2522clruphh4y00023b6f3pxb2vig%2522%257D%252C%2522clrt62s8v00053b6fkyxjn53h%2522%253A%257B%2522id%2522%253A%2522clrt62s8v00053b6fkyxjn53h%2522%252C%2522activeTabId%2522%253A%2522clrt62s8v00043b6fz380935y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrt62s8v00043b6fz380935y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clrupb900001m3b6fvemu3ttc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clrt62s8v00033b6fju4cqxhn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrt62s8v00033b6fju4cqxhn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

```
import "./styles.css";
import { Box } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Bounds, OrthographicCamera, ArcballControls } from "@react-three/drei";

export default function App() {
  return (
    <div className="App">
      <Canvas>
        <OrthographicCamera makeDefault position={[0, 0, 1000]}>
          <ambientLight intensity={0.1} />
          <directionalLight color="white" position={[0, 0, 1000]} />
        </OrthographicCamera>
        <ArcballControls
          makeDefault
          adjustNearFar={true}
          enableZoom={true}
          enablePan={true}
        ></ArcballControls>
        <Bounds margin={3} fit clip observe maxDuration={0}>
          <mesh>
            <Box position={[0, 1, 0]}>
              <meshStandardMaterial color="red" />
            </Box>
          </mesh>
        </Bounds>
      </Canvas>
    </div>
  );
}
```

**Comment by matteoxplo** [comment]
+1

Seems that bounds that not set the target to the calculated center keep using [0,0,0] instead.

**Comment by sunillarsson** [comment]
I solved this by wrapping my mesh and bounds in a suspense component.

**Comment by zaesur** [comment]
I'm having a similar issue with Bounds, namely that using OrbitControls _during_ the zoom animation places the orbit target outside of the model. If you wait for the animation to finish it works as expected and the model remains the target.

Here's a codesandbox highlighting the issue:  https://codesandbox.io/p/devbox/drei-issue-with-bounds-krjrl5?file=%2Fsrc%2FApp.tsx
