### ISSUE TITLE
useTexture does not work on react native with Expo

### ISSUE THREAD

**Issue by itsyoboieltr** [pmndrs/drei#1809]
- `three` version: 0.161.0
- `@react-three/fiber` version: 8.15.16
- `@react-three/drei` version: 9.97.0
- `node` version: v20.9.0
- `npm` (or `yarn`) version: 10.1.0

### Problem description:

I am trying to load a sprite, but it errors.

<img width="903" alt="image" src="https://github.com/pmndrs/drei/assets/72046715/b2bd4644-9f7e-4076-9aaf-3525fb07e656">

### Relevant code:

```tsx
import { useTexture } from '@react-three/drei/native';

export default function Test() {
  const sprite = useTexture(require('./sprite.png'));
  return <></>;
}
```

### Suggested solution:

Maybe I am misusing it? but I would expect this to work.

**Comment by divyansh4300** [comment]
Try wrapping the component with Canvas
```
import React from 'react';
import { Canvas } from 'react-three-fiber';
import { useTexture } from '@react-three/drei';

function Test() {
  const sprite = useTexture(require('./sprite.png'));
  return (
    <mesh>
      <planeBufferGeometry attach="geometry" args={[1, 1]} />
      <meshBasicMaterial attach="material" map={sprite} />
    </mesh>
  );
}

export default function App() {
  return (
    <Canvas>
      <Test />
    </Canvas>
  );
}

```
