### ISSUE TITLE
typesctipt errors `import React from 'react'` related to `esModuleInterop` being enabled.

### ISSUE THREAD

**Issue by JustFly1984** [pmndrs/drei#183]
Please disable `esModuleInterop` in tsconfig.json and replace ```import React from 'react'``` with ```import * as React from 'react'``` in all components.

**Comment by gsimone** [comment]
Can you document the issue and PR the change?

**Comment by JustFly1984** [comment]
created PR https://github.com/pmndrs/drei/pull/184

Issue was reproducing only in projects with esModuleInterop: false.
Current fixed imports are working for both states of esModuleInterop.

Also fixed some rendering issues and improved performance.

**Comment by joshuaellis** [comment]
Fixed in #198
