### ISSUE TITLE
Text component is not working in a Next.js app

### ISSUE THREAD

**Issue by yoanngueny** [pmndrs/drei#1840]
- `three` version: 0.161.0
- `@react-three/fiber` version: 8.15.16
- `@react-three/drei` version: 9.99.0
- `node` version: 20.9.0
- `npm` (or `yarn`) version: 9.8.1

### Problem description:

The component <Text> creates an error in the console when used inside a Next.js app.
The error refers to a worker trying to access a defined window in Troika.

### Relevant code:

Here is a simple codesandbox example: https://codesandbox.io/p/sandbox/loving-wave-zc56dc

<img width="726" alt="Capture d’écran 2024-02-22 à 15 28 28" src="https://github.com/pmndrs/drei/assets/2699248/9008c07d-6768-47f9-9bcd-7678bee1e77d">

### Suggested solution:

I've tried to investigate the problem. It seems to be related to a Troika dependency named Typr.
But the pull request I've suggested doesn't seem to be correct. The owner asked me to invest in Troika or Drei.
https://github.com/fredli74/Typr.ts/pull/5

**Comment by CodyJasonBennett** [comment]
Which Next.js version? We've seen relentless regressions on their side related to the App Router and I can only suggest pinning. 14.0.1 was known to work.

I can try a workaround in a moment we've used before with a similar regression of Next.

**Comment by yoanngueny** [comment]
Yes, I use next 14.1.0

**Comment by yoanngueny** [comment]
I tried the fix branch but I get this error.

![Capture d’écran 2024-02-23 à 15 24 02](https://github.com/pmndrs/drei/assets/2699248/28fdedd1-0d0a-40cb-a961-c928fd0a044d)

**Comment by CodyJasonBennett** [comment]
If you want to test out the PR, try:

```js
{
  "dependencies": {
    "@react-three/drei": "https://pkg.csb.dev/pmndrs/drei/commit/47d99046/@react-three/drei"
  }
}
```

**Comment by yoanngueny** [comment]
Thanks! I just did it.

But the first window error is still there.

**Comment by CodyJasonBennett** [comment]
I think you need to take this up with Next.js upstream and/or pin to an earlier version. Something is seriously wrong with bundling as that code shouldn't be evaluated on the server; that's what the PR is supposed to prove or workaround. As I mentioned, 14.0.1 was known to work if you aren't using any features from 14.1.

**Comment by paperdiamond** [comment]
I am currently using next 14.1.0 w/ the updated v9.99.3 and the issue is persisting. I'm unable to use  `<Text>` without receiving the following error. @CodyJasonBennett 
<img width="918" alt="Screenshot 2024-02-26 at 9 43 55 AM" src="https://github.com/pmndrs/drei/assets/9064085/568269f4-42d3-48ee-be6c-6468ea7c564a">

**Comment by CodyJasonBennett** [comment]
Please see my last comment. There is an issue in the Next compiler we can't work around and requires either a previous version or a fix upstream.

**Comment by paperdiamond** [comment]
I see. Thank you for the quick response!

**Comment by ahaded777** [comment]
![Uploading Capture d'écran 2024-02-25 204940.png…]()
@CodyJasonBennett

**Comment by ahaded777** [comment]
![Capture d'écran 2023-12-07 181528](https://github.com/pmndrs/drei/assets/131011542/98e1c8ca-4d89-42da-9b4c-d5e0d5721109)

**Comment by ahaded777** [comment]
![Capture d'écran 2024-02-25 204940](https://github.com/pmndrs/drei/assets/131011542/4b54a3dd-f24e-4ab9-acc9-2cde9e8db365)
@CodyJasonBennett no effect ?
