### ISSUE TITLE
three 0.162.0 breaks drei

### ISSUE THREAD

**Issue by cdeath** [pmndrs/drei#1852]
- `three` version: 0.162.0
- `@react-three/fiber` version: 8.15.16
- `@react-three/drei` version: 9.99.4
- `node` version: v18.19.1
- `pnpm` version: 8.15.4

### Problem description:

✘ [ERROR] No matching export in "node_modules/.pnpm/three@0.162.0/node_modules/three/build/three.module.js" for import "LinearEncoding"

    node_modules/@react-three/drei/core/SpotLight.js:3:76:
      3 │ ...enderTarget, RGBAFormat, LinearEncoding, ShaderMaterial, DoubleS...

### Suggested solution:

<img width="542" alt="image" src="https://github.com/pmndrs/drei/assets/17791147/cd33b8a0-ac80-4607-bdd1-ab064e3f35d4">

**Comment by cdeath** [comment]
for now i pinned three at 0.161.0

**Comment by tb-viktor** [comment]
Same here. We were hoping to upgrade to r162 since it contains an important bug fix, but then this error popped up.

**Comment by chuhongkyu** [comment]
Same here. I also encountered the same issue and proceeded with using "three": "0.161.0".

**Comment by CodyJasonBennett** [comment]
This is fixed in <https://github.com/pmndrs/drei/releases/tag/v9.99.5>
