### ISSUE TITLE
OrbitControls Key Control Doesn't Work

### ISSUE THREAD

**Issue by Luigi600** [pmndrs/drei#186]
## Description

It is not possible to handle the OrbitControls component with keys.

## Expected Behavior

I can use my arrow keys to control the camera as the example in the readme.

## Environment
```
react:16.13.1 & react:17.0.0
@react-three/drei:2.2.6 & @react-three/drei:2.2.7
react-three-fiber:5.3.0
three:0.123.0
```

## Minimal Example / Reproducion / Sandbox

[CodeSandbox](https://codesandbox.io/s/react-three-orbit-controls-keys-w7ddo)

## Background

I have updated the dependencies of a project. I replaced the old drei version `drei:0.0.70` with the new version `@react-three/drei:2.2.7`. The OrbitControls worked fine with the old version, but now I can't use the arrow keys anymore.

It is still possible that the fault lies with me. However, I was also advised in the Discord server to create this issue.

**Comment by joshuaellis** [comment]
Hi @Luigi600 I actually think this is an issue wth `three`. The key controls work on version 0.122.

I've done some digging to confirm this and raised an issue in the three repo https://github.com/mrdoob/three.js/issues/20805

**Comment by joshuaellis** [comment]
As this is a `three.js` issue, i'm going to close it as we cannot fix it. You can track the fix on the above link.

**Comment by agcty** [comment]
This still doesn't seem to work even after https://github.com/mrdoob/three.js/pull/21054 has been merged.

Neither 

 ```jsx
<MapControls
    ref={controlsRef}
    minPolarAngle={-Math.PI / 2}
    maxPolarAngle={Math.PI / 2}
    keys={{
      LEFT: "ArrowLeft", //left arrow
      UP: "ArrowUp", // up arrow
      RIGHT: "ArrowRight", // right arrow
      BOTTOM: "ArrowDown", // down arrow
    }}
    listenToKeyEvents={window}
    maxDistance={30}
    minDistance={0}
    enabled={!isZooming}
 />
```

Nor this 

```jsx
useEffect(() => {
    controlsRef?.current?.listenToKeyEvents(window)
  }, [])
```

seems to have any effect

**Comment by TiagoCavalcante** [comment]
@agcty I'm having the same problem, I have added a comment to the issue saying it needs to be re-opened.

**Comment by TiagoCavalcante** [comment]
@joshuaellis this is working in three.js now, but not in @react-three/drei.

**Comment by jayPreak** [comment]
Anyone found a way to make this work?

**Comment by Sean-Bradley** [comment]
I instead extended from the three addons OrbitCrontols instead of using the DREI version.

E.g.,
https://sbedit.net/ef4a583194aae9d5557cf1bd9ae7162fe0aabf24

use arrow keys to pan, hold ctrl of shift aswell to rotate.
