### ISSUE TITLE
useKTX2() seems not to work

### ISSUE THREAD

**Issue by stefano-ciotola** [pmndrs/drei#1860]
### Environment:
- three version: 0.161
- @react-three/fiber version: 8.15.19
- @react-three/drei version: 9.99.5
- node version: 20.11.0
- npm (or yarn) version: 10.2.4

### Problem description:

When attempting to load a KTX2 texture using `useKTX2('my_texture_path')`, the console throws a ReferenceError: `_KTX2Loader is not defined`, preventing the successful loading of KTX2 textures.

### Full error log:
```
ReferenceError: _KTX2Loader is not defined
handleError@http://localhost:3000/static/js/bundle.js:85964:58
./node_modules/webpack-dev-server/client/overlay.js/createOverlay/<@http://localhost:3000/static/js/bundle.js:85983:18
EventListener.handleEvent*listenToRuntimeError@http://localhost:3000/static/js/bundle.js:86156:10
createOverlay@http://localhost:3000/static/js/bundle.js:85976:84
./node_modules/webpack-dev-server/client/index.js?protocol=ws%3A&hostname=0.0.0.0&port=3000&pathname=%2Fws&logging=none&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true@http://localhost:3000/static/js/bundle.js:84689:105
options.factory@http://localhost:3000/static/js/bundle.js:163923:31
__webpack_require__@http://localhost:3000/static/js/bundle.js:163352:32
@http://localhost:3000/static/js/bundle.js:164567:30
@http://localhost:3000/static/js/bundle.js:164571:12
```

The example provided in the documentation does not seem to work either (https://drei.pmnd.rs/?path=/docs/loaders-ktx2--docs).

I have followed the standard setup and installation procedures for three, @react-three/fiber, and @react-three/drei as recommended in the docs.

**Comment by MathisEngels** [comment]
Having the same issue here, same specs.

**Comment by freddywhd** [comment]
same issue here.

**Comment by ektogamat** [comment]
Same issue here :)

**Comment by pavsoldatov** [comment]
I am pretty sure the issue is still unresolved.
