### ISSUE TITLE
Hard to use cameraControls ?

### ISSUE THREAD

**Issue by LAGENCECREE** [pmndrs/drei#1885]
having hard time tryng to implement camera controls 🧐

1 -
in this intent : https://codesandbox.io/p/sandbox/bounds-and-makedefault-forked-6k92q9?file=%2Fsrc%2FApp.js 
i get the following error
```
"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`."

```
2-
on a local dev environnement (using vite, without codesandbox)
i have another problem, an inifnite loop error about an undefined .target property in the cameraControls component...

a bit disapointed :S

**Comment by netgfx** [comment]
Have you checked the main repository? https://github.com/yomotsu/camera-controls
this drei component is a wrapper. The original repository has many examples

**Comment by LAGENCECREE** [comment]
I will look deeply
i thought that drei collection avoided worrying too much about lower layers, 
<CameraControls> and <Bounds> components are not compatibles  :(
https://codesandbox.io/p/sandbox/bounds-and-makedefault-forked-6k92q9?file=%2Fsrc%2FApp.js
