### ISSUE TITLE
useGLTF with Draco: TypeError: WebAssembly.instantiate() - with fix

### ISSUE THREAD

**Issue by nathansearles** [pmndrs/drei#189]
Started seeing the following errors today. After some digging it looks like it's related to [this issue](https://github.com/google/draco/issues/653) with the Draco decoders.

```
failed to asynchronously prepare wasm: TypeError: WebAssembly.instantiate(): 
Import #2 module="wasi_unstable" error: module is not an object or function
```

```
Uncaught (in promise) RuntimeError: abort(TypeError: WebAssembly.instantiate(): 
Import #2 module="wasi_unstable" error:module is not an object or function). 
Build with -s ASSERTIONS=1 for more info.
```

**Quick fix**

Thankfully we can point to other decoders. Doing the following resolved the issue.

```
const { nodes, materials } = useGLTF(
  "draco_model.glb",
  "https://www.gstatic.com/draco/versioned/decoders/1.4.0/"
);
```

Another options is to use decoder version "https://www.gstatic.com/draco/versioned/decoders/1.3.6/".

Hope this helps someone else out there tearing their hair out this evening!

**Comment by deanssmart** [comment]
I have had this exact issue... my site was working the other day and then it kept just throwing up the WebAssembly.instantiate() error. Thanks for the fix it has worked for me 

` const { scene } = useLoader(GLTFLoader, "scene.gltf", draco("https://www.gstatic.com/draco/versioned/decoders/1.4.0/"));`

**Comment by alex-shortt** [comment]
It's been spotty for a while but recently it seems like the cdn began working again, can anyone else confirm this?

**Comment by nathansearles** [comment]
The Draco decoder URL (https://www.gstatic.com/draco/v1/decoders/) that Drei uses appears to be working again.

You can test it by going to: https://www.gstatic.com/draco/v1/decoders/draco_decoder.js

For now I'd still use:

```
const { nodes, materials } = useGLTF(
  "draco_model.glb",
  "https://www.gstatic.com/draco/versioned/decoders/1.4.0/"
);
```

**Comment by drcmda** [comment]
i've made a small patch pinning the version
