### ISSUE TITLE
<Edges> doesn't support `geometry` prop anymore after v9.102.0

### ISSUE THREAD

**Issue by TimKraemer** [pmndrs/drei#1893]
- `@react-three/drei` version: ^9.102.0

### Problem description:

https://github.com/pmndrs/drei/commit/eda982937b0f91e0e469a41b679bcd07831650b1 breaks `geometry` prop as documented in https://github.com/pmndrs/drei#edges

### Relevant code:

I'm using `<Edges>` like this and would like to keep using it with a `geometry` prop:

```js
      <Edges
        geometry={
          new BoxGeometry(
            dimensions.x + PADDING_IN_METER,
            dimensions.y + PADDING_IN_METER / 2,
            dimensions.z + PADDING_IN_METER
          )
        }
		...
      >
        <lineBasicMaterial
          color="#ff0a82"
          castShadow="false"
        />
      </Edges>
```

### Suggested solution:

I tried fixing it with:

```js
// src/core/Edges.tsx
const geometry = ref.current.geometry ?? parent.geometry
```

but this results in a lot more errors down the line, which I'm currently not able to solve

**Comment by CodyJasonBennett** [comment]
@drcmda, what was the point of eda982937b0f91e0e469a41b679bcd07831650b1?

**Comment by Kalabedo** [comment]
Hey, i use Edges in my project, since the update when i export my scene i get this: 

![grafik](https://github.com/pmndrs/drei/assets/41572877/83161216-f98a-4395-b344-3afb2fc6f873)

caused by Edges. Is this the same problem?
Before it worked fine. Is there a fix, other then remove the Edges before exporting?

Greetings Tom

**Comment by TimKraemer** [comment]
Thank you @nickthegroot for the fix!
It does accept geometries - however a custom `lineBasicMaterial` seem to be ignored:

```jsx
<Edges
  geometry={
    new BoxGeometry(1,1,1)
    )
  }
  ...
>
  <lineBasicMaterial linewidth="5" color="#ff0000" />
</Edges>
```
