### ISSUE TITLE
<Splat> onClick

### ISSUE THREAD

**Issue by cyango** [pmndrs/drei#1895]
I'm having a weird behaviour with onClick on Splat component.
I can click in the front side of this bounding box, but not on the Splat itself. If i drag around, i can't even click on the bounding box.

Is this expected behaviour or how can i do a workaround?

![image](https://github.com/pmndrs/drei/assets/30806279/b3f37a14-aa66-4fce-9bae-3e2f122c1ea5)

**Comment by NORXONDOR** [comment]
Hi. Sorry I can't help your issue, but I was trying to figure out how to generate a bounding box arounda Splat. I kept running into the issue where I couldn't get the reference of it due to no forwardRef in the implementation. Any chance you could help me out?

**Comment by Alecapra96** [comment]
same problems just here
