### ISSUE TITLE
shaderMaterial uniforms are shared between instances

### ISSUE THREAD

**Issue by stefan-miljakovic** [pmndrs/drei#190]
#### Bug descriptions

Shader materials have shared uniforms during initial render.

#### Steps to reproduce

1. Create a component which uses an object as a uniform (could be Vector3 / Color as example given). 
2. All instances will then have same reference to the object, instead of separate

#### Demonstration

https://codesandbox.io/s/relaxed-bardeen-1lce4

**Comment by drcmda** [comment]
looks like its the uniforms. it's the only part that i can see that could touched by both instances.

**Comment by joshuaellis** [comment]
I think given the infancy of `component-material` we should still keep `shaderMaterial`.

In reference to the issue, would this maybe have something to do with the reconciler & `extend`, if you don't extend the material and summon it in a more "traditional" way, the problem doesn't persist – https://codesandbox.io/s/friendly-cdn-4ytnz?file=/src/App.js what's your take based on this example @drcmda? They seem to have different UUIDs which i guess is a good start.
