### ISSUE TITLE
OrbitControls prevent onClick events from triggering in mobile

### ISSUE THREAD

**Issue by suhdonghwi** [pmndrs/drei#193]
When I use `<OrbitControls/>`, `onClick` events does not trigger in mobile devices. (In PC env it works just fine)

`onPointerDown`, `onPointerUp`, these events trigger. Only `onClick` has a problem.

**Comment by drcmda** [comment]
i think this is a bug in threejs. they call preventDefault maybe it's that. we have no control over orbitcontrols - drei just spares you the long import and the useFrame(() => control.update()) method.

**Comment by joshuaellis** [comment]
@suhdonghwi i'm going to close this as I agree with @drcmda, if you need more support we can reopen this.

**Comment by antokhio** [comment]
can add that on windows 10 touchscreen issue persists in Chrome browser, using mouse onClick works as expected, using touch - no

**Comment by joshuaellis** [comment]
> can add that on windows 10 touchscreen issue persists in Chrome browser, using mouse onClick works as expected, using touch - no

If you're interested in making a PR, check out three-stdlib.
