### ISSUE TITLE
How to manually update scroll offset properly?

### ISSUE THREAD

**Issue by algosdev** [pmndrs/drei#1943]
### Question:

I'm using  `ScrollControls` and `useScroll`, based on scroll.offset, I'm moving camera inside useFrame. `ScrollControls `has `pages={20}`. At some point, when button is clicked, I need to manually update `scroll.offset` to half way `(page=10)`, and make it possible to continue scroll from there. I've tried setting `scroll.offset = 0.5`, which worked. But after I start scrolling, `scroll.offset` goes to its previous value. I've also tried `scroll.el.scrollTo` method - no luck. `scroll.range`, `scroll.curve` methods seems to be not what I want (still playing with them).

Anyone knows the way?

**Comment by valentindiehl** [comment]
Having the same issue :(
