### ISSUE TITLE
Could not load: Property 'Image' does not exist

### ISSUE THREAD

**Issue by truesteps** [pmndrs/drei#1946]
### What is your question:

Heya! I'm trying to render a gltf model onto my scene, following https://www.youtube.com/watch?v=O8q8H9c9XZ4 this tutorial, but whenver I put my model into the Canvas in Suspense, I get the following error: Could not load: Property 'Image' does not exist.  I'm pasting the model code below, generated by GltfJsx from a website that is linked in the videotutorial. Anyone could help me with thisone? I've been stuck on it for a while now and google unfortunately didn't help.

Also attaching screen of error:

<img width="430" alt="Screenshot 2024-05-01 at 11 23 51" src="https://github.com/pmndrs/drei/assets/12614944/7d84dd7c-ae6d-44ec-a1e1-db236e83722c">

Thx in advance.

```TypeScript
import * as THREE from 'three';
import React from 'react';
import {useGLTF} from '@react-three/drei/native';
import {GLTF} from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Couch002: THREE.Mesh;
    Couch_legs002: THREE.Mesh;
    Cube004: THREE.Mesh;
  };
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
  };
};

export default function CompressedChair(props: JSX.IntrinsicElements['group']) {
  const {nodes, materials} = useGLTF(
    require('../assets/compressedChair.glb'),
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Couch002.geometry}
        material={materials['Material.005']}
        position={[0.624, 0.535, 0.356]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Couch_legs002.geometry}
        material={materials['Material.008']}
        position={[0.562, 0.535, 0.563]}
        rotation={[0, 1.571, 0]}
        scale={[0.808, 0.808, 0.758]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.006']}
        position={[0.78, 1.044, 0.813]}
        rotation={[1.601, 0.906, -2.105]}
      />
    </group>
  );
}

useGLTF.preload(require('../assets/compressedChair.glb'));

```

**Comment by netgfx** [comment]
Can you check the network tab on the dev tools to see if there is a request that fails? Perhaps it is trying to load a texture from somewhere. Otherwise if you could make a codesandbox or something so we can see it in action it would help

**Comment by truesteps** [comment]
@netgfx there is also this warning that pops up:

<img width="487" alt="Screenshot 2024-05-01 at 11 45 52" src="https://github.com/pmndrs/drei/assets/12614944/9dea754b-6f3c-4719-8dce-281c754bacbd">

I'm working on setting up devtools :D i'm running this in react native

**Comment by truesteps** [comment]
I tried using the model in the tutorial, and it worked. Seems like there might be an issue wit the model. Thanks, i'll try and re-export it

**Comment by truesteps** [comment]
@netgfx ended up being some sort of issue with a compressed glb output from blender. Do you know any tips or tricks as to how to optimize glb/gltf formats without it becoming unusuable? But the issue is fixed :) thanks for pointing me in the right direction
