### ISSUE TITLE
WeakMap key must be an Object

### ISSUE THREAD

**Issue by fl1k** [pmndrs/drei#1948]
- `three` version: 0.164.1
- `@react-three/fiber` version: 8.16.3
- `@react-three/drei` version:  9.105.6
- `node` version: 21.7,3
- `npm` (or `yarn`) version: 10.5.2
- Expo: 50.0.17

### Problem description:
I am using Expo, 
 I keep getting this error every time I try using functionality of either fiber or drei
 `TypeError: WeakMap key must be an Object, js engine: hermes`
From drei: import { Environment } from '@react-three/drei/native'
From fiber: useLoader(TextureLoader) - I fixed it by switching to three texture loading with new TextureLoader()

### Relevant code:

```js
  <View style={{flex: 3}}>
                        <Suspense>
                            <Canvas shadows
                                    onCreated={(state) => {
                                        const _gl = state.gl.getContext();
                                        const pixelStorei = _gl.pixelStorei.bind(_gl);
                                        _gl.pixelStorei = function (...args) {
                                            const [parameter] = args;
                                            switch (parameter) {
                                                case _gl.UNPACK_FLIP_Y_WEBGL:
                                                    return pixelStorei(...args);
                                            }
                                        };
                                    }}
                            >
                                <OrbitControls/>
                                <mesh position={[0, -0.25, 0]}
                                      ref={mesh}
                                      material={materials}
                         
                                >
                                    <boxGeometry args={[w, w * aspect, 0.05]}/>
                                </mesh>
                                <ambientLight intensity={0.8 * Math.PI}/>
                                <Environment preset="lobby" />



                            </Canvas>
                        </Suspense>
                    </View>

```

Am I doing something wrong? I have been debugging this for 6-7 hours and couldn't find a solution, I found that this happens when there is three version mismatch but I don't have multiple three versions installed, is there a specific version needed for react-fiber?
Error is thrown at three.cjs (22974:21)

**Comment by Josh-Williams-Curtin** [comment]
Having the same issue, also noticed that <Environment /> crashes the app on boot when running on a release apk.

**Comment by Josh-Williams-Curtin** [comment]
@thirandev Nope sorry, I have given up on using the <Environment /> component for the time being.

**Comment by thirandev** [comment]
@Josh-Williams-Curtin, I’ve identified the solution and successfully tested it on both Android and iOS release builds. Instead of wrapping the entire `Canvas` with `Suspense` from the outside, the `Suspense` component should be moved inside the `Canvas`. Below is the updated code snippet where I’ve modified @fl1k's implementation while maintaining the Environment component.


> ### Updated Code:
> ```js
>                       <View style={{flex: 3}}>
>                             <Canvas shadows
>                                     onCreated={(state) => {
>                                         const _gl = state.gl.getContext();
>                                         const pixelStorei = _gl.pixelStorei.bind(_gl);
>                                         _gl.pixelStorei = function (...args) {
>                                             const [parameter] = args;
>                                             switch (parameter) {
>                                                 case _gl.UNPACK_FLIP_Y_WEBGL:
>                                                     return pixelStorei(...args);
>                                             }
>                                         };
>                                     }}
>                             >
>                              <Suspense fallback={null}>
  >                                 <OrbitControls/>
  >                                 <mesh position={[0, -0.25, 0]}
  >                                       ref={mesh}
  >                                       material={materials}
  >                          
  >                                 >
>                                     <boxGeometry args={[w, w * aspect, 0.05]}/>
>                                 </mesh>
>                                 <ambientLight intensity={0.8 * Math.PI}/>
>                                 <Environment preset="lobby" />
>                              </Suspense>
>                          </Canvas>
>                     </View>
> ```

**Comment by rodgetech** [comment]
This error is still around

**Comment by rohitS3** [comment]
The issue is still there. Below is my code -
```
<Canvas
                gl={{ physicallyCorrectLights: true }}
                camera={{ position: [-6, 0, 16], fov: 36 }}
                onCreated={(state) => {
                    state.gl.setClearColor('#000000');
                    state.gl.physicallyCorrectLights = true;
                }}
            >
                <Suspense fallback={null}>
                    <group rotation={[0, Math.PI / 2, 0]}>
                        <Environment preset="lobby" background backgroundBlurriness={0} />
                    </group>
                    <ambientLight position={[2, 5, 5]} intensity={Math.PI} />
                    <Model isSpeaking={isSpeaking} currentViseme={currentViseme} onModelLoaded={() => setIsModelLoaded(true)} />
                </Suspense>
</Canvas>
```

**Comment by meloluvert** [comment]
I have the same error @wandolch , did you find a solution?
