### ISSUE TITLE
Question about View 

### ISSUE THREAD

**Issue by DDman1984** [pmndrs/drei#1957]
Hi, guy
I see a demo about [View](https://codesandbox.io/p/sandbox/multiple-views-with-uniform-controls-forked-9klrdy?file=%2Fsrc%2FApp.js%3A86%2C10-88%2C18)

According to my understanding of code, does constructing a view also simultaneously create a mesh object in the scene? If this is correct, would there be performance issues when displaying a high-polygon model? In other words, if I have N views intending to display a model with 1,000,000 triangles, will the scene need to render N * 1,000,000 triangles simultaneously?

In practice, I did observe the triangle count on the Perf monitor steadily increasing in the scene....

**Comment by talkingtab** [comment]
If you create <View/> nothing shows. Same with 
```
<View>
</View>
```
So you must create something. 
The sandbox you linked to is gone, but in the original, if you delete the {children} of the SidePanel, nothing shows up.
