### ISSUE TITLE
Rendering starts too late with frameloop demand and CameraControls transitions

### ISSUE THREAD

**Issue by AaronClaes** [pmndrs/drei#2005]
- `three` version: 0.0165
- `@react-three/fiber` version: 8.16.8
- `@react-three/drei` version: 9.107.0

### Problem description:

When setting the canvas frameloop to `demand`, the `<CameraControls />` functions trigger `invalidate()` too late. 

When the canvas is not being rendered and you do an action like this, you will notice the problem:
```tsx 
controls.dolly(1, true) // true for the transition to be smooth
```

When the transition is set to `false`, it is not noticeable. But with the transition, the first few frames are skipped. 
When de Canvas is already rendering, this problem does not happen, it is only the initial trigger.

### Relevant code:

In the codesandbox below you will notice that if you give the Canvas time to stop rendering, and you then click the box, the initial transition of the camera controls is not smooth. If you keep clicking it, the following transitions (when the canvas is still running) are smooth. 

https://codesandbox.io/p/sandbox/use-controls-bug-2mtn6l

### Suggested solution:

I am unsure if this is a @react-three/fiber problem or something in the CameraControls component. It might even have something to do with how the camera-controls library works, but it would be nice to see this fixed, or have a workaround.

I have tried to use `invalidate` to start rendering earlier but did not have any success with this.

Thanks!

**Comment by vmakela** [comment]
The CameraControls update code looks pretty suspicious to me. It only calls `controls.update` for the implementation on every frame rendered, and it only forces renders on camera events. It does kind of work for animated transitions because the `transitionstart` event gets fired when starting the transition, but it does come with a delay.

Something like this would fix it, but I'm not sure if it is actually wanted here.

```diff
diff --git a/src/core/CameraControls.tsx b/src/core/CameraControls.tsx
index 082b967..b2dcab7 100644
--- a/src/core/CameraControls.tsx
+++ b/src/core/CameraControls.tsx
@@ -1,5 +1,6 @@
 import {
   Box3,
+  Clock,
   EventDispatcher,
   MathUtils,
   Matrix4,
@@ -16,7 +17,7 @@ import {
 
 import * as React from 'react'
 import { forwardRef, useMemo, useEffect } from 'react'
-import { extend, useFrame, useThree, ReactThreeFiber, EventManager } from '@react-three/fiber'
+import { extend, useThree, ReactThreeFiber, EventManager } from '@react-three/fiber'
 
 import CameraControlsImpl from 'camera-controls'
 import { ForwardRefComponent } from '../helpers/ts-utils'
@@ -81,18 +82,24 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
 
   const controls = useMemo(() => new CameraControlsImpl(explCamera), [explCamera])
 
-  useFrame((state, delta) => {
-    if (controls.enabled) controls.update(delta)
-  }, -1)
-
   useEffect(() => {
     controls.connect(explDomElement)
     return () => void controls.disconnect()
   }, [explDomElement, controls])
 
   useEffect(() => {
+    const clock = new Clock()
+    let animationFrame: number
+    const update = () => {
+      animationFrame = requestAnimationFrame(update)
+      const delta = clock.getDelta()
+      const needFrame = controls.update(delta)
+      if (needFrame) {
+        invalidate()
+      }
+    }
+
     const callback = (e) => {
-      invalidate()
       if (regress) performance.regress()
       if (onChange) onChange(e)
     }
@@ -111,6 +118,7 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
     controls.addEventListener('control', callback)
     controls.addEventListener('transitionstart', callback)
     controls.addEventListener('wake', callback)
+    animationFrame = requestAnimationFrame(update)
 
     return () => {
       controls.removeEventListener('update', callback)
@@ -119,6 +127,7 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
       controls.removeEventListener('control', callback)
       controls.removeEventListener('transitionstart', callback)
       controls.removeEventListener('wake', callback)
+      cancelAnimationFrame(animationFrame)
     }
   }, [controls, onStart, onEnd, invalidate, setEvents, regress, onChange])
 ```

**Comment by AaronClaes** [comment]
Is there a reason that `callback` is not triggered inside the [`onStartCb`](https://github.com/pmndrs/drei/blob/c9a680cc653aa85537a2c7b0a724b69171d42b31/src/core/CameraControls.tsx#L100C3-L100C63) function? 
When I add this, the transition starts rendering way earlier. It is not 100% perfect yet but it is probably the best that can be done without having a separate animation loop like in the solution above.

```tsx
const onStartCb: CameraControlsProps["onStart"] = (e) => {
    callback(e); // trigger callback here as well
    if (onStart) onStart(e);
};
```

**Comment by AaronClaes** [comment]
> Something like this would fix it, but I'm not sure if it is actually wanted here.

I am still looking into other solutions but can't find any, could your solution have a big performance impact? 
Or what would be an argument to not do it this way?

**Comment by vmakela** [comment]
> I am still looking into other solutions but can't find any, could your solution have a big performance impact? Or what would be an argument to not do it this way?

It's a bit ugly, and it has an extra delay of one frame if the requestAnimationFrame callback ends up being called after rendering. A better way to implement it would probably be to somehow include it in fiber's frame loop, but I'm not sure how that should be done.

**Comment by drcmda** [comment]
> The CameraControls update code looks pretty suspicious to me. It only calls `controls.update` for the implementation on every frame rendered, and it only forces renders on camera events. It does kind of work for animated transitions because the `transitionstart` event gets fired when starting the transition, but it does come with a delay.
> 
> Something like this would fix it, but I'm not sure if it is actually wanted here.
> 
> ```diff
> diff --git a/src/core/CameraControls.tsx b/src/core/CameraControls.tsx
> index 082b967..b2dcab7 100644
> --- a/src/core/CameraControls.tsx
> +++ b/src/core/CameraControls.tsx
> @@ -1,5 +1,6 @@
>  import {
>    Box3,
> +  Clock,
>    EventDispatcher,
>    MathUtils,
>    Matrix4,
> @@ -16,7 +17,7 @@ import {
>  
>  import * as React from 'react'
>  import { forwardRef, useMemo, useEffect } from 'react'
> -import { extend, useFrame, useThree, ReactThreeFiber, EventManager } from '@react-three/fiber'
> +import { extend, useThree, ReactThreeFiber, EventManager } from '@react-three/fiber'
>  
>  import CameraControlsImpl from 'camera-controls'
>  import { ForwardRefComponent } from '../helpers/ts-utils'
> @@ -81,18 +82,24 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
>  
>    const controls = useMemo(() => new CameraControlsImpl(explCamera), [explCamera])
>  
> -  useFrame((state, delta) => {
> -    if (controls.enabled) controls.update(delta)
> -  }, -1)
> -
>    useEffect(() => {
>      controls.connect(explDomElement)
>      return () => void controls.disconnect()
>    }, [explDomElement, controls])
>  
>    useEffect(() => {
> +    const clock = new Clock()
> +    let animationFrame: number
> +    const update = () => {
> +      animationFrame = requestAnimationFrame(update)
> +      const delta = clock.getDelta()
> +      const needFrame = controls.update(delta)
> +      if (needFrame) {
> +        invalidate()
> +      }
> +    }
> +
>      const callback = (e) => {
> -      invalidate()
>        if (regress) performance.regress()
>        if (onChange) onChange(e)
>      }
> @@ -111,6 +118,7 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
>      controls.addEventListener('control', callback)
>      controls.addEventListener('transitionstart', callback)
>      controls.addEventListener('wake', callback)
> +    animationFrame = requestAnimationFrame(update)
>  
>      return () => {
>        controls.removeEventListener('update', callback)
> @@ -119,6 +127,7 @@ export const CameraControls: ForwardRefComponent<CameraControlsProps, CameraCont
>        controls.removeEventListener('control', callback)
>        controls.removeEventListener('transitionstart', callback)
>        controls.removeEventListener('wake', callback)
> +      cancelAnimationFrame(animationFrame)
>      }
>    }, [controls, onStart, onEnd, invalidate, setEvents, regress, onChange])
> ```

useFrame is the ticker/frameloop. opening up new requestAnimFrame-loops can only hurt performance, you should imo never call raf and always use useFrame instead.

what is

```jsx
const needFrame = controls.update(delta)
```

?

**Comment by drcmda** [comment]
quick fix
```jsx
    <mesh
      onClick={() => {
        invalidate();
        requestAnimationFrame(() => controls.dolly(1, true));
      }}
      
      ```

**Comment by drcmda** [comment]
will add a small example for keeping things in sync.

**Comment by vmakela** [comment]
I just realized that no frames are actually skipped, but the `controls.update` function just ends up being called with a huge delta if no frames have been rendered in a while. `camera-controls` seems to only use the `delta` provided in the `update` function for tracking time, so the time `controls.dolly` is called at doesn't matter. Doing all animated transitions like
>```js
>invalidate()
>requestAnimationFrame(() => controls.dolly(1, true))
>```
ensures that a frame has been rendered just before starting the animation, so it keeps the delta small enough.


> what is
> 
> ```js
> const needFrame = controls.update(delta)
> ```
> 
> ?

`controls.update` returns true if something has changed and new frame should be rendered. I don't think that a `useFrame` can be canceled, so it isn't useful for the current implementation.

**Comment by drcmda** [comment]
> ```js
>     <mesh
>       onClick={() => {
>         invalidate()
>         requestAnimationFrame(() => controls.dolly(1, true))
>       }}
> ```

intresting! so cc thinks it will always render. this might be a limitation of the library. regardless, the raf trick would also take care of animations that truly start immediately.

i added the gotcha to the docs

**Comment by abernier** [comment]
this PR should fix it [https://github.com/pmndrs/drei/pull/2451#:~:text=🐛-,it%20also%20fixes%20a%20bug,-with%20frameloop%3D"demand](https://github.com/pmndrs/drei/pull/2451#:~:text=%F0%9F%90%9B-,it%20also%20fixes%20a%20bug,-with%20frameloop%3D%22demand)
