### ISSUE TITLE
use without react-three-fiber

### ISSUE THREAD

**Issue by arpu** [pmndrs/drei#201]
Hey,

would it be possible to use drei without react-three-fiber ? 

iike with theejs only or aframe Environment?

**Comment by drcmda** [comment]
some things you can use, like meshBounds, but neither three nor aframe have real components and that eliminates the rest. three has none at all, it isn't even aware of lifecycles, mount/unmount phases, and aframe only has directives - web components are pretty inept when it comes to integration and the consensus is that you use them for small self-contains bits of code/ui. drei components are aware of r3f, its settings, resolution, events, lifecycles, renderloop and so on, that is what makes this so easy compared to a ton of code you'd normally have to write for each primitive.

**Comment by arpu** [comment]
thx for the information @drcmda 

I look how i can do use react-three.fiber in long run, would be nice i could use some aframe components like the networked-aframe  and drei/react-three-fiber at same time

**Comment by arpu** [comment]
for now i think this can be closed
