### ISSUE TITLE
Environment map presets

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#202]
Environment maps are a requirement for metallic materials to render properly, so it would be helpful to have a way to quickly pull in a basic environment map without manually downloading a bunch of files and setting up paths.
 
How would you feel about including a set of three.js example cube textures as presets for the environment component? So we could simply say:
```jsx
<Environment preset="pisa" />
```
Here's an example sandbox where I've extended the Environment component with a few presets from Three.js that I'm dynamically loading from jsDelivr:
https://codesandbox.io/s/r3f-environment-helper-lj4jo?file=/src/App.js

**Comment by gsimone** [comment]
We do have something similar with `useNormalTexture` and `useMatcapTexture`, so a PR for this would be more than welcome!

**Comment by drcmda** [comment]
it would be awesome. but can it even be made safely? the cdn says 

    Package size exceeded the configured limit of 50 MB. Try https://github.com/mrdoob/three.js/tree/r123/examples/textures/cube/ instead.

**Comment by mattrossman** [comment]
@drcmda I'm not seeing that from the sandbox on my end, are you trying to access [the entire cube texture directory](https://cdn.jsdelivr.net/gh/mrdoob/three.js@r123/examples/textures/cube/)? In the example above each texture is accessed individually.

I'm interpreting that message to mean that any individual file can't exceed 50 MB. The cube textures are far from that (highest I saw was ~500 KB).

**Comment by drcmda** [comment]
this url: https://cdn.jsdelivr.net/gh/mrdoob/three.js@r123/examples/textures/cube/

**Comment by drcmda** [comment]
make the pr if jsdelivery is good to go!
