### ISSUE TITLE
Float does not work with on demand rendering

### ISSUE THREAD

**Issue by AaronClaes** [pmndrs/drei#2033]
- `three` version: 0.166.1
- `@react-three/fiber` version: 8.16.8
- `@react-three/drei` version: 9.108.4

### Problem description:

The `Float` component does not work when the frameloop is set to `demand`. 

### Relevant code:

```tsx
function Component() {
	return (
		<Canvas frameloop="demand">
			<Float>
				<Box />
			</Float>
		</Canvas>
	);
}
```

`invalidate` is not being called inside the Float component.

### Suggested solution:

Call `invalidate` inside the Float component `useFrame`

**Comment by CodingReaper1** [comment]
i have 9.112.0 version and it is still not resolved

**Comment by AaronClaes** [comment]
> i have 9.112.0 version and it is still not resolved

Did you pass the `autoInvalidate` prop as mentioned in the PR? That should fix the problem. 
We decided not to make it auto invalidate by default because this might not be the expected behavior and would break certain cases.
