### ISSUE TITLE
Billboard does not respect position after updating three to 0.166

### ISSUE THREAD

**Issue by pehaa** [pmndrs/drei#2042]
- `three` version: 0.166.0 and 0.166.1
- `@react-three/fiber` version: 8.16.8
- `@react-three/drei` version: 9.108.4
- `node` version: 20.10.0  
- `npm` (or `yarn`) version: 10.8.2

### Problem description:

After updating `three` to version 0.166, `Billboard` does not respect the `position` props. All objects overlap.

### Relevant code:

[See sandbox](https://codesandbox.io/p/sandbox/spherical-word-cloud-forked-c6rkft) 

Switching three version to 0.165 fixes the issue.

### Suggested solution:

I suspect it's related to this change in v0.166 
- Object3D
Respect matrixWorldAutoUpdate in matrix update methods. https://github.com/mrdoob/three.js/pull/28533 (@CodyJasonBennett)

**Comment by steoo** [comment]
can reproduce, been driving me crazy while following this https://codesandbox.io/p/sandbox/spherical-word-cloud-forked-ymf4nd?file=%2Fsrc%2FApp.js%3A12%2C59. In my version (react-three/drei v: 9.108.4) – it won't work

**Comment by ttillberg** [comment]
in my case rolling back three to 0.165.0 temporary fixed it - far from ideal of course
