### ISSUE TITLE
The grass (instances) example in the readme / documentation should be updated. 

### ISSUE THREAD

**Issue by raptyk** [pmndrs/drei#2047]
There is an grass example in documentation (https://github.com/pmndrs/drei?tab=readme-ov-file#instances) is not working:

> 👉 Note: While creating instances declaratively keeps all the power of components with reduced draw calls, it comes at the cost of CPU overhead. For cases like foliage where you want no CPU overhead with thousands of intances you should use THREE.InstancedMesh such as in this [example](https://codesandbox.io/s/grass-shader-5xho4?file=/src/Grass.js).

![grass](https://github.com/user-attachments/assets/219258d9-d508-492c-a1a9-c0baa20ff6dc)

**Comment by rndexe** [comment]
There is an updated version here:
https://pmndrs.github.io/examples/demos/grass-shader

Source code:
https://github.com/pmndrs/examples/tree/main/demos/grass-shader
