### ISSUE TITLE
[component idea] Curve Editor

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#205]
Inspired by this tweet by @AndrewPrifer https://twitter.com/AndrewPrifer/status/1339941921788194817

We could wrap the Curve editing functionality with a component that exposes props for 
- number of handles & initial positions
- editing status (is being edited, is showing handles, is showing curve)
- callbacks on state change?

**Comment by joshuaellis** [comment]
I've been looking at this briefly today, I see a problem being that there's lots of different kinds of `Curve` is the idea to support them all? I don't think all of them lend themselves to be edited nicely, i.e the base `Curve` component doesn't have a `setPoints` func. What do you think?
