### ISSUE TITLE
Doesn't work with npm

### ISSUE THREAD

**Issue by dmurvihill** [pmndrs/drei#2090]
- `three` version: n/a
- `@react-three/fiber` version: n/a
- `@react-three/drei` version: n/a
- `node` version: 20.11.0
- `npm` (or `yarn`) version: 10.2.4

### Problem description:

`npm install` in a fresh clone and you get a bunch of peer dependency errors.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @monogrid/gainmap-js@3.0.5
npm ERR! Found: three@0.151.3
npm ERR! node_modules/three
npm ERR!   dev three@"^0.151.0" from the root project
npm ERR!   peer three@">=0.126.1" from camera-controls@2.7.2
npm ERR!   node_modules/camera-controls
npm ERR!     camera-controls@"^2.4.2" from the root project
npm ERR!   8 more (maath, meshline, three-mesh-bvh, three-stdlib, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer three@">= 0.159.0" from @monogrid/gainmap-js@3.0.5
npm ERR! node_modules/@monogrid/gainmap-js
npm ERR!   @monogrid/gainmap-js@"^3.0.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: three@0.168.0
npm ERR! node_modules/three
npm ERR!   peer three@">= 0.159.0" from @monogrid/gainmap-js@3.0.5
npm ERR!   node_modules/@monogrid/gainmap-js
npm ERR!     @monogrid/gainmap-js@"^3.0.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/dolan/.npm/_logs/2024-09-10T03_59_35_720Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/dolan/.npm/_logs/2024-09-10T03_59_35_720Z-debug-0.log
```

If npm is not supported for development, that should be up at the top of the README.

### Relevant code:

Yarn 4.3.1 emits warnings but is a little more accepting:
```
➤ YN0000: · Yarn 4.3.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ three is listed by your project with version 0.151.3 (pab95c), which doesn't satisfy what @monogrid/gainmap-js and other dependencies request (>=0.159.0).
➤ YN0002: │ @react-three/drei@workspace:. doesn't provide @types/node (pf82ca), requested by ts-node and other dependencies.
➤ YN0002: │ @react-three/drei@workspace:. doesn't provide webpack (pe3030), requested by babel-loader.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 388ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5s 736ms
➤ YN0000: · Done with warnings in 6s 377ms
```

**Comment by DennisSmolek** [comment]
I've done 4 different projects today and not had this issue.

Reading the error, you have other npm plugins causing problems wit outdated versions of three.
Try deleting your package lock and npm_modules. After that make sure your versions are up to date.

If that still doesn't work please share your package.json

**Comment by dmurvihill** [comment]
It's [this one](https://github.com/pmndrs/drei/blob/master/package.json).

**Comment by DennisSmolek** [comment]
> It's [this one](https://github.com/pmndrs/drei/blob/master/package.json). I got this in a brand-new fresh clone of drei, no package lock or node_modules to speak of.

No the package.json of your project that is throwing errors.

Here is a code sandbox running the latest drei in react with no errors:
https://codesandbox.io/p/sandbox/ywf5xn

I can make a fancier r3f one if you want but you can see the npm is loading it no problem. Download that sandbox and see what happens.

It sounds like you have issues in your own build/project

**Comment by dmurvihill** [comment]
I'm having this issue installing and building drei itself.

**Comment by dmurvihill** [comment]
Here's a [branch](https://github.com/dmurvihill/drei/tree/canary-tm-test-install) with a [failing CI run](https://github.com/dmurvihill/drei/actions/runs/10896741007/job/30237042018) to demonstrate the issue.

**Comment by DennisSmolek** [comment]
Ok to clarify.

You read the [Contributing Guidelines](https://github.com/pmndrs/drei/blob/master/CONTRIBUTING.md) that says the package was developed, tested, and built using yarn.

But you want to use NPM instead, and the npm isn't configured to allow builds with different versions like the yarn configuration is.

Drei has minimum support for three at 149 but it looks like one of the packages moved their three version to 168. (most likely just pinned to latest)

As the error message says, you can force it, add the legacy deps flag, or adjust the config to allow the version missmatch with a warning instead of a block.

Also, you should generally use the standard build pipeline if you plan to contribute back

**Comment by dmurvihill** [comment]
Thanks for clarifying. No, I'm trying to trace a bug four packages upstream and didn't see the contributor guidelines. If npm is not supported that's no problem.
