### ISSUE TITLE
How can obtain the value of  getPolarAngle () in the orbitControls?

### ISSUE THREAD

**Issue by nestorchura2019** [pmndrs/drei#210]
When we use the orbitControls component we can assign (set) various properties of the OrbitControls 
 `<OrbitControls autoRotate autoRotateSpeed ={5} target={[1,4,1]}/>`
but how can I call the methods like **.getPolarAngle () .getAzimuthalAngle () .update ()**

**Comment by drcmda** [comment]
if you want to obtain a reference to any object in r3f (or react in general) then you use useRef.

**Comment by nestorchura2019** [comment]
thanks I will try

**Comment by nestorchura2019** [comment]
Works, thanks.
