### ISSUE TITLE
Setting request headers on a Loader?

### ISSUE THREAD

**Issue by j6k4m8** [pmndrs/drei#218]
I'm trying to set request headers on a texture loaded with a TextureLoader. My understanding is that  I can use `useLoader` and pass a class of loader to use, but I'm not sure if there's a way to call the underlying `setRequestHeader` function on the Loader object.

Is this exposed to the user, or will I need to do some digging in the original THREE code?

My ideal is the following:

```js
const texture = useTexture("my-cool-image.png", {
    headers: {
        "Authorization": "Blah"
    }
});
```

What is the right approach here?

**Comment by Pomevak** [comment]
Yes, you can use [useLoader](https://github.com/pmndrs/react-three-fiber/blob/master/markdown/api.md#useloader) instead. You can pass a callback to the third parameter to configure the loader.

**Comment by j6k4m8** [comment]
Got it, thank you @Pomevak! I've updated to this:

```ts
import { TextureLoader } from "three";
import { useLoader } from "react-three-fiber";

const texture = useLoader(
    TextureLoader,
    "my-image-url.
    (loader) => {
        loader.setRequestHeader({
            "Content-Type": "image/jpeg",
        });
    }
);
```

But it doesn't appear that requests are being set: The network request does indeed take place, but without headers. Do you have any thoughts as to why this might be?

I also realize that this might be a better issue for the r3f repo; please let me know if you'd like me to move it :)

**Comment by joshuaellis** [comment]
I think this should be moved to react-three-fiber. Especially as this repo does not manage the `useLoader` function, so i'm going to close this. However looking at the function, we just pass the loader, so it might be a problem with `THREE.TextureLoader`. So you may end up having to post on `three.js`.

**Comment by w3ichen** [comment]
I got it working with `loader.setRequestHeader`

```
import { useGLTF } from "@react-three/drei";
const { scene } = useGLTF(mesh, undefined, undefined, (loader) => {
  loader.setRequestHeader({
    Authorization: `Bearer ...`,
  });
});
```
