### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by sovetski** [pmndrs/drei#2186]
- `three` version: 0.170.0
- `@react-three/fiber` version: 9.0.0-rc.0
- `@react-three/drei` version: 9.115.0
- `node` version: v20.10.0
- `npm` (or `yarn`) version: 10.2.3

### Problem description:

Hi,

After upgrading to the version of `three` to `^0.170.0`, I have the following error:

`TypeError: Cannot read properties of undefined (reading 'replace')`

It comes from `Text` component, when I remove it, error disappears

### Relevant code:

```jsx
<Text color="black">
    Hello World
</Text>
```

**Comment by tarasromil** [comment]
I have the same issue - here is the sandbox:
https://codesandbox.io/p/sandbox/suspicious-river-wtc4tg

**Comment by A7medAbdien** [comment]
The same

**Comment by stephenfjohnson** [comment]
Same

**Comment by billysimmons** [comment]
Same

**Comment by OldManMeta** [comment]
I've got this also - no text at all. Can this be prioritized please.

**Comment by Igor-Vuk** [comment]
Same problem. This started happening with the latest three.js 0.170.0. Version 0.169.0 works fine

**Comment by imeqquinox** [comment]
Issue has been fixed with latest @react-three/drei v9.166.0

**Comment by abernier** [comment]
> Issue has been fixed with latest @react-three/drei v9.116.0

@sovetski can you confirm and close?

**Comment by sovetski** [comment]
@abernier its works perfectly thank you
