### ISSUE TITLE
[Idea] Stories should be written in TS

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/drei#220]
I just saw #219 and realised if the stories were written in TS then this issue probably wouldn't have happened. I'm happy to work on this if you want to make the move, it's a bit of a chore, but in the long run it'd probably be useful (especially when making new components).

**Comment by gsimone** [comment]
Absolutely, it's a lot of work, but if you or somebody can start, I'll be glad to help

**Comment by gsimone** [comment]
Also kinda related, stories right now import from the component, ideally they should import from src/index to give us an early error if we forgetti spaghetti exports

**Comment by joshuaellis** [comment]
>ideally they should import from src/index to give us an early error if we forgetti spaghetti exports
Yes good point, might as well do that here too.

On the subject of exports, is it worth sorting out the export pattern because people keep having issues with `react-native` 
* #212 
* #182 
* #19 

I thought you could potentially have `@react-three/drei/native` and not include `Html`, maybe make a native `Loader`. I can make a new issue if you prefer.

**Comment by gsimone** [comment]
yeah, do open an issue for that, making an ad-hoc export for native makes sense, let's see what others suggest

**Comment by joshuaellis** [comment]
fixed in #231
