### ISSUE TITLE
{progress} = Useprogress()   Don't update the value of progress, always 0%, codesandbox example

### ISSUE THREAD

**Issue by nestorchura2019** [pmndrs/drei#225]
When I try to implement the usePorgress, the load number is not updated, it always stays at zero%, until the complete model is loaded, using Supense.

You can see the error if you use chrome dev tools with the network in 3G mode

codesandbox example
https://codesandbox.io/s/floating-shoe-with-loading-ui-4bs7l?file=/src/App.js:4876-5021
https://4bs7l.csb.app/
![image](https://user-images.githubusercontent.com/56547770/104146546-83bd6680-53a1-11eb-9341-b0f30daa13a5.png)
![image](https://user-images.githubusercontent.com/56547770/104146700-f62e4680-53a1-11eb-8ced-2458074d0bd7.png)

**Comment by nestorchura2019** [comment]
i think the {progress} of useProgress(), dont have get the percentage to show

**Comment by nestorchura2019** [comment]
`function Loader() {
  const { active, progress, errors, item, loaded, total } = useProgress()
  return <Html center>{progress} % loaded</Html>
}`


`<Suspense fallback={<Loader />}>
          <Shoe />
 </Suspense>`

**Comment by RenaudRohlinger** [comment]
@nestorchura2019 On your sandbox you were using two different imports of drei and @react-three/drei, you should just use @react-three/drei, example updated :
https://codesandbox.io/s/floating-shoe-with-loading-ui-forked-1pyed?file=/src/App.js

Also, I don't think the loading takes into consideration the download progress of xhr files such as hdr in some case so it might just from 0 to 75/80% in this example.

**Comment by nestorchura2019** [comment]
> @nestorchura2019 On your sandbox you were using two different imports of drei and @react-three/drei, you should just use @react-three/drei, example updated :
> https://codesandbox.io/s/floating-shoe-with-loading-ui-forked-1pyed?file=/src/App.js
> 
> Also, I don't think the loading takes into consideration the download progress of xhr files such as hdr in some case so it might jump from 0 to 75/80% in this example.

Yes because in the drei examples in codesandbox I see that they use drei and react-three / drei

**Comment by nestorchura2019** [comment]
@RenaudRohlinger thanks looks good. 
Ill check in the morning.

**Comment by nestorchura2019** [comment]
> @nestorchura2019 On your sandbox you were using two different imports of drei and @react-three/drei, you should just use @react-three/drei, example updated :
> https://codesandbox.io/s/floating-shoe-with-loading-ui-forked-1pyed?file=/src/App.js
> 
> Also, I don't think the loading takes into consideration the download progress of xhr files such as hdr in some case so it might jump from 0 to 75/80% in this example.

I tested with another glb model that had texture and the same, it only shows from 70% onwards.
from 0% jumps directly to 70%

Is there another way to make it more precise?

**Comment by RenaudRohlinger** [comment]
Natively on threejs there is a onProgress callback for any gltf / datatexture. I remember there was an issue when the file was with some specific server configuration where it lost the initial total size (see https://github.com/mrdoob/three.js/issues/15584) and always keep the progress at 0.  I have no idea about how it works with the useProgress hook but it should be doable. Maybe @gsimone or @drcmda has an idea otherwise I could check to implement that.

**Comment by nestorchura2019** [comment]
@RenaudRohlinger I had that problem that the progress in three.js was always zero but in Local it worked, but it seems that it was a problem with the hosting (firebase), a friend told me that in AWS it worked.
But in reeact.js I am not sure what the error is so the% load is not accurate

**Comment by joshuaellis** [comment]
I'm going to close this as it looks like an issue with three.js, @nestorchura2019 if you need anymore support, we can reopen this.

**Comment by xinaesthete** [comment]
I have a similar issue, only when I log the progress value I see it steadily increasing

```tsx
function Progress() {
  const { progress } = useProgress();
  console.log('progress', progress);
  return (
    <div>loading: {Math.floor(progress)}%...</div>
  )
}
```

Seems much more like a React issue, which I have less experience of, but I really don't see why this is happening, but since google lead me here I figured it could be relevant.

**Comment by jamesryan-dev** [comment]
+1 following as my progress jumps from 0% -> 70% -> loaded

**Comment by Madflows** [comment]
bump, same here

**Comment by sayjeyhi** [comment]
not working correctly
