### ISSUE TITLE
Add R3F v9 in peerDependencies

### ISSUE THREAD

**Issue by verekia** [pmndrs/drei#2253]
Installing R3F v9 with Drei gives the following error due to the [@react-three/fiber@">=8.0 peerDependency](https://github.com/pmndrs/drei/blob/v10/package.json#L148):

```
➜  next15-app-r3f9-react19 git:(main) ✗ npm i
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: next15-app-r3f9-react19@0.1.0
npm error Found: @react-three/fiber@9.0.0-rc.1
npm error node_modules/@react-three/fiber
npm error   @react-three/fiber@"9.0.0-rc.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @react-three/fiber@">=8.0" from @react-three/drei@9.120.0
npm error node_modules/@react-three/drei
npm error   @react-three/drei@"9.120.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
```

With the following dependencies:

```json
  "dependencies": {
    "@react-three/drei": "9.120.0",
    "@react-three/fiber": "9.0.0-rc.1",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "next": "15.0.4",
    "three": "0.171.0"
  }
```

- Node v22.10.0
- NPM v10.9.0

In the meantime, `npm i --legacy-peer-deps` works.

**Comment by abernier** [comment]
should we add `|| ^9`?

**Comment by abernier** [comment]
i've checked and unintuitively:
```js
semver.satisfies('9.0.0-rc.1', '>=8.0') // false
```
as well as
```js
semver.satisfies('9.0.0-rc.1', '^8 || ^9') // false
```
we can either specifically add `|| 9.0.0-rc.1` in drei's peerDep or wait for `9.0.0`?

@verekia what do you think?

**Comment by MuntasirSZN** [comment]
Any Update?

**Comment by MuntasirSZN** [comment]
> i've checked and unintuitively:
> 
> ```js
> semver.satisfies('9.0.0-rc.1', '>=8.0') // false
> ```
> 
> as well as
> 
> ```js
> semver.satisfies('9.0.0-rc.1', '^8 || ^9') // false
> ```
> 
> we can either specifically add `|| 9.0.0-rc.1` in drei's peerDep or wait for `9.0.0`?
> 
> @verekia what do you think?

Currently, i think `|| 9.0.0-rc.1` will do.

**Comment by verekia** [comment]
We can use `^9.0.0-0` to allow pre-releases of `9.0.0` too.
```js
semver.satisfies('9.0.0-rc.1', '^8 || ^9.0.0-0') // true
semver.satisfies('9.1.1', '^8 || ^9.0.0-0') // true

semver.satisfies('9.2.3-rc.4', '^9.0.0-0') // false
```

**Comment by abernier** [comment]
#2259 merged, release 9.120.4 in progress...

i didn't know that `-0` semver trick, thank you

@verekia can you confirm drei 9.120.4 is now installable with r3v v9-rc ?

**Comment by verekia** [comment]
Ah, we're going to need to update the react peerDep as well, since Drei requires 18 and R3F9 requires 19:

https://github.com/pmndrs/drei/blob/master/package.json#L135
https://github.com/pmndrs/react-three-fiber/blob/v9/packages/fiber/package.json#L63

I'll make a follow-up PR.

**Comment by abernier** [comment]
but as of now, i don't think drei is yet compatible with React 19, is it?

**Comment by verekia** [comment]
But since R3F 9 is not compatible with React 18, we're a bit stuck here.

**Comment by abernier** [comment]
let's wait otherwise, i don't think there is a special rush on going react 19 until r3f v9 is here, don't you think?

**Comment by abernier** [comment]
but maybe drei is compatible with react 19, i haven't tested...

**Comment by verekia** [comment]
I am using Drei it in my React 19, R3F9 game. So far the components I am using work, except MultiMaterial. I think we can expect issues with a lot of them, so maybe this deserves to be a major bump + alpha version. It would be clearer that this new version of Drei is supposed to go with React 19, R3F9, and that there will be issues during this transition phase.
