### ISSUE TITLE
Contact shadows example is broken

### ISSUE THREAD

**Issue by marcofugaro** [pmndrs/drei#226]
Contact shadow example on storybook doesn't work. I am seeing no shadows.

https://drei.react-spring.io/?path=/story/shaders-contactshadows--contact-shadow-st

Tested on Chrome for macOS.

### Screenshot
<img width="739" alt="Screenshot 2021-01-10 at 22 17 10" src="https://user-images.githubusercontent.com/7217420/104172232-3a523300-5404-11eb-9520-b299981bca04.png">

**Comment by joshuaellis** [comment]
This has been fixed in #223

**Comment by joshuaellis** [comment]
fixed in #231
