### ISSUE TITLE
Node module CurveModifier.js Failed to compile

### ISSUE THREAD

**Issue by Kaushal-Panchal** [pmndrs/drei#234]
### This is the error I am facing while using drei , Looks like an issue with latest version ( "@react-three/drei": "^2.2.15" )

**Failed to compile.**

./node_modules/@react-three/drei/CurveModifier.js
Module not found: Can't resolve 'three/examples/jsm/modifiers/CurveModifier' in 'F:\Work\MyProjects\React-Three\mine_craft\node_modules\@react-three\drei'

**Comment by joshuaellis** [comment]
Hi @Kaushal-Panchal can you please tell us what version of three you're using? I imagine you don't have the correct version to call `CurveModifier`

**Comment by Kaushal-Panchal** [comment]
> Hi @Kaushal-Panchal can you please tell us what version of three you're using? I imagine you don't have the correct version to call `CurveModifier`

Hey , @joshuaellis  ... 
**react-three-fiber: "^5.3.13**
 **three : ^0.121.1,**
These are my current dependencies!

**Comment by joshuaellis** [comment]
Yep, `CurveModifier` wasn't added until r122 – https://github.com/mrdoob/three.js/pull/20538 you'll need to update dependencies if you want to use `CurveModifier` or downgrade `@react-three/drei`
