### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by jbixon13** [pmndrs/drei#248]
### Describe the feature you'd like:

As a potential contributor I'd like some basic guidelines for how to compose a PR for maintainers. Specifically I think some clarity around whether I should be creating a story for a potential component in `.storybook` and whether knobs should be used vs. `use-tweaks`, or if there are other styles I should conform to such as making a csb demo 

I think there used to be some instructions (should use ts, etc.) but not sure if those are still applicable

### Suggested implementation:

- Basic install instructions 
- Style guide for demo/story (if needed as part of PR)

**Comment by joshuaellis** [comment]
That's a good idea. 

I recently added some templates for issues which I'm finding the useful. I hope people reporting the issues are too!

I think we could do with one for PRs & a contributing guide.
