### ISSUE TITLE
SVG and/or Icon support

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#251]
### Describe the feature you'd like:

When building 2D UI, it's very useful to have a collection of vector icons to quickly pull in for things like buttons. It would be similarly helpful to have 3D representations of those icons for things like VR menus.

### Suggested implementation:

One approach would be to add an `<Svg />` component or `useSVG` hook that interfaces directly with Three's `SVGLoader` for loading `.svg` files with Suspense. This would be better suited for large, multi-colored SVG files (see the Three.js [SVGLoader example](https://threejs.org/examples/?q=svg#webgl_loader_svg))

Another approach, as seen below, is to create something more tailored to an icon set like [Material Design Icons](https://github.com/Templarian/MaterialDesign) which would provide devs with a bunch of useful presets (something like 6,000 icons are available). This involves extracting some functions that SVGLoader uses internally. The API is familiar to folks who use @mdi/react for 2D UIs.

Tweet demo: https://twitter.com/the_ross_man/status/1352103779978641414

A final consideration for the approach in that demo is that it may be better to use a webfont to render the icons inside of `<Text />` rather than creating complex geometry.

Looking for feedback on what approach(es) people would find most useful.

**Comment by joshuaellis** [comment]
Hi @mattrossman sorry for the delay in replying.

Firstly, adding a hook like `useSvg` is a great idea. It'd fit in with the other loader hooks we've got e.g. `useTexture`. 

I think taking the route of handling icon libraries is interesting. My only worry is looking at the demo, there's a lot of code there - potentially reinventing the wheel?

How would you imagine the webfont would work?

**Comment by mattrossman** [comment]
@joshuaellis I agree, there is a lot of code duplicated from `three/examples` that make the SVG icon approach bloated.

The webfont would be provided by [`@mdi/font`](https://github.com/Templarian/MaterialDesign-Font-Build). I just experimented with how to display icon fonts in `troika-3d-text` and wrote an [equivalent webfont demo here](https://codesandbox.io/s/r3f-material-design-icons-webfont-em5i6). I really wish I didn't have to manually search for the font URL and unicode values but overall there isn't much of a job for drei here. Note that some icon fonts, like the [official Google distribution of Material Icons](https://google.github.io/material-design-icons/) support ligatures so you could simply type something like `refresh` inside <Text /> and it would get converted to the appropriate symbol.

Personally, I'd be fine to just close this issue and let these demos serve as a copy/paste reference. Even the `useSVG` hook would be like one line, so probably not worth adding. If anyone knows of a helper lib to more easily pull in the @mdi/font CDN URL and get unicode characters by name though, do share!

**Comment by joshuaellis** [comment]
Hm, I think you're original implementation makes the most sense, it works quicker ootb! I'm just wondering what are the benefits over creating an `Icon3D` component over just using the `SVGLoader` & passing icons from `@mdi/font`? Or is that not possible? I haven't used SVGLoader much tbh.

If we did want to go down this route, maybe it would make more sense to propose that THREE's internals are extracted into similar util functions, that way we don't have two copies and we have to keep them in sync (although I doubt they'll change that much).

**Comment by mattrossman** [comment]
Yes, it's possible to pull in the SVGs from @mdi/font, though this means you need to put each icon import on a separate line. My goal in the original demo was to mirror the API from `@mdi/react` as closely as possible
