### ISSUE TITLE
Storybook Knobs -> Controls

### ISSUE THREAD

**Issue by jbixon13** [pmndrs/drei#252]
### Describe the feature you'd like:

Transitioning from knobs to controls (and some of the theorized advantages) have been documented [here](https://medium.com/storybookjs/storybook-controls-ce82af93e430).

@gsimone discussed an attempt at this transition; any knowledge you have on some of the pitfalls you ran into would be appreciated.

Another relevant resource is [this open issue](https://github.com/storybookjs/storybook/issues/11984) on transitioning dynamic knobs:

**Comment by joshuaellis** [comment]
Hi @jbixon13 would you be interested in heading the implementation of this change? @Code47X has already implemented a new story with controls in #245.

**Comment by jbixon13** [comment]
yes! I'll start work on it; do you think it makes sense to wait until this PR is merged so I don't have to deal with any potential conflicts in `.storybook/main.js` and its installs?
