### ISSUE TITLE
Compilation error upon install

### ISSUE THREAD

**Issue by jfoxworth** [pmndrs/drei#253]
I installed drei in the normal manner. I tried to use the Html, Stars, Sky, and other components and got the error below upon compilation. The package is basically unusable. I tried deleting the node_modules folder and reinstalling, but that didn't solve the issue.

    Module not found: Can't resolve 'three/examples/jsm/modifiers/CurveModifier' in '/Users/.../node_modules/@react-three/drei'
    /Users/.../node_modules/three/examples/jsm/lines/LineGeometry.js:2
    import { LineSegmentsGeometry } from "../lines/LineSegmentsGeometry.js";

This is caused when the following line is used to add it to the React component

    import { Html } from "@react-three/drei";

    <Html scaleFactor={100}>
        <div class="content">
          This is the floater
        </div>
      </Html>

This is my package.json file

    {
    "name": "my-app",
    "version": "1.0.0",
    "private": true,
    "scripts": {
      "dev": "next dev",
      "build": "next build",
      "start": "next start"
      },
    "devDependencies": {
      "@babel/plugin-proposal-export-default-from": "7.10.4"
    },
    "dependencies": {
      "@react-three/drei": "2.2.18",
    "axios": "0.19.2",
    "chroma-js": "2.1.0",
    "next": "9.5.0",
    "next-redux-wrapper": "6.0.2",
    "prop-types": "15.7.2",
    "ramda": "0.27.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-redux": "7.2.1",
    "react-three-fiber": "4.2.18",
    "redux": "4.0.5",
    "redux-devtools-extension": "2.13.8",
    "redux-saga": "1.1.3",
    "three": "0.119.0"
    }
    }

My guess is that this is some sort of package conflict.

**Comment by joshuaellis** [comment]
Hi @jfoxworth,

You need to be running at least v122 of three to use the generic installs. However, if you're reluctant to updating three, you may be able to get away with importing `Html` like so: `import { Html } from '@react-three/drei/html`

**Comment by jfoxworth** [comment]
I updated three.js and now I have this error ...
./node_modules/@react-three/drei/Environment.js
Module not found: Can't resolve 'use-asset' in '/Users/...'
I tried using the other method with /html and that did not work either.

**Comment by joshuaellis** [comment]
If you can provide a mwe we can look into it for you.

**Comment by jfoxworth** [comment]
mwe?

**Comment by joshuaellis** [comment]
Minimal working example

**Comment by jfoxworth** [comment]
Can I ask what the difference is between installing @react-three/drei and just drei?

**Comment by joshuaellis** [comment]
Drei is the old namespace, it’s not really up to date, and afaik were looking to depreciate it. I would use @react-three/drei

**Comment by jfoxworth** [comment]
Ok. They both give me the same error. What can I do to provide a mwe? Other than a package.json, what can I do?

**Comment by joshuaellis** [comment]
Create an example repo with the application you’re currently working in that we can clone. Alternatively create a code sandbox and provide the link to said sandbox.

**Comment by jfoxworth** [comment]
I think that's the bummer because I originally did this is code sandbox before coming over to my main code base to implement it and I had no issues. Is there any other package that may need to be updated in included that I am forgetting?

**Comment by joshuaellis** [comment]
`react-three-fiber`? The peer-dependencies for `drei` Have r3f at v5-something (I can’t remember right now)

**Comment by joshuaellis** [comment]
Also you’re going to have issues with nextjs & three, I’d look at our next-starter to understand how to get past that caveat.

**Comment by jfoxworth** [comment]
I updated react-three-fiber to the latest version and managed to get another error.

Server Error
SyntaxError: Unexpected token {

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/joshuafoxworth/.../node_modules/three/examples/jsm/lines/LineGeometry.js (1)
Module._compile
internal/modules/cjs/loader.js (721:23)
Object.Module._extensions..js
internal/modules/cjs/loader.js (787:10)
Module.load
internal/modules/cjs/loader.js (653:32)
tryModuleLoad
internal/modules/cjs/loader.js (593:12)
Function.Module._load
internal/modules/cjs/loader.js (585:3)
Module.require
internal/modules/cjs/loader.js (690:17)
require
internal/modules/cjs/helpers.js (25:18)
Object.<anonymous>

**Comment by joshuaellis** [comment]
yep, that looks like the `three.js` problem with next I was talking about. You'll either need to use `next-transpile-modules` or dynamically inject the componenest from THREE // drei (because we import the components from THREE) like so:

```js
import dynamic from 'next/dynamic'

const MyComponent = dynamic(() => import('./MyComponent'), { ssr: false })
```

In my experience i suggest you just use `next-transpile-modules`. It's easier and less of an import headache.

**Comment by jfoxworth** [comment]
What am I importing dynamically in that case? Is it the /drei/html or my react component?

**Comment by joshuaellis** [comment]
Your component that contains the drei/three module.

**Comment by jfoxworth** [comment]
OK. Thanks. I appreciate the help.

**Comment by jfoxworth** [comment]
You saved me. I never would have figured this out on my own.

**Comment by joshuaellis** [comment]
The next thing is annoying and I think it has to do with the way `three` have set their library up, it's a bit odd(?). But the dependency thing i'll have to double check that the repo is suggesting the correct peer levels for the project. No worries, glad I could help.
