### ISSUE TITLE
Compilation error: Attempted import error: 'Geometry' is not exported from 'three'.

### ISSUE THREAD

**Issue by LukaszGrela** [pmndrs/drei#261]
- `three` version: 0.125.1
- `react-three-fiber` version: 5.3.18
- `@react-three/drei` version: 2.2.22
- `node` version: 12.15.0
- `npm` (or `yarn`) version: yarn 1.19.0

### Problem description:
Can't compile after installation of drei and using any of the shape component

> Failed to compile.
>
> ./node_modules/@react-three/drei/useSubdivision.js
> Attempted import error: 'Geometry' is not exported from 'three'.

### Relevant code:

```js
import { Box, Plane } from '@react-three/drei';
import { Canvas } from "react-three-fiber";

function App() {
  return (
    <Canvas>
      <ambientLight />
      <pointLight position={[10, 10, 10]} />
      <Plane args={[2, 2]} />
      <Box position={[-1.2, 0, 0]} />
      <Box position={[1.2, 0, 0]} />
    </Canvas>
  );
}

export default App;

```

**Comment by LukaszGrela** [comment]
I've tried to use the sandboxed example: https://codesandbox.io/s/r3f-render-target-forked-nklno?file=/src/index.js but this one also fails:

```
ModuleNotFoundError: Could not find module in path: 'three/examples/jsm/modifiers/SubdivisionModifier' relative to '/node_modules/@react-three/drei/useSubdivision.js'
```

**Comment by joshuaellis** [comment]
We currently do not support THREE@125 because they removed `Geometry` and `Subdivision`. We will be in the upcoming v3

**Comment by Marguelgtz** [comment]
@joshuaellis Having the same issue, which version of three should we stick to for now?

**Comment by billythemusical** [comment]
For those that get this error and want a solution, reverting Three to an earlier version with `yarn add three@0.124.0` worked for me (at least for the first few examples).

**Comment by mysterybear** [comment]
or `yarn add @react-three/drei@beta` and swap out `react-three-fiber` for `@react-three/fiber` works for me! :)

**Comment by krish-bhanushali** [comment]
Same error.
    "drei": "^2.2.21",
    "react-three-fiber": "^5.3.22",
    "three": "^0.125.1",

**Comment by joshuaellis** [comment]
@krish-bhanushali and for anyone else having this issue:

## Geometry was removed from `three@0.125.0` check the peer deps of the `drei` package you're installing. If you want to use `three@125` you need to use `@react-three/drei` at a minimum of `3.0.0`.

### I am locking this issue
