### ISSUE TITLE
useAnimations is broken

### ISSUE THREAD

**Issue by tiborsaas** [pmndrs/drei#263]
- `three` version: 0.125.1
- `react-three-fiber` version: 5.3.18
- `@react-three/drei` version:2.2.2

### Problem description:

useAnimations throws an error.

### Error output:

```bash
C:\dev\private-projects\dead-off\node_modules\@react-three\drei\useSubdivision.js:3:36: Cannot resolve dependency 'three/examples/jsm/modifiers/SubdivisionModifier'
  1 | import { useRef, useEffect } from 'react';
  2 | import { Geometry, BufferGeometry } from 'three';
> 3 | import { SubdivisionModifier } from 'three/examples/jsm/modifiers/SubdivisionModifier';
    |                                    ^
  4 | 
  5 | function useSubdivision(subdivisions) {
  6 |   const ref = useRef();
```

According to the Three.js changelog, the `SubdivisionModifier` is indeed removed:

https://github.com/mrdoob/three.js/releases/tag/r125

### Suggested solution:

The linked issue has some good ideas: https://github.com/mrdoob/three.js/pull/21072

**Comment by joshuaellis** [comment]
`@react-three/drei` does not support `three` r125. We support up to `0.124.x`.

**Comment by tiborsaas** [comment]
Makes sense. Maybe it would worth mentioning it in the readme.

**Comment by joshuaellis** [comment]
I do believe its in the package peer deps of the latest release, even if you were using r124, it would not work with drei 1.2.2 because CurveModifier was introduced in r122. So in short, i'd update to the latest version of `@react-three/drei` and keep at `three` 124.
