### ISSUE TITLE
Fix install instructions

### ISSUE THREAD

**Issue by jbixon13** [pmndrs/drei#264]
- `three` version: 123
- `react-three-fiber` version: 5.3.13
- `@react-three/drei` version: 2.2.23
- `node` version: 10.15.1
- `npm` (or `yarn`) version: 1.21.1

### Problem description:

Forking drei and then following instructions in `CONTRIBUTING.md` does not work. Running: 
- `git clone`
- `cd drei`
- `npm install`
produces a build error. This is resolved by running `yarn install` instead of `npm install`

### Suggested solution:

change `CONTRIBUTING.md` to use `yarn install` instead of `npm install`

**Comment by joshuaellis** [comment]
Closed by #265
