### ISSUE TITLE
An error message appears in the TXT component, when update to 3,0

### ISSUE THREAD

**Issue by carllx** [pmndrs/drei#270]
An error message appears in the TXT component, when update to 3,0
**Unhandled Runtime Error**
**Error: Error in worker registerModule call: window is not defined**

**Call Stack**
openRequests.<computed>
node_modules/troika-worker-utils/dist/troika-worker-utils.esm.js (593:0)
Worker.worker.onmessage
node_modules/troika-worker-utils/dist/troika-worker-utils.esm.js (579:0)

- `three` version:^0.125.1
- `react-three-fiber` version:^5.3.18
- `@react-three/drei` version:^3.0
- `node` version:12.14.1
- `npm` (or `yarn`) version:6.14.11

**Comment by joshuaellis** [comment]
Hi @carllx 

Here's a codesandbox example of the text component: https://codesandbox.io/s/r3f-troika-text-forked-hhgc3?file=/src/index.js it's using the same packages you've written and I cannot see an error. Please submit a minimal working example so we can review your issue. This is requested when you create a bug report.

**Comment by carllx** [comment]
@joshuaellis , thanks for Many thanks for the prompt reply.
I have no idea what cause the error, 

There is nothing special about my code


```javaScript
import` React } from "react";
import { Text } from "@react-three/drei";
const PlanetSystema = () => {
  
  return (
    <>
      <Text> {"ddddd"}</Text>
    </>
  );
};
export default PlanetSystema;
```
The following error is displayed in the browser console

```
02b286a6-c071-4369-bdfc-a5f881511340:50 ReferenceError: window is not defined
    at d189bef2-d678-45f0-8364-9203e997e279:134
    at typrFactory (d189bef2-d678-45f0-8364-9203e997e279:1692)
    at init (85cb3b98-aced-4165-88d8-c519255898ed:5)
    at registerModule (02b286a6-c071-4369-bdfc-a5f881511340:38)
    at 02b286a6-c071-4369-bdfc-a5f881511340:21
    at Array.map (<anonymous>)
    at registerModule (02b286a6-c071-4369-bdfc-a5f881511340:19)
    at 02b286a6-c071-4369-bdfc-a5f881511340:21
    at Array.map (<anonymous>)
    at registerModule (02b286a6-c071-4369-bdfc-a5f881511340:19)
registerModule @ 02b286a6-c071-4369-bdfc-a5f881511340:50
(anonymous) @ 02b286a6-c071-4369-bdfc-a5f881511340:21
registerModule @ 02b286a6-c071-4369-bdfc-a5f881511340:19
(anonymous) @ 02b286a6-c071-4369-bdfc-a5f881511340:117
```


`| openRequests.<computed> | @ | troika-worker-utils.esm.js?2e99:593
-- | -- | -- | --
  | worker.onmessage | @ | troika-worker-utils.esm.js?2e99:579
  | Promise.then (async) |   |  
  | getTextRenderInfo | @ | troika-three-text.esm.js?5180:1202
  | sync | @ | troika-three-text.esm.js?5180:2160
  | eval | @ | Text.js?ce0b:33
  | commitHookEffectListMount | @ | react-reconciler.dev…pment.js?c996:12485
  | commitLifeCycles | @ | react-reconciler.dev…pment.js?c996:12546
  | commitLayoutEffects | @ | react-reconciler.dev…pment.js?c996:15993
  | callCallback | @ | react-reconciler.dev…pment.js?c996:12184
  | invokeGuardedCallbackDev | @ | react-reconciler.dev…pment.js?c996:12233
  | invokeGuardedCallback | @ | react-reconciler.dev…pment.js?c996:12292
  | commitRootImpl | @ | react-reconciler.dev…pment.js?c996:15716
  | unstable_runWithPriority | @ | scheduler.development.js?3069:646
  | runWithPriority | @ | react-reconciler.dev…opment.js?c996:2495
  | commitRoot | @ | react-reconciler.dev…pment.js?c996:15551
  | performSyncWorkOnRoot | @ | react-reconciler.dev…pment.js?c996:14857
  | eval | @ | react-reconciler.dev…opment.js?c996:2546
  | unstable_runWithPriority | @ | scheduler.development.js?3069:646
  | runWithPriority | @ | react-reconciler.dev…opment.js?c996:2495
  | flushSyncCallbackQueueImpl | @ | react-reconciler.dev…opment.js?c996:2541
  | flushSyncCallbackQueue | @ | react-reconciler.dev…opment.js?c996:2528
  | scheduleUpdateOnFiber | @ | react-reconciler.dev…pment.js?c996:14421
  | updateContainer | @ | react-reconciler.dev…pment.js?c996:18229
  | render | @ | web.js?3079:602
  | eval | @ | web.js?3079:1145
  | commitHookEffectListMount | @ | react-dom.development.js?61bb:20573
  | commitLifeCycles | @ | react-dom.development.js?61bb:20634
  | commitLayoutEffects | @ | react-dom.development.js?61bb:23426
  | callCallback | @ | react-dom.development.js?61bb:3945
  | invokeGuardedCallbackDev | @ | react-dom.development.js?61bb:3994
  | invokeGuardedCallback | @ | react-dom.development.js?61bb:4056
  | commitRootImpl | @ | react-dom.development.js?61bb:23151
  | unstable_runWithPriority | @ | scheduler.development.js?3069:646
  | runWithPriority$1 | @ | react-dom.development.js?61bb:11276
  | commitRoot | @ | react-dom.development.js?61bb:22990
  | performSyncWorkOnRoot | @ | react-dom.development.js?61bb:22329
  | eval | @ | react-dom.development.js?61bb:11327
  | unstable_runWithPriority | @ | scheduler.development.js?3069:646
  | runWithPriority$1 | @ | react-dom.development.js?61bb:11276
  | flushSyncCallbackQueueImpl | @ | react-dom.development.js?61bb:11322
  | flushSyncCallbackQueue | @ | react-dom.development.js?61bb:11309
  | discreteUpdates$1 | @ | react-dom.development.js?61bb:22420
  | discreteUpdates | @ | react-dom.development.js?61bb:3756
  | dispatchDiscreteEvent | @ | react-dom.development.js?61bb:5889`

**Comment by joshuaellis** [comment]
`window is not defined` usually points to SSR. Are you using SSR?

**Comment by carllx** [comment]
Yes, you are right, I am using nextjs, but the component only import in browser, I have no idea why is still trigger the warning.
```javascript
const myText = dynamic(
  () => import('./myText'),
  { ssr: false }
)
```

**Comment by joshuaellis** [comment]
Can you provide a minimum working example and I can have a proper look? Without it will be a real struggle, there's a lot depending on your config etc

**Comment by joshuaellis** [comment]
Hi @carllx,
I've had a look at this issue using `nextjs` here – https://codesandbox.io/s/bold-engelbart-1c7zz?file=/pages/index.js and are still unable to reproduce the issue, to take this any further I must insist we have an example of your code that can reproduce the issue.

**Comment by carllx** [comment]
@joshuaellis Thank you for trying to find a solution for my problem these days. I have tried many times. Just finally found the problem, in my configuration file `next.config.js`
```javascript
const withTM = require('next-transpile-modules')([
    '@react-three/drei',
    'three',
  ])
```
Comment out withTM, everything is normal
```javascript
module.exports = withPlugins([
   // withTM,
   withBundleAnalyzer]
```
