### ISSUE TITLE
ReferenceError: Can't find variable: global

### ISSUE THREAD

**Issue by cedeber** [pmndrs/drei#273]
### Problem description:

Hello, the `global` variable can't be found, like here: https://github.com/pmndrs/drei/blob/99c4500472a5b5d90fe05e059f591065f3edd5f2/src/helpers/base64.ts#L3

Although I didn't compile the project - I won't be able to run `npm install` on the current master branch, it failed - I understand that in the case of ES module for the browser it doesn't work. I won't be surprised, regarding the code, that even TypeScript complains.

I believe that global is window in the browser?

I compile the npm module with Snowpack and Vitejs and they both failed the same way. Both of these bundlers focus on ES Modules.

### Suggested solution:

Declare the variable or import it from somewhere, properly.

Thanks.

**Comment by joshuaellis** [comment]
Hi @cedeber,

I'm not familiar with ES modules for the browser tbh. But to give you some context, we have to polyfill the `Blob` for SSR.
If you'd like to fix this bug that'd be very helpful.

Thanks.

**Comment by cedeber** [comment]
Ok, good to know. I don't have lots of free time, but I can have a look.

**Comment by joshuaellis** [comment]
I don't think anyone really has lots of free time lol! I did a quick google and here's a workaround for you, and just to let you know, the repo is written in TS and works in TS but thank you for the concern.

Here is the workaround: https://github.com/snowpackjs/snowpack/discussions/1085

If you do find yourself with sometime to help apply a permanent fix, that would be awesome.
