### ISSUE TITLE
impossible to use latest version with three <125

### ISSUE THREAD

**Issue by unphased** [pmndrs/drei#281]
Unfortunately three.js r125 is broken for me (blank canvas). So I can't use it. But since v124 is before the type `listenToKeyEvents` was introduced to OrbitControls, this produces a catch-22. 

The problem is that this error 

```
 Property 'listenToKeyEvents' is missing in type '{ enableDamping: false;       
 → zoomSpeed: number; maxDistance: number; minDistance: number; mouseButtons:   
 → { LEFT: MOUSE; MIDDLE: MOUSE; RIGHT: MOUSE; }; }' but required in type       
 → 'Pick<Overwrite<Object3DNode<OrbitControls, typeof OrbitControls>, {         
 → target?: Vector3 | [number, number, number] | undefined; }>, "object" | ...  
 → 62 more ... | "listenToKeyEvents">'.                                         
 [tsserver: 2741]                                                               
```
cannot be eliminated by using `//@ts-ignore`, and the type definitions provided with drei are depending on the three.js corresponding types to have all the items listed. I really wonder if there isn't a cleaner way to specify the type that doesnt leak/pollute the three types' names out so they're replicated in drei's typings?

```
export declare const OrbitControls: React.ForwardRefExoticComponent<Pick<ReactThreeFiber.Overwrite<ReactThreeFiber.     
Object3DNode<OrbitControlsImpl, typeof OrbitControlsImpl>, {                                                            
    target?: import("three").Vector3 | [number, number, number] | undefined;                                            
}>, "object" | "attach" | "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "position" | "up" 
| "scale" | "rotation" | "matrix" | "quaternion" | "layers" | "dispose" | "addEventListener" | "hasEventListener" |     
"removeEventListener" | "dispatchEvent" | "onClick" | "onContextMenu" | "onDoubleClick" | "onPointerDown" |             
"onPointerMove" | "onPointerUp" | "onPointerOver" | "onPointerOut" | "onWheel" | "onPointerMissed" | "center" | "reset" 
| "enabled" | "update" | "keys" | "target" | "domElement" | "minDistance" | "maxDistance" | "minZoom" | "maxZoom" |     
"minPolarAngle" | "maxPolarAngle" | "minAzimuthAngle" | "maxAzimuthAngle" | "enableDamping" | "dampingFactor" |         
"enableZoom" | "zoomSpeed" | "enableRotate" | "rotateSpeed" | "enablePan" | "panSpeed" | "screenSpacePanning" |         
"keyPanSpeed" | "autoRotate" | "autoRotateSpeed" | "enableKeys" | "mouseButtons" | "touches" | "listenToKeyEvents" |    
"saveState" | "getPolarAngle" | "getAzimuthalAngle"> & React.RefAttributes<unknown>>;                                   
```

**Comment by joshuaellis** [comment]
Unfortunately, this isn't a bug. The peer deps for v3.x.x currently clearly states `three>=0.125.0`. This is because of the breaking changes they introduced in regards to removing Geometries. You could opt to use the last version of v2, which I think is something like 2.22.x? You can check on NPM for that.

**Comment by unphased** [comment]
Yeah I wanted to change the tag from bug but didn't see a way to. Agree maybe not a bug. And I get that three is a special snowflake that doesn't do semantic versioning, so that's fine that 125 is a breaking version. But I am just curious if there isn't a better way to define these types. I take it that the .d.ts files are generated somehow? Do you know what tool does that generation? It's just such a tight binding of interfaces here that it smells fishy to me, but I'm still a bit of a TS noob so it might be the "proper way".

**Comment by joshuaellis** [comment]
Are you on about the TS files for `three`? They're removed from `dev` and will be in r126. I'm in the process with another dev in moving them to DT.

>  I take it that the .d.ts files are generated somehow?

I believe Mr Doob maintained them himself. So if there is a bug in the `.d.ts` files you could be right, if you can raise it in the DT repo & tag me that'd be great, if you can fix it, hold off to submit a PR until https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50930 is merged and I'll be able to review it.

**Comment by unphased** [comment]
I was trying to use v3 of drei with three r122 which your first comment addressed and obviously I just need to use v2 of drei in that situation. 

The smelly bit of TS i'm on about is the 2nd code block in my original post. As you can see it is a type definition for drei's `OrbitControls`, which is based off of three's `OrbitControls` (here imported as `OrbitControlsImpl`), my comment is that the definition curiously leaks out every single name of method on three's OrbitControls, it turns out with drei v3 and r122 (in my testing) this was the only point of incongruity: Once I patched out the offending (missing) `listenToKeyEvents` prop name from that list, typescript could complete the build. So all I'm saying is this would've been avoided if, say, some other method was used that didn't require blindly listing out all of three's r125 specific prop names present on its `OrbitControls`' type.

**Comment by joshuaellis** [comment]
> I thought it was autogenerated (note im talking about drei's orbitcontrols d.ts, not any of three's typings) because i cloned the repo and couldn't find this particular .d.ts.

They're auto-generated when our source files (written in TS) are compiled. But they're normally a clone of the `three` .d.ts files, in this case, they still pull in the OG type file. so I'm just gonna leave this as a conflict of libraries.

**Comment by fnick851** [comment]
I am using `Next.js`. And as a temporary and easy workaround, you could do:
```jsx
{
    //@ts-ignore
    <OrbitControls />
}
```
in your `JSX` to suppress the error. 

This is not fixing the issue but at least it'll allow you to build.
