### ISSUE TITLE
Global not defined in ESM bundles.

### ISSUE THREAD

**Issue by dsm23** [pmndrs/drei#284]
- `three` version: 0.125.2
- `react-three-fiber` version: 5.3.18
- `@react-three/drei` version: 3.2.2
- `node` version: 15.5.1
- `npm` (or `yarn`) version: 2.4.0

### Problem description:

It appears that importing from the @react-three/drei library in one of the 2 snowpack react templates throws the ReferenceError: global is not defined. Issues appears to be specific to this library

**Comment by joshuaellis** [comment]
Hi @dsm23,

Have you seen this issue? https://github.com/pmndrs/drei/issues/273

it contains a work around, however if you want to provide a fix that we can permanently implement that would be great! We currently use global as a fix for SSR.

I’m not clued up enough on Snowpack to suggest a solution for the long term yet.

**Comment by joshuaellis** [comment]
This is the offending line: https://github.com/pmndrs/drei/blob/9f30f826980099af90cadc1d919a07bb023ce8c2/src/helpers/base64.ts#L3. I’m wondering if we need it. Whether importing Blob would simply fix our old SSR issue and now new ESM issue...

I could remove this line and release a beta tomorrow to see...

**Comment by dsm23** [comment]
I had not seen the other issue, thank you for point it out to me. If you do need the offending statement would a `globalThis` not also work?

**Comment by joshuaellis** [comment]
Hi @dsm23,

I've released a patch on `3.2.3-beta.1` if you could try it out in snowpack that'd be great. I can test later in the day with SSR.

**Comment by dsm23** [comment]
works well, thank you

**Comment by joshuaellis** [comment]
You're welcome @dsm23 👌🏼

**Comment by cedeber** [comment]
This is good news, thanks. I confirm that it works with snowpack without the Node polyfill. Now, I'll test it with Vite too :-D

**Comment by cedeber** [comment]
Also works with Vitejs 🥳
