### ISSUE TITLE
TransformControls block useResource re-rendering

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#294]
- `three` version: 0.125.2
- `react-three-fiber` version: 5.3.18
- `@react-three/drei` version: 3.4.1
- `node` version: (codesandbox)
- `npm` (or `yarn`) version: (codesandbox)

### Problem description:

R3F's [`useResource`](https://github.com/pmndrs/react-three-fiber/blob/master/markdown/api.md#useResource) is supposed to re-render when the ref has been filled. For some reason, drei's `<TransformControls />` block this behavior for its children.

### Relevant code:

https://codesandbox.io/s/drei-use-resource-bug-vbnrr?file=/src/App.js

Notice from the console that only `Thing1` is re-rendered.

### Suggested solution:

(unknown)

**Comment by joshuaellis** [comment]
Thanks @mattrossman

I've just had a quick look this morning, my initial thought could be it's failing because of this:

```jsx
    return controls ? (
      <>
        <primitive dispose={undefined} object={controls} {...transformProps} />
        <group ref={group} {...objectProps}>
          {children}
        </group>
      </>
    ) : null
```

So initially the children aren't rendered. In this case `Thing2` I could be wrong, but it's a starting point at least because it also fails if you use `React.useRef()`.

**Comment by mattrossman** [comment]
Paul says `useResource` will be deprecated in the next R3F release since it's behavior can be replicated with a `useState` pattern. The issue doesn't occur with the `useState` pattern, so I think we can close this.

Updated sandbox:
https://codesandbox.io/s/drei-use-resource-bug-forked-txgp9?file=/src/App.js
