### ISSUE TITLE
Pass custom position function to <Html />

### ISSUE THREAD

**Issue by dahannes** [pmndrs/drei#295]
### Describe the feature you'd like:

Pass a custom `calculatePosition()` function to `<Html />` component.

I have this use case where I need to make sure the html content (chart labels) sticks to the edge of the viewport and thus remains visible, even though the underlying canvas object gets moved off the screen. 

### Suggested implementation:

Pass function as prop `<Html calculatePosition={(el, camera, size) => [number, number]} />`

e.g. for my special use case I am overriding the function like this:
```diff
function calculatePosition(el, camera, size) {
  const objectPos = v1.setFromMatrixPosition(el.matrixWorld);
  objectPos.project(camera);
  const widthHalf = size.width / 2;
  const heightHalf = size.height / 2;
  return [
-    objectPos.x * widthHalf + widthHalf
+    Math.max(0, objectPos.x * widthHalf + widthHalf),
-    -(objectPos.y * heightHalf) + heightHalf
+    Math.min(size.height, -(objectPos.y * heightHalf) + heightHalf),
  ];
}
```

📦 https://codesandbox.io/s/r3f-sticky-labels-ijhzv

**Comment by joshuaellis** [comment]
Hi @dahannes,

If you could create a sandbox of your suggested implementation that'd be great!
We can then critique it and make sure there aren't any issues.

Thanks

**Comment by dahannes** [comment]
@joshuaellis thx – Here is the sandbox https://codesandbox.io/s/r3f-sticky-labels-ijhzv

**Comment by joshuaellis** [comment]
Looks good, won't break anyone's builds if they update. Do you want to make a PR (incl the sandbox) and we can get other team members to check it out?

**Comment by dahannes** [comment]
Sure, will look into the PR tomorrow

**Comment by drcmda** [comment]
i wonder if this cant be done in a better way though. html has a portal prop that would allow you to place it into an absolute overlay. these escape hatches are often very specific and i'd try to avoid them if humanly possible. we already have them in r3f and it's gotten to a point where it starts to seriously damage going forward because they create unwanted stopgaps when you want to refactor.

could you first check if a portal attach helps?

**Comment by dahannes** [comment]
I see your point @drcmda , but I don't think this can be solved with a separate portal element.

The portal itself would just be a static container, but I need to calculate the position for each element on every frame.
Therefore I need the same arguments as the original function: el, camera, size
