### ISSUE TITLE
weather component

### ISSUE THREAD

**Issue by jbixon13** [pmndrs/drei#297]
### Describe the feature you'd like:

I built a weather component that I've used to create effects like rain or snow in a scene. I could clean up my implementation and open a PR if it has use within drei

### Suggested implementation:

https://codesandbox.io/s/weather-testing-v2-o8wwo?file=/src/Components/Rain.jsx

**Comment by joshuaellis** [comment]
Hi @jbixon13,

I've had a look at this quicky, so forgive me I've misunderstood something but these are my initial thoughts:

Currently, I think the visual style is too dictated, it'd be good to understand what this feature is offering at its core and bring that out when you look at something like `Reflector` there are a lot of parameters which really vary the visual style and let people use the component in their work without the need of worry that its visual style won't fit.

What do you think?

**Comment by jbixon13** [comment]
Yeah I planned to expose more props to the user through refactoring, things like point size, the width, height, depth of the point distribution, color of the points, potentially a texture instead of solid color. 

Do you think it needs to be more generic than that? At that point the only thing we're enforcing are that there are points falling from the top to bottom of the scene.
