### ISSUE TITLE
HDRI Lighting

### ISSUE THREAD

**Issue by stockHuman** [pmndrs/drei#3]
Hello hello!

Don't know if this is too small / uncommon to warrant inclusion, but I've often used the following to quickly set the scene's environment to an HDRI map.

```javascript
import { useEffect } from 'react'
import { UnsignedByteType, PMREMGenerator } from 'three'
import { useThree } from 'react-three-fiber'
import { RGBELoader } from 'three/examples/jsm/loaders/RGBELoader.js'

// or pass as a prop / import from project assets..
const HDRI = 'https://hdrihaven.com/files/hdris/royal_esplanade_1k.hdr'

export default () => {
  const { gl, scene } = useThree()
  const pmremGenerator = new PMREMGenerator(gl)
  const loader = new RGBELoader()
  loader.setDataType(UnsignedByteType)
  pmremGenerator.compileEquirectangularShader()

  useEffect(() => {
     loader.load(HDRI, texture => {
        const envMap = pmremGenerator.fromEquirectangular(texture).texture

	scene.environment = envMap
        // one can also set scene.background to envMap here

	texture.dispose()
	pmremGenerator.dispose()
     })
   }, [scene, loader, pmremGenerator])

   return null
}
```
Very useful library, this one! Nominating the next one be named _trois_. :P

**Comment by drcmda** [comment]
i have something very close to this but im using something called "HDRCubeTextureLoader" to load the hdr. this could be hard to abstract, do you know what the difference is? if there are dozens of formats im not sure how we could pack it into a re-usable component ...

**Comment by stockHuman** [comment]
Nice! 

To my knowledge they are implementations of the same thing, as [CubeTex](https://github.com/mrdoob/three.js/blob/e8145dcaa83f57da82a3d3d413c89e34b9f01571/examples/jsm/loaders/HDRCubeTextureLoader.js) ultimately calls [RGBELoader ](https://github.com/mrdoob/three.js/blob/8791f00b3ee4919a89d33be7cab2fa9a355b94cc/examples/jsm/loaders/RGBELoader.js), and the latter seems to contain the real file parsing logic. I wasn't there for the history of its inclusion, nor for the decision to develop a six-file loader, so on that end your guess is as good as mine.

I know of [this](https://github.com/matheowis/HDRI-to-CubeMap) [thing](https://matheowis.github.io/HDRI-to-CubeMap/), maybe it has to do with with the decision to support both methods of loading HDRIs, but I guess asking Mr. Doob directly is really the only way out of speculation.

That aside, a component that abstracts this all might be overkill or boilerplate-filled. Best leave this issue for someone to find?

**Comment by drcmda** [comment]
we can keep it open meanwhile. the component itself would be super nice to have.

**Comment by emileswain** [comment]
https://matheowis.github.io/HDRI-to-CubeMap/ is an extremly handy web tool for generating the required assets. I have a bunch of hdr equirectangular textures, but as a single texture and not in the cubemap format. It lets you create the images as pngs or hdrs.

**Comment by AndrewPrifer** [comment]
Hey all, I just bumped into a related issue and came up with quite a similar hook:
```ts
const useEquirectangularHDR = (url: string) => {
  const { gl } = useThree();
  const pmremGenerator = new THREE.PMREMGenerator(gl);
  pmremGenerator.compileEquirectangularShader();

  const hdrEquirect = useLoader(RGBELoader, url);

  const hdrCubeRenderTarget = pmremGenerator.fromEquirectangular(hdrEquirect);
  hdrEquirect.dispose();
  pmremGenerator.dispose();

  return hdrCubeRenderTarget.texture;
};
```

This hook works similar to the currently included useCubeTexture, but loads hdrs, in equirectangular rendering and uses PMREMGenerator.

The way I see it, what's currently missing is not just different formats but other orthogonal config options as well when loading envmaps.

- format: hdr, exr, png etc.
- rendering: equirectangular, six image cubemap, cubemap in one image
- PMREMGenerator

The last bit is quite essential, in my experience if you don't use `PMREMGenerator`, even with textures already rendered as CubeMap, things can look terribly wrong with `Standard/PhysicalMaterial`.

Currently `drei` has one hook called `useCubeTexture` for loading envMaps, but it has multiple problems: it cannot load hdr, you need to convert to png, it can only load cubemaps, but not equirectangular, and perhaps the most damning, it doesn't use PMREMGenerator. @drcmda @gsimone I think it would be worth coming up with a hook that can handle at least png AND hdr, can load both equirectangular and cubemaps, and _always_ uses PMREMGenerator. What do you think?

**Comment by gsimone** [comment]
I'm all for it, and you seem to know a lot about this, do you want to help out/make a PR/suggest an API?

There's also this component that might be a good place to test these hooks https://github.com/pmndrs/drei/blob/master/src/Environment.tsx

**Comment by AndrewPrifer** [comment]
@gsimone I looked around and thought about it a bit.

The most flexible implementation would be if we let users provide their own image loader, and determine based on whether `urls` is an array or not, whether the provided map is equirectangular or not. Path is optional in both cases, since even for cube maps it's just convenience.
```ts
function useCubeTexture(loader: TextureLoader | DataTextureLoader, urls: string | string[], path?: string) {}
```

The only issue I see with this API is that it would require people to go digging in three/examples/loaders, but that's a small sacrifice for the gained flexibility.

There is one difficulty I see that I wouldn't want to deal with myself, which is three's lackluster typescript typings. I see react-three-fiber already does some tricks redefining Loader.

**Comment by AndrewPrifer** [comment]
Yet another path we could take, considering how simple it is to create something custom (my hook that works perfectly for my use case is no more than 10 lines), would be to provide one easy to use, best practice, zero config hook, but then we'll have to make some assumptions for what the community as a whole would find the easiest. I'm inclined to say that the easiest way to get your hands on hdr textures is hdrihaven, and for that reason alone it would make sense to provide a hook that simply accepts a url to an equirectangular hdr image. @gsimone what do you think?

**Comment by AndrewPrifer** [comment]
@gsimone @drcmda  I think when this issue was created, the `Environment` component wasn't exported yet. I think that solves most (all?) problems raised here. Should we close this?

**Comment by gsimone** [comment]
It doesn't quite solve it, but it's a good springboard for people looking to add env maps ( or they can just use it ™ ). So agree on closing this!

**Comment by AndrewPrifer** [comment]
Oh yes, it doesn't quite return a map, but you were gonna assign it to `scene.environment`/`background` anyway :P I think we can close it.

**Comment by cptSwing** [comment]
> @gsimone @drcmda @joshuaellis I think when this issue was created, the `Environment` component wasn't exported yet. I think that solves most (all?) problems raised here. Should we close this?

Sorry for bringing this up here, but I am a little confused: Does Environment now use PMREMGenerator or does it not? I certainly can't find any mention of it when digging through the various loaders etc..?

**Comment by AndrewPrifer** [comment]
@cptSwing https://github.com/mrdoob/three.js/pull/22178 integrates PMREMGenerator into WebGLRenderer so these conversions happen automatically. Unless you need it for debugging, you no longer need to use PMREMGenerator in user code. 🎉 It was removed from drei/Environment too a few commits back to reflect this change.

**Comment by cptSwing** [comment]
> @cptSwing [mrdoob/three.js#22178](https://github.com/mrdoob/three.js/pull/22178) integrates PMREMGenerator into WebGLRenderer so these conversions now happen automatically. Unless you need it for debugging, you no longer need to use PMREMGenerator in user code. 🎉 It was removed from drei/Environment too a few commits back to reflect this change.

Well I'll be! No wonder I couldn't find anything. Thanks for the headsup :)
