### ISSUE TITLE
HTML Orthographic Camera does not zoom in and out accordingly

### ISSUE THREAD

**Issue by nathanbryantdev** [pmndrs/drei#308]
- `three` version: ^0.112.1
- `react-three-fiber` version:^4.2.21
- `@react-three/drei` version:^1.5.7
- `node` version: v12.18.4
- `npm` (or `yarn`) version: 6.14.6

### Problem description:

While using an Orthographic camera, the objectScale is not producing the correct scaling. It is blowing up the proportion of the HTML markers by 1000x

### Relevant code:
`function objectScale(el, camera) {
  if (camera instanceof THREE.PerspectiveCamera) {
    var objectPos = v1.setFromMatrixPosition(el.matrixWorld);
    var cameraPos = v2.setFromMatrixPosition(camera.matrixWorld);
    var vFOV = camera.fov * Math.PI / 180;
    var dist = objectPos.distanceTo(cameraPos);
    return 1 / (2 * Math.tan(vFOV / 2) * dist);
  }

  if (camera instanceof THREE.OrthographicCamera) return camera.zoom;
  return 1;
}`

### Suggested solution:
This will fix the issue: 
`
function objectScale(el, camera) {
  var objectPos = v1.setFromMatrixPosition(el.matrixWorld);
  var cameraPos = v2.setFromMatrixPosition(camera.matrixWorld);
  var vFOV = (camera.fov * Math.PI) / 180;
  var dist = objectPos.distanceTo(cameraPos);

  if (camera instanceof THREE.OrthographicCamera) {
    return 1 / ((2 * Math.tan(vFOV / 2) * dist) / camera.zoom);
  } else {
    return 1 / (2 * Math.tan(vFOV / 2) * dist);
  }
}
`

**Comment by joshuaellis** [comment]
closed via #311
