### ISSUE TITLE
Change Controls to receive active camera from props

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#320]
<OrbitControls camera={camera} />

This would allow orbit controls in non-default camera scenarios, such as multiple fbos

https://user-images.githubusercontent.com/1862172/110030871-82237580-7d36-11eb-911c-5fd31f492c0c.mov

**Comment by joshuaellis** [comment]
To clarify, this is because the current impl, uses the default camera?

**Comment by gsimone** [comment]
yeah, I tested the change it just works ™ with few changes https://codesandbox.io/s/r3f-multi-view-mdnhl?file=/src/OrbitControls.js

This should be done for all controls (including Transform, IIRC)

**Comment by joshuaellis** [comment]
Closed by #321
