### ISSUE TITLE
How to correctly import / build the Html component as a dependencie

### ISSUE THREAD

**Issue by AlaricBaraou** [pmndrs/drei#329]
Hello everyone,

I was initially using the drei Html component in react-three-a11y but I replaced it with my own "fork" and it fixed my problem.
So if this "issue" don't seem related to drei feel free to close it.

react-three-a11y ( https://github.com/pmndrs/react-three-a11y/ ) is bundled through tsdx ( which use Rollup )

If you look at this component https://github.com/pmndrs/react-three-a11y/blob/flat_import/src/A11y.tsx 
it used to import Html this way 
`import { Html } from '@react-three/drei/web/Html'`
When doing it this way it seems that the cjs output will look like something like this 
`var Html = require('@react-three/drei/web/Html');`
The require require a file using import and therefore cause an error saying `SyntaxError: Cannot use import statement outside a module`

Because of that I tried importing it this way 
`import { Html } from '@react-three/drei';`
But if I do it, my cjs build goes from 5kb to 150kb as it seems to import all of drei
But at least this way I don't have any issue with remaining import in the file.

I tried my best with tsdx / rollup configs but I've find no way to fix this.
In case it's a problem caused by drei, we suggested that I should open this issue.

Again, builds, esm, cjs, etc.. not my cup of tea, so maybe It's just something that is not related to drei

Happy to provide more information that could help.

**Comment by joshuaellis** [comment]
Yeah, I can see our build process isn't creating the `.cjs.js` files in the directories - `dist/web/html.cjs.js` will not exist. 🤔 thanks for raising this issue, I'll look into it today and get it resolved asap, it's probably causing other people headaches without them realising.

**Comment by AlaricBaraou** [comment]
I'll try the alpha release today, I'll let you know :)

**Comment by AlaricBaraou** [comment]
@joshuaellis I just tried with "@react-three/drei": "3.11.1-alpha.1" as you can see in react-three-a11y@1.0.2-alpha-0
Unfortunately, when I import it to react-three-fiber I get the error below
`"SyntaxError: Cannot use import statement outside a module"`
And if I take a look at the drei folder inside react-three-a11y node mudule I don't see any dist/web/html.cjs. ( if that's what I was supposed to get ) 
Cf image below 
![no_cjs](https://user-images.githubusercontent.com/7174039/111386219-3a90d800-86ac-11eb-80c1-476c644083c1.PNG)
![a11y-dep](https://user-images.githubusercontent.com/7174039/111386221-3b296e80-86ac-11eb-978d-d269045cb1a0.PNG)

If you want to double check, here is what I published in order to test. 
Here is the repo https://github.com/pmndrs/react-three-a11y/tree/drei-test 
The npm release https://www.npmjs.com/package/@react-three/a11y/v/1.0.2-alpha-0

Maybe I missed something but I didn't resolve the issue for me.
