### ISSUE TITLE
Line component thickness appears to vary depending on browser width.

### ISSUE THREAD

**Issue by steveruizok** [pmndrs/drei#331]
- `three` version: "^0.126.1"

- `react-three-fiber` version: "^5.3.19",
- `@react-three/drei` version: "^3.11.0"
- `node` version: v15.8.0
- `npm` (or `yarn`) version: 7.5.0

### Problem description:

![Kapture 2021-03-16 at 20 31 21](https://user-images.githubusercontent.com/23072548/111376248-2098ca80-8697-11eb-9106-192207032b6f.gif)

When changing the browser width, the width of the Line component appears to grow or shrink.

### Relevant code:

Slightly overwrought [sandbox](https://codesandbox.io/s/rtf-glob-8s8mb) where I noticed it.

![Kapture 2021-03-16 at 20 25 43](https://user-images.githubusercontent.com/23072548/111375268-f09cf780-8695-11eb-8b20-37908f5ef592.gif)

The [storybook example](https://drei-pmndrs.vercel.app/?path=/story/abstractions-line--basic-line) also exhibits the bug.

Apologies for the motion sickness. 🤢

**Comment by joshuaellis** [comment]
This is probably an issue with `LineMaterial` in [`three.js`](https://www.github.com/mrdoob/three.js). Probabyl to do with the vertex shader, unless you can see an issue with our implementation?
