### ISSUE TITLE
Reflector gives "TypeError: gl.setRenderTarget is not a function" error on unmount

### ISSUE THREAD

**Issue by 3lijah** [pmndrs/drei#333]
- `three` version: 0.124.0
- `react-three-fiber` version: 5.3.19
- `@react-three/drei` version: v3.11.2
- `node` version: v12.18.3
- `npm` (or `yarn`) version: npm v6.14.6
- `next` version: 10.0.9

### Problem description:

When navigating away from page containing a R3F canvas which contains a Reflector I receive an error "TypeError: gl.setRenderTarget is not a function" I believe this occurs when unmounting the ThreeJS component.

```Call Stack
Object.current
node_modules\@react-three\drei\core\Reflector.js (163:0)
renderGl
/_next/static/chunks/2.js (64560:38)
<unknown>
node_modules\react-three-fiber\web.js (103:0)
Map.forEach
<anonymous>
renderLoop
/_next/static/chunks/2.js (64589:9)
```

### Relevant code:

```js
    <Reflector
      resolution={512}
      args={[100, 500]}
      position={[0, 0, 150]}
      mirror={0.3}
      mixBlur={1}
      mixStrength={2}
      rotation={[-Math.PI / 2, 0, 0]}
      blur={[200, 50]}
      dispose={null}
    >
      {(Material, props) => (
        <Material metalness={0} map={normal} normalScale={[1, 1]} {...props} />
      )}
    </Reflector>
```

### Suggested solution:

It might be related to https://github.com/pmndrs/react-three-fiber/issues/722?

**Comment by gsimone** [comment]
cc @emmelleppi

**Comment by emmelleppi** [comment]
mmm it's strange, I tried to replicate on the fly with a codesandbox but I have no errors.
I mount and unmount the whole Canvas on the click.

https://codesandbox.io/s/drei-reflector-forked-z0895?file=/src/App.js

is it possible that it is something closely related to nextjs?

**Comment by emmelleppi** [comment]
OK, I correct my previous comment. With a few attempts, sometimes the error is thrown, not always.
I think I've also understood the problem.
Btw, thank you for the report ✌️

**Comment by emmelleppi** [comment]
Hi @3lijah 
We have discovered that the problem you have exposed in this issue is not directly attributable to the Reflector. But it was a consequence of incorrect handling of the render loop inside react-three-fiber.

With the new version 6.0.0 of react-three-fiber, this is solved :)

https://github.com/pmndrs/react-three-fiber/releases/tag/v6.0.0

Thank you!
