### ISSUE TITLE
Add a toggle to useHelper

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#334]
`useHelper(ref, constructor, toggle)` so that it ca be easily turned off

**Comment by snelsi** [comment]
Hacky workaround:
`useHelper(showHelper ? ref : { current: null }, proto, ...args)`

**Comment by saitonakamura** [comment]
Current implementation of useHelper has `...args` argument, so if we want to add another argument it'd be a breaking change. Any thought how it's better to tackle it (don't give a damn, provide a hook with another name, wait till next major version?)
