### ISSUE TITLE
Add hidden check to <Html/>

### ISSUE THREAD

**Issue by j-era** [pmndrs/drei#340]
### Describe the feature you'd like:

Hey, I want to suggest a feature to check if the <Html> element's position is hidden and hide it if it is.

### Suggested implementation:

Could be solved by providing an additional property which enables checking if the <Html> object is hidden. The check itself can be realized with raycasting and a distance check.

I wrote an implementation in my fork I'd like to PR.

**Comment by joshuaellis** [comment]
Hi @j-era,

Sure why don't you make a PR and we can go from there!

Probably best if you haven't done so already to ensure you've made a demo of the feature in some capacity.

**Comment by j-era** [comment]
Hey, do you have any new conciderations concerning the PR? Please let me know if I can help.
