### ISSUE TITLE
useMatcapTexture broken?

### ISSUE THREAD

**Issue by Code47X** [pmndrs/drei#344]
Were there any changes to `useMatcapTexture`? I've have some code sandboxes that used `useMatcapTexture` without issues, but now it seems that most are failing to load the matcap textures. I checked and the matcap file is still in the repo. Possible it's just an issue with codesandbox, but everything was working until recently.

![image](https://user-images.githubusercontent.com/5169367/112689445-4c127680-8e48-11eb-9fe4-ae755f6a2df3.png)

![image](https://user-images.githubusercontent.com/5169367/112689501-68161800-8e48-11eb-83b8-f7870453e43c.png)

Here is one of the failing codesandboxes for reference:
https://codesandbox.io/s/cell-fracture-gw7gd

**Comment by joshuaellis** [comment]
I recognise that user name! @emmelleppi – any thoughts?

**Comment by gsimone** [comment]
Works for me, if you have these kind of network problems just download the image and use it from `public` 👍

**Comment by Code47X** [comment]
Yup I checked last night and everything was working again. I think it probably was just some network issue, or maybe I just hit the cdn at a bad time. Anyway, all good now - thanks!
