### ISSUE TITLE
OrbitControls TS2740 error: Type '{}' is missing...

### ISSUE THREAD

**Issue by imding** [pmndrs/drei#345]
Hi,

I have a Typescript React App project where I'm trying to use the OrbitControls component from @react-three/drei.

However when it seems to want all the props to be defined.

![image](https://user-images.githubusercontent.com/20434337/112717393-522b5480-8f27-11eb-8977-2db0a20021d8.png)

Right now I'm working around it using @ts-nocheck for the entire file. Any tips are much appreciated!

**Comment by joshuaellis** [comment]
Please provide a repro of the issue, either a repo or sandbox.

**Comment by always-maap** [comment]
I think you need to install three and @types/three

**Comment by always-maap** [comment]
> Please provide a repro of the issue, either a repo or sandbox.

here's an example
https://codesandbox.io/s/three-orbitcontrols-559cb?file=/src/App.tsx

**Comment by imding** [comment]
Hey both, thanks for the reply. I'll check if I have @types/three installed, but I'm using three syntax all over the project and this is the only place ts is complaining so I didn't think that was the issue.

**Comment by always-maap** [comment]
> Hey both, thanks for the reply. I'll check if I have @types/three installed, but I'm using three syntax all over the project and this is the only place ts is complaining so I didn't think that was the issue.

I test with that sandbox and installing @types/three fixes the problem

**Comment by imding** [comment]
Okay good to know, thanks!
