### ISSUE TITLE
MapControls doesn't work as expected

### ISSUE THREAD

**Issue by GuskiS** [pmndrs/drei#351]
- `three` version: 0.126.1
- `@react-three/fiber` version: 6.0.0
- `node` version: 12.18.3
- `npm` (or `yarn`) version: 1.22.5
- browser version: `chrome@latest`/`edge@latest`

### Problem description:
When visiting https://drei.pmnd.rs/?path=/story/controls-mapcontrols--map-controls-scene-st everything works as expected.

When I tried running drei's storybook locally, I get this:
![MapControls](https://user-images.githubusercontent.com/3505777/113345157-bc366600-933a-11eb-9b29-ba21f0765381.gif)

**Comment by joshuaellis** [comment]
This looks like a bug with `three-stdlib`...

**Comment by GuskiS** [comment]
Done.
