### ISSUE TITLE
OrbitControls keys

### ISSUE THREAD

**Issue by servinlp** [pmndrs/drei#352]
- `three` version: 0.127
- `@react-three/fiber` version: 6.0.5
- `@react-three/drei` version: 4.0.1
- `node` version: 10.20.1
- `npm` (or `yarn`) version:

### Problem description:

I'm trying to run `OrbitControls` with the (as it's previously called) `enableKeys` feature. Now I know this was renamed in Three.js  to `listenToKeyEvents` but this doesn't seem to do anything as a prop.

### Relevant code:
Here's a [codesandbox](https://codesandbox.io/s/silent-leaf-gxz1m?file=/src/App.js)

Perhaps I'm misinterpreting something because Ts is giving the following hint but the `listenToKeyEvents` only seems to need a `HTMLDOMElement` as described by the docs [here](https://threejs.org/docs/index.html?q=orbit#examples/en/controls/OrbitControls.listenToKeyEvents). 
`listenToKeyEvents?: ((domElement: HTMLElement) => void) | undefined`

If it is a bug please let me know and perhaps I can help with a PR/fix.

**Comment by joshuaellis** [comment]
We're now using `three-stdlib` instead of `threejs`, so the 'examples' work in node. I suggest you open a bug in that repo although it may be quicker for you to submit a PR to that repo 😄

**Comment by servinlp** [comment]
Cool will look into it!

**Comment by agcty** [comment]
also having this issue @servinlp were you able to get the prop to work? evem calling listenToKey in useEffect seems to be ver y buggy

**Comment by servinlp** [comment]
No not yet. The code we use right now, and is working for us, is this.
```javascript
// Here controlsRef is a ref on the OrbitControls or MapControls you use.
useEffect(() => {
    if (controlsRef.current) {
      // listenToKeyEvents as a prop on OrbitControls or MapControls doesn't work yet
      // listenToKeyEvents requires a HTMLElement but following the documentation it should be put on window
      controlsRef.current.listenToKeyEvents(window);
    }
  }, [controlsRef]);
```

**Comment by drcmda** [comment]
if three-stdlib/orbit is up to date and comparable with three/jsm/controls/orbit then i think the prop should be renamed in drei accordingly. in drei currently each version is pinned to a std counterpart.

**Comment by servinlp** [comment]
Just checked and it is in `three-stdlib`. Seeing as it is now a method instead of a prop (how it was with `enableKeys`) my method is probably the intended way. As seen in the [example](https://github.com/mrdoob/three.js/blob/master/examples/misc_controls_orbit.html#L66).
