### ISSUE TITLE
Missing dependency use-asset?

### ISSUE THREAD

**Issue by n2k3** [pmndrs/drei#353]
- `three` version: 0.125.1
- `@react-three/fiber` version: 6.0.5
- `@react-three/drei` version: 4.0.1
- `node` version: v12.12.0
- `npm` version: 6.14.2

### Problem description:
While building my code it gives this error, which seems to be related to this repo.
It seems the `use-asset` package is not included as a [dependency of drei](https://www.npmjs.com/package/@react-three/drei?activeTab=dependencies).
```
ERROR in C:/Git/[redacted]/node_modules/@react-three/drei/core/Environment.js
Module not found: Error: Can't resolve 'use-asset' in 'C:\Git\[redacted]\node_modules\@react-three\drei\core'
```

### Relevant code:
Not relevant

### Suggested solution:
Adding `"use-asset"` to `dependencies` in `package.json` in the drei's `package.json`.
Temporary workaround manually adding `"use-asset"` to `dependencies` in `package.json` in your own repo.

---
I could be missing something and/or I could be wrong.

**Comment by joshuaellis** [comment]
Hi, thanks for bringing this to our attention. It seems it's slipped into  `devDeps`. I'll push a patch version now.

**Comment by AffiTheCreator** [comment]
happen again the use-asset dependecy

**Comment by seb776** [comment]
Happens also with     
"@react-three/fiber": "^8.16.8",
"drei": "^2.2.21",
