### ISSUE TITLE
Storybook: TransformControls stories broken

### ISSUE THREAD

**Issue by stephent** [pmndrs/drei#355]
- affected version: as currently deployed at https://drei.pmnd.rs

### Problem description:

- Storybook implementation appears that it is intended to disable OrbitControls when the TransformControls is dragged, but this is not working (tested in Safari 14 + Chrome 89). As the transform is dragged, both it and the camera move
- Changing the knobs for TransformControlsLockSt does not make any change in the appearance or function of the TransformControl, e.g. changing from translation to rotation leaves TransformControl in 'translate' mode.

I suspect this may be an issue with TransformControl itself, as I observe both the same problems in my own project.

### Relevant code:
https://drei.pmnd.rs/?path=/story/controls-transformcontrols--transform-controls-lock-st

**Comment by joshuaellis** [comment]
> I suspect this may be an issue with TransformControl itself, as I observe both the same problems in my own project.

You're probably right, so this should be an issue opened in `three-stdlib` although ngl, if you're looking for a quick fix, it's certainly quicker for you to fix it yourself 🙌🏼

**Comment by stephent** [comment]
I meant the drei implementation of TransformControls, rather than the threejs one...

**Comment by joshuaellis** [comment]
> [Update: OK, so there's a thing called three-stdlib - learning more every day... Will see what more I can uncover about the problem and open up an issue over there.]

yep! Sounds good

**Comment by joshuaellis** [comment]
released in 4.2.0
