### ISSUE TITLE
OrbitControl Dampening Issue

### ISSUE THREAD

**Issue by jchailatte** [pmndrs/drei#356]
- `three` version: 0.126.1
- `@react-three/fiber` version: 6.0.6
- `@react-three/drei` version: 4.0.3
- `node` version: 14.4.0
- `npm` (or `yarn`) version: 

### Problem description:

The dampening when utilizing OrbitControls is not longer working after I updated to using version 4.0.0. 

### Relevant code:

Sandbox after 4.0.0
https://codesandbox.io/s/optimistic-golick-hxlpc?file=/src/App.js

Sandbox prior to 4.0.0
https://codesandbox.io/s/clever-sanderson-8zf7c?file=/src/index.js

### Suggested solution:

I'm not completely sure if the issue is coming from `three-stdlib` since dampening is still enabled according to `OrbitControls.jsx` but it seems likely.

**Comment by joshuaellis** [comment]
It's probably an issue with `three-stdlib` i'd open an issue there & if you're interested, looking at the issue will most certianly get you a quicker fix 🙏🏼

**Comment by jchailatte** [comment]
Got it I'll open an issue over there.

**Comment by jchailatte** [comment]
Oh I think the issue is actually coming from `drei`. The parameter got renamed to `enableDamping` whereas it is passed as `enableDampening` within `drei`.

**Comment by joshuaellis** [comment]
Ah, looks like it could be an easy contribution? 😄

**Comment by jchailatte** [comment]
Never contributed to open source before tbh 😆 . Would I just open a pr?

**Comment by joshuaellis** [comment]
> Never contributed to open source before tbh 😆 . Would I just open a pr?

Absolutely!!
