### ISSUE TITLE
Gizmo helpers not showing up.

### ISSUE THREAD

**Issue by zeeshanali33096** [pmndrs/drei#358]
Hello, 

I am trying to use the Gizmo helper but they don't show up. Can you please tell me where am I going wrong?

```js
import { GizmoHelper, GizmoViewcube, OrbitControls } from "@react-three/drei";
import { OrbitControls as OrbitControlsImpl } from "three-stdlib";   
// Typescript would not let me have OrbitControls from @react-three/drei as type for the controlRef 

import { useRef } from "react";

import { Vector3 } from "three";

const CameraComponentOrbit = () => {
  const controlsRef = useRef<OrbitControlsImpl>(null); 
  return (
    <>
      <OrbitControls ref={controlsRef} />

      <GizmoHelper
        alignment="top-right"
        margin={[50, 50]}
        onTarget={() => controlsRef?.current?.target0 as Vector3}
        onUpdate={() => {
          if (controlsRef.current) {
            controlsRef.current.update();
          }
        }}
      >
        <GizmoViewcube />
      </GizmoHelper>
    </>
  );
};

export default CameraComponentOrbit;
```

I already have a default Perspective Camera included.

My package versions: 

`"@react-three/cannon": "^1.0.0",
    "@react-three/drei": "^4.0.3",
    "@react-three/fiber": "^6.0.8",
    "three": "^0.127.0",
    "zustand": "^3.4.0"
`

**Comment by joshuaellis** [comment]
Have you had a look at the storybook example we have? 

https://drei.pmnd.rs/?path=/story/gizmos-gizmoviewcube--default-story

If you can create the example in a sandbox, that would be really helpful to debug.

**Comment by zeeshanali33096** [comment]
I did go through the storybook [example](https://drei.pmnd.rs/?path=/story/gizmos-gizmoviewcube--default-story). 

At line 21, 

`const controlsRef = React.useRef<OrbitControls>()`

This is where typescript messes up. I tried adding a `//@ts-ignore` but no change, the Gizmo doesn't show up.

Here is the [sandbox](https://codesandbox.io/s/billowing-wood-ovs0m)

**Comment by joshuaellis** [comment]
Well, I'm stumped – @w3dot0 got any thoughts? 😓

**Comment by w3dot0** [comment]
@zeeshanali33096  For some reason attaching the background color breaks the Gizmo Display, @joshuaellis maybe a render order issues? I'm still digging, but if you comment that line out you can see the cube.
![image](https://user-images.githubusercontent.com/605606/113949230-9fc77d00-97c3-11eb-9fac-09405d9d17ab.png)

![image](https://user-images.githubusercontent.com/605606/113949298-c5548680-97c3-11eb-9987-0caf05cbeb7c.png)

**Comment by zeeshanali33096** [comment]
Hmm @w3dot0 removing the background color seems to work for now.

**Comment by zeeshanali33096** [comment]
@joshuaellis  any work arounds for this? The white looks really horrific.

**Comment by joshuaellis** [comment]
@zeeshanali33096 my bad, was this not fixed? NGL i'm not looking into it right now, if you need a fix quick I would look into it yourself and submit a PR 😄

**Comment by zeeshanali33096** [comment]
No worries. I played around with the `renderOrder` but nothing seems to work. Would definitely look into the code

**Comment by zeeshanali33096** [comment]
So when a texture background is used, the gizmo is visible but the environment texture is used on the gizmo child(image attached)
![Screenshot 2021-04-19 at 5 26 44 AM](https://user-images.githubusercontent.com/15167124/115166927-2d17a500-a0d3-11eb-8ecb-04a101f3073e.png)

here is the [sandbox](https://codesandbox.io/s/aged-shape-fqcx4).

I have figured out a fix for `Color()` attached to the scene background, now the texture remains!

**Comment by zeeshanali33096** [comment]
I feel this has to do with @react-three/fiber. Opened a [bug](https://github.com/pmndrs/react-three-fiber/issues/1259)

**Comment by Its-Just-Nans** [comment]
> So when a texture background is used, the gizmo is visible but the environment texture is used on the gizmo child(image attached) ![Screenshot 2021-04-19 at 5 26 44 AM](https://user-images.githubusercontent.com/15167124/115166927-2d17a500-a0d3-11eb-8ecb-04a101f3073e.png)
> 
> here is the [sandbox](https://codesandbox.io/s/aged-shape-fqcx4).
> 
> I have figured out a fix for `Color()` attached to the scene background, now the texture remains!

Hello,
Is this bug fixed ?
https://github.com/pmndrs/drei/issues/358#issuecomment-822094736
How did you solve it ?


Here is an example where I have still an issue with the gizmo and Environment Value
https://codesandbox.io/s/eager-brook-kghigv?file=/src/App.tsx
