### ISSUE TITLE
Extending Prop definitions.

### ISSUE THREAD

**Issue by zeeshanali33096** [pmndrs/drei#361]
Hi guys,

I can't seem to find to find the prop definition to extend an already existing component.

Eg, 

`import { Box } from "@react-three/drei";

interface MetalBox extends ????? {  
    material: MaterialProps;
    physics: BoxProps;
}

const metalBox = (props: MetalBox) => {
   return <Box args={}/>
}`

`???? -  //What do I extend the interface to? If I extend Box, I get an error saying its a value, did you mean typeof Box?`

Another case is [here](https://drei.pmnd.rs/?path=/story/gizmos-gizmoviewport--default-story) on line 21. It shows an error on the line - `OrbitControls is used as a value, did you mean typeof OrbitControls?`

Please help me!

**Comment by joshuaellis** [comment]
All your additional props go to `mesh` so you should be extending from `THREE.Mesh`.

OrbitControls is a component in `drei` not a class. So you need to use `import { OrbitControls } from 'three-stdlib'` and pass that class to your ref or whatever you need it for.
