### ISSUE TITLE
Uncaught R3F hooks can only be used within the Canvas component while using <Html> tag

### ISSUE THREAD

**Issue by clementpeleman** [pmndrs/drei#364]
![image](https://user-images.githubusercontent.com/28512676/114274477-d2b97d00-9a1e-11eb-82c8-2b28d7b0cfe1.png)
I am getting an error when i try to use the Html tag inside the Canvas tag. Without the html inside the canvas everything works fine.

Error:
![image](https://user-images.githubusercontent.com/28512676/114274511-f7adf000-9a1e-11eb-9b04-2aa74e458c69.png)

**Comment by SaraVieira** [comment]
Hey!

This has tripped me up a bunch too.

It needs to be in a child component of the canvas 

So you need to move the Canvas component up, maybe to the index.js and wrap everything in that component

**Comment by clementpeleman** [comment]
Thanks for the answer!
It seems to give me the same error :/

**Comment by SaraVieira** [comment]
Can you share the code or create a sandbox?

**Comment by clementpeleman** [comment]
https://codesandbox.io/s/heuristic-albattani-8u7d8?file=/src/App.js Thanks in advance!

**Comment by joshuaellis** [comment]
I think someone opened a similar problem in r3f?

**Comment by SaraVieira** [comment]
YEah what I was thinking it was does not work as you said: https://codesandbox.io/s/silly-wind-wlemg?file=/src/App.js


Can't really understand why

**Comment by gsimone** [comment]
This looks to be caused by mismatching r3f versions between drei's (4.1.4 needs @react-three/fiber) and the sandbox. 

Fixed => https://codesandbox.io/s/sleepy-edison-oyonx

**Comment by clementpeleman** [comment]
Wow, that simple! Thanks.

**Comment by jeffscottward** [comment]
Im running into this same error right now. :(

**Comment by tcoopman** [comment]
I have the same error.

This doesn't work:
```jsx
function Test() {
  const { gl } = useThree();
  return "test";
}

export default function Foo() {
  return (
    <Canvas>
      <Html as="div">
        <Test />
      </Html>
    </Canvas>
  );
}
```

but this does:
```jsx
function Test() {
  const { gl } = useThree();
  return (<Html as="div">test</Html>);
}

export default function Foo() {
  return (
    <Canvas>
        <Test />
    </Canvas>
  );
}
```
