### ISSUE TITLE
direct CJS imports do not work

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/drei#365]
- `@react-three/drei` version: >=4.x.x

### Problem description:

This is an issue both `drei` & `three-stdlib`, we export the individual files as `cjs` but when you import them using something like `nextjs` as `@react-three/drei/core/useGLTF`:

![Screenshot_2021-04-11_at_18 31 51](https://user-images.githubusercontent.com/37798644/114316082-e1c12d80-9af9-11eb-88b4-52ba8f4de784.jpg)

### Relevant code:

A simple example can be seen using `gltfjsx`:

![image](https://user-images.githubusercontent.com/37798644/114316103-f998b180-9af9-11eb-8fd1-5fc987e008ee.png)

### Suggested solution:

Well, you should be able to do:

```js
import { useGLTF } from '@react-three/drei/core/useGLTF'
```

and it not cause any issues without prepending `.cjs` at the end of the route.

**Comment by enkicoma** [comment]
Hey, `useGLTFLoader` doesn't exists in `drei` instead I think should be`useGLTF`:
`import { useGLTF } from '@react-three/drei/core/useGLTF';`

**Comment by joshuaellis** [comment]
Thanks! I've updatedit now incase someone gets time to look at it before me.

**Comment by saurabhiam** [comment]
> ![image](https://user-images.githubusercontent.com/3684584/116008205-f12f9300-a630-11eb-974c-bcfca8dda32f.png)

Hey @joshuaellis 
Offtopic, how did you highlight the block background? I am using Bracket Pair Colorizer 2 and still searching for the way to highlight the block background.

**Comment by joshuaellis** [comment]
sorry, that screenshot is from someone else IDE but i think theres on called `indent-rainbow`?

**Comment by saurabhiam** [comment]
Finally 😄

**Comment by ArcaDelDelirio** [comment]
Same here!
![image](https://user-images.githubusercontent.com/41389257/120074009-a02d1780-c092-11eb-873c-b810b377c2e8.png)

Any solution to this ?

**Comment by drcmda** [comment]
that is not cjs anyway, it can only either be csj or esm when you import from "library" because it will go into package.json to determine which path it takes. if you import from some random file ofc it has import statements. i think you mean to write import { ..., ..., ... } from '@react-three/drei'
