### ISSUE TITLE
Update troika-three-text for direction support

### ISSUE THREAD

**Issue by m9dfukc** [pmndrs/drei#371]
Please update the [troika-three-text](https://github.com/protectwise/troika/tree/master/packages/troika-three-text) dependency to v0.41.0 ... now comes with full "direction" and "bidi" support!

**Comment by joshuaellis** [comment]
You're welcome to submit a PR! ⭐

**Comment by m9dfukc** [comment]
Ok I'll add a PR ... as soon as the package is on npm. In all my excitement I overlocked that it is not published yet 🤦

**Comment by lojjic** [comment]
Oh snap! I thought I'd published but apparently not. Will do that now. It'll be 0.41.0
