### ISSUE TITLE
Actions are not set when calling useAnimations

### ISSUE THREAD

**Issue by ekaradon** [pmndrs/drei#377]
- `three` version: 0.127.0
- `@react-three/fiber` version: 6.0.16
- `@react-three/drei` version: 4.2.0
- `node` version: v15.9.0
-  `yarn` version: 1.22.10
-  `typescript` version: 4.1.2
- `tsc` version: Version 4.2.4 

### Problem description:

The actions are never set when using `useAnimations`, they are just initialized to null.
![failing to set actions](https://i.imgur.com/lAXvXLq.png)

### Relevant code:
https://codesandbox.io/s/priceless-visvesvaraya-08tvs?file=/src/App.tsx

### Suggested solution:
I see two problems here:
 - A typescript error
 - A bug on the set

For the error:
![typescript error](https://i.imgur.com/NXfJQer.png)
Here is what I propose:

```typescript

// those come and replace the old definition
type Api<T extends string, U = { [K in T]?: AnimationAction }> = {
  ref: React.MutableRefObject<Object3D | undefined | null>
  clips: AnimationClip[]
  mixer: AnimationMixer
  names: T[]
  actions: U
}
type ExtendedAnimationClip<T extends String> = AnimationClip & { name?: T }

...

// the new signature of the hook
export function useAnimations<T extends string>(
  clips: ExtendedAnimationClip<T>[],
  root?: React.MutableRefObject<Object3D | undefined | null>,
): Api<T> {


...

// the parameter where the typescript error happened
      clips.forEach((clip: ExtendedAnimationClip<T>) => {

```

For the bug itself, I suggest just surrounding the assignment of brackets. 

```typescript

      clips.forEach((clip: ExtendedAnimationClip<T>) => {
        api.actions[clip.name] = mixer.clipAction(clip, currentRoot)
      })

```

I don't explain why or how this happen but it seems that not surrounding an assignment of brackets can lead in some case to the assignment not taking place at all. If you have any idea why I'm interested.

I can also do a pull request if you want.

**Comment by drcmda** [comment]
it needs to render out the elements first for them to be available in the mixer, this can only happen in useEffect/useLayoutEffect, that's why the actions are first null and then filled, this is not a bug. the brackets don't change anything, but i guess hot-reload made it look like they're now filled? we have multiple examples in the docs pages that use animations - the system is definitively working.

**Comment by ekaradon** [comment]
Yeah you are right for the curly brackets. I checked it again just doing that and it changes nothing. The actions are not showed initialized in the component loop. Maybe the hot-reload got me confused. I don't know. So, the issue would be that you can't visualize the actions from the component render loop? I don't know if this is really an issue then. Feel free to dismiss the pull request and the ticket then.

**Comment by ekaradon** [comment]
UPDATE: Okay, so after taking of hot reload I can confirm that it was probably that. 
By reloading my browser everytime, I can confirm the actions are not showing up initialized in the render loop. But they are working in the useEffect loop. 
I can modify the pull request to just fix the typescript part (if this is not another illusion of my mind)?
But, would it be not better if the api returned would be really modified when the actions are set? I mean it's a bit disturbing to use something you cannot see initialized in the main render loop? 
The api could be a state here instead of a Memo in order to modify the actions? What do you think?

**Comment by ekaradon** [comment]
I updated the Pull Request with a fixup doing something like that.

**Comment by ekaradon** [comment]
I forgot to update the description of the hook from the main `README.md`. I didn't remember it was briefly described:

![Screenshot_20210517_220117](https://user-images.githubusercontent.com/9439390/118549214-70f5dc80-b75b-11eb-9a11-8c2f3563addf.png)

Just adding a question mark would be enough I suppose. :confounded:
