### ISSUE TITLE
Text leaks geometry when unmounted

### ISSUE THREAD

**Issue by lojjic** [pmndrs/drei#379]
- `@react-three/drei` version: 4.3.1

### Problem description:

When a `Text` is unmounted, the underlying mesh's `dispose` method is not being called. This is causing that object's geometry to remain in memory indefinitely. I've created a sandbox that logs `gl.info.memory.geometries` and shows it increasing over time as a single Text instance is replaced: https://codesandbox.io/s/hopeful-diffie-sddhj

I initially thought this may be due to:

```js
<primitive
  dispose={undefined}
```

However removing that still doesn't result in `dispose` being called.

Adding something like this does fix it, but I don't know if it's the best way:

```js
    React.useEffect(() => {
      return () => troikaMesh.dispose()
    }, [])
```

**Comment by drcmda** [comment]
thats by design, primitives never dispose because they channel external objects. but dreis Text should absolutely dispose. i think the dispose={undefined} is a v5 leftover.

**Comment by lojjic** [comment]
Thanks, I've created PR #380 to add that useEffect cleanup handler and remove the dispose={undefined}
