### ISSUE TITLE
Environment Preset within Stage not working

### ISSUE THREAD

**Issue by jchailatte** [pmndrs/drei#381]
- `three` version: 
- `@react-three/fiber` version:
- `@react-three/drei` version:
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:

When using the environment prop for Stage, nothing shows up. 

### Relevant code:

```js
<Stage environment="sunset">
   <mesh/>
</Stage>
```

### Suggested solution:
`Background` prop missing from `Environment`. I assume this was meant to be set to true.

**Comment by gsimone** [comment]
The environment prop sets an env map, so you'd see changes on shaders that do make use of that. You can see it working here https://gltf.pmnd.rs/ (just select Suzanne and then play with the controls on the upper right). Am I misunderstanding something?

**Comment by jchailatte** [comment]
I was working on a storybook for Stage which had enums for the prop `environment`. I was wondering if something was supposed to show up since currently nothing happens when you pass "city" for example to the prop.

**Comment by jchailatte** [comment]
Oh I think I see a slight difference in shadows when you change the env. Ok I thought the background was supposed to show up.
