### ISSUE TITLE
AxesHelper and GridHelper don't work and maybe some others as well

### ISSUE THREAD

**Issue by ivnmaksimovic** [pmndrs/drei#384]
- `three` version: 0.128.0
- `@react-three/fiber` version: 6.0.16
- `@react-three/drei` version: 4.3.0
- `node` version: 14.13.0
- `yarn` version: 1.22.5

### Problem description:

`useHelper` doesn't work with helpers that don't have update method, like AxesHelper or GridHelper for example.
`Uncaught TypeError: helper.current.update is not a function`

### Relevant code:

```js
const mesh = useRef()
useHelper(mesh, AxesHelper, 5);

<mesh ref={mesh} ... />
```

### Suggested solution:

Check for existance of `update` method before calling it.

**Comment by ivnmaksimovic** [comment]
Ok. Obviously I don't know how to use react-three-fiber. The following is enough so there is no need for useHelper at all.
```js
<Sphere>
  <meshBasicMaterial attach="material" />
  <axesHelper />
</Sphere>
```

**Comment by gsimone** [comment]
axesHelper is kind of its own thing, with ArrowHelper, since they just create their own objects. Other helpers like the light ones do benefit from useHelper 👍
