### ISSUE TITLE
Reflector should not render when not facing the camera

### ISSUE THREAD

**Issue by oveddan** [pmndrs/drei#386]
### Describe the feature you'd like:

The three.js reflector does not render when the reflector material's normal is not visible from the camera:
https://discourse.threejs.org/t/reflector-does-the-scene-render-in-the-reflector-surface-if-its-not-visible-or-if-its-not-facing-the-camera/23913

### Suggested implementation:

As far as I can tell from looking at the drei implementation, this is not the case.
The desired behavior could be acheived with this check, in beforeRender:

`if ( view.dot( normal ) > 0 ) return;`

**Comment by gsimone** [comment]
Good catch, want to make a PR?

**Comment by oveddan** [comment]
Sure!
