### ISSUE TITLE
Feature request: Camera capture surface

### ISSUE THREAD

**Issue by oveddan** [pmndrs/drei#387]
### Describe the feature you'd like:

Similar to a reflector - it would be great if you could render onto a plane a capture from within the scene, except unlike the reflector, the camera position is not determined by where the player is - the developer would specify in particular where the camera is located.

The code would look like:

```jsx
<CameraCapture cameraLookAt={} cameraRotation={} />
```jsx

### Suggested implementation:

This would borrow from code from the Reflector component, and instead of updating the view matrix parameters based on the users camera position, it would update it based on the configured camera params.

**Comment by njm222** [comment]
I really like this suggestion, very flexible. 

I would like to suggest that this **replaces** the `Reflector` component and similar to what @oveddan suggested we just pass a _configured_ camera position instead of using the user's camera position.
