### ISSUE TITLE
ContactShadows disappear at positive values of position-y

### ISSUE THREAD

**Issue by romarybi** [pmndrs/drei#391]
- `three` version: 0.123.0
- `@react-three/fiber` version:6.0.12
- `@react-three/drei` version: 4.1.8

### Problem description:

ContactShadows disappear when the y-position is set to any positive value. For instance position={[0,0,0]} works fine, the shadows are displayed, but at position={[0,1,0]}, there is nothing. All negative values seem to work, the problem only occurs at positive values. Am I missing something or is this a bug?

**Comment by joshuaellis** [comment]
Can you provide a code sandbox to show the issue please?

**Comment by drcmda** [comment]
it doesn't sound like a bug to me, all this does is point a camera up and film with a really short far value. you need to adjust the "far" props or it cuts off. all these smoke and mirror effects are really hard to control.

**Comment by romarybintsev** [comment]
Here is a sandbox, adjusting the far prop doesn't fix the issue. 
https://codesandbox.io/s/contact-shadows-0ul6z

**Comment by CodyJasonBennett** [comment]
This is because the scene is being clipped by the near frustum plane. I added a `near` prop in #1556 you can use to customize this behavior.

https://codesandbox.io/s/m5t7x9
