### ISSUE TITLE
useAnimations cannot read property 'getState' of null

### ISSUE THREAD

**Issue by Rguarnizo** [pmndrs/drei#392]
### What is your question: What is the right way to use animations?

I'm trying to use the animations in the model, I'm doing the following:

      import * as THREE from 'three'
      import React, { useRef, useState, useEffect } from 'react'
      import { useFrame } from 'react-three-fiber'
      import { useGLTF } from '@react-three/drei'
    
      import { useAnimations } from '@react-three/drei'
      import gsap from "gsap";
      
    export default function Tokyo(props) {
      const group = useRef()
      const { nodes, materials, animations } = useGLTF('/Models/Tokyo/scene.gltf')
    
      const { actions } = useAnimations(animations,group)
    
      useEffect(() => {
    
        console.log(actions)
    
        setTimeout(() => {
          gsap.to(group.current.rotation,{
            
            y:Math.PI/2,
            delay:6,
            scrollTrigger: {
              trigger:".Productos",
              scrub: 1, 
              start: 'top top',
              end: '100%'
            }
          })
        });
      });
  
      return (
        <Model>
       )

But not work, I get the following error: 

![image](https://user-images.githubusercontent.com/43024059/117591389-de6d9180-b0f9-11eb-9b96-b55ee528eb96.png)

What am I doing wrong,or what happens?

**Comment by drcmda** [comment]
const { actions } = useAnimations(animations,group) needs group to be a valid ref. your code just says `<Model />` is that just pseudo code? you can see a simpler example of how it work here: https://codesandbox.io/s/gltf-animations-pecl6?file=/src/Model.js

**Comment by Rguarnizo** [comment]
I could not say if the error is due to the bad importation of the package `import { useFrame } from 'react-three-fiber'` I have changed it by `import { useFrame } from '@react-three/fiber'` and works to me, I leave this possible solution in case someone comes to pass the same.

**Comment by a-barbieri** [comment]
Just to be 100%:

> It's important to remember that Fiber hooks can only be called inside a <Canvas /> parent!

meaning your component must be imported and added as Canvas child.

see 'useFrame' https://docs.pmnd.rs/react-three-fiber/getting-started/basic-animations#use-frame

I had the same error using `useFrame` on the same component where I was returning the `Canvas` element.
