### ISSUE TITLE
HTML annotations in back of 3D Object

### ISSUE THREAD

**Issue by burungiu** [pmndrs/drei#398]
Hello,

I have some problems with hiding annotations on 3D object.  I attached annotations on the all sides of the 3D object and it looks like they didn't hide when object is in front of annotations. Is there is a way to hide annotations when they are behind object?

Thank you!

**Comment by joshuaellis** [comment]
Can you provide a codesanbox? It's hard to visualise what you're asking.

**Comment by burungiu** [comment]
https://codesandbox.io/s/html-annotations-zu2wo?from-embed there is a simple example. "Hello World"-s doesn't dissapear then 3D object are in front of them.

**Comment by joshuaellis** [comment]
Well the HTML is rendered on top of the canvas. I think this PR – https://github.com/pmndrs/drei/pull/341 might the solution you're looking for?
