### ISSUE TITLE
Class constructor cannot be invoked without 'new' for Text component with Parcel

### ISSUE THREAD

**Issue by driescroons** [pmndrs/drei#413]
- `three` version: 0.128.0
- `@react-three/fiber` version: 6.1.2
- `@react-three/drei` version: 5.2.0
- `node` version: 14.15.4
- `npm` (or `yarn`) version: 1.17.3

### Problem description:

For my WebXR game, I'm migrating to parcel v2. However, I've ran into an issue with the Text component.

I get the following issue when importing the Text component from the Drei package.

```
Uncaught TypeError: Class constructor InstancedBufferGeometry cannot be invoked without 'new'
    at new GlyphsGeometry
```

![image](https://user-images.githubusercontent.com/27679518/118667207-165c8f00-b7f4-11eb-9621-6cd583bc6fdf.png)

Here is the location this error is thrown:
![image](https://i.imgur.com/lMxavLV.png)

However, the weird thing is that when I build the project and use live-server to host the example, I don't get any issue:
![image](https://user-images.githubusercontent.com/27679518/118667390-47d55a80-b7f4-11eb-9957-de3755577e27.png)

It seems like whenever I'm serving, parcel is using the umd distributable, but when building, using the esm?
![image](https://user-images.githubusercontent.com/27679518/118679480-34c78800-b7fe-11eb-9879-66fbc5f992c7.png)

It seems like Parcel is using the incorrect files in order to build the application. I've also [created an issue on parcels github](https://github.com/parcel-bundler/parcel/issues/6306), but I think the fix should be done within the drei package.

I've setup a repro repo to showcase the issue. You can find that here: https://github.com/driescroons/parcelv2troika3dtext

**Comment by joshuaellis** [comment]
Sorry, I'm a bit unclear, why do you think it's an issue with `drei` and not `trokia-three-text`?

**Comment by driescroons** [comment]
Hi Josh, I appreciate the quick reply. I should indeed add this as an issue to `trokia-three-text`.
