### ISSUE TITLE
Conflict between OrbitControls and camera.lookAt

### ISSUE THREAD

**Issue by zcemycl** [pmndrs/drei#419]
```
<Canvas 
       shadowMap   gl={{ alpha: false }}  camera={{position:[data.camx,
       data.camy,data.camz],fov:data.fov}}
       onCreated={(state) => {
       const {camera,gl,scene} = state;
      setCam(camera)
      camera.lookAt(data.camlx,data.camly,data.camlz)
      scene.background = new THREE.Color('lightblue')
     gl.toneMapping = THREE.ACESFilmicToneMapping
  gl.outputEncoding = THREE.sRGBEncoding
   }}>
...
    <Physics>
       <Suspense fallback={null}>
       <Box position={[data.boxx,10,0]} color={data.color}/>
         <Plane/> 
      <OrbitControls ref={control}/>                       
     </Suspense>
   </Physics>
 </Canvas>
```
I am trying to use `react-dat-gui` to control some camera properties, such as lookAt (camera rotation). `cam.lookAt(vec3)` works when I exclude the `OrbitContorls`. Is there any way to fix this? 

I read some reports from others, they either choose to change the source code or pass a camera handle to OrbitControls. But I did not manage to do that.

**Comment by drcmda** [comment]
orbitcontrols control the camera, that's just what they do. you can't have that and then control it yourself, it will be immediately overwritten. you may be able to get away with it by calling control.current.update() after your change, i think the camerashake component does that, you may want to look into that. but this is not a bug in drei.

**Comment by tlambert03** [comment]
I recognize this isn't a bug, but I've been struggling to accomplish what I think is a similar goal of just initializing the view looking at a certain position.   If I remove `OrbitControls` it's all good, if I add it, it's always initialized looking at the origin.  What syntax could/should I use to initialize the view looking at anything other than the origin when using OrbitControls?
