### ISSUE TITLE
Can't resolve 'three/examples/js/libs/stats.min'

### ISSUE THREAD

**Issue by MrSpijker** [pmndrs/drei#427]
- `three` version: ^0.129.0
- `@react-three/fiber` version: ^6.2.2
- `@react-three/drei` version: ^5.3.1
- `node` version: v14.15.4
- `npm` (or `yarn`) version: yarn 1.22.4

### Problem description:
Whenever I import something from the drei repo it fails to compile.
`  ERROR in ./node_modules/@react-three/drei/core/Stats.js
  Module not found: Error: Can't resolve 'three/examples/js/libs/stats.min' in 'C:......\node_modules\@react-three\drei\core'
   @ ./node_modules/@react-three/drei/core/Stats.js 3:0-57 11:44-53`

### Suggested solution:
Tried cleaning node modules.
Installing them all over again. Also copied versions from codesandboxes where it runs without a problem but I keep getting the same issue.

My entire project runs in an electron environment driven by webpack, so no NextJs is involved.
Might also add all our dependencies are installed as dev dependencies. However, this has not presented problems in the past.

**Comment by joshuaellis** [comment]
Hm, can you provide an reproduction of the issue? I appreciate it's an electron app so maybe a small stripped out repo? Unless you can replicate it in codesandbox... because I can't replicate this – https://codesandbox.io/s/nice-hugle-jjvgy?file=/src/App.js

**Comment by MrSpijker** [comment]
Well it turns out I found the culprit.
The import of **import StatsImpl from 'three/examples/js/libs/stats.min';** in the Stats.js
Code edit below allows it to compile:

`import * as React from 'react';
import { addEffect, addAfterEffect } from '@react-three/fiber';
// import StatsImpl from 'three/examples/js/libs/stats.min';
import useEffectfulState from '../helpers/useEffectfulState.js';

function Stats({
  showPanel = 0,
  className,
  parent
}) {
  // const stats = useEffectfulState(() => new StatsImpl(), []);
  // React.useEffect(() => {
  //   if (stats) {
  //     const node = parent && parent.current || document.body;
  //     stats.showPanel(showPanel);
  //     node == null ? void 0 : node.appendChild(stats.dom);
  //     if (className) stats.dom.classList.add(className);
  //     const begin = addEffect(() => stats.begin());
  //     const end = addAfterEffect(() => stats.end());
  //     return () => {
  //       node == null ? void 0 : node.removeChild(stats.dom);
  //       begin();
  //       end();
  //     };
  //   }
  // }, [parent, stats, className, showPanel]);
  return null;
}

export { Stats };
`

**Comment by joshuaellis** [comment]
How have you downloaded three without `three/examples`?

**Comment by MrSpijker** [comment]
Just ```yarn add three```
Aha.... 😅

**Comment by joshuaellis** [comment]
I've just added `three` to my project: 
![image](https://user-images.githubusercontent.com/37798644/120494916-20fe5300-c3b4-11eb-9323-b9a7d269a00c.png)

And the folder is there, so I think you'll have to provide a repro for us to consider this a bug 👍🏼

**Comment by MrSpijker** [comment]
So I found the issue.
Yarn's **autoclean** process.

.yarnclean file contents:
```
# test directories
__tests__
node_modules/*/test
node_modules/*/tests
powered-test

# asset directories
docs
doc
website
images

# examples
example
examples

# code coverage directories
coverage
.nyc_output

# build scripts
Makefile
Gulpfile.js
Gruntfile.js

# configs
.tern-project
.gitattributes
.editorconfig
.*ignore
.eslintrc
.jshintrc
.flowconfig
.documentup.json
.yarn-metadata.json

# misc
*.gz
*.md
```

Which contains.... examples 😅
