### ISSUE TITLE
mixer from useAnimations doesn't set _root property

### ISSUE THREAD

**Issue by yaroslavnikiforov** [pmndrs/drei#429]
- `three` version: 0.129.0
- `@react-three/fiber` version: 6.2.2
- `@react-three/drei` version: 5.3.1
- `node` version: 14.15.0
- `yarn` version: 1.22.10

### Problem description:

The `_root` property of the mixer returned by `useAnimations` hook is always undefined. This doesn't allow you to use methods of AnimationMixer, for example `mixer.clipAction()` as it relies on this property.

### Relevant code:
Just try to call `mixer.clipAction(clips[0])` in useEffect from this example:
[https://codesandbox.io/s/gltf-animations-pecl6](https://codesandbox.io/s/gltf-animations-pecl6)

**Comment by joshuaellis** [comment]
Please provide a minimal reproduction of the issue.

**Comment by yaroslavnikiforov** [comment]
Here is a demo:
[https://codesandbox.io/s/gltf-animations-forked-ukf1b?file=/src/Model.js](https://codesandbox.io/s/gltf-animations-forked-ukf1b?file=/src/Model.js)

**Comment by JDansercoer** [comment]
@joshuaellis @yaroslavnikiforov I'm facing this issue as well. These are my versions

* three version: 0.134.0
* @react-three/fiber version: 7.0.17
* @react-three/drei version: 7.19.2

Any idea?

**Comment by lexa18** [comment]
Confirm this problem. I faced the same situation.

**Comment by GoreStarry** [comment]
Have the same issue.
