### ISSUE TITLE
usage of this library in nwjs seems to result in webpack runtime compile error about invalid characters

### ISSUE THREAD

**Issue by epoplive** [pmndrs/drei#436]
I had been trying to use this library in nw.js (node webkit, like electron), and I was able to get react-three/fiber working successfully, however as soon as I tried to import a component from this library, I would get a runtime webpack compile error about invalid characters in the webpack output.

As far as I can tell, the issue appears to be related to the settings of node-remote and the atob polyfill.  My question is essentially, does this library work with nwjs, and if so what are the suggested settings?

I created this fairly minimal example repo to show the issue.  I know it's not completely as bare as it could be, but I wanted to show a couple things and it can be made more simple by commenting out everything except the drei import statement.  Please note that you can remove the giant chromium-flags, that was just there while i was testing through random stuff.

Here's the primary things to see in my repo:
1. running just react (yarn start), shader renders fine
2. with node-remote (yarn start-nw) pointed at the react web server, you get a runtime invalid character error
3. with node-remote only containing file://*, the shader works as expected, but the react is no longer fully functional

https://github.com/epoplive/nsjw-atob-error

**Comment by joshuaellis** [comment]
Did you open an issue in `nw`?

**Comment by epoplive** [comment]
@joshuaellis yes, however I ended up closing it after spending a significant amount of time in discord and their official gitter chat and realizing the attitude in that community is something I don't want to be a part of.  Their responses boiled down to a few basic responses:
1. I don't know the build tools very well yet, that must be my problem
2. Use vue.js
3. I have explained the issue poorly so its not worth looking at (sorry, I don't entirely understand it myself)
4. My repo is not minimal enough, I should learn the basics of programming...and how to respectfully show an issue to someone of their status

I am personally switching back to electron, where I have already verified I do not have the same issue and this library works great with webpack/react.  I'm interested to know what the solution is, and thought maybe someone here might have interest in taking a look at it.

**Comment by joshuaellis** [comment]
Had a talk with `nw.js` person, It's not an issue with this library unfortunately, it could be an internal thing:

> all JS is scoped, if your code is running in the browser context nw or atob is actually referenceing window.nw or window.atob the window. part is not required unless the context is weird (like inside a vue/angular/react component). If your code is executing in the Node context then nw or atob would actually be referencing global.nw or global.atob
just like how you can do document.getElementById or window.document.getElementById
NW.js will also create window.process and window.require for convienience

Since the `drei` polyfill will just be calling `atob` which in theory is supported in the window environment, if you wanted to be sure you could `patch-package` the library to call `window.atob` although i doubt it would fix the issue.

**Comment by epoplive** [comment]
> Had a talk with `nw.js` person, It's not an issue with this library unfortunately, it could be an internal thing:
> 
> > all JS is scoped, if your code is running in the browser context nw or atob is actually referenceing window.nw or window.atob the window. part is not required unless the context is weird (like inside a vue/angular/react component). If your code is executing in the Node context then nw or atob would actually be referencing global.nw or global.atob
> > just like how you can do document.getElementById or window.document.getElementById
> > NW.js will also create window.process and window.require for convienience
> 
> Since the `drei` polyfill will just be calling `atob` which in theory is supported in the window environment, if you wanted to be sure you could `patch-package` the library to call `window.atob` although i doubt it would fix the issue.

Yeah, the issue isn't really directly with any of the components, which is why it's a little hard to figure out what to do with.  I just wanted to exhaust all avenues, and possibly document for others before they spend as much time as I did.  Thanks for taking a look!
