### ISSUE TITLE
Can't resolve 'detect-gpu' in 'node_modules\@react-three\drei\core'

### ISSUE THREAD

**Issue by yashrajjain726** [pmndrs/drei#440]
Getting this error in the latest version of @react-three/drei.
 "Can't resolve 'detect-gpu' in 'node_modules\@react-three\drei\core'"

**Comment by joshuaellis** [comment]
Please provide a reproduction of the bug. Infact, please follow the template we provide.

**Comment by yashrajjain726** [comment]
I followed the template the organization provided and the error was still showing. After many installs and uninstalls, it automatically got over.
