### ISSUE TITLE
<TransformControls /> component does not work in typescript after upgraded drei from 2.1.1 to 5.0.0

### ISSUE THREAD

**Issue by philxia** [pmndrs/drei#444]
- `three` version:
- `@react-three/fiber` version: 6.0.0
- `@react-three/drei` version: 5.0.0
- "three": "0.128.0",
- "typescript": "~4.3.2",
- `node` version: 12.18.2
- `npm` (or `yarn`) version: 1.22.4

### Problem description:

I got a Typescript error as below after upgraded drei from 2.1.1 to 5.0.0.
Here is the discussion https://github.com/pmndrs/drei/discussions/434

### Relevant code:

Type '{ children: Element; mode: string; position: Vector3; rotation: Euler; onPointerUp: (event: any) => void; }' is missing the following properties from type 'Pick<Props, "id" | "camera" | "quaternion" | "attach"
| "attachArray" | "attachObject" | "args" | "children" | "key" | "onUpdate" | "position" | "up" | "scale" |
"rotation" | ... 89 more ... | "showZ">': camera, size, enabled, space, and 7 more. TS2740

143 |     const transformControl: any = (
144 |       <>
145 | <TransformControls
| ^
146 | mode={mode}
147 | position={getVector3(this.props.instance.position)}
148 | rotation={

### Suggested solution:

I can work around this by either provide all required props or modify https://github.com/pmndrs/drei/blob/master/src/core/TransformControls.tsx#L18 to make them all optional. I will provide a PR to mark most props optional and see your suggestion.

**Comment by mathdroid** [comment]
This actually happens to a lot of other components, like `PerspectiveCamera`, `OrbitControls`, and others. I can submit a PR similar to #445 if it's wanted. cc @joshuaellis
