### ISSUE TITLE
Three example module SubdivisionModifier failing to import

### ISSUE THREAD

**Issue by geoff-harper** [pmndrs/drei#448]
- `three` version: 0.128.0
- `@react-three/fiber` version: 5.3.19
- `@react-three/drei` version: 2.2.22
- `node` version: 14.15.1
- `npm` (or `yarn`) version: 1.19.1

### Problem description:

I've dug through previous issues with similar closed issues and they didn't seem to apply here. This is running in browser (confirmed on most recent FF and Chrome builds) and as far as I can tell, I'm fully compliant with peer deps. I can confirm that `SubdivisionModifier` isn't in three's output dir

### Relevant code:
In the compiled file:
```js
/* harmony import */ var three__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! three */ "../../node_modules/three/build/three.module.js");
!(function webpackMissingModule() { var e = new Error("Cannot find module 'three/examples/jsm/modifiers/SubdivisionModifier'"); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```

### Suggested solution:

Frankly the situation with `three-stdlib` vs the `examples` folder is really obtuse. A simple comment in the readme doesn't give me enough context to even begin to understand the problem. Why isn't `three-stdlib` a dependency if it's being used? Previous issues cite it being used in favour of `examples` but the most recent version of this lib is importing from `examples`.

**Comment by joshuaellis** [comment]
> Frankly the situation with three-stdlib vs the examples folder is really obtuse. A simple comment in the readme doesn't give me enough context to even begin to understand the problem. Why isn't three-stdlib a dependency if it's being used? Previous issues cite it being used in favour of examples but the most recent version of this lib is importing from examples.

Your version of `drei` is very old thats why _you_ don't think its a dependancy. `drei` is at v6 now...

**Comment by geoff-harper** [comment]
> Your version of drei is very old

Woof, no kidding. It's impressive I missed that somehow. Apologies for the tone, build tool errors drive me crazy
