### ISSUE TITLE
CatmullRomCurve3 spline in Drei

### ISSUE THREAD

**Issue by marcelpi** [pmndrs/drei#456]
Is there any chance CatmullRomCurve3 will be added to drei? It's far better than the Cubic or Quadratic curves.

**Comment by joshuaellis** [comment]
Do you mean an abstraction? Similar to our `Line` component?

**Comment by marcelpi** [comment]
> Do you mean an abstraction? Similar to our `Line` component?

Yes, exactly. Similar to Line, QuadraticBezierLine or CubicBezierLine.

**Comment by joshuaellis** [comment]
Not currently no, but it's pretty easy to set one up yourself in a similar style to `Line` if you'd like to make a PR
