### ISSUE TITLE
Bad Quality Drei Environment HDRI files

### ISSUE THREAD

**Issue by him666** [pmndrs/drei#461]
- `three` version: ^0.129.0
- `@react-three/fiber` version: ^7.0.1
- `@react-three/drei` version: ^6.2.0
- `node` version: v14.10.0

- `npm` (or `yarn`) version: yarn 1.22.5

### Problem description:

environment hdri files resolution is being downscaled.

### Relevant code:

```js
<Environment
            files={'/environments/preset.hdr'} 
            background
          />
```

### Suggested solution:

adding prop to receive resolution 
res="1k" or 256, 512
whatever suits better

```js
<Environment
            files={'/environments/preset.hdr'} 
            background
            resolution={512}
          />
```

**Comment by joshuaellis** [comment]
Thanks @him666 feel free to make a PR for this!

**Comment by magicspon** [comment]
Any updates on this...
the difference is quite shocking:
r3f: https://eq-site-c0nedilrs-spon.vercel.app/demo 
vanilla: https://mango-dentists.surge.sh/

**Comment by gsimone** [comment]
Note that the Environment component is meant to generate a cube texture for environmental lighting, not to use as a cube background. The texture generated from the PMREMGenerator is always 256x256  https://threejs.org/docs/#api/en/extras/PMREMGenerator

**Comment by drcmda** [comment]
i think for envmap lighting it makes sense to keep resolution as low as possible, as @gsimone said, we just use prem. there should be zero difference between vanilla and r3f if you use the same means to get your environment. but maybe environment can be extended with a resolution prop and then not use prem? but i know too little about it, three has changed drastically in that area and i didnt keep up.
