### ISSUE TITLE
controls need a way to be accessible throughout the scene tree

### ISSUE THREAD

**Issue by drcmda** [pmndrs/drei#466]
whenever the camera needs to be adjusted controls must be updated. for this to be composable it has to be generic, so that a foreign component may fetch "current" controls without dependency injection.

currently we use DI, for instance `<Stage controls={...} />` or camera-shake but this makes it extremely hard for components to be generic.

### suggestion 1

a new state entry in r3f: state.controls which defaults to null. our controls would write themselves into that with the `makeDefault` prop same as our cameras. 

### suggestion 2

a new state entry in r3f that is generic, but observable. 

```jsx
export function OrbitControls({ makeDefault }) {
  const setUserData = useThree(state => state.setUserData)
  useEffect(() => {
    if (makeDefault) {
      setUserData({ drei_currentControls: refControls })
      return () => setUserData({ drei_currentControls: null })

...

function Stage() {
  const controls = useThree(state => state.userData.drei_currentControls)
  ...
```

this way anything could put anything into the root state and let everything observe it. i guess i would prefer this one. downside is ofc that namespace bleeding exists. but it would still be a nice escape hatch and components could document and type their userData entries.

**Comment by joshuaellis** [comment]
I'm confused why using your own state model e.g. with Zustand couldn't handle suggestion 2 on it's own without adding the complexity to the r3f state object?

**Comment by drcmda** [comment]
r3f would just ship an empty userdata object and perhaps a setter that automatically merges state. there is no other overhead or complexity. all it would do is allow for some share observable grounds to that separate components can form contracts without DI.
