### ISSUE TITLE
OrbitControls enableRotate set to false has no effect on drei 7.0.5

### ISSUE THREAD

**Issue by janroesler** [pmndrs/drei#467]
- `three` version: 0.129.0
- `@react-three/fiber` version: 7.0.1
- `@react-three/drei` version: 7.0.4 / 7.0.5

### Problem description:

Setting OrbitControls enableRotate to false has no effect in drei version 7.0.5, in drei version 7.0.4 it works like expected.
In the Sandbox you can switch the drei version:
https://codesandbox.io/s/dreiorbitcontrolsenablerotate-c2j9i?file=/src/index.js:392-430

**Comment by joshuaellis** [comment]
@haywirez could this be to do your commit?

**Comment by haywirez** [comment]
It seems like `controls.connect(gl.domElement)` might be needed after all (#459). See https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L300, event listeners are initialized inside that call. Related to this issue in three: https://github.com/mrdoob/three.js/issues/20575

**Comment by joshuaellis** [comment]
@stephencorwin this would affect TransformControls no? 🤔

**Comment by stephencorwin** [comment]
It should be fixed in the next version once that is deployed.

**Comment by violabg** [comment]
version 7.06 brought back a bug that was present in previous version.
basically OrbitControls can't rotate on mobile, you can test it on chrome simulating an mobile device or iPad,
https://codesandbox.io/s/dreiorbitcontrolsenablerotate-c2j9i?file=/src/index.js:392-430.

in version 7.05 this was working correctly, but introduced other problem related to this issue
