### ISSUE TITLE
can't get nodes, materials from useGLTF using Typescript

### ISSUE THREAD

**Issue by violabg** [pmndrs/drei#469]
- `three` version: 0.129
- `@react-three/fiber` version: 7.02
- `@react-three/drei` version: 7.05
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:

I have a typescript project and can't get can't get nodes, materials from useGLTF.

I used to be able to do so, not sure in which version it stoped working.
is this a bug or there is a particular reason why isn't possible anymore.

```js
import {  useGLTF } from "@react-three/drei";
const { scene, nodes, materials, animations } = useGLTF(modelUrl);
```

**Comment by joshuaellis** [comment]
Please follow the template. Provide a reproduction of the issue.

**Comment by violabg** [comment]
I have created a code sandbox 
https://codesandbox.io/s/goofy-elgamal-2twlf?file=/src/App.tsx

has you can see nodes, materials are not available on type definition for useGLTF

**Comment by violabg** [comment]
I saw that this issue has been closed
https://github.com/pmndrs/drei/issues/482
but why GLTF interface is still missing properties nodes and materials?

```js
export interface GLTF {
    animations: AnimationClip[];
    scene: Group;
    scenes: Group[];
    cameras: Camera[];
    asset: {
        copyright?: string;
        generator?: string;
        version?: string;
        minVersion?: string;
        extensions?: any;
        extras?: any;
    };
    parser: GLTFParser;
    userData: any;
}
```

**Comment by drcmda** [comment]
they are not part of the gltfloader. r3f adds these two. 

if you want then you can either let gltfjsx type it out for you or you create them manually:

```jsx
type GLTFResult = GLTF & {
  nodes: {
    Chassis_1: THREE.Mesh
    Chassis_2: THREE.Mesh    
  }
  materials: {
    BodyPaint: THREE.MeshStandardMaterial
    BodyPaint_Accent: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chassis-draco.glb') as GLTFResult
```

**Comment by violabg** [comment]
Thanks for the clarification.

**Comment by camjackson** [comment]
@drcmda Thanks for clarifying that it's R3F that loads the nodes and materials, and not the three.js loader.

Given that `useGLTF` uses R3F's `useLoader` though, isn't it true that `useGLTF` will always return the nodes and materials? So wouldn't it make sense for the type of `useGLTF` to be `GLTFResult` and not `GLTF`?

**Comment by joshuaellis** [comment]
> So what is the signature of new GLTFLoader().load? We need its second param to be a function that accepts a GLTF, but it isn't explicitly defined!. Could this be the source of the error?

Isn't it defined here? https://github.com/three-types/three-ts-types/blob/6a5f78138c10ca144f15f4e3ea3b989c60f307d1/types/three/examples/jsm/loaders/GLTFLoader.d.ts#L44

**Comment by camjackson** [comment]
Ok I at least figured out the problem with my sandbox. I hadn't included the `@types/three` dependency. I've included that now, so you can hopefully see for yourself that `useGLTF` is returning a plain `GLTF` without the extras: https://codesandbox.io/s/intelligent-curran-oi1z1?file=/src/index.js
