### ISSUE TITLE
OrbitControls can't rotate on mobile

### ISSUE THREAD

**Issue by violabg** [pmndrs/drei#470]
- `three` version: 0.129
- `@react-three/fiber` version: 7.02
- `@react-three/drei` version: 7.06
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:

not sure which version of drei introduced this bug, but since 7.00 up to 7.06,  OrbitControls can't rotate properly on mobile, you can test it on chrome simulating a mobile device or iPad.
It looks like the whole page is moving when you drag your finger on screen, and if you try to zoom, it will zoom the page and not the 3d model.

version 7.05 solved the problem, but introduced other problem related to issue https://github.com/pmndrs/drei/issues/467

### Relevant code:
https://codesandbox.io/s/dreiorbitcontrolsenablerotate-c2j9i?from-embed

**Comment by biowaffeln** [comment]
I ran across this one myself too. It has to do with changes in how `OrbitControls` is implemented in [pmndrs/three-stdlib](http://github.com/pmndrs/three-stdlib), and drei implementation hasn't caught up. For now, you can work around the issue by adding `touchAction: "none"` to the canvas.

https://codesandbox.io/s/dreiorbitcontrolsenablerotate-forked-9d5vw

**Comment by joshuaellis** [comment]
> For now, you can work around the issue by adding touchAction: "none" to the canvas.

This is the correct workaround, following a short chat in the discord server, we're going to amend this in `three-stdlib`
