### ISSUE TITLE
uniforms not updating unless assigned in args attribute

### ISSUE THREAD

**Issue by KimPaow** [pmndrs/drei#481]
- `three` version:  0.130.1
- `@react-three/fiber` version: 6.013
- `@react-three/drei` version: 7.1.2
- `node` version: 15.12.0
- `npm` (or `yarn`) version: 1.22.10

### Problem description:
When you pass uniforms to shaderMaterial they do not update when passed via `uniforms`. I only got it to work when passing it into the `args` array.

There are plenty of examples available on the web according to which this should work. At the same time I cannot find anything that says that this should not work. I am new to r3f and this could be a misunderstanding on my part, if so - sorry!

### Relevant code:
Please take a look at TestComponent here, the time uniform is updating as expected when uniforms are passed via the args array but not when passed via `uniforms` attribute.
https://codesandbox.io/s/sad-smoke-txh7p?file=/src/App.js

**Comment by joshuaellis** [comment]
Yes it does? https://codesandbox.io/s/hungry-flower-0quhy?file=/src/App.js

**Comment by KimPaow** [comment]
Ah, that's my bad. It seems that a hard refresh on the codesandbox makes it work, I should've been more thorough. The same does not apply for my local project with roughly the same setup, however.

Closing this since the problem is likely elsewhere.
