### ISSUE TITLE
useGLTF hook has inaccurate typings

### ISSUE THREAD

**Issue by biowaffeln** [pmndrs/drei#482]
- `three` version: ^0.128.0
- `@react-three/fiber` version: ^6.0.0
- `@react-three/drei` version: 7.1.2

### Problem description:

The `useGLTF` hook has a return type of `GLTF | GLTF[]`, even if the passed argument is `string` and not `string[]`.

### Relevant code:

```js
// Property 'scene' does not exist on type 'GLTF | GLTF[]
const { scene } = useGLTF("model.glb") 
```

### Suggested solution:

Use a generic type, like so:

```ts
export function useGLTF<T extends string | string[]>(
  path: T,
  useDraco: boolean | string = true,
  useMeshOpt: boolean = true,
  extendLoader?: (loader: GLTFLoader) => void
) {
  const gltf = useLoader(GLTFLoader, path, extensions(useDraco, useMeshOpt, extendLoader))
  return gltf
}
```

**Comment by ghostmurda** [comment]
- "three": "^0.146.0"
- "@react-three/fiber": "^8.9.1"
- "@react-three/drei": "^9.40.0"

I am getting almost the same ts error
`Property 'scene' does not exist on type '(GLTF & ObjectMap) | (GLTF & ObjectMap)[]'`
