### ISSUE TITLE
<html> onOcclude issue with helpers

### ISSUE THREAD

**Issue by Theonlyhamstertoh** [pmndrs/drei#497]
- `three` version: 0.130.1
- `@react-three/fiber` version: 7.0.6
- `@react-three/drei` version: 7.2.2
- `node` version: v16.4.2
- `npm` (or `yarn`) version: 7.18.1

### Problem description:

The problem occurs when using `<html>` `occlude` property. When you add a `<axesHelper />` to the `canvas`, the text inside the `html` will flicker rapidly. If console.log the `visibility` in the `onOcclude` property, you will see it switching between `true` and `false` continously. Getting rid of the `axesHelper` fixes the problem. Here is a [demo](https://codesandbox.io/s/mixing-html-and-webgl-forked-si90s?file=/src/App.js)

When using `gridHelper`, the html will consider the `gridHelper` as something to occlude from, acting like a object plane in a way.

### Suggested solution:

Although the `occlude` property, will occlude the entire scene, it would make more sense if the `helper` components are not counted especially the `axesHelper` and `gridHelper`.

**Comment by msantic** [comment]
Still an issue when using e.g. drei/Grid helper it messes up with occlude logic. There is a workaround by passing array of ref objects to occlude argument but it would be much better to implicitly ignore all helper objects.
