### ISSUE TITLE
<html> Modify three props without rerendering

### ISSUE THREAD

**Issue by MaxTwentythree** [pmndrs/drei#498]
### Describe the feature you'd like:

I would like to modify three properties of the Html component via ref (without state changes forcing a rerender).
When I create an Html component, I can access the created html-div element via its ref.
But three properties (specifically "visible", "scale", "position", ...) are not accessible via the ref, so how can I change them without rerendering?

### Suggested implementation:

Would it be possible to have a Html prop like "refThree" to do what I want?
e.g.:

```
<Html
  ref={htmlRef}
  refThree={threeRef}
  visible
  style={{ width,  height }}
  scale={[0.5, 0.5, 1]}
>

...

htmlRef.current.style.width = '1000px';
threeRef.current.scale.set(1, 1, 1);
threeRef.current.visible = false;

```

**Comment by joshuaellis** [comment]
I think you'd be better off wrapping the `Html` in `group` and performing the `three` changes on that element. I don't think we should be passing two different `refs` and splitting the props between those elements...

**Comment by MaxTwentythree** [comment]
Well, sure, that's the way I have it right now, but there are some problems there.
The HTML component does not always react correctly to changes in the enclosing group,
especially with the visible prop.

I initially render my html stuff like this (with the enclosing group invisible initially):

```
<group
    ref={groupRef}
    visible={false}
>
    <Html>...</Html>
</group>
``

I want to set group.visible to true later via the groupRef.
But the change of the visibility is not reflected down to the HTML component.
The HTML content is rendered only when I force rerendering of the whole component!
I think I encountered similar issues with scaling.

Maybe this is a bug then and I should create a new issue for that?

**Comment by joshuaellis** [comment]
Oh I see. It's not necessarily a bug, but if you want to hide the `Html` component, I would use `css` to change that. Changing the visibility of the group won't do anything to the HTML because it's rendered in the `ReactDOM` root as it's DOM not THREEjs.

**Comment by MaxTwentythree** [comment]
I already hide and show the HTML's content via css.. in addition to changing the groups visibility..
But rendering the group initially invisible means that the Html children are not being rendered,
even after changing groupRef visible to true. (Is this intended behavior or is it just me?)

Now I use a state variable to force a rerender on the first time the html content gets displayed.
All in all this works, but it feels a little awkward and for my usecase rerenders are not my best friends.

Because the Html component lives in the r3f-world it would be cool to have access to it's three-side via ref,
or have some other functionality to handle visibility.. but I see why a second ref is weird..
