### ISSUE TITLE
Environment black for other canvases than the first

### ISSUE THREAD

**Issue by robclouth** [pmndrs/drei#499]
### Versions
"@react-three/drei": "7.2.2",
"@react-three/fiber": "7.0.6",
"three": "0.130.1",

### Problem description:

When having multiple canvases, only the first instance of Environment works. Subsequent ones are black. 

### Code
https://codesandbox.io/s/heuristic-tu-9q8o4?file=/src/index.js

**Comment by CodyJasonBennett** [comment]
I've fixed this in #554, but I'm working on including resolution params in that PR.

Sandbox here: https://codesandbox.io/s/pensive-kirch-uc7s5

**Comment by drcmda** [comment]
this is not a problem in newer react: https://codesandbox.io/s/the-difference-between-color-modes-dus84

env maps cannot be re-used among canvases and since env is cached in drei it creates problem. in react 18 each canvas has a cache bound, problem solved.

@CodyJasonBennett is prem needed? it is in useasset because prem takes so long that it creates a glitch. as in the model appears without env, then it calculates, then it gets applied. with suspense it happens in lock step which imo is important. maybe threejs has changed and prem isnt a necessity any longer but if it still takes time i think suspense is more important than the multi canvas usecase - which will 100% be solved by the react team in just a few weeks.

**Comment by CodyJasonBennett** [comment]
@drcmda, I'm not sure. I tried removing it to solve both issues but will have to take a closer look at PMREM.

**Comment by srcnalt** [comment]
Using the Environment component from #554 fixed the issue for me to display it on multiple canvases, however now on mobile devices I get no light at all. Will investigate more why this happens.

**Comment by CodyJasonBennett** [comment]
I believe PMREM was contributing lighting information. Maybe I should be focusing on the background's implementation with three.

**Comment by tigrik2017** [comment]
Still valid. In my case, it occurs not on navigation, but moving between two same 3D viewer components on the same page which contain environment components, making them visible one by one. In that case, the first one loses the environment and after hiding the second, it won't restore. I'm using the latest react v17.0.2

**Comment by tigrik2017** [comment]
Still valid. In my case, it occurs not on navigation, but moving between two same 3D viewer components on the same page which contain environment components, making them visible one by one. In that case, the first one loses the environment and after hiding the second, it won't restore.

versions installed:
react: 17.0.2
drei: 8.6.1
fiber: 7.0.24
three: 0.136.0

**Comment by w3ichen** [comment]
As of Aug 19 2022:

I tried #554 but no luck.
I was able to fix it by upgrading react-three to the latest version.

**Not working versions**
```
    "@react-three/drei": "^7.27.5",
    "@react-three/fiber": "^7.0.24",
    "@types/three": "^0.135.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "three": "^0.136.0",
```

**Newer versions that work! 🎉**
```
    "@react-three/drei": "^9.22.7",
    "@react-three/fiber": "^8.3.1",
    "@types/three": "^0.143.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "three": "^0.143.0",
```

**Comment by KaldrArt** [comment]
`
<Environmnet  preset={'sunset'} background  backgroundBlurriness={0.4}/>
`
it worked.


https://github.com/user-attachments/assets/e278a007-663f-4322-a88b-c15c0dfd7d91



bug still exists if I use files attribute and set a customized image in the tag.

`
<Environment files={'/images/alev-takil-DLG_1rHKrVM-unsplash.jpg'}  background  backgroundBlurriness={0.4}/>
`


https://github.com/user-attachments/assets/60b5a227-ffb3-4d79-8b02-3460389c32ef
