### ISSUE TITLE
`SkeletonHelper.update` should not be called anymore in `useHelper`

### ISSUE THREAD

**Issue by ThomasRutzer** [pmndrs/drei#500]
- `three` version: 0.130.1
- `@react-three/fiber` 7.0.6:
- `@react-three/drei` version: 7.2.2
- `node` version: 15.10.0
- `npm` version: 7.18.1

### Problem description:

When using `useHelper` with `THREE.SkeletonHelper`, it throws an error:
`THREE.SkeletonHelper: update() no longer needs to be called.`

The update is [called for every helper](https://github.com/pmndrs/drei/blob/master/src/core/useHelper.tsx#L30) here

### Relevant code:

```js
  useHelper(ref, SkeletonHelper)

```

### Suggested solution:

Maybe an additional argument passed to `useHelper` can suppress the update call. This way, each developer can decide whether to call `update` or not.

**Comment by joshuaellis** [comment]
Hey, thanks for the report! It would be great to see an example of the API change you're proposing, maybe in a PR and we can take it forward from there! 🙏🏼

**Comment by ThomasRutzer** [comment]
Yes, sure I'll think about that. [Just drop an issue from the official ThreeJS docs here](https://github.com/mrdoob/three.js/pull/18539), which states that this call is really obsolete by current versions of ThreeJS

**Comment by joshuaellis** [comment]
Closing as this has been fixed in `three`
