### ISSUE TITLE
Warning: meshopt_decoder is using experimental SIMD support 

### ISSUE THREAD

**Issue by drcmda** [pmndrs/drei#501]
useGLTF uses MeshOpt, which is a global side effect. see: https://github.com/pmndrs/three-stdlib/blob/main/src/libs/MeshoptDecoder.js

This causes this message, but worse, it adds meshopt to the bundle (thankfully it is not that large), if the app uses it or not. and i do not believe that it can be tree shaken in production currently.

It seems to me that we should not have a closure in three-stdlib and instead of doing

```jsx
(loader as GLTFLoader).setMeshoptDecoder(MeshoptDecoder)
```

we should then do

```jsx
(loader as GLTFLoader).setMeshoptDecoder(MeshoptDecoder())
```

i don't know if that helps it to tree shake off, but in any way, the warning disappears. 

unfortunately `three-stdlib` is not pinned in drei, and i think it should be. it could be a breaking change, or maybe not? we could also test to make 100% sure it's backward compat:

```jsx
(loader as GLTFLoader).setMeshoptDecoder(typeof MeshoptDecoder === 'function' ? MeshoptDecoder() : MeshoptDecoder)
```

**Comment by joshuaellis** [comment]
I've often thought incl. `three-stdlib` as a dep instead of a peer-dep has been obtuse, every-time there's a fix in three-stdlib, we've had to subsequently update and release `drei`. If i'm really honest, I think it should be reverted back to the peer-dep and putting in safes like:

```js
(loader as GLTFLoader).setMeshoptDecoder(typeof MeshoptDecoder === 'function' ? MeshoptDecoder() : MeshoptDecoder)
```

Would be the ideal solution.

**Comment by CodyJasonBennett** [comment]
I've addressed this in https://github.com/pmndrs/three-stdlib/pull/84, but is there anything to be done in Drei?

**Comment by drcmda** [comment]
just the invocation in useGLTF.tsx as quoted by @joshuaellis could you put that in? then lets merge it and get rid of that awful log once and for all. :-)
