### ISSUE TITLE
OrthographicCamera's frustrum is different on initial render and after window resize

### ISSUE THREAD

**Issue by smashercosmo** [pmndrs/drei#515]
### Problem description:

When you change default OrthographicCamera's frustrum, camera starts behaving pretty weirdly on resize

Check the demo https://codesandbox.io/s/magical-haslett-q09p3
Try to resize browser window vertically

### Packages

@react-three/drei:  7.3.1
@react-three/fiber 7.0.6
three: ^0.130.1

**Comment by DavidNaumann** [comment]
Pulling info across from repeat #548 , repeatable instance of issue: [sandbox env](https://codesandbox.io/s/romantic-snow-esvty?file=/src/App.js)

**Comment by drcmda** [comment]
for reference:

ortho source: https://github.com/pmndrs/drei/blob/master/src/core/OrthographicCamera.tsx

r3f automatic camera handling: https://github.com/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/store.ts#L350-L354

the cameras are responsive by default, you don't need left/right/... unless there's a specific reason for that. but if you do that you have to switch the camera to `manual` and then r3f takes a hands-off approach.
