### ISSUE TITLE
Module not found: ESM packages (zustand) need to be imported. 

### ISSUE THREAD

**Issue by marleykanui** [pmndrs/drei#517]
- `three` version: 0.131.3
- `@react-three/fiber` version: 7.0.6
- `@react-three/drei` version: 7.4.0
- `node` version: 16.6.1
- `npm` (or `yarn`) version: yarn 1.22.11

### Problem description:

I don't know if this is the right place for this, but I just upgraded to 4.0 and now I'm getting:

error - ./node_modules/@react-three/drei/index.cjs.js:1:276
Module not found: ESM packages (zustand) need to be imported. Use 'import' to reference the package instead.

I get this in the terminal when launching my NextJS dev server. Since this looks like it may be an issue within the module index and all I'm doing is importing drei components into my own like I was doing with other versions, I thought I should inquire about it here. Feel free to remove this if it's irrelevant or user error. Thank you for your time. 

### Relevant code:

error - ./node_modules/@react-three/drei/index.cjs.js:1:276
Module not found: ESM packages (zustand) need to be imported. Use 'import' to reference the package instead.

**Comment by joshuaellis** [comment]
Please provide a repo of the issue so we can review it.

**Comment by marleykanui** [comment]
Sorry about that. Here you go:

https://github.com/marleykanui/baklavegan/tree/drei-fix

Thank you

**Comment by marleykanui** [comment]
Getting this in Vercel logs when deploying preview if this helps at all. 
[
<img width="1011" alt="vercel log - drei" src="https://user-images.githubusercontent.com/34557865/129383707-6b4da513-a727-4182-b1f7-3b46daf869a9.png">
](url)

**Comment by marleykanui** [comment]
> Please provide a repo of the issue so we can review it.

I have provided the repo that is causing issues. Thank you for your help

**Comment by joshuaellis** [comment]
There's way too much going on in that repo to diagnose a problem, id ask if you can supply a minimal reproduction of the issue, whereby it is as small as can be.

**Comment by drcmda** [comment]
i just saw this: https://twitter.com/dai_shi/status/1427604302936215553 maybe it helps. it looks like the npm eco system is slowly collapsing due to the cjs/esm spec nonsense. i havent dug into it yet but it looks like a huge effort for package authors to navigate byzantine rules.

**Comment by marleykanui** [comment]
This is no longer an issue in 7.6.1 update
