### ISSUE TITLE
GizmoHelper not showing when used with react-three/postprocessing

### ISSUE THREAD

**Issue by quacrobat** [pmndrs/drei#519]
- `three` version: latest
- `@react-three/fiber` version: latest
- `@react-three/drei` version: latest
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:
When I use postprocessing EffectComposer, the drei GizmoHelper disappears.

### Relevant code:
See codesandbox: https://codesandbox.io/s/react-three-postprocessing-vs-drei-viewcube-veq3c?file=/src/index.js
if you delete the <EffectComposer /> the Gizmo reappears. (Even with actual effects within it, it's the same problem)

### Suggested solution:
Seems related to https://github.com/pmndrs/drei/issues/358 ?

**Comment by joshuaellis** [comment]
GizmoHelper came in as a contribution, as such we'll need the community to resolve issues like this. Thank you for the report!

**Comment by johnmarinelli** [comment]
I did some hacking, adding a `2` to the second argument of `GizmoHelper`'s `useFrame` will make it work when using `EffectComposer` (thanks to this comment https://github.com/pmndrs/react-three-fiber/discussions/1260#discussioncomment-675562)  maybe there should be a `renderPriority` argument passed in to `GizmoHelper` just as there is in `EffectComposer`?

**Comment by quacrobat** [comment]
> adding a `2` to the second argument of `GizmoHelper`'s `useFrame` will make it work

I confirm this works, amazing find, thank you.

**Comment by joshuaellis** [comment]
> I did some hacking, adding a `2` to the second argument of `GizmoHelper`'s `useFrame` will make it work when using `EffectComposer` (thanks to this comment [pmndrs/react-three-fiber#1260 (comment)](https://github.com/pmndrs/react-three-fiber/discussions/1260#discussioncomment-675562)) maybe there should be a `renderPriority` argument passed in to `GizmoHelper` just as there is in `EffectComposer`?

I think this a good idea, thanks @johnmarinelli, would you mind making a PR for this? 😄

**Comment by drcmda** [comment]
small correction, the gizmo can't have a fixed number, because then it would cause other components trouble. but it has a renderPriority that allows you to stack it in any order necessary:

```jsx
<EffectComposer />
<Gizmo renderPriority={2} />
```

**Comment by Abolfazlshabani** [comment]
> small correction, the gizmo can't have a fixed number, because then it would cause other components trouble. but it has a renderPriority that allows you to stack it in any order necessary:
> 
> ```js
> <EffectComposer />
> <Gizmo renderPriority={2} />
> ```



> small correction, the gizmo can't have a fixed number, because then it would cause other components trouble. but it has a renderPriority that allows you to stack it in any order necessary:
> 
> ```js
> <EffectComposer />
> <Gizmo renderPriority={2} />
> ```

Hello I'm new in r3f and learning it , and i'm developing this project (for test HUD)
https://codesandbox.io/s/e662p3   (i just add a HUD and a 3Dtext on that)
now i fixed displaying scene with add renderPriority={2} to HUD (that was for EffectComposer) and now effect doesn't run on HUD 
but i want to add effect for car and the text, how i can add effect for HUD 
can you help me please?

**Comment by cjfweb** [comment]
> > small correction, the gizmo can't have a fixed number, because then it would cause other components trouble. but it has a renderPriority that allows you to stack it in any order necessary:
> > ```js
> > <EffectComposer />
> > <Gizmo renderPriority={2} />
> > ```
> 
> Hello I'm new in r3f and learning it , and i'm developing this project (for test HUD) https://codesandbox.io/s/e662p3 (i just add a HUD and a 3Dtext on that) now i fixed displaying scene with add renderPriority={2} to HUD (that was for EffectComposer) and now effect doesn't run on HUD but i want to add effect for car and the text, how i can add effect for HUD can you help me please?

use 3or4or5?
