### ISSUE TITLE
GizmoHelper preserveDrawingBuffer stops frame clear

### ISSUE THREAD

**Issue by marks311** [pmndrs/drei#520]
When using a GizmoHelper and setting the gl preserveDrawingBuffer to true, the Helper stops all canvas Elements from clearing the last frames.
minimal setup Sandbox example: https://codesandbox.io/embed/flamboyant-rgb-d3lrx

**Comment by joshuaellis** [comment]
GizmoHelper came in as a contribution, as such we'll need the community to resolve issues like this. Thank you for the report!
