### ISSUE TITLE
Unable to call useGLTF inside webworkers

### ISSUE THREAD

**Issue by robosushie** [pmndrs/drei#523]
Hi I am using @react-three/fiber ^7.0.6 and @react-three/drei ^7.5.0.
I am trying to offload my 3D object loading on my website using a webworker.

When I am trying to use the useGLTF hook in my webworker I am getting this error -

> Uncaught ReferenceError: document is not defined
    at fixFileAndXHR (Blob.js:518)
    at Object.<anonymous> (Blob.js:577)
    at Blob.js:15
    at Blob.js:23
    at Object.<anonymous> (Blob.js:690)
    at Object../node_modules/blob-polyfill/Blob.js (Blob.js:690)
    at __webpack_require__ (bootstrap:19)
    at Module.<anonymous> (base64.js:1)
    at Module../node_modules/@react-three/drei/helpers/base64.js (base64.js:19)
    at __webpack_require__ (bootstrap:19)

![image](https://user-images.githubusercontent.com/61646255/130367732-d1d46ab9-b5df-4456-ae0d-3475f5c0a97e.png)

Is there a way to make it work in webworkers because I know window, document and other DOM elements are not accessable in webworkers. is there are way out or should I try with the default GLTFLoader with webworkers ?

**Comment by joshuaellis** [comment]
I'd probably use the direct import of the component – drei/core/useGLTF instead of root, that should avoid bringing in the other components as I believe the blob poly fill we're using is the cause of this issue. You're of course welcome to post the issue there too

**Comment by robosushie** [comment]
@joshuaellis Thanks that helped in mitigating the issue ut I am geeting a different issue now with @react-three-fiber.esm module

![image](https://user-images.githubusercontent.com/61646255/130368227-c7861643-e5de-43b7-a570-6fe363f1d447.png)
