### ISSUE TITLE
GizmoHelper "property `onUpdate` is missing in type", shouldn't `onUpdate` be declared as optional?

### ISSUE THREAD

**Issue by grndctrl** [pmndrs/drei#527]
- `three` version:
- `@react-three/fiber` version: 7.0.6
- `@react-three/drei` version: 7.4.0
- `node` version: 16.3.0
- `npm` (or `yarn`) version: 7.15.1

### Problem description:

Adding a GizmoHelper to my scene gives me the TypeScript error:
"property `onUpdate` is missing in type"
However the GizmoHelper runs fine without it, as I tested it with a mock function.

### Relevant code:

```
<GizmoHelper onUpdate={() => console.log('tick')}>
  <GizmoViewcube />
</GizmoHelper>
```

### Suggested solution:

Shouldn't onUpdate be declared as optional as well?
`GizmoHelper.d.ts`
```js
export declare type GizmoHelperProps = JSX.IntrinsicElements['group'] & {
    alignment?: 'top-left' | 'top-right' | 'bottom-right' | 'bottom-left';
    margin?: [number, number];
    onUpdate?: () => void; // <-- set onUpdate to optional?
    onTarget?: () => Vector3;
};
```

**Comment by joshuaellis** [comment]
Yes you're right! thank you.
