### ISSUE TITLE
How to use my own local hdr file in component "Stage"

### ISSUE THREAD

**Issue by Andy-Leo** [pmndrs/drei#536]
I found in **Stage** component, the **environment** is load from online. The network of that website is not good for me. Can i load my own hdr file from localhost instead. Let me know, thanks！

**Comment by drcmda** [comment]
https://codesandbox.io/s/staging-models-9b56t

```jsx
<Environment path="/cube" />
<Stage environment={null}>
  <Model />
```

**Comment by Andy-Leo** [comment]
> https://codesandbox.io/s/staging-models-9b56t
> 
> ```js
> <Environment files="/my.hdr" />
> <Stage environment={null}>
>   <Model />
> ```

It work. Nice & easy. Thank you very much.
