### ISSUE TITLE
declarative points/instances

### ISSUE THREAD

**Issue by drcmda** [pmndrs/drei#537]
## the problem

instancing is a sealed structure. it can't be easily and effectively tied to nested reactive state, you can't form components that perform individual tasks, you can't share, compose or outsource behaviour. not even to mention events.

## solution

```jsx
<Points>
  <pointsMaterial />
  <Point position={[1, 2, 3]} color="red" onClick={onClick} onPointerOver={onPointerOver} ... />
  // As many as you want, make them conditional, mount/unmount them, lazy load them, etc ...
```

```jsx
<Instances>
  <boxGeometry />
  <meshStandardMaterial />
  <Instance position={[1, 2, 3]} rotation={[Math.PI / 3, 0, 0]} scale={2} color="red" onClick={onClick} ... />
  // ...
```

demo: https://codesandbox.io/s/r3f-points-czhxx?file=/src/App.js

advantages:

- declarative
- single draw call
- render optimized (renders only when needed)
- can be nested and grouped, points can have relative positions
- positions/colors can be set renderless (refs), or reactively by props
- individual pointer events
- points can have real (non-instanced) children, like annotations

it works by defining a hard limit that can't be extended, say 100.000 or 1.000. it then sets a draw-range and only processes as many points as accumulate in the declarative scene graph. this also allows you to mount/unmount points ofc.

```jsx
function AnimatePositionAndColor() {
  const ref = useRef()
  useFrame((state) => {
    // Animate position and color frame by frame
    ref.current.position.y = Math.sin(state.clock.elapsedTime)
    ref.current.color.setHSL(1 + Math.sin(state.clock.elapsedTime) / 2, 1, 0.5)
  })
  return <Point ref={ref} />
}

<Canvas>
  <Points scale={20} limit={1000}>
    <Point position={[2, 3, 4]} color="green" />
    {/* Nesting and relative positions! */}
    <group position={[0.5, 0, 0]} rotation={[0, 0, 0.5]}>
      {/* Component composition! */}
      <AnimatePositionAndColor />
    </group>
    <Point position={[1, 2, 3]} color="red" />
    {/* Children and annotations! */}
    <Point position={[2, 0, 0]}>
      <Html>html annotation!</Html>
    </Point>
    {/* Events! */}
    <Point position={[3, 0, 0]} onPointerOver={(e) => ...} onPointerOut={(e) => ...} onClick={(e) => ...} />
  </Points>
```

materials can be set as easy as

```jsx
<Points>
  <pointsMaterial />
```

and for instances

```jsx
<Instances>
  <boxGeometry />
  <meshStandardMaterial />
```

**Comment by drcmda** [comment]
i'm also working on the same thing for instances

```jsx
<Instances>
  <boxGeometry />
  <meshStandardMasterial vertexColors />
  <group position .... >
    <Instance position .... />
```

**Comment by joshuaellis** [comment]
this has been added.
