### ISSUE TITLE
Merged: type defs for children

### ISSUE THREAD

**Issue by oveddan** [pmndrs/drei#556]
The Merged feature is awesome!  For merged, it's hard to know how to use the child components with typescript. It would be great if there was a storybook example using typescript.

**Comment by madou** [comment]
I'll look into this, starting to use the Merged component and getting hit by it :-)

**Comment by mustafalazzawe** [comment]
Also running into issues with Merged while using typescript, would anyone have any examples I can refer to?

**Comment by Archimagus** [comment]
Same.  Still not example of what type to use for the callback.

**Comment by david-urvoy** [comment]
Hi, here is an example of what worked for me for defining such a type, considering you are defining some kind of RTF <mesh> subclass  :
```
<Merged meshes={[box]}>
    {
        (Box: (props: MeshProps) => ReactNode) => (
            <>
                <Box position={[0, -1.2, .5]} />
            </>
    )}
</Merged>
```
