### ISSUE TITLE
Bug - Instances - if material assigned to Instances, and Instances becomes unmounted, get "cannot read properties of null" error

### ISSUE THREAD

**Issue by oveddan** [pmndrs/drei#558]
When using the `Instances` component, and dynamically assigning the material via `material` prop, if the component is unmounted, then you get an error:

`Cannot read properties of null (reading 'isInterleavedBufferAttribute')`

Can be reproduced here:
https://codesandbox.io/s/instances-forked-17qci?file=/src/index.js

In my situation, I want to share a material with multiple instances, so I assign it as `material`.

**Comment by oveddan** [comment]
This is probably a bug on three.js behalf

**Comment by oveddan** [comment]
Same issue happens if you have the material declared in a child component:

https://codesandbox.io/s/instance-with-nested-material-rujrz?file=/src/index.js

The reason I would want this to happen is if I have some reusable logic for creating this material and I want to encapsulate that in a component.

**Comment by CodyJasonBennett** [comment]
I believe this is related to https://github.com/pmndrs/react-three-fiber/issues/1551.

**Comment by CodyJasonBennett** [comment]
Updating R3F should fix this issue with the above fix.
