### ISSUE TITLE
FlyControls (and others) with makeDefault?

### ISSUE THREAD

**Issue by nshiab** [pmndrs/drei#565]
Hi!

First, thanks for the amazing work with r3f and drei. So useful! :)

When I use OrbitControls from drei, I am able to retrieve it in other components with:
const controls = useThree(state => state.controls)

Could you change FlyControls and the other controls so we could retrieve them easily too?

Or could you explain how to add something in useThree ? So we can add and retrieve things by ourselves?

Thanks!

**Comment by drcmda** [comment]
it could be the prop is still missing. would you add it?
