### ISSUE TITLE
useGLTF and useGLTFLoader (old) , Model is not rendering how can i solve this issue

### ISSUE THREAD

**Issue by arunkumaarsrinivasan** [pmndrs/drei#577]
- `three` version:three@0.133.1 
- `@react-three/fiber` version:@7.0.15 
- `@react-three/drei` version:@7.13.1 
- `node` version: v14.17.5
- `npm` (or `yarn`) version:6.14.8

### Relevant code:
https://github.com/wrongakram/R3F-Chairs/blob/master/src/App.js

used this repo as a reference

import './App.scss';
import React, {Suspense} from 'react';
import {Canvas, useLoader} from '@react-three/fiber';
import {Html,useGLTF,OrbitControls,Stars} from '@react-three/drei';
// import { Flex, Box } from '@react-three/flex';
import Header from './components/header';
import { Section } from './components/section';

const Scene=()=> {
  const gltf = useGLTF('/scene.gltf',true)
  return (
    // <Suspense fallback={null}>
    //   <primitive object={gltf.scene} dispose={null} />
    // </Suspense>
    <primitive object={gltf.scene} dispose={null} />

  )
}

const HTMLContent = () => {
  return (
    <Section factor={1.5} offset={1}>
    <group position={[0,250,0]}>
    
    <Html fullscreen>
        <div className="container">
        <mesh position={[0,0,0]}>
      <Scene />
    </mesh>
          <h1 className='title'>Let's ROVE</h1>
        </div>
      </Html>
      </group>
      </Section>
  )
}

const STARS = () => {
  return (
    <Stars
  radius={200} // Radius of the inner sphere (default=100)
  depth={80} // Depth of area where stars should fit (default=50)
  count={1500} // Amount of stars (default=5000)
  factor={5} // Size factor (default=4)
  saturation={0} // Saturation 0-1 (default=0)
  fade // Faded dots (default=false)
/>
  )
}

function App() {
  return (
    <>
    <Header />
    <Canvas colorManagement camera={{position: [0,0,120], fov: 70}}>
    <STARS />
    <Suspense fallback={null}>
      <HTMLContent />
    </Suspense>
    
    </Canvas>
    </>
  );
}

export default App;

```

### Suggested solution:

<!--
It's ok if you don't have a suggested solution, but it really helps if you could
do a little digging to come up with some suggestion of how to improve things.
-->

**Comment by designmatty** [comment]
There seems to be an issue with the CDN that is hosting the Draco Decoder. Without this decoder your GLTF's will almost always fail to load.

https://github.com/pmndrs/drei/blob/b9812c7ac943cf771b1835d1533141eef74d93d9/src/core/useGLTF.tsx#L14

That hosted file does not exist on the gstatic servers any longer.

**Comment by drcmda** [comment]
it should be fixed if you update drei.
