### ISSUE TITLE
RFC: Remove useTesselation, useSimplification and useEdgeSplit

### ISSUE THREAD

**Issue by gsimone** [pmndrs/drei#578]
I originally added them, I was going through some of the stories and found a lot of bugs with the implementations, but that's not even the problem.

I'd rather remove these and note promote bad patterns, the best thing for this modifiers would be to just imperatively apply them to the meshes or build custom hooks if they somehow need to be dynamic.

I'm opening an RFC for this since it would require a major, let me know if there are objections.

Another important point is that these rarely are applied more than once on a geometry, so it's a waste of code to have an abstraction where you can just make it in two lines of code 😓

**Comment by drcmda** [comment]
@gsimone i have not used them but i agree, let's remove them if they promote bad patterns.

**Comment by bjornstar** [comment]
I'm not sure why github closed this with #640, but it's supposed to be closed by #664. Could you re-open it until that PR gets merged?

**Comment by bjornstar** [comment]
Can this issue be unpinned since it's now resolved?
