### ISSUE TITLE
Changing color does not apply on the first time

### ISSUE THREAD

**Issue by m4cn4ir** [pmndrs/drei#579]
try it here: https://codesandbox.io/s/floating-instanced-shoes-h8o2d?file=/src/App.js
The very first time you hover a shoe, the color won´t change to red. Hovering on another will then change the color as intended. 
Reproduction is a bit weird - reloading the sandbox won´t trigger it, but closing/reopening the tab will. Reproduced on Linux, Windows & mac.

Not really sure if it belongs to drei or r3f. Sorry if posted on the wrong forum.

**Comment by imgntn** [comment]
i've seen this behavior in my own scene as well - the instance doesn't draw until it receives a mouse event!
