### ISSUE TITLE
Support KTX2 textures in `useGLTF`

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#587]
### Describe the feature you'd like:

Include a way to enable `KTX2Loader` in `useGLTF` to support models with basis compressed KTX2 textures.

This model used in the Three.js examples has KTX2 compressed textures and throws an error when you attempt to load it with drei: [facecap.glb](https://github.com/mrdoob/three.js/blob/d9af9952fc32c2a1281707946177135b90297aab/examples/models/gltf/facecap.glb)

### Suggested implementation:

From [this example](https://github.com/mrdoob/three.js/blob/d9af9952fc32c2a1281707946177135b90297aab/examples/webgl_morphtargets_face.html):

```js
const ktx2Loader = new KTX2Loader()
        .setTranscoderPath( 'js/libs/basis/' )
        .detectSupport( renderer );

gltfLoader.setKTX2Loader( ktx2Loader )
```

I believe we'd need to add the basis transcoder from [`three.js/examples/js/libs/basis`](https://github.com/mrdoob/three.js/tree/master/examples/js/libs/basis) somewhere ~~(probably into `three-stdlib`)~~ and adjust the path accordingly. I also understand that some special considerations had to be added for MeshOpt compression in [three-stdlib/pull/84](https://github.com/pmndrs/three-stdlib/pull/84) to allow for proper tree shaking, we'll probably need to do something similar to allow the Basis stuff to be tree shaken.

### API consequence to consider

The number of positional parameters passed to `useGLTF` is already large and will continue to grow as this and future extensions are added. I propose changing the API to use an object of options rather than positional parameters.

For example:

```js
useGLTF('/model.glb', {
  useMeshopt: true,
  useKtx2: true,
  extendLoader: (loader) => { ... }
})
```

We could also explore reorganizing the extension flags:

```js
useGLTF('/model.glb', {
  extensions: ['meshopt', 'ktx2'],
  extendLoader: (loader) => { ... }
})
```

### Other thoughts

There's a lot of acronyms around compressed texture support in Three.js that I'm not very familiar with, perhaps someone with more experience in that area could look things over to ensure we support all the Basis stuff properly. E.g. I see there is also a [`BasisTextureLoader`](https://threejs.org/docs/?q=basis#examples/en/loaders/BasisTextureLoader) for loading `.basis` files, though I don't see a corresponding setter method for it on the GLTFLoader like I see with `setKTX2Loader()`

**Comment by RenaudRohlinger** [comment]
WIP https://github.com/pmndrs/drei/pull/712
