### ISSUE TITLE
CubeCamera nonfunctional

### ISSUE THREAD

**Issue by aaronsantiago** [pmndrs/drei#604]
- `three` version: 0.133.1
- `@react-three/fiber` version: 7.0.17
- `@react-three/drei` version: 7.17.2
- `node` version: v14.18.1
- `npm` (or `yarn`) version: 6.14.15

### Problem description:

CubeCamera from drei seems like it does nothing. Environment maps used are completely black.

### Relevant code:

https://codesandbox.io/s/pensive-sunset-byspg?file=/src/App.js

### Suggested solution:

Couldn't figure out much about what's going on, sorry. Seems like all of the relevant code is running--the three CubeCamera is created, the FBO is created, the render functions are being called etc.

**Comment by winkerVSbecks** [comment]
Something to do with Three v132. Dropping it to 131 works again

**Comment by Pasi-D** [comment]
Still got the same issue with `@react-three/drei` version: 9.68.2
