### ISSUE TITLE
Bounds without camera rotation.

### ISSUE THREAD

**Issue by timoxley** [pmndrs/drei#607]
I'd like a version of `Bounds` but without the camera rotation 
Camera would maintain the current direction but still pan to fit the object on-screen .

Usecase: Use with MapControls for top-down view of the world, like in an RTS game.

### Suggested implementation:

```typescript
const direction = (
  fixedOrientation
    ? camera.getWorldDirection(new THREE.Vector3())
    : center.clone().sub(camera.position).normalize()
).multiplyScalar(distance)
```

https://codesandbox.io/s/bounds-and-makedefault-forked-y12ie?file=/src/Bounds.tsx:3342-3530

It probably shouldn't be a prop on `Bounds` but rather an argument to `fit`. Your call.

**Comment by emaLorenzo** [comment]
Hey @timoxley thanks, I used your version with fixed rotation here

https://user-images.githubusercontent.com/10750168/160702881-c06cda7a-16bc-41d2-991f-c4599b52a148.mp4

**Comment by hakimmazouz** [comment]
Any news on getting this into Bounds? 😃

Facing the same issue with rotation drifting off from starting orientation upon subsequent fit calls.
