### ISSUE TITLE
Unable to resolve module `three-mesh-bvh` (Native / Expo)

### ISSUE THREAD

**Issue by neilgamb** [pmndrs/drei#636]
- `three` version: "^0.134.0"
- `@react-three/fiber` version: "^8.0.0-beta-02",
- `@react-three/drei` version: "^7.22.1",
- `node` version: 14.17
- `npm` (or `yarn`) version: yarn 1.22.5
- `expo` version:  "~43.0.2",

### Problem description:

I just installed three, r3f and drei in an expo app via the [instructions here](https://docs.pmnd.rs/react-three-fiber/getting-started/installation#expo-and-react-native).  

The app is running on both native and web via expo's react-native-web interface.  So far everything is working OK on web.

When importing `import { useGLTF, Center } from '@react-three/drei/native'` however, I am getting the following error message on the native device (iPad):

```

While trying to resolve module `three-mesh-bvh` from file `/Users/neilsongamble/Dev/Scandy/project-chewie/apps/frontend/node_modules/@react-three/drei/native/index.js`, the package `/Users/neilsongamble/Dev/Scandy/project-chewie/apps/frontend/node_modules/three-mesh-bvh/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/neilsongamble/Dev/Scandy/project-chewie/apps/frontend/node_modules/three-mesh-bvh/build/index.umd.cjs`. Indeed, none of these files exist:

  * /Users/neilsongamble/Dev/Scandy/project-chewie/apps/frontend/node_modules/three-mesh-bvh/build/index.umd.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/neilsongamble/Dev/Scandy/project-chewie/apps/frontend/node_modules/three-mesh-bvh/build/index.umd.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  ```

![IMG_66E12EFDEC16-1](https://user-images.githubusercontent.com/26474370/142510086-b48a194e-48bc-403d-b96c-eae1c59f0306.jpeg)

### Suggested solution:
none so far sorry

**Comment by joshuaellis** [comment]
This should go in the relevant repo, being three-mesh-bvh.... We can't do anything about it in this repo I don't think. 

Although if it came to it I suppose we could move it to web only. But I feel like it's a straight forward fix for the other maintainer.

**Comment by neilgamb** [comment]
'... /three-mesh-bvh/build/index.umd.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)'

From the `three-mesh-bvh` team:

"Specifically it seems that expo is not trying to load index.umd.cjs (which exists if you look in the directory) and instead trying a variety of other extensions on the provided file instead, which is odd. The cjs extension is one of the recommended ways from node.js for distinguishing and supporting commonjs "require"-style files compared to modules (mjs) files."

**Comment by xD3CODER** [comment]
You should be able to solve this issue by adding `cjs` to your  `sourceExts` in the babel config

**Comment by CodyJasonBennett** [comment]
Indeed, this is an issue with your metro configuration. See [R3F's native installation instructions](https://docs.pmnd.rs/react-three-fiber/getting-started/installation#react-native) if you run into further trouble.
