### ISSUE TITLE
OrbitControls Sticky Remedy Removed

### ISSUE THREAD

**Issue by mysterybear** [pmndrs/drei#638]
I think this https://github.com/mrdoob/three.js/issues/22848 may be affecting drei?

If I update from drei 5.3.1 to 7.22.1 I get this bug

**Comment by mysterybear** [comment]
Here's a sandbox https://codesandbox.io/s/github/mysterybear/orbit-controls-enabled-basics?file=/src/components/App.tsx

It's got the 5.3.1 version, so it works fine (drag the box around, it disables the controls and everything works great)

Update drei and you'll find that after the last pointer event, when the controls are re-enabled, they seem to then update based on the pointer events since disabling

**Comment by mysterybear** [comment]
Weirdly, if I pin drei's version to 5.3.1 in the main app I'm working on, this problem is still present... Very confusing

**Comment by mysterybear** [comment]
Tried copy-pasting the yarn.lock from the demo project (linked sandbox) into my main app and I can get a test page where the bug doesn't persist, so it's _definitely something_ to do with dependencies, just not sure exactly what!

**Comment by joshuaellis** [comment]
`three-stdlib`?

**Comment by mysterybear** [comment]
> `three-stdlib`?

Have tried pinning at 2.0.0 and then 2.3, 2.4... Doesn't seem to be it...

**Comment by mysterybear** [comment]
My pinning must not have been working right or something. This is definitely the culprit: https://github.com/pmndrs/drei/commit/9fe44e83ab7b162ff1a81c2fe83e952814d4f951 so yeah I think it's a `three-stdlib` thing, though not sure if `drei` should pin `three-stdlib` back before the regression, so will wait for a maintainer to close this, but feel free.

**Comment by drcmda** [comment]
@mysterybear you or someone else needs to update three-stdlib. the control lives there. you can just cherry-pick their commits. we do no use three/jsm because we need to be able to apply bugfixes that three doesnt allow, but the downside is that we might miss upstream fixes.

**Comment by CodyJasonBennett** [comment]
Appreciate the fix. (Related PR: https://github.com/pmndrs/three-stdlib/pull/102.
