### ISSUE TITLE
[Native] Environment full black after navigate

### ISSUE THREAD

**Issue by xD3CODER** [pmndrs/drei#651]
- `three` version: 0.133.1
- `@react-three/fiber` version: 8.0.0-beta-02
- `@react-three/drei` version: 7.14.3
- `node` version: 14.18.1
- `npm` (or `yarn`) version: 1.22.17

### Problem description:

I'm using react-navigation to navigate in my rn-app. After navigating to a screen containing an `Environment />`, if I navigate  to another screen containing an `Environment />`, the environment is completely black.

Maybe related to this issue #499

**Comment by tigrik2017** [comment]
Still valid. In my case, it occurs not on navigation, but moving between two same 3D viewer components on the same page which contain environment components, making them visible one by one. In that case, the first one loses the environment and after hiding the second, it won't restore.
