### ISSUE TITLE
Set className on outer element in drei HTML

### ISSUE THREAD

**Issue by joshon** [pmndrs/drei#679]
### Describe the feature you'd like:

I would like to be able to set a selector on the outermost div created by Drei HTML. In [my case I want it so that I can control the z-index manually](https://github.com/pmndrs/drei/discussions/660) - but I think it would be useful to expose in general. Currently, {...divProps} applies to the child div, I would like to be able to access the parent. You can access the parent through the "as" property which sets the element type, but that seems like a hack simply for CSS selector purposes.

### Suggested implementation:

Perhaps adding a property called wrapperClassName that added a className to the outermost div would be a good enhancement.

**Comment by joshuaellis** [comment]
resolved by #690
