### ISSUE TITLE
All props are required in all components

### ISSUE THREAD

**Issue by LuckeeDev** [pmndrs/drei#687]
- `three` version: 0.135.0
- `@react-three/fiber` version: 7.0.23
- `@react-three/drei` version: 8.0.0
- `node` version: 16.13.1
- `npm` (or `yarn`) version: 1.22.15

### Problem description:

All exported components require all props and in TypeScript throw errors like
```
Type '{ children: Element; castShadow: boolean; }' is missing the following properties from type 'Pick<Omit<MeshProps, "args"> & { args?: [radius?: number | undefined, widthSegments?: number | undefined, heightSegments?: number | undefined, phiStart?: number | undefined, phiLength?: number | undefined, thetaStart?: number | undefined, thetaLength?: number | undefined] | undefined; children?: ReactNode; }, "mater...': onPointerMissed, material, quaternion, position, and 92 more.
```
This doesn't allow the app to start properly because type checking stops the compilation.

### Relevant code:

```js
<Sphere castShadow={true}>
  <meshBasicMaterial attach="material" color="hotpink" />
</Sphere>
```

### Suggested solution:

I remember using `drei` a while back and not encountering this issue. Maybe it's something that was introduced with the new version? I hope someone can help me out!

**Comment by joshuaellis** [comment]
have you installed @types/three

**Comment by LuckeeDev** [comment]
@joshuaellis I hadn't, thanks for helping me out!
