### ISSUE TITLE
Bounds changes camera orientation/rotation

### ISSUE THREAD

**Issue by BlakeBrown** [pmndrs/drei#700]
- `three` version: 0.135.0
- `@react-three/fiber` version: 6.0.13
- `@react-three/drei` version: 8.3.1
- `node` version: 14.14.6
- `npm` (or `yarn`) version: 8.1.0

### Problem description:

Here is my desired behavior, when I add a `Bounds` wrapper to my model, hot-refresh seems to rotate the horse about it's center.
 
https://user-images.githubusercontent.com/6283620/146652296-1db0eae0-b401-4a3f-ab72-e7f75b1b1483.mov

However, when I refresh the page `Bounds` seems to change the orientation of the camera such that it rotates about the center of the world, and not the horse model.

https://user-images.githubusercontent.com/6283620/146652298-efce123e-7dec-48c0-9d82-9d86dd99f2a9.mov

### Relevant code:

```js
 <Canvas>
        <Suspense fallback={null}>
          <OrbitControls autoRotate={true} autoRotateSpeed={5} makeDefault />
          <Stage
            contactShadow
            shadows
            adjustCamera
            center="default"
            intensity={0.4}
            environment="city"
            preset="rembrandt"
          >
            <Bounds clip fit>
              <Model src={props.src} />
            </Bounds>
          </Stage>
        </Suspense>
      </Canvas>
```

### Suggested solution:

I've tried playing around with several of the components I'm using in my code, but haven't had any success. Any ideas how to fix this issue?

**Comment by BlakeBrown** [comment]
Nvm, figured out what was wrong! Bounds should be outside of the Stage :)

**Comment by drcmda** [comment]
i would not use stage in production or mix it with bounds tbh. stage is a prototyping component for quick results but the centering is error-prone. if you are happy with the results just copy the stage component, remove the center stuff and just go with the lights, shadows and so on.
