### ISSUE TITLE
Attempted import error: 'GammaEncoding' is not exported from 'three'.

### ISSUE THREAD

**Issue by Uhmopt** [pmndrs/drei#705]
Hi 

I am trying to use this package, however, after installing this package, the project can not be built.

It shows the following issues.

```Failed to compile.

./node_modules/three-stdlib/nodes/core/NodeBuilder.js
Attempted import error: 'GammaEncoding' is not exported from 'three'.
```

![image](https://user-images.githubusercontent.com/92436742/147380393-efa423d0-9691-49b8-adc0-cd18fb930387.png)

I did not have any code related to this package excluding a line of simple import.

```
import { PerspectiveCamera, PositionalAudio } from "@react-three/drei";
```

Does it occur only to me?

Please help me.

**Comment by RenaudRohlinger** [comment]
Hello@Uhmopt. It's because the GammaEncoding has been removed in the latest version of threejs (0.136.0).
Temporary you can go back to 0.135.0 to fix the issue while we are updating three-stdlib which is a dependency of Drei.
