### ISSUE TITLE
Issue when using `Points` with bufferAttributes (type error)

### ISSUE THREAD

**Issue by Carnageous** [pmndrs/drei#706]
- `three` version: 0.135.0
- `@react-three/fiber` version: ^7.0.24
- `@react-three/drei` version: ^8.3.1
- `node` version: v14.18.0
- `npm` version: 8.0

### Problem description:

In react/typescript, when using drei's `<Points>` with "bufferAttributes" as stated in the readme, I get a type error:
```
Type '{ children: Element; positions: never[]; colors: number[]; }' is not assignable to type 'IntrinsicAttributes & Pick<PointsInstancesProps | PointsBuffersProps, "attach" | "attachArray" | "attachObject" | ... 94 more ... | "onWheel"> & RefAttributes<...>'.
  Property 'positions' does not exist on type 'IntrinsicAttributes & Pick<PointsInstancesProps | PointsBuffersProps, "attach" | "attachArray" | "attachObject" | ... 94 more ... | "onWheel"> & RefAttributes<...>'.
```

From your sourcecode, I can clearly see, that `Points`'s attributes include `PointsBuffersProps`, so I suppose this should work. Is there any requirement in the typescript version?

### Relevant code:

```tsx
<Points positions={points} colors={colors}> // <== Here the error
  <pointsMaterial />
</Points>
```

If it's relevant, I am using typescript ^4.1.2 and the app was created with CRA, and I manually updated to react-scripts version 5.0.0.

### Suggested solution:
Not sure. I was able to reproduce this bug multiple times, but if you cannot, a hint on what I'm doing wrong would be awesome.

// Edit
I get the same error for the "limit" prop

**Comment by Carnageous** [comment]
Seems to be an issue only with typescript versions above ~ 4.5.4

**Comment by joshuaellis** [comment]
Please provide a codesandbox reproduction of the issue.

**Comment by Carnageous** [comment]
Sure, here you go: https://codesandbox.io/s/throbbing-sun-jt9pf?file=/src/View.tsx.

Issue can be seen in View.tsx:17 @joshuaellis

**Comment by kaos** [comment]
I also note an issue with the `OrbitControls` in that sandbox, similar to those reported in #113. Which I phase, and trying to solve/workaround.

**Comment by khiner** [comment]
I am seeing the same thing - `limit` not an attribute on `Points` and `position` not an attribute on `Point`.

Versions:
TS: 4.5.3
Three: 0.136.0
Fiber: 7.0.24
Drei: 8.3.1

**Comment by mcndt** [comment]
Today I created a fresh react project using the TypeScript template and I encounter a similar issue with `OrthographicCamera`:

![image](https://user-images.githubusercontent.com/23149353/148446166-b0bc38fa-2f25-4560-86ea-ebc89183c9c3.png)

TS: 4.5.4
Three: 0.136.0
Fiber: 7.0.24
Drei: 8.3.1

**Comment by joshuaellis** [comment]
@mcndt have you installed `@types/three`?

**Comment by joshuaellis** [comment]
The issue is typescript cant infer which prop set to use:

```ts
export const Points = React.forwardRef<THREE.Points, PointsBuffersProps | PointsInstancesProps>(
  (props, forwardedRef) => {
    if ((props as PointsBuffersProps).positions instanceof Float32Array) {
      return <PointsBuffer {...(props as PointsBuffersProps)} ref={forwardedRef} />
    }

    return <PointsInstances {...(props as PointsInstancesProps)} ref={forwardedRef} />
  }
)
```

This bit in particular – `PointsBuffersProps | PointsInstancesProps`

IMO this component shouldn't be written like this, it's casting the type and not narrowing. If it were narrowing Typescript wouldn't have the issue.

I'll leave this here for whoever is interested in fixing the issue.

**Comment by drcmda** [comment]
i did this, but my TS is weak to say the least, how would narrowing work? i can fix it ...

**Comment by joshuaellis** [comment]
Narrowing should work but you don't have a unique identifier thats apparent on both types I think 🤔

**Comment by mcndt** [comment]
> @mcndt have you installed `@types/three`?

That helped a lot of these issues yes. Although it’s a but confusing to a new user as to whether this package should be installed or not. Anyways thanks!

**Comment by joshuaellis** [comment]
@mcndt if you're using typescript and you install a version of `three` that doesn't have types it will prompt you to install it. 

It's kind of a given for TS packages.

**Comment by jpenailillo** [comment]
Same issue with `Point`

![image](https://user-images.githubusercontent.com/65561498/150136558-2837372f-dac7-48ae-aeac-a8e50e2270b8.png)
