### ISSUE TITLE
TrackballControls do not work with frameloop="demand"

### ISSUE THREAD

**Issue by nermolov** [pmndrs/drei#708]
- `three` version: 0.136.0
- `@react-three/fiber` version: 7.0.24
- `@react-three/drei` version: 8.3.1

### Problem description:

Unlike OrbitControls, TrackballControls doesn't seem to invalidate the frame and thus doesn't trigger rendering with `frameloop="demand"`

### Relevant code:

https://codesandbox.io/s/agitated-pascal-nvw2m?file=/src/App.js

### Suggested solution:

I tried using the experimental CameraControls.TrackballControls as #171 suggested that solves this issue, but couldn't get that working either.

**Comment by surdu** [comment]
This is [documented in Three Fiber](https://docs.pmnd.rs/react-three-fiber/advanced/scaling-performance#triggering-manual-frames)
