### ISSUE TITLE
Strange behavior with Environment, JS vs TS

### ISSUE THREAD

**Issue by antokhio** [pmndrs/drei#713]
- `three` version: 0.136.0
- `@react-three/fiber` version: 7.0.24
- `@react-three/drei` version: 8.3.1
- `node` version:  v16.13.1
- `npm` (or `yarn`) version: 1.22.17

### Problem description:
Environment displays image in differently in react js app and react ts app
![image](https://user-images.githubusercontent.com/1254168/148074427-d48b7cbe-9043-4c19-8354-79c13a01e6db.png)
![image](https://user-images.githubusercontent.com/1254168/148074481-6b07e8ea-15ea-45d4-9ecc-8d62e24179d8.png)

### Relevant code:
https://codesandbox.io/s/cool-morning-po3lv?file=/src/App.tsx:215-449

```js
    <Canvas style={{ width: "100vw", height: "100vh" }}>
      <Suspense fallback={null}>
        <OrbitControls />
        <Box args={[1, 1, 1]} />
        <Environment preset="apartment" background />
      </Suspense>
    </Canvas>
```

### Suggested solution:

Really no clue why that happens...

**Comment by joshuaellis** [comment]
I changed the version in your sandbox to .135 and it changed the "quality" of the texture. Must be a regression / change in THREE

**Comment by antokhio** [comment]
thanks @joshuaellis did worked perfectly
