### ISSUE TITLE
useDetectGPU pointing to 3.x version

### ISSUE THREAD

**Issue by liqueflies** [pmndrs/drei#717]
- `three` version: 0.135.0
- `@react-three/fiber` version: 7.0.24
- `@react-three/drei` version: 8.4.0
- `node` version: 14
- `npm` (or `yarn`) version:

### Problem description:

Hello,
the function useDetectGPU is pointing to a 3.x version on dependencies so it's not working good to iPhone, M1 chips etc...
detect-gpu is now at 4.x version

### Suggested solution:

Just update the version on the dependency list!
For now I installed the fresh version of detect-gpu and copied the drei useDetectGPU file into my utils.

Thank you!

**Comment by joshuaellis** [comment]
Feel free to make a PR to address this issue 😄

**Comment by liqueflies** [comment]
👍 
Is right to put dependencies as "latest" as is maintained by pmndrs?

**Comment by joshuaellis** [comment]
I wouldn't just incase there's a breaking change (e.g. v5) that we haven't seen. PMNDRS is a very large org, we're not watching all repos!

**Comment by CodyJasonBennett** [comment]
The v4 bump came from https://github.com/pmndrs/detect-gpu/commit/00b4c619b5a822ab0b009c9ca87ad0726be48c67.
