### ISSUE TITLE
Cloud not loading or showing errors

### ISSUE THREAD

**Issue by jonrrivera** [pmndrs/drei#723]
- `three` version:
- `@react-three/fiber` version:
- ^7.0.7
- `@react-three/drei` version:
^7.11.0
- `node` version:
- v17.2.0
- `npm` (or `yarn`) version:
- 8.1.4

### Problem description:

I am looking to integrate the [Cloud](https://github.com/pmndrs/drei#cloud) into my scene but nothing is rendering. I'm thinking it could be from this [breaking change?](https://github.com/pmndrs/drei/issues/631). Please help :)

**Comment by CodyJasonBennett** [comment]
Takes a while to decode but it runs fine on v7. https://zpt8t.csb.app/

**Comment by CodyJasonBennett** [comment]
We had migrated hosts for assets so this component should work as expected now.
