### ISSUE TITLE
An outline helper

### ISSUE THREAD

**Issue by TresAbhi** [pmndrs/drei#728]
### About:

A simple helper that wraps meshes/groups and displays an outline around them.

### Suggested implementation:

Here's the simplest way to do this:

#### Normal usage:

This will outline all meshes inside individually:
```tsx
<OutlineHelper>
  <YourMesh />
  <YourMesh2 />
<OutlineHelper>
```

#### Group usage:

This will outline all meshes with one box containing all:
```tsx
<OutlineHelper mode="grouped">
  <YourMesh />
  <YourMesh2 />
<OutlineHelper>
```

**Comment by DennisSmolek** [comment]
Maybe you can do something with the existing https://github.com/pmndrs/drei#edges component?

**Comment by TresAbhi** [comment]
@DennisSmolek, that is exactly what I needed. Thanks!

**Comment by TresAbhi** [comment]
`BoxHelper` seems to be closer to what I needed. It's not really implemented into drie (though you can use `useHelper`), it's good enough. Closing issue.
