### ISSUE TITLE
Error rendering PresentationControls

### ISSUE THREAD

**Issue by jonrrivera** [pmndrs/drei#738]
- `three` version:
- `@react-three/fiber` version:
- 7.0.19
- `@react-three/drei` version:
-  7.22.7
- `node` version:
- v17.2.0
- `npm` (or `yarn`) version:
- 8.1.4

### Problem description:

Importing PresentationControls is giving me the following error:

<img width="888" alt="Screen Shot 2022-01-25 at 1 50 24 PM" src="https://user-images.githubusercontent.com/18686388/151065730-58bcece8-8b8b-4495-8589-a62fda532b4d.png">

### Relevant code: (Same as documentation [Demo](https://codesandbox.io/s/bouncy-watch-forked-z0sed?file=/src/App.js:288-720))

```jsx

      import { PresentationControls } from '@react-three/drei'

      <Canvas flat dpr={[1, 2]} camera={{ position: [0, 0, 8], fov: 25 }}>
        <PresentationControls
          global
          zoom={0.8}
          rotation={[0, -Math.PI / 4, 0]}
          polar={[0, Math.PI / 4]}
          azimuth={[-Math.PI / 4, Math.PI / 4]}>
          <LogoModel position={[0, -1, 0]} />
        </PresentationControls>
      </Canvas>


```

**Comment by CodyJasonBennett** [comment]
Seems this is just a version mismatch. You'll have to update Drei to at least v7.26.0 where PresentationControls were introduced.
