### ISSUE TITLE
MeshReflectorMaterial in Typescript return "is missing the following properties from type 'Pick<Props, "userData""

### ISSUE THREAD

**Issue by marc-aurele-besner** [pmndrs/drei#752]
Hi,

Inspired by one of the last example of the 3d gallery, I wanted to start working on something similar but in ts.
I'm having some issue make MeshReflectorMaterial work in ts, while I have no problem in js...
In ts it require a bunch of props...
I made a sandbox of the issue (https://codesandbox.io/s/magical-ride-n8bgu?file=/src/components/Ground.tsx:521-807), if anyone has a idea of what I'm doing wrong...
Thank you very much

-  "three": "^0.137.5",
-  "@react-three/drei": "^8.8.1",
-  "@react-three/fiber": "^7.0.26",
-  "@types/three": "^0.137.0",

### Relevant code:
https://codesandbox.io/s/magical-ride-n8bgu?file=/src/components/Ground.tsx:521-807

```js
<MeshReflectorMaterial
                blur={[300, 100]}
                resolution={512}
                mixBlur={1}
                mixStrength={60}
                roughness={1}
                depthScale={1.2}
                minDepthThreshold={0.4}
                maxDepthThreshold={1.4}
                color="#151515"
                metalness={0.5}
            />
```

### Suggested solution:

I use Reflector previously, but I understand it was replaced by this new MeshReflectorMaterial...

**Comment by bh41352** [comment]
MeshReflectorMaterial doesn't work with three 0.137.0, in 0.136.0 works but not how excepted, but in 0.135.0 works perfectly.

Relevant code:

https://codesandbox.io/s/vigilant-buck-5sch7?file=/src/App.js

**Comment by marc-aurele-besner** [comment]
Thank you, indeed that work in js, but I'm still having the same issue if I add this component in a .tsx file...
I fix the issue by isolating the ground on a .js file but still weird...
