### ISSUE TITLE
Image rendering textures darker than expected

### ISSUE THREAD

**Issue by smatysik** [pmndrs/drei#753]
Thank you for such a wonderful library that makes 3D accessible to more people!

- `three` version: `0.137.5`
- `@react-three/fiber` version: `7.0.26`
- `@react-three/drei` version: `8.8.1`

### Problem description:

When using Drei's `Image` component, the texture is rendered much darker than either the original image or the same texture rendered on a MeshBasicMaterial.

### Relevant code:

Test codesandbox: https://codesandbox.io/s/black-forest-l7kgc?file=/src/App.js

```
<Image position={[1.5, 0, 0]} url={"/landscape.jpeg"} scale={3} />
```

![image](https://user-images.githubusercontent.com/1480505/152665034-1c68ff2e-3999-4973-960b-abf52af6e6a2.png)

### Suggested solution:

I'm quite new to R3F/ThreeJS, so perhaps this behavior is expected, but I would expect that `Image` render the texture to be true to the source image.

**Comment by RenaudRohlinger** [comment]
Hello, by default react-three-fiber uses a color mapping. To disable that, add the `flat={true}` property to the canvas 👍

**Comment by smatysik** [comment]
@RenaudRohlinger Thank you, for the fix and for the documentation! Much appreciated! Closing the issue.
