### ISSUE TITLE
MeshReflectorMaterial doesn't work with three 137

### ISSUE THREAD

**Issue by besjanhallaqi** [pmndrs/drei#754]
- `three` version: 0.137.4
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.3.1

### Problem description:

MeshReflectorMaterial doesn't work with three 137, in 136 works but not how excepted, but in 135 works perfectly.

### Relevant code:\

https://codesandbox.io/s/vigilant-buck-5sch7?file=/src/App.js

**Comment by loekTheDreamer** [comment]
I've been struggling with this all day. Thanks to your codesandbox. I couldn't understand why the codesandbox works and on My machine, it doesn't. Finally figure out the problem: the versions are messed up.
I found that this combo works correctly on create-react-app:
```
"three": "^0.136.0",
"@react-three/drei": "^8.3.1",
"@react-three/fiber": "^7.0.26",
```
Hope it fixes your issue.
