### ISSUE TITLE
`PointMaterial` TypeScript error

### ISSUE THREAD

**Issue by ChrisCrossCrash** [pmndrs/drei#773]
- `three` version: 0.137.5
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.9.0
- `node` version: 16.13.1
- `npm` (or `yarn`) version: Yarn 1.22.15

### Problem description:

When I use `PointsMaterial` with its `scale` prop as shown in Drei's `README.md`, I get the TypeScript error:

```
Property 'scale' does not exist on type 'IntrinsicAttributes & RefAttributes<unknown>'.
```

However, setting the prop does correctly scale the points. I'm pretty sure that the type is just incorrectly defined.

![image](https://user-images.githubusercontent.com/40023417/154802871-93e0760a-22da-4144-8c27-7b3b0bc78f12.png)

![image](https://user-images.githubusercontent.com/40023417/154802883-1d5f32aa-72e6-4bb0-847a-0dcabf0af11b.png)

### Relevant code:

Here's a [Code Sandbox demonstrating the issue](https://codesandbox.io/s/pointmaterial-bug-0gu8t3?file=/src/App.tsx).

### Suggested solution:

I'm not really sure how to fix this, but I'll let you know if I find out.

**Comment by ericsvendsen** [comment]
I'm seeing the same thing with `<Points>`. With each prop, Typescript complains it does not exist on type. Functionally, everything works as expected though. For now I'm just adding `// @ts-ignore` before the props to get around the issue - is there a better way to mitigate this until a solution is found?
```
<Points
    // @ts-ignore
    limit={1000}
    range={1000}
    positions={positionArr}
    colors={colorArr}
>
```
