### ISSUE TITLE
PointerLockControls: onPointerOver / onPointerOut

### ISSUE THREAD

**Issue by mjurczyk** [pmndrs/drei#777]
- `three` version: r137 (latest)
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.10.2
### Problem description:

After activation, `PointerLockControls` hide the cursor and (theoretically) act as if it was always in the centre of the screen (and move camera with delta.)

The issue is that, as the Pointer Lock API hides the cursor, the cursor seems not to be actually in the center. It remains in the position at which `PointerLockControls` was activated. `onPointerOver` (and similar events [handled by react-three-fiber internally](https://github.com/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/events.ts#L385)) won't trigger unless user understands that the cursor is not in the centre, but hidden at the last visible location.

### Relevant code:

https://codesandbox.io/s/gallant-babycat-uv1h68?file=/src/index.jsx

### Suggested solution:

Add exception handling in either `@react-three/fiber` or `@react-three/drei` to raycast in `defaultCamera.getWorldDirection()` whenever Pointer Lock API fires `locked` event.

**Comment by drcmda** [comment]
looking at the code https://github.com/pmndrs/three-stdlib/blob/main/src/controls/PointerLockControls.ts it just locks it whereever, it doesn't attempt to counteract non center positioning. in a regular three app you wouldn't care, you'd just shoot a ray from center-view.

likewise in react you can prime offsets to be at the center, and now the ray shoots straight.

```jsx
<Canvas
  raycaster={{
    computeOffsets: (e) => ({ offsetX: e.target.width / 2, offsetY: e.target.height / 2 }),
  }}>
````

https://vkgi6.csb.app

**Comment by drcmda** [comment]
fixed it https://github.com/pmndrs/drei/commit/dfacf9499e99d380deb9f0dc00ff3cac6793941f
