### ISSUE TITLE
Text 'Blinks' when string changes.

### ISSUE THREAD

**Issue by antokhio** [pmndrs/drei#778]
- `three` version: 0.138.0
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.10.6
- `node` version:
- `npm` (or `yarn`) version:

### Problem description:

Text "Blinks" (disappears) with all the geometry currently in canvas...
Happens on some text change

test case https://codesandbox.io/s/determined-mcnulty-qi323e?file=/src/App.tsx:318-381
discord https://discord.com/channels/740090768164651008/741751532592038022/946440580001562664

![111](https://user-images.githubusercontent.com/1254168/155568423-baef1699-06d8-446f-bb3a-9339a444adf1.gif)

### Relevant code:
```js
const [text, setText] = useState("hello world");

<input type="text" onChange={(e) => setText(e.target.value)} />
<Text color="black" anchorX="center" anchorY="middle" fontSize={1}>
    {text}
</Text>


```

### Suggested solution:
Don't seems to be happened on old example... https://codesandbox.io/s/troika-3d-text-via-react-three-fiber-forked-ou1qe8

**Comment by drcmda** [comment]
should be fixed: https://github.com/pmndrs/drei#text
