### ISSUE TITLE
TransformControls still requires every attribute

### ISSUE THREAD

**Issue by ajnozari** [pmndrs/drei#780]
- `three` version: 0.138.0
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.11.0
- `node` version: v16.14.0
- `npm` (or `yarn`) version: 3.2.0

### Problem description:

TransformControls still requires every "required" attribute. I believe the pick isn't properly working on TS.

This is being seen on both IntelliJ and VStudio, and has been traced to the ForwardRefExoticComponents in `TransformControls.d.ts`.  

### Relevant code:

```js 
<TransformControls mode={'translate'}>
    <mesh position={[0, 0, 0]}>
        <boxGeometry args={[0.1, 0.11, 0.1]} />
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={1.0}
        />{' '}
    </mesh>
</TransformControls>
```

Please let me know if you require any further information.

**Comment by drcmda** [comment]
i can't reproduce: https://codesandbox.io/s/spring-bush-0x3ts9?file=/src/App.tsx you need to install @types/three otherwise nothing whatsoever in three has types. three itself has cast out all types recently.

**Comment by ajnozari** [comment]
@types/three is installed, and still results in this behavior.

<img width="213" alt="Screen Shot 2022-02-27 at 6 09 50 PM" src="https://user-images.githubusercontent.com/1380829/155903937-03ee25d4-f346-4513-9b7c-d7376fd4858d.png">

Something about the pick isn't playing nice but as it is happening on two different IDE's I'm not exactly sure why?

**Comment by ajnozari** [comment]
So I was digging to see if I could find more information on this, and found a GitHub issue that directed me towards the Type: `React.JSXElementConstructor` instead of the `React.ForwardRefExoticComponent`.

What's interesting is this is an open bug in IntelliJ and VStudio. Strangely though, in my testing swapping `ForwardRefExoticComponent` for `JSXElementConstructor` did solve the issue. The component functions normally and my IDE stops complaining about missing attributes.

Since in this case drei is not returning an exotic component of objects, but instead a proper React component this could be used instead. It seems `React.ForwardRefExoticComponent` is a subclass of `JSXElementConstructor` so it should still be valid and solves the IDE's not handling `ForwardRefExoticComponent` properly.

Since neither IntelliJ NOR MSFT seem to be interested in actually solving this problem despite open issues, I feel the best place to implement this is in this package.

I'd make a PR but I'm not sure if this is actually a proper fix for this issue? Feedback would be appreciated.

**Comment by Seanmclem** [comment]
Seems like this is still not fixed? @ajnozari, I would love additional detail on how you solved it. I'm not quite sure how I'd achieve what you described with the details you provided
