### ISSUE TITLE
Gizmo Not acting as expected... Maybe I am expecting something incorrect though so Please correct me if I am wrong.

### ISSUE THREAD

**Issue by amritbanerjee** [pmndrs/drei#783]
Current Version As on [Storybook](https://drei.pmnd.rs/?path=/story/gizmos-gizmohelper--gizmo-helper-story&args=alignment:top-right)
### Problem description:

On the GizmoHelper with Gizmo as "GizmoViewcube" when on an a Side Elevation (Lets Say Left View) when you click one of the Edge View instead of the Model spinning just by 45° It makes a 135° Turn.
Its Easy to have a look on Storybook [Here](https://drei.pmnd.rs/?path=/story/gizmos-gizmohelper--gizmo-helper-story&args=alignment:top-right)
 

### Relevant Gif:
![eEEqEyMRWp](https://user-images.githubusercontent.com/18136303/156320834-44a25741-da11-4e2c-98a9-4d3d8b4019f1.gif)

### Suggested solution:

I have a feeling when I am hovering over the Box edge it is probably selecting the back Plane rather than the Front But I am really not sure. Any help would be Appreciated.

**Comment by drcmda** [comment]
the storybook is extremely weird but i tried in a real project and there it didnt behave like that. it's like in the storybook stoppropagation doesn't work so it clicks all the edges and faces it can reach. could you confirm if you get the same erratic behaviour in a local project or a sandbox just to make sure.
