### ISSUE TITLE
PositionalAudio doesn't work on iOS

### ISSUE THREAD

**Issue by elrumordelaluz** [pmndrs/drei#784]
- `three` version: 0.138.3
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.12.0
- `node` version: v16.13.1
- `npm` (or `yarn`) version: yarn@1.22.17

### Problem description:

PositionalAudio isn't working on iOS

### Relevant code:
It does not work the following code from [this sandbox](https://codesandbox.io/s/gkfhr?file=/src/Model.js:936-985)

```js
<positionalAudio ref={sound} args={[listener]} />
```
nor this one, using Component:

```js
import { PositionalAudio, Points } from '@react-three/drei'

<PositionalAudio url={url} ref={sound} {...props} />
```

In both cases works as expected on different browsers (not mobile).

**Comment by drcmda** [comment]
audio needs previous interaction with the browser, a click for instance.

**Comment by elrumordelaluz** [comment]
I managed to start the `audio` after user interaction, however for some reason, everything works well internally in r3f but without sound.
I am moving particles, based on `getAverageFrequency` from `AudioAnalyser`, so the dots moves according to the music, but no audio output on the phone.

Seems to happen only on some iOS versions, so pretty sure it isn't a `three` or `r3f` -related issue.

**Comment by drcmda** [comment]
safari has its own rules, it doesn't work like the other browsers. i think the click handler itself must start the audio feed. the dom spec says you just need interaction then you can start where ever. this could be one of these things where you just have to do what apple wants, imperatively.

**Comment by elrumordelaluz** [comment]
In fact I'm forced, thank you!
