### ISSUE TITLE
[ERROR]: Building with Webpack produced error

### ISSUE THREAD

**Issue by kyuzu** [pmndrs/drei#785]
- `three` version: `0.138.3`
- `@react-three/fiber` version: `7.0.26`
- `@react-three/drei` version: `7.27.5`
- `node` version: `16.13.1`
- `npm` version: `8.1.2`

### Problem description:

When building my ReactJS app with `webpack`, it produced the following error:
```ts
ERROR in ./node_modules/@react-three/drei/core/Stats.js 3:0-57
Module not found: Error: Package path ./examples/js/libs/stats.min is not exported from package /home/kyuzu/Project/portfolio/node_modules/three (see exports field in /home/kyuzu/Project/portfolio/node_modules/three/package.json)
 @ ./node_modules/@react-three/drei/index.js 36:0-40 36:0-40
 @ ./components/Bauble.tsx 3:0-44 26:20-27
 @ ./components/Core.tsx 6:0-30 44:122-128
 @ ./app/App.tsx 2:24-52
 @ ./app/index.tsx 3:0-15
 @ ./src/app.ts 1:0-22
 @ ./src/index.ts 2:0-15
```
### Relevant code:

I'm not sure if my code is relevant here since the problem is with `import`(s) of `@react-three/drei` itself.

### Suggested solution:

Maybe `import` from `./examples/jsm/` instead? (Assuming the you're `import`ing from `three`)

**Comment by kyuzu** [comment]
`@react-three/cannon` also produced [this](https://github.com/pmndrs/use-cannon/issues/351#issuecomment-1059270673) warning. Thought it might be related to this.

**Comment by drcmda** [comment]
we dont use three/jsm but three-stdlib. stats is directly imported from stats.js which is declared here https://github.com/pmndrs/drei/blob/master/package.json#L66 i don't see a bug tbh.

**Comment by drcmda** [comment]
ps this is core/Stats.tsx https://github.com/pmndrs/drei/blob/master/src/core/Stats.tsx
and `stats.js` https://github.com/mrdoob/stats.js/blob/master/src/Stats.js

**Comment by drcmda** [comment]
pps latest version of drei is 8.12.0 it might be just that.

**Comment by kyuzu** [comment]
> pps latest version of drei is 8.12.0 it might be just that.

I'll update to latest and try again. Thanks for your time
