### ISSUE TITLE
OrbitControls key controls doesn't work

### ISSUE THREAD

**Issue by TiagoCavalcante** [pmndrs/drei#786]
- `three` version: 137.5 & 138.3
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.12.1
- `node` version: 14.19.0 & v16.14.0
- `npm` (or `yarn`) version: 7.19.1 & 8.3.1

### Problem description:

ObitControls with the keyboard is not working. This is the same issue as [drei#186](https://github.com/pmndrs/drei/issues/186), but now it isn't on three.js side, it is on react-three side.

### Relevant code:

```js
<Canvas>
  <OrbitControls listenToKeyEvents={window} />
</Canvas>
```

### Suggested solution:

I have console logged `listenToKeyEvents`, that function exists, but even calling it manually doesn't work. It doesn't seem to be a problem from missing a `controls.update()` because the controls work normally, and isn't a problem with binding to wrong keys because overwriting the default keys doesn't fix the bug. So I don't know how it could be fixed.

I haven't found any PR to three-stdlib doing the same [three.js#21054](https://github.com/mrdoob/three.js/pull/21054), so maybe the bug is there, but I'm not sure.
https://github.com/pmndrs/drei/blob/master/src/core/OrbitControls.tsx#L5

**Comment by hengkx** [comment]
I also encountered a problem. How to solve it? Thank you

**Comment by TiagoCavalcante** [comment]
@hengkx I didn't closed this because it was solved, I closed this because the issue should be in three-std. Anyway, a time after I solved this by adding my own event listeners.
