### ISSUE TITLE
Support more than one class on the Stats component

### ISSUE THREAD

**Issue by discosultan** [pmndrs/drei#789]
### Describe the feature you'd like:

The `Stats` component has a `className` property for styling the component. Unlike all the React DOM built-in components, it only allows a single class to be passed. The following raises an exception:

```jsx
<Stats className="class-a class-b" />
```

It would be intuitive if the above scenario was allowed, correctly attaching the two classes to the underlying DOM element.

### Suggested implementation:

I would change the [current implementation on master](https://github.com/pmndrs/drei/blob/1e9fac88071a68f9b7d88bda3e30e1e8cb44be1e/src/core/Stats.tsx#L19) from:

```ts
if (className) stats.dom.classList.add(className)
```

to:

```ts
if (className) stats.dom.classList.add(...className.split(" ").filter((cls) => cls))
```

The `.filter((cls) => cls))` gets rid of empty strings in the array.

**Comment by drcmda** [comment]
makes sense, would you make the pr?

**Comment by discosultan** [comment]
@drcmda Will open a PR soon. How can I test or validate that the change doesn't break anything?
