### ISSUE TITLE
OrbitControls don't work in react-native

### ISSUE THREAD

**Issue by cneltyn** [pmndrs/drei#801]
- `three` version: 0.138.3
- `@react-three/fiber` version: ^8.0.0-beta.3
- `@react-three/drei` version: ^8.16.5
- `node` version: 16.14.0
- `yarn` version: 1.22.4
- `react-native` version: 0.64.3

### Problem description:

The use of OrbitControls imported from drei/native leads to **ReferenceError: Can't find variable: document**.

### Relevant code:

Simple example from [here](https://github.com/CodyJasonBennett/r3f-native-starter/blob/main/App.js) , just have added OrbitControls.

```js
import React, { Suspense } from 'react'
import { useFrame, Canvas } from '@react-three/fiber/native'
import { useGLTF, Environment, OrbitControls } from '@react-three/drei/native'
import iphoneModelPath from './assets/iphone.glb'

const Model = ({ url, ...rest }) => {
  const { scene } = useGLTF(url)
  useFrame(() => (scene.rotation.y += 0.05))
  return <primitive {...rest} object={scene} />
}

const App = () => (
  <Canvas gl={{ physicallyCorrectLights: true }} camera={{ position: [-6, 0, 16], fov: 36 }}>
    <color attach="background" args={[0xe2f4df]} />
    <ambientLight />
    <directionalLight intensity={1.1} position={[0.5, 0, 0.866]} />
    <directionalLight intensity={0.8} position={[-6, 2, 2]} />
    <Suspense fallback={null}>
      <Environment preset="park" />
      <Model url={iphoneModelPath} />
    </Suspense>
    <OrbitControls />
  </Canvas>
)

export default App
```
Is there any ability to rotate the model with fingers in react-native the other way?

**Comment by asabadyr** [comment]
Hi guys, do you plan supporting OrbitControls for RN? Any support I can provide to help?

**Comment by cneltyn** [comment]
Any updates with the new version of drei for RN?

**Comment by Jervi-sir** [comment]
is there any alternative that does the same job in reactNative ?

**Comment by foufrix** [comment]
Hi @Jervi-sir, 
This is not entirely my work, but I updated an existing package and will try to maintain it https://github.com/foufrix/expo-three-orbit-controls

You can install directly from github for the moment, I'll look on how to add it to npm. 
For the moment only moving the object around is working, zooming and moving around is not working yet, I'm looking into it and feel free to send pull request

**Comment by 01miaom** [comment]
I useed PanResponder to achieve OrbitControls-like functionality for moving the object around and zooming.

Object Rotation:
```
      if (gestureState.numberActiveTouches === 1 && !controls.isZooming) {
        // If not zooming or panning, rotate around the sphere (theta and phi)
        controls.isRotating = true;

        const deltaX = (gestureState.moveX - controls.lastX) / 100;
        const deltaY = (gestureState.moveY - controls.lastY) / 100;

        controls.lastX = gestureState.moveX;
        controls.lastY = gestureState.moveY;

        setTheta((prev) => prev + deltaX);
        setPhi((prev) => Math.max(0.1, Math.min(Math.PI - 0.1, prev - deltaY)));
      }
```

Zooming: 

```
        if(controls.lastDistance === null){
          //first time update
          controls.lastDistance = distance;
        }
        if (controls.lastDistance !== null && Math.abs(distance - controls.lastDistance) > 1 ) {
          // Zoom
          controls.isZooming = true;
          controls.isPanning = false;

          const deltaDistance = distance - controls.lastDistance;
          setCylinderR((prev) => Math.max(0.1, prev - deltaDistance / 100));
          controls.lastDistance = distance;
        }
```

panning functionality can also be achieved by calculating vectors, but my application doesn't require this. Implementing this method doesn't require installing any additional libraries.
