### ISSUE TITLE
Html block mouseEnter and mouseLeave

### ISSUE THREAD

**Issue by ida-fe** [pmndrs/drei#805]
Case as demo：
https://codesandbox.io/s/jolly-dirac-oym9il?file=/src/App.js
1. bind mouseEnter and mouseLeave on canvas wrapper element,
2. create red rectangle with `<Html>` in canvas
3. mouse move in reactangle，mouseLeave trigger

![image](https://user-images.githubusercontent.com/82094079/158583681-d6189392-65c7-4ca0-af08-3c8ae3ea3954.png)

expect 2 and 3 wont trigger in picture

- `three` version: 0.134.0
- `@react-three/fiber` version: 7.0.17
- `@react-three/drei` version: 7.17.1
- `node` version: 16.11.1
- `npm` (or `yarn`) version: 8.0.0

**Comment by foxxycodes** [comment]
I think this is working as intended, since inside a `Canvas` element, there actually can not be any active DOM-elements. All `Html`-elements placed inside `Canvas` are styled in a way to be "on top" of the `Canvas` element.
