### ISSUE TITLE
Instances and Merged skip a frame

### ISSUE THREAD

**Issue by verekia** [pmndrs/drei#815]
- `three` version: 0.137.4
- `@react-three/fiber` version: 7.0.26
- `@react-three/drei` version: 8.7.4
- `node` version: 16.5.0
- `npm` (or `yarn`) version: 1.22.17

### Problem description:

When using `Instances` or `Merged` and adding mesh items, they appear in the center of the scene with no transforms at (0, 0, 0) for a split second (well, 1 frame), before receiving the proper transformation.

The problem can be seen in this Codesandbox: https://codesandbox.io/s/instances-skipping-an-update-m90kx3?file=/src/App.js:207-806

Click on the button to add a cube. It should not flicker in the center.

### Relevant code:

There seems to be a comment that is likely related to this in `Instances.tsx`: https://github.com/pmndrs/drei/blob/master/src/core/Instances.tsx#L76

```jsx
    React.useEffect(() => {
      // We might be a frame too late? 🤷‍♂️
      parentRef.current.instanceMatrix.needsUpdate = true
    })
```

To reproduce (same code as the Codesandbox):

```jsx
const geometry = new BoxGeometry()
const material = new MeshStandardMaterial({ color: '#f00' })

export default function App() {
  const [cubes, setCubes] = useState([])

  return (
    <>
      <button onClick={() => setCubes((x) => [...x, { id: Math.random(), pos: [1, 1, 1] }])}>Add cube</button>
      <Canvas>
        <ambientLight intensity={4} />
        <Instances material={material} geometry={geometry}>
          {cubes.map((c) => (
            <Instance key={c.id} position={c.pos} />
          ))}
        </Instances>
        <OrbitControls makeDefault />
      </Canvas>
    </>
  )
}
```

Is there any possible workaround in the meantime?

**Comment by verekia** [comment]
In the meantime, a dirty workaround to not get meshes flashing in the middle of the scene, is to translate the `Instances` out of view, and translate the content back to its original location. For instance:

```jsx
  <Instances position={[999, 999, 999]}>
    <group position={[-999, -999, -999]}>
      // ...
    </group>
  </Instances>
```

**Comment by leone6** [comment]
seconding this bug request, would be nice to use Instances in my games but until the flickering goes away i will have to use different approaches

**Comment by mwmwmw** [comment]
Bringing this discussion with @leone6 here for context. https://github.com/pmndrs/react-three-fiber/discussions/2206

I also have this sandbox with Instances.tsx included to hack on.
https://codesandbox.io/s/instances-hqsw6o?file=/src/Instances.tsx

I have tried everything I could think of to fix this issue. 

This doesn't contribute to the flash as far as I could tell.
```js
    React.useEffect(() => {
      // We might be a frame too late? 🤷‍♂️
      parentRef.current.instanceMatrix.needsUpdate = true
    })
```

**Comment by verekia** [comment]
I think there are 2 bugs going on here.

**1-frame mesh flashing at the center bug**: For what it's worth, I have tried an other implementation of React instanced mesh similar to Drei's : [@hmans's version in his Trinity engine](https://github.com/hmans/trinity/blob/0307231fe483b86c101895b7eb7e6e30c8d28a79/packages/toybox/src/instances.tsx). In that implementation I use R3F instead of the Trinity renderer. Anyway bottom line is I was **still** getting the same initial 1-frame flash of the mesh appearing at the center. I also tried to set `instanceMatrix.needsUpdate = true` literally everywhere in the code of Drei's Instances, and was still getting that bug. So I think this problem does not come from Drei but higher up in the stack. Probably R3F (or maybe Three?).

**Mesh showing up at the position of an other instance bug**: With that being said, with Drei's version, I was also getting an other different strange behavior, which is that when I pushed new meshes to my array of instances, I was getting some weird mesh positions, appearing for a short time in the position of last instance before being moved to the right place. Maybe some kind of bug due to using temporary matrix or vector to store the position of a mesh before updating the matrix? I'm not skilled enough to understand well what's going on in Drei's `Instances.tsx`. I was not getting that bug with the Trinity implementation of Instances. I think this could be what the `// We might be a frame too late? 🤷‍♂️` comment might be about.

**Comment by drcmda** [comment]
looks like something has changed in threejs. before it would not have drawn anything until updatematrix was called. i can completely remove the useFrame and it will draw a single box simply by changing the count.

**Comment by drcmda** [comment]
could you stress test this box a little? https://codesandbox.io/s/instances-skipping-an-update-forked-kuigdb?file=/src/Instances.tsx

it moves these two lines into the useFrame and removes the useEffect

```jsx
      parentRef.current.count = instances.length
      parentRef.current.instanceMatrix.updateRange.count = parentRef.current.instanceColor.updateRange.count = Math.min(limit, range !== undefined ? range : limit, instances.length) * 16
```

im not sure if that's correct but i believe the update-range should be limit * 16, not just limit, like before. that would explain some weird behaviour. moving the count into the useframe makes sure that positions have all been set before it can start to show something

**Comment by leone6** [comment]
hey this version you put together is working great. i'm not sure the best way to stress test it, but i forked your sandbox and changed App.js so that the boxes are spawning in random spots. there is no more flickering at the world origin! and i was able to click and add many boxes by clicking a lot so it looks like what you changed is really helping. i will look at what you changed specifically because i am really curious but wanted to say thank you!

https://codesandbox.io/s/instances-skipping-an-update-forked-ki7t30?file=/src/App.js

**Comment by leone6** [comment]
@drcmda  i also commented out the infamous effect from the original Instances.tsx:
// React.useEffect(() => {
  //   // We might be a frame too late? 🤷‍♂️
  //   parentRef.current.instanceMatrix.needsUpdate = true
  // })

and it seems to be working fine without it.  so we might be able to get rid of the layoutEffect ANDthe regular effect?

great catch with the 16 by the way. 
![itemsize](https://user-images.githubusercontent.com/70736254/166127859-5270f487-7dcc-4b8f-a663-68974d692d53.JPG)
if i'm understanding correctly it looks like updateRange needs a number that is based on the attribute itemSize... good to know.

**Comment by drcmda** [comment]
alright, i will make the change ...

**Comment by verekia** [comment]
@drcmda The update correctly fixes the flickering at the center, but introduced a bug when removing instances. They don't seem to clear correctly:

https://codesandbox.io/s/instances-skipping-an-update-forked-ywwi51?file=/src/App.js

You can see that cubes are cleared only after a new one is added.

(clearing was working immediately in the previous version).

**Comment by drcmda** [comment]
ok, makes sense, i will remove the check

**Comment by drcmda** [comment]
could you try again?

**Comment by verekia** [comment]
This solves the clearing problem thank you very much!
I still seem to be getting some flickering at the center in my game in some circumstances. Will try to come up with a codesandbox to isolate the issue.

**Comment by verekia** [comment]
@drcmda False alarm, the bug was coming from my code. Thank you so much for investigating this issue and solving it!

**Comment by leone6** [comment]
woohoo looks like it's time for me to update to react 18 and all the new versions of r3f, zustand, drei, etc. thanks guys.
