### ISSUE TITLE
Beta version isn't working

### ISSUE THREAD

**Issue by TiagoCavalcante** [pmndrs/drei#820]
- `three` version: 0.138.3
- `@react-three/fiber` version: 8.0.0-beta.3
- `@react-three/drei` version: 9.0.0-beta.1
- `node` version: 16.13.2
- `npm` version: 8.5.5

### Problem description:

The beta version isn't working with React-Native because of a missing dependency: three-mesh-bvh

### Relevant code:

```bash
expo init MyProject
cd MyProject
npm i react@rc
npm i three
npm i @react-three/fiber@beta --legacy-peer-deps
npm i @react-three/drei@beta --legacy-peer-deps
# modify any file in the project so it imports @react-three/drei
npm start
# Open the page and press "Run in browser/Android/iOS there
# See the bug
```

### Suggested solution:

I don't know what can be done, I have also tried installing that package by myself but the error is still there.

**Comment by Shipeijing** [comment]
I also encountered this problem

**Comment by JSneak** [comment]
I am also having this issue. Are there any updates?

**Comment by JSneak** [comment]
I found this in the discord, but this in my metro.config.js fixed it for me
```
module.exports = {
    resolver: {
      sourceExts: ['jsx', 'js', 'ts', 'tsx','umd','cjs'], 
    },
  };

 ```

fixed the issue for me

**Comment by CodyJasonBennett** [comment]
Is UMD relevant for three-mesh-bvh? I have cjs for https://docs.pmnd.rs/react-three-fiber/getting-started/installation#react-native but I'll have to amend it in that case.

**Comment by TiagoCavalcante** [comment]
The latest version with React 18 is working now.
