### ISSUE TITLE
ScrollControls and hitBox

### ISSUE THREAD

**Issue by PooLP** [pmndrs/drei#845]
- `three` version: 0.139.2
- `@react-three/fiber` version: 7.0.27
- `@react-three/drei` version: 7.25.5
- `node` version:14.16.0
- `npm` (or `yarn`) version:6.14.11

### Problem description:

If the the app have a HTML header with height, this height shifts the hitBox of WebGL item.

codeSandBox : 
https://codesandbox.io/s/horizontal-tiles-forked-i4rv1x

On this based on @drcmda sample, each item hitBox is shifted
![Animation](https://user-images.githubusercontent.com/582733/161379591-c39762d1-5b6c-4222-aa86-f7df490f739e.gif)

If i remove ScrollControl, the hitBox is ok =>
https://codesandbox.io/s/horizontal-tiles-forked-504iuk

I'm a beginner, I don't know if it's a bug.

**Comment by PooLP** [comment]
Hi, thanks 🥇 
But, the lastest version didn't work with React 16 and i wanted proposed a sample for PnP spfx sample repository (https://pnp.github.io/sp-dev-fx-webparts/). The SPFx framework allow a possibility to add functionality to MS SharePoint ans MS Teams, I thought it was interesting to add possibility to use React Three Fiber and Drei (and others) to this, but work only with React 16.

I'll wait (it's MS, so I'll wait a long time :D)

**Comment by coopbri** [comment]
@PooLP did you figure out a solution for this? I am encountering the same issue (`ScrollControls` pointer event offset) on:

- `react`: 18.2.0
- `three`: 0.142.0
- `@react-three/fiber`: 8.0.27
- `@react-three/drei`: 9.16.0

If I discover a fix I will report it here.

**Comment by AlexRAV** [comment]
Hi, I still have similar issues. Hitboxes of elements shifted down relative to their actual position by the height of header. If I'll remove header, everything is working. I can change position of header to absolute, but that's a hack, header shouldn't affect to these element. Is there any explanation for this behavior?
<img width="306" alt="image" src="https://user-images.githubusercontent.com/13298791/213445245-02a758e1-96f4-4749-a2bd-32e605015650.png">

**Comment by AlexRAV** [comment]
I don't have scroll controls by the way, I only have a scene with Html component with transform prop.
