### ISSUE TITLE
new View component: THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by drcmda** [pmndrs/drei#848]
It seems to happen randomly. I've caught a gpu status report here: https://gist.github.com/drcmda/d673bcb234a4e3b1851cf1964be651bc

@FarazzShaikh can this be related to clearing and or scissor?

**Comment by FarazzShaikh** [comment]
Not sure, will test

**Comment by FarazzShaikh** [comment]
Does it happen here too? https://farazzshaikh.github.io/react-three-scissor/

Doesn’t for me, maybe a Mac thing?
