### ISSUE TITLE
Unexpected behaviour - OrbitControls not working as expected when GizmoHelper is clicked on

### ISSUE THREAD

**Issue by inodino** [pmndrs/drei#860]
- `three` version: 0.138.3
- `@react-three/fiber` version: 7.0.27
- `@react-three/drei` version: 8.20.2
- `node` version: v14.18.1
- `yarn` version: 1.22.18

### Problem description:

I have a simple scene with \<Canvas />, \<PerspectiveCamera />, \<GizmoHelper /> and \<OrbitControls /> elements. Everything works as expected except from when I click on the GizmoHelper (no matter what view/side) and the OrbitControls starts to rotate in strange ways during mouse dragging over the Canvas. As I am dragging the mouse (left/right), I expect the camera to rotate around the target position and this works until I click on the GizmoHelper. It seems like the axes get messed up. Has anyone experienced this before?

### Relevant code:

You can add any other object to the Scene in order to see the effect of clicking the GizmoHelper and interacting with the OrbitControls afterwards. 

```js
import { Canvas, OrbitControls, PerspectiveCamera, GizmoHelper } from "@react-three/drei";

export const Scene = (props) => {
  return (
    <Canvas>
      <GizmoHelper />
      <PerspectiveCamera makeDefault />
      <OrbitControls makeDefault />
    </Canvas>
  );
};
```

Below is a screen recording of this:

![bug](https://user-images.githubusercontent.com/6719727/163216941-7168c0d0-975f-4c34-b690-e66863d078ea.gif)

### Suggested solution:

I don't have any proposed solution and I have tried to identify the issue but no luck...

**Comment by susiwen8** [comment]
Kinda feel like feature not bug

**Comment by saudino** [comment]
Are they supposed to work like this when you use them together? Do you have any suggestion on how I could maintain the same rotation after I click on the GizmoHelper?

**Comment by susiwen8** [comment]
Yep, Indeed it's fetaure.
https://github.com/pmndrs/drei/blob/master/src/core/GizmoViewcube.tsx#L139

> Do you have any suggestion on how I could maintain the same rotation after I click on the GizmoHelper?

Sorry I have no idea

**Comment by gsimone** [comment]
This is not a feature, what's happening is conflict between the mutation on the camera via tweenCamera and orbit controls

**Comment by gsimone** [comment]
@drcmda didn't we solve this for similar cases?

**Comment by la55u** [comment]
Noticed the same thing. After clicking on the gizmo cube Orbitcontrol allows rotating the scene in directions it didn't allow before, so I think it's a bug.
