### ISSUE TITLE
Dynamically change image url.

### ISSUE THREAD

**Issue by MohsinUddinAbir** [pmndrs/drei#871]
When changing the Image URL (<Image url={url} />) in runtime it removes everything and after image load, rerenders, which is not expected. How can I solve this problem?

**Comment by gsimone** [comment]
the <Image /> component fetches the passed url via useTexture, effectively causing a suspense trigger.

We should probably consider an alternative API

```jsx
const [preloadedTexture1, preloadedTexture1, ] = useTexture(...)
...
<Image texture={preloadedTexture1} />
```

This would probably work by splitting the component in two:

```jsx
const Image = ({ url, texture, ...props }) => {
   if (url) return <ImageThatFetches url={url} {...props} />
   if (texture) return <ImageThatOnlyDisplays texture={texture} {...props} />
}
```

Would you like to make a PR?
