### ISSUE TITLE
useGLTF returns incomplete type

### ISSUE THREAD

**Issue by krispya** [pmndrs/drei#894]
- `three` version: 0.139.2
- `@react-three/fiber` version: 8.0.12
- `@react-three/drei` version: 9.6.2
- `node` version: 14.17.3
- `npm` (or `yarn`) version: 8.9.0

useGLTF returns type `GLTF` which is defined from the [declare file ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/examples/jsm/loaders/GLTFLoader.d.ts) as:

```ts
export interface GLTF {
    animations: AnimationClip[];
    scene: Group;
    scenes: Group[];
    cameras: Camera[];
    asset: {
        copyright?: string | undefined;
        generator?: string | undefined;
        version?: string | undefined;
        minVersion?: string | undefined;
        extensions?: any;
        extras?: any;
    };
    parser: GLTFParser;
    userData: any;
}
```

But it is missing the `nodes` and `materials` properties. I'm not sure if this is an issue on the DefinitelyTyped side or something we can fix on the Drei side.

**Comment by system32uwu** [comment]
Updates? We can safely patch the package to overwrite this for the time being right?

**Comment by system32uwu** [comment]
guess you can just use [this](https://github.com/pmndrs/gltfjsx) instead:

`npx gltfjsx model.gltf --types`

**Comment by rgbjoy** [comment]
I'd love this fixed

**Comment by trebeljahr** [comment]
I think there's at least one more issue related to this namely #1159 so a few people seem to run into this. 

would love to help fix it, but I don't know enough about GLTF formats to come up with good types for what nodes and materials could potentially be, because I guess it depends on the GLTF file and what it contains?

**Comment by trebeljahr** [comment]
ok, looked at the closed issues too and it seems like there was a whole discussion around this already #469

**Comment by trebeljahr** [comment]
specifically this comment seems to answer it nicely: 

https://github.com/pmndrs/drei/issues/469#issuecomment-882054348
