### ISSUE TITLE
MeshReflectorMaterial - add ability to set layers for the virtualCam.

### ISSUE THREAD

**Issue by vsabinin** [pmndrs/drei#910]
Hi all,

We work on a project and use MeshReflectorMaterial to create a mirror to show User his avatar in the surrounding scene. 
However, we don't want him to see his avatar with the regular camera.

Can we add an option to configure layers for MeshReflectorMaterial?

```
layers?: number[]

const [virtualCamera] = React.useState(() => {
  const virtualCamera = new PerspectiveCamera();
  layers?.forEach(layer => {
    camera.layers.enable(layer);
  });
  return virtualCamera;
});
 
```

Happy to hear your feedback.

**Comment by Skagoo** [comment]
Ran in to this issue as well. Is there any chance this will be supported in the future?
