### ISSUE TITLE
Can't resolve react-dom/client 17.0.1

### ISSUE THREAD

**Issue by yuesth** [pmndrs/drei#914]
- `three` version:^0.140.2
- `@react-three/fiber` version:^8.0.19
- `@react-three/drei` version:^9.11.0
- `node` version:14.18.13
- `npm` (or `yarn`) version: 1.22.17 (yarn)
- `react` version:17.0.1
- `react-dom` version:17.0.1

### Problem description:
Implementing react three drei above my NextJS app getting an error when go to the page which import react three drei, like the following:
`./node_modules/@react-three/drei/web/Html.js:3:0
Module not found: Can't resolve 'react-dom/client'
Import trace for requested module:
./node_modules/@react-three/drei/index.js
./components/Model3D/ThreeDModel.js
./pages/new.js`

Expected: I go to 'new' page, then I can load 3d model with .glb format from HTML input tag using `useGLTF`

### Relevant code:
```js
import React from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { OrbitControls } from '@react-three/drei'
import { parseImgUrl } from 'utils/common'

const Model1 = ({ threeDUrl }) => {
	const loadedGltf = useGLTF(parseImgUrl(threeDUrl), true)
	return (
		<>
			<primitive object={loadedGltf.scene} dispose={null} />
			<OrbitControls />
			<ambientLight />
		</>
	)
}

export { Model1 }
```

### Suggested solution:
At this time, I think root cause of the error is that my react three drei which I used don't supported react@17.0.1. I expected that previous react three drei version support react@17.0.1 then really wonder what specified version that support react@17.0.1 or maybe the error was caused by other things. Thank you for your support, that's always my pleasure.

This is entire dependencies within package.json
<img width="480" alt="Screen Shot 2022-05-22 at 06 56 39" src="https://user-images.githubusercontent.com/31039577/169672687-45ec89d3-583b-49a8-8427-58c9abdc38cf.png">
<img width="426" alt="Screen Shot 2022-05-22 at 06 57 09" src="https://user-images.githubusercontent.com/31039577/169672690-0753c8d2-4139-4d41-9ef8-e05c7e682298.png">

**Comment by lucasbbs** [comment]
@joshuaellis, what version should I use in my React project version 16.14.0?
