### ISSUE TITLE
Edges with Text3D `Cannot read properties of undefined (reading 'count')`

### ISSUE THREAD

**Issue by marcelmusiol** [pmndrs/drei#920]
- `three` version: 0.140.2
- `@react-three/fiber` version: 8.0.19
- `@react-three/drei` version: 9.11.3

### Problem description:

When using `<Edges />` with `<Text3D>` it crashes on the first render. When it hotreloads (changing something in the codesandbox editor) it works. Seems like the generated Geometry of Text3D isn't ready yet when Edges needs them. Is there a way to suspend Edges until Text3D is ready?

### Relevant code:

https://codesandbox.io/s/text3d-with-edges-hqo6fn?file=/src/App.js

**Comment by FarazzShaikh** [comment]
`Text3D` is suspensful if the `font` prop is a path. Wrapping it in `<Suspense />` makes it work as expected .https://codesandbox.io/s/text3d-with-edges-forked-5vkkmr?file=/src/App.js

If you'd not like it to suspend, provide the font as a JSON object imported like so;
```js
import font from "./font.json"

<Text3D font={font} />
```

**Comment by marcelmusiol** [comment]
> `Text3D` is suspensful if the `font` prop is a path. Wrapping it in `<Suspense />` makes it work as expected .https://codesandbox.io/s/text3d-with-edges-forked-5vkkmr?file=/src/App.js

It still shows an error for me, I dont know...

> If you'd not like it to suspend, provide the font as a JSON object imported like so;
> 
> ```js
> import font from "./font.json"
> 
> <Text3D font={font} />
> ```

that works, thanks!

**Comment by FarazzShaikh** [comment]
What’s the error you get?

**Comment by marcelmusiol** [comment]
> What’s the error you get?

I think it's the same as before, `Cannot read properties of undefined (reading 'count')`
<img width="1119" alt="Screenshot 2022-07-03 at 22 13 03" src="https://user-images.githubusercontent.com/46103209/177057428-52682356-1f74-48ba-9501-75bfb7ced1b5.png">

**Comment by drcmda** [comment]
just update your dependencies and the error goes away. this was a bug in fiber.
