### ISSUE TITLE
useGLTF from @react-three/drei doesn't work with MeshPhysicalMaterial transmission on IOS systems

### ISSUE THREAD

**Issue by PaoloCaligiana** [pmndrs/drei#922]
Describe the bug

IOS SYSTEMS ONLY (on Android it works properly):
useGLTF from @react-three/drei doesn't work with MeshPhysicalMaterial transmission on IOS systems:
when transmission attribute is set to a value, the loaded model with useGLTF duplicates itself every time I read at runtime a new mesh belonging to the model (instead of update the model itself).

Code

import { useGLTF } from '@react-three/drei' //("^8.16.4" version)
//...
const { nodes } = useGLTF(model_path);
<img width="696" alt="actualBehavior" src="https://user-images.githubusercontent.com/37023556/171154291-ba3c6336-1b7d-499a-abe5-7696cab674d7.png">
<img width="858" alt="expected" src="https://user-images.githubusercontent.com/37023556/171154298-ebbf8161-ba24-4991-a131-9102841bfdda.PNG">

return (
  <group />
      {props.meshes_config.map((meshConfig, index) =>{

        { 
          <meshPhysicalMaterial
              transmission= someValue}>
//etc...

**Comment by FarazzShaikh** [comment]
Can you provide a CodeSandbox demo for this issue?

**Comment by rogersanick** [comment]
+1 - I'm also having this issue
