### ISSUE TITLE
Toggling between `useGLTF` asset and a `<Text/>` or `<Text3D/>` makes the glTF asset disappear

### ISSUE THREAD

**Issue by haywirez** [pmndrs/drei#932]
It seems like toggling between `useGLTF` asset and a `<Text/>` or `<Text3D/>` in a scene makes the glTF asset disappear, even though it's mounted in the tree.

![drei-bug](https://user-images.githubusercontent.com/14359218/172000492-a2d7183c-4ee8-4263-bb3d-4a2da3c171d0.gif)

For reproduction, see:

https://codesandbox.io/s/r3f-drei-gltf-text-bug-l21qen?file=/src/index.js

Perhaps something to do with how loaders work internally?

**Comment by CodyJasonBennett** [comment]
I'm able to reproduce this between R3F v7-v8 (and Drei 8-9, React 17-18).

Interestingly, this affects any foreign object passed through primitives:

```jsx
const object = new THREE.Mesh(new THREE.BoxGeometry())

//

return !menu ? (
  <primitive ref={ref} object={object}>
    <meshStandardMaterial attach="material" />
  </primitive>
) : (
  <Text text={'menu'} outlineColor="black" outlineWidth="1" anchorX="center" anchorY="middle" fontSize="1">
    <meshStandardMaterial />
  </Text>
)
```

**Comment by CodyJasonBennett** [comment]
Tracking this behavior down to 5692b703c795fa8aaffb89ad6ab6297f25d91b4c where Text is now an async component. Notice how the demo works as expected if you wrap `<Text />` with `<Suspense />` immediately.

```jsx
return !menu ? (
  <primitive ref={ref} object={object}>
    <meshStandardMaterial attach="material" />
  </primitive>
) : (
  <Suspense>
    <Text text={'menu'} outlineColor="black" outlineWidth="1" anchorX="center" anchorY="middle" fontSize="1">
      <meshStandardMaterial />
    </Text>
  </Suspense>
)
```

This isn't the case if you put it up any higher, which is how you'd normally flatten nested async ops.

```jsx
<Suspense>
  <Thing />
</Suspense>
```

**Comment by drcmda** [comment]
Correct, text finally has deterministic load, that made it a suspending component.

**Comment by haywirez** [comment]
Should we update the README to reflect those by default, e.g.:

> ```jsx
> <Suspense fallback={null}>
>   <Text color="black" anchorX="center" anchorY="middle">
>     hello world!
>   </Text>
> </Suspense>
> ```
> 
> Text will suspend while loading the font data, but in order to completely avoid FOUC you can pass the characters it needs to render.
> 
> ```jsx
> <Suspense fallback={null}>
>   <Text font={fontUrl} characters="abcdefghijklmnopqrstuvwxyz0123456789!">
>     hello world!
>   </Text>
> </Suspense>
> ```

or do you think that's confusing? I had no idea it could cause problems, so maybe it'd be helpful. I'm happy to make a PR to update all, there's only a few components with suspense badges.

**Comment by CodyJasonBennett** [comment]
Sorry for the delayed response, we since annotated suspenseful components -- https://github.com/pmndrs/drei#text.
