### ISSUE TITLE
MeshReflectorMaterial stops working with @react-three/fiber 8.0.20 or higher

### ISSUE THREAD

**Issue by TimKraemer** [pmndrs/drei#940]
- `three` version: 0.141.0
- `@react-three/fiber` version: 8.0.20 (or higher)
- `@react-three/drei` version: 9.13.0
- `node` version: 16.13.1
- `npm` (or `yarn`) version: yarn 1.22.5

### Problem description:

MeshReflectorMaterial stops working with @react-three/fiber 8.0.20 or higher, it's just not "reflecting" anymore.

### Relevant code:

Here's a fork of the image-gallery example:
https://codesandbox.io/s/image-gallery-forked-s8ps0p?file=/src/App.js

As soon as you upgrade `@react-three/fiber` to `8.0.20` or higher it stops working.

### Suggested solution:

I have no idea, as far as I can tell, there are no error messages or warnings related to this.

**Comment by iuriiiurevich** [comment]
It seems to work as expected with `@react-three/fiber` **8.0.23**

**Comment by FarazzShaikh** [comment]
Seems to be fixed in `8.0.23` https://codesandbox.io/s/image-gallery-forked-12yhuf reopen if needed
