### ISSUE TITLE
Html not displaying content in version 9.13.1

### ISSUE THREAD

**Issue by gapon2401** [pmndrs/drei#955]
- `@react-three/fiber` version: 8.0.27
- `@react-three/drei` version: 9.13.1

### Problem description:

When the page is loaded, there is no `Html` content at all.
In version 9.13.0 of `@react-three/drei` problem cannot be reproduced, everything is working fine

Here is version 9.13.0, where we can see black rectangular: https://codesandbox.io/embed/loving-stitch-5nppfy
Version 9.13.1, where there is no any rectangular: https://codesandbox.io/embed/naughty-kowalevski-2wzuiu

**Comment by FarazzShaikh** [comment]
Fixed in `9.14.2` via 6a8efbc40fbe643e01b47f0ea0c76aa61a4a0fb6
