### ISSUE TITLE
useBounds() hook undefined

### ISSUE THREAD

**Issue by dreammonkey** [pmndrs/drei#956]
### Discussed in https://github.com/pmndrs/drei/discussions/953

<div type='discussions-op-text'>

<sup>Originally posted by **dreammonkey** June 17, 2022</sup>
I'm trying to implement the useBounds hook as shown in the example [here](https://github.com/pmndrs/drei#bounds)

But it seems the hook is undefined, am I doing something wrong ?

https://codesandbox.io/s/optimistic-brahmagupta-skj3vz?file=/src/App.js</div>

**Comment by FarazzShaikh** [comment]
`useBounds` needs to be used INSIDE the `<Bounds />` context/component.  https://codesandbox.io/s/shy-wave-eykygi?file=/src/App.js:204-257

It is
```jsx
function Bar() {
    const bounds = useBounds()
}

function Foo() {

    <Bounds>
        <Bar/>
}
```
and not
```jsx
function Bar() {
  
}

function Foo() {
    const bounds = useBounds()

    <Bounds>
        <Bar/>
}

```

**Comment by dreammonkey** [comment]
Thank you very much 👍 , so obvious though 🙈
