### ISSUE TITLE
Could not resolve "react-composer"

### ISSUE THREAD

**Issue by ligdy7** [pmndrs/drei#960]
When I start the example, this error occurs
<img width="823" alt="iShot_2022-06-29_13 26 51" src="https://user-images.githubusercontent.com/26371465/176358396-862e57e2-79da-4c23-a235-6cf6ae248ab3.png">

**Comment by joshuaellis** [comment]
This issue is related to `drei` not `react-three-fiber`.

**Comment by starryskystar** [comment]
> This issue is related to `drei` not `react-three-fiber`.

ok thanks, i'll take a look

**Comment by FarazzShaikh** [comment]
Can you please delete `node_modules` and your yarn/npm lock file then re-install dependancies and see if that fixes it?
