### ISSUE TITLE
Using a loaded FBX model in another canvas, make it disappear in other canvases

### ISSUE THREAD

**Issue by AmirHo3einJS** [pmndrs/drei#994]
Hello, I have a car and a tunnel component that use the useFbx hook to load my models, when I use these components in another Canvas component, the other Canvas goes black and the car and tunnel models are removed from it. How can I solve this problem?

**Comment by drcmda** [comment]
this is how threejs works, one object can't be in two places, it will simply call parent.remove and rip it of its current place.

the solution is to use immutable scene graph. check out gltfjsx (and i would generally recommend using compressed glb's, it's faster, leaner). you can also do that by hand, check out the useGraph hook. https://docs.pmnd.rs/react-three-fiber/api/hooks#usegraph though gltfjsx is preferable.

if none of these work for you check out drei/Clone

**Comment by AmirHo3einJS** [comment]
> 

Thank you, I used the **Clone component** from **drei** for this project but I would defiantly use gltfjsx in my future projects.

**Comment by markusjohnsson** [comment]
One would expect the hook to result in different instances though.
