### ISSUE TITLE
When using components from `/drei` I get this error - TypeError: Cannot read properties of undefined (reading 'generateUUID')

### ISSUE THREAD

**Issue by devsgnr** [pmndrs/drei#996]
- `three` version: 
- `@react-three/fiber` version: 8.2.2
- `@react-three/drei` version: 9.17.3
- `node` version: v18.4.0
- `npm` (or `yarn`) version: yarn v1.22.19
- with `Typescript`
- and `next` version: 12.2.2
- and `react` and `react-dom` version: 18.2.0

### Problem description:
Whenever I try to use the `<Sky />` or `<Stars />` component - I get this error after refreshing the page
`TypeError: Cannot read properties of undefined (reading 'generateUUID')`

### Relevant code:

```tsx
const ThreeDBoxScene = () => {
  return (
    <Canvas camera={{ zoom: 3, near: 1 }}>
      <ambientLight intensity={1} />
      <spotLight position={[10, 10, 10]} angle={0.15} />
      <BoxModel position={[0, 0, 0]} />
      <PlatformModel
        position={[0, -1, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[10, 10, 1]}
      />
      <Stars />
    </Canvas>
  );
};
```

**Comment by FarazzShaikh** [comment]
can you provide a minimal CSB to demo this issue? No such error is thrown here https://codesandbox.io/s/elated-curie-9wt94s?file=/src/components/Lights.jsx:102-231

Maybe try upgrading to the latest version of 3JS?

**Comment by devsgnr** [comment]
@FarazzShaikh - Wrapping `ThreeDBoxScene` in  `<Suspense />` solved the error for me. I guess it was because it was SSR
