### ISSUE TITLE
About <View /> The mouse parameter in the call to useFrame is 0 in the View component, and any element onClick in the View component cannot be responded to.

### ISSUE THREAD

**Issue by ximudada1996** [pmndrs/drei#998]
As the title says,

The mouse parameter in the call to useFrame is 0 in the View component, and any element onClick in the View component cannot be responded to. But it works outside of the View component.

**Comment by louisjmorgan** [comment]
Have you set pointer-events: 'none' in the css for the Canvas component?  I had a similar problem where my orbital controls weren't working and this fixed it.  You will also need the onCreated property on <Canvas /> to be set as in the documentation.  I think the CSS should also be mentioned in the documentation, however, as it's clearly crucial to the function of <View />.
